### PR TITLE
chore: add get_path_to_descendant to NodeIndex

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/101)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/101)* status: all files reviewed, 10 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMErez9yHQJuDq3SjZ:-NxMErez9yHQJuDq3Sj_:b-8vks7c) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/errors.rs#L11)):*
> ```XML
>         reason: &'static str,
>     },
> }
> ```

is this possible? non-blocking



_Suggestion:_
```XML
#[derive(Debug, Error)]
pub(crate) enum TypesError {
    #[error("Failed to convert type {from:?} to {to}. Reason: {reason}.")]
    ConversionError<T: Sized + Debug> {
        from: T,
        to: &'static str,
        reason: &'static str,
    },
}
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMF4V-D4j31t4PE1ME:-NxMF4V-D4j31t4PE1MF:b9h4v8) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/types.rs#L93)):*
> ```XML
>     }
> 
>     pub(crate) fn get_path_to_descendant(&self, descendant: NodeIndex) -> PathToBottom {
> ```

docstring
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMFDXZA3eXh6xTHwHB:-NxMFDXZA3eXh6xTHwHC:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/types.rs#L93)):*
> ```XML
>     }
> 
>     pub(crate) fn get_path_to_descendant(&self, descendant: NodeIndex) -> PathToBottom {
> ```





_Suggestion:_
```XML
pub(crate) fn get_path_to_descendant(&self, descendant: Self) -> PathToBottom {
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMFcAPCZ9w4N40To-n:-NxMFcAQ9MJV_hDx7yqG:b-2h3w3l) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/types.rs#L159)):*
> ```XML
>         Self(U256::from_be_bytes(value.to_bytes_be()))
>     }
> }
> ```

@nimrod-starkware FYI (please delete)



_Code quote:_
```XML
impl From<Felt> for NodeIndex {
    fn from(value: Felt) -> Self {
        Self(U256::from_be_bytes(value.to_bytes_be()))
    }
}
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMGk2o23dWNfsvJIxA:-NxMGk2o23dWNfsvJIxB:b1mbzce) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/types.rs#L161)):*
> ```XML
> }
> 
> impl TryInto<Felt> for NodeIndex {
> ```

IIRC in rust it is recommended to impl the From direction (you get the respective `into` for free)



_Suggestion:_
```XML
impl TryFrom<NodeIndex> for Felt {
```
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMHOj77GvTdeVk_mEq:-NxMHOj77GvTdeVk_mEr:b-73f7m6) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/types_test.rs#L97)):*
> ```XML
>     assert_eq!(left_descendant.get_lca(&right_descendant), lca);
> }
> ```

add tests for specific edge cases please (node==descendant case, check for panic if descendant is not a descendant... whatever you can think of that is interesting in your opinion).
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMIBsE9eQ2yhVcjyyL:-NxMIBsE9eQ2yhVcjyyM:b-s45lwb) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L30)):*
> ```XML
> 
>     #[allow(dead_code)]
>     fn get_path_to_lca(&self, root_index: &NodeIndex, leaf_indices: &[NodeIndex]) -> PathToBottom {
> ```

this function doesn't need a list as input; the calling code can take care of what is the "first and last" indices.
the calling code may even be able to do it without panicking.

(actually, maybe make the same change in the "has leaves on both sides" function..? does that make sense?)



_Suggestion:_
```XML
fn get_path_to_lca(&self, root_index: &NodeIndex, left_index: &NodeIndex, right_index: &NodeIndex)
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMHvin9B07qfZTrWMD:-NxMHvin9B07qfZTrWME:b-741f67) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L34)):*
> ```XML
>         // * Sorted.
>         // * Descendants of the given index.
>         // * Non-empty list.
> ```

docstrings are above the declaration (can be before or after attributes),
and lead with triple-slashes



_Suggestion:_
```XML
    /// Returns the path from the given root_index to the LCA of the leaves. Assumes the leaves are:
    /// * Sorted.
    /// * Descendants of the given index.
    /// * Non-empty list.
    #[allow(dead_code)]
    fn get_path_to_lca(&self, root_index: &NodeIndex, leaf_indices: &[NodeIndex]) -> PathToBottom {
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMJUlR4XJ7eX_02wm0:-NxMJUlSBErq9OKTonLT:b-ekw3hf) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree_test.rs#L68)):*
> ```XML
> 
> #[rstest]
> #[case::small_tree_single_leaf(3, 1, vec![NodeIndex::from(8)], PathToBottom {path:EdgePath(Felt::ZERO), length:EdgePathLength(3)})]
> ```

add cases where the path is longer than 1? isn't that interesting? or am I missing something
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMJC516EWDRVPEORi7:-NxMJC516EWDRVPEORi8:b2x10rk) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree_test.rs#L92)):*
> ```XML
>         skeleton_tree.get_path_to_lca(&root_index, &leaf_indices),
>         expected
>     );
> ```

this change will reduce boilerplate in your `#[case]`s



_Suggestion:_
```XML
    #[case] leaf_indices: Vec<U256>,
    #[case] expected: PathToBottom,
) {
    let skeleton_tree = empty_skeleton(tree_height);
    let root_index = NodeIndex::new(root_index.into());
    assert_eq!(
        skeleton_tree.get_path_to_lca(&root_index, &leaf_indices.iter().map(NodeIndex::new).collect()),
        expected
    );
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/101)* status: all files reviewed, 10 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 159 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMFcAPCZ9w4N40To-n:-NxMKxNREzsWoBjTOReB:b-aiimew) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/types.rs#L159)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@nimrod-starkware FYI (please delete)
</blockquote></details>

in [PR](https://github.com/starkware-libs/committer/pull/103)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/101)* status: all files reviewed, 10 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMVmxq4oegVeuZogw9:-NxMVmxr4uUFw-7X57uU:b88pbza) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/errors.rs#L9)):*
> ```XML
>         from: &'static str,
>         to: &'static str,
>         reason: &'static str,
> ```

why not use `String` instead of `&'static str`?
like here
https://github.com/starkware-libs/committer/blob/4d3e772d520d80fdc4988760e4f58e83d0690a2f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs#L15



_Code quote:_
```XML
        from: &'static str,
        to: &'static str,
        reason: &'static str,
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/101)* status: all files reviewed, 10 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMVmxq4oegVeuZogw9:-NxNYVlHCGyBKvxpQaMQ:b-i45syv) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/errors.rs#L9)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

why not use `String` instead of `&'static str`?
like here
https://github.com/starkware-libs/committer/blob/4d3e772d520d80fdc4988760e4f58e83d0690a2f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs#L15
</blockquote></details>

IIUC `static str` is more efficient, you have the string in the code, and pointers to it, instead of creating dynamic strings to be owned by the error.
___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMErez9yHQJuDq3SjZ:-NxNDMAk-efM8hI1pwKp:b-n0pxc5) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/errors.rs#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this possible? non-blocking
</blockquote></details>

Almost.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMF4V-D4j31t4PE1ME:-NxNDdLA9HhzWfsiU3wK:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/types.rs#L93)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

docstring
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMFDXZA3eXh6xTHwHB:-NxNDfuc2mmgl24mxXVX:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/types.rs#L93)):*
> ```XML
>     }
> 
>     pub(crate) fn get_path_to_descendant(&self, descendant: NodeIndex) -> PathToBottom {
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMGk2o23dWNfsvJIxA:-NxR9saO6ctPovGv1mLi:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/types.rs#L161)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

IIRC in rust it is recommended to impl the From direction (you get the respective `into` for free)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMHOj77GvTdeVk_mEq:-NxRAA515RBlmgW5-mDq:b-8y5w2s) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/types_test.rs#L97)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add tests for specific edge cases please (node==descendant case, check for panic if descendant is not a descendant... whatever you can think of that is interesting in your opinion).
</blockquote></details>

It this OK? It's more convenient to do the edge cases on small examples.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMIBsE9eQ2yhVcjyyL:-NxRDuys1RW7ipcsxKQN:b-g6td3g) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L30)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this function doesn't need a list as input; the calling code can take care of what is the "first and last" indices.
the calling code may even be able to do it without panicking.

(actually, maybe make the same change in the "has leaves on both sides" function..? does that make sense?)
</blockquote></details>

Why is this better? To move the responsibility of the "sorted" list to the caller? I think this might code duplcation for the empty/length 1 checks.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 34 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMHvin9B07qfZTrWMD:-NxREVgB6yS_XqR_PL6a:b-crq31d) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

docstrings are above the declaration (can be before or after attributes),
and lead with triple-slashes
</blockquote></details>

I know that actually. Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 68 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMJUlR4XJ7eX_02wm0:-NxRF4-z2QBggfdK1Ylb:bjsdlll) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree_test.rs#L68)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add cases where the path is longer than 1? isn't that interesting? or am I missing something
</blockquote></details>

The path is larget than 1 in the first and last cases (the value is 0, but the length is larger). I can add an explicit unique path if you want something different than 0.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMJC516EWDRVPEORi7:-NxRJ3OG26kEXYIrzuDZ:b-980zwu) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree_test.rs#L92)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this change will reduce boilerplate in your `#[case]`s
</blockquote></details>

Not sure this was too useful, but I've learnt a bit of rust things.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 10 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/101#-:-NxRt1gM5yoVqvQ60UWL:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 199 at r3](https://reviewable.io/reviews/starkware-libs/committer/101#-NxRNFb1-khTfOyNTa00:-NxRNFb1-khTfOyNTa01:b-tsgud9) ([raw file](https://github.com/starkware-libs/committer/blob/941dfc426aa68e05973da2ca6de93ad7a8b34828/crates/committer/src/patricia_merkle_tree/types.rs#L199)):*
> ```XML
>         let bytes = value.0.to_be_bytes();
>         Ok(Felt::from_bytes_be_slice(&bytes))
>     }
> ```

`Self` is now `Felt`.
non-blocking



_Suggestion:_
```XML
    fn try_from(value: NodeIndex) -> Result<Self, Self::Error> {
        if value.0 > U256::from_be_bytes(Self::MAX.to_bytes_be()) {
            return Err(TypesError::ConversionError {
                from: value,
                to: "Felt",
                reason: "NodeIndex is too large",
            });
        }
        let bytes = value.0.to_be_bytes();
        Ok(Self::from_bytes_be_slice(&bytes))
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/committer/101#-NxMIBsE9eQ2yhVcjyyL:-NxRTITA5vZFqR75fZi7:bcd0khx) ([raw file](https://github.com/starkware-libs/committer/blob/fde194ea0e4baa02ad68ed841430d84292e2bbb3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L30)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Why is this better? To move the responsibility of the "sorted" list to the caller? I think this might code duplcation for the empty/length 1 checks.
</blockquote></details>

you're right, it doesn't help much.. unblocking

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/101)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

**Pull request merged**
