### PR TITLE
build: defining skeletons forest input and introducing updated skeleton forest

### PR DESCRIPTION
**Pull request by nimrod-starkware**
introducing updated skeleton forest

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/110)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/110)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/block_committer/commit.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/committer/110#-NxquYCOBy-FKhH1kEzO:-NxquYCOBy-FKhH1kEzP:bgcgnjm) ([raw file](https://github.com/starkware-libs/committer/blob/d8ab3dabbbac2d8c32d055ee900ecab10fe5aed9/crates/committer/src/block_committer/commit.rs#L30)):*
> ```XML
>                 input.tree_heights,
>             ),
>             &input.state_diff.accessed_addresses(),
> ```

this is all leaves of the contract (global) tree that have changed?
i.e. either have a diff in the storage, or a change in nonce/class hash?



_Code quote:_
```XML
input.state_diff.accessed_addresses()
```
___
*[`crates/committer/src/block_committer/input.rs` line 0 at r3](https://reviewable.io/reviews/starkware-libs/committer/110#-NxquipfBoZ7IA3pZeAj:-NxquipfBoZ7IA3pZeAk:b6mos1i) ([raw file](https://github.com/starkware-libs/committer/blob/d8ab3dabbbac2d8c32d055ee900ecab10fe5aed9/crates/committer/src/block_committer/input.rs#L0)):*
looks like you aren't rebased...? why are these changes appearing in this PR?
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/committer/110#-NxquzWZ8q75PkjmTw1T:-NxquzWZ8q75PkjmTw1U:b-ih94k3) ([raw file](https://github.com/starkware-libs/committer/blob/d8ab3dabbbac2d8c32d055ee900ecab10fe5aed9/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L65)):*
> ```XML
>         state_diff: &StateDiff,
>     ) -> OriginalSkeletonTreeResult<OriginalSkeletonForest<L, T>> {
>         let storage = S::from(storage);
> ```

this function should work with storage API.
the calling code (currently implemented for storage coming from input) should do the `Storage::from` part.



_Suggestion:_
```XML
    #[allow(dead_code)]
    pub(crate) fn create_original_skeleton_forest<S: Storage>(
        storage: S,
        global_tree_root_hash: HashOutput,
        classes_tree_root_hash: HashOutput,
        tree_heights: TreeHeight,
        current_contract_state_leaves: &HashMap<ContractAddress, ContractState>,
        state_diff: &StateDiff,
    ) -> OriginalSkeletonTreeResult<OriginalSkeletonForest<L, T>> {
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 223 at r3](https://reviewable.io/reviews/starkware-libs/committer/110#-Nxqv_9tDeAa3srNAQZf:-Nxqv_9tDeAa3srNAQZg:bh5j3j8) ([raw file](https://github.com/starkware-libs/committer/blob/d8ab3dabbbac2d8c32d055ee900ecab10fe5aed9/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L223)):*
> ```XML
>         &input.current_contract_state_leaves,
>         &input.state_diff,
>     )
> ```

why did you decide to split the `Input` into explicit parameters on the `create_X_forest` functions?
(genuine question)



_Code quote:_
```XML
    > = OriginalSkeletonForest::create_original_skeleton_forest::<MapStorage>(
        input.storage,
        input.global_tree_root_hash,
        input.classes_tree_root_hash,
        input.tree_heights,
        &input.current_contract_state_leaves,
        &input.state_diff,
    )
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/110)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/block_committer/commit.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/committer/110#-NxquYCOBy-FKhH1kEzO:-NxuwQTN9oJ0X7hF8fQz:b-mdy27e) ([raw file](https://github.com/starkware-libs/committer/blob/d8ab3dabbbac2d8c32d055ee900ecab10fe5aed9/crates/committer/src/block_committer/commit.rs#L30)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is all leaves of the contract (global) tree that have changed?
i.e. either have a diff in the storage, or a change in nonce/class hash?
</blockquote></details>

yes, exactly
___
*[`crates/committer/src/block_committer/input.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/committer/110#-NxquipfBoZ7IA3pZeAj:-Nxux76lDHJxtUxjRtln:bz9xjyc) ([raw file](https://github.com/starkware-libs/committer/blob/d8ab3dabbbac2d8c32d055ee900ecab10fe5aed9/crates/committer/src/block_committer/input.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

looks like you aren't rebased...? why are these changes appearing in this PR?
</blockquote></details>

should be fine now, sorry
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 65 at r3](https://reviewable.io/reviews/starkware-libs/committer/110#-NxquzWZ8q75PkjmTw1T:-NxuxKIsADLMmrdRwiSy:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d8ab3dabbbac2d8c32d055ee900ecab10fe5aed9/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L65)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this function should work with storage API.
the calling code (currently implemented for storage coming from input) should do the `Storage::from` part.
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 223 at r3](https://reviewable.io/reviews/starkware-libs/committer/110#-Nxqv_9tDeAa3srNAQZf:-NxuxfNp7dbZ_jFTTph8:b-x7yogs) ([raw file](https://github.com/starkware-libs/committer/blob/d8ab3dabbbac2d8c32d055ee900ecab10fe5aed9/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L223)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why did you decide to split the `Input` into explicit parameters on the `create_X_forest` functions?
(genuine question)
</blockquote></details>

Isn't it better that a function will take what it actually needs?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/110)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/110#-:-NxvGlT20kM0wHJ2WoK_:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
