### PR TITLE
chore(skeleton): update_node_in_empty_tree func in UpdatedSkeleton

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/148)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/148)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/committer/148#-Nyp2yJz26tR3Ws8u_9w:-Nyp2yJz26tR3Ws8u_9x:b-a559pk) ([raw file](https://github.com/starkware-libs/committer/blob/8e7b83da2ebd8c630680596140876d5c3e1ca8db/crates/committer/src/patricia_merkle_tree/types.rs#L63)):*
> ```XML
>     pub(crate) fn is_leaf(&self) -> bool {
>         Self::FIRST_LEAF <= *self && *self <= Self::MAX
>     }
> ```

this and other "functions" here depend on the tree height (e.g. `Self::MAX`)... not sure what to do about it at this point but maybe worth adding a TODO.
worth considering adding a generic height parameter, if this kind of thing works:
```
pub struct NodeIndex<H: u8>(U256);

impl NodeIndex {
    pub const BITS: u8 = TreeHeight(H);
    ...
```



_Code quote:_
```XML
    pub(crate) fn is_leaf(&self) -> bool {
        Self::FIRST_LEAF <= *self && *self <= Self::MAX
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/committer/148#-Nyp44gD0FAwops8K-iT:-Nyp44gE1yN52kAafZst:b-y1ciao) ([raw file](https://github.com/starkware-libs/committer/blob/8e7b83da2ebd8c630680596140876d5c3e1ca8db/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L275)):*
> ```XML
>     &[],
>     3
> )]
> ```

add
1. leaves on both sides case
2. empty subtree case



_Code quote:_
```XML
#[rstest]
#[case::one_leaf(
    &NodeIndex::ROOT,
    &[(U256::ONE<<251, 1)],
    TempSkeletonNode::Original(OriginalSkeletonNode::Edge { path_to_bottom: PathToBottom::from("0".repeat(251).as_str())}),
    &[],
    3
)]
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/committer/148#-Nyp4Ntg4j7tWRD0D7sV:-Nyp4Nth7hQgh5FNiUKp:b-inmih3) ([raw file](https://github.com/starkware-libs/committer/blob/8e7b83da2ebd8c630680596140876d5c3e1ca8db/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L288)):*
> ```XML
>         .map(|(index, _)| NodeIndex::new(*index))
>         .collect();
>     let mut expected_skeleton_tree = updated_skeleton.skeleton_tree.clone();
> ```

this seems expensive.
can you please check which tree types have `Clone` derived on them, and if it can be gated behind `cfg(test)`?
i.e. convert `#[derive(Clone)]` to `#[cfg_attr(test, derive(Clone))]` for tree implementing types?
we don't want to accidentally clone the entire hashmap in business logic



_Code quote:_
```XML
skeleton_tree.clone()
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/148)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/committer/148#-Nyp2yJz26tR3Ws8u_9w:-NytujMT8fseBGrT0poY:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/8e7b83da2ebd8c630680596140876d5c3e1ca8db/crates/committer/src/patricia_merkle_tree/types.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this and other "functions" here depend on the tree height (e.g. `Self::MAX`)... not sure what to do about it at this point but maybe worth adding a TODO.
worth considering adding a generic height parameter, if this kind of thing works:
```
pub struct NodeIndex<H: u8>(U256);

impl NodeIndex {
    pub const BITS: u8 = TreeHeight(H);
    ...
```
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/committer/148#-Nyp44gD0FAwops8K-iT:-Nyu00UaEScNLdeZ_8Yu:bq9inry) ([raw file](https://github.com/starkware-libs/committer/blob/8e7b83da2ebd8c630680596140876d5c3e1ca8db/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L275)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add
1. leaves on both sides case
2. empty subtree case
</blockquote></details>

What does 2 mean? (This function is called on an Originally empty tree/subtree).
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/committer/148#-Nyp4Ntg4j7tWRD0D7sV:-NytvSMPCZpWrvlMvqxT:bjyhskz) ([raw file](https://github.com/starkware-libs/committer/blob/8e7b83da2ebd8c630680596140876d5c3e1ca8db/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L288)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this seems expensive.
can you please check which tree types have `Clone` derived on them, and if it can be gated behind `cfg(test)`?
i.e. convert `#[derive(Clone)]` to `#[cfg_attr(test, derive(Clone))]` for tree implementing types?
we don't want to accidentally clone the entire hashmap in business logic
</blockquote></details>

The clone is defined for `NodeIndex` and `UpdatedSkeletonNode` - and AFAIU this let us clone a hashmap of these keys and values. I think we do want the clone property for the basic structs (i.e., for the `get_nodes` func.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/148)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/committer/148#-Nyp44gD0FAwops8K-iT:-NyuBfel-XgKOVMdwAMM:bykf5w8) ([raw file](https://github.com/starkware-libs/committer/blob/8e7b83da2ebd8c630680596140876d5c3e1ca8db/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L275)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

What does 2 mean? (This function is called on an Originally empty tree/subtree).
</blockquote></details>

ah, right
I meant:
2. case where the root is a leaf (I want the `root.is_leaf()` case covered)
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/committer/148#-Nyp4Ntg4j7tWRD0D7sV:-NyuCGpS26wJr8WbK6jB:bbvd8ax) ([raw file](https://github.com/starkware-libs/committer/blob/8e7b83da2ebd8c630680596140876d5c3e1ca8db/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L288)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

The clone is defined for `NodeIndex` and `UpdatedSkeletonNode` - and AFAIU this let us clone a hashmap of these keys and values. I think we do want the clone property for the basic structs (i.e., for the `get_nodes` func.
</blockquote></details>

we want the `Clone` property  on the basic types of size O(1), but *not* on the tree types. `skeleton_tree.clone()` is a red flag. remove the `Clone` from just the tree type (which contains a hashmap, right?), implement it only for tests, and see if compilation fails?
if it doesn't, great; if it does, revert your change and add a TODO to fix... we really shouldn't be cloning trees
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 306 at r2](https://reviewable.io/reviews/starkware-libs/committer/148#-NyuBuaV1OA-x3MkPeRb:-NyuBuaV1OA-x3MkPeRc:b-45ad00) ([raw file](https://github.com/starkware-libs/committer/blob/6350763e7cdf11d68e514253ba93ecd0fd0c8272/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L306)):*
> ```XML
>         (NodeIndex::from(3),
>         UpdatedSkeletonNode::Edge{ path_to_bottom: PathToBottom::from("1".repeat(250).as_str())})],
> )]
> ```

duplicated case (or did I miss some tiny difference)?



_Suggestion:_
```XML
#[case::leaves_on_both_sides(
    &NodeIndex::ROOT,
    &[(U256::ONE<<251, 1), ((U256::ONE<<252)-1_u128, 1)],
    TempSkeletonNode::Original(OriginalSkeletonNode::Binary),
    &[
        (NodeIndex::from(2),
        UpdatedSkeletonNode::Edge{ path_to_bottom: PathToBottom::from("0".repeat(250).as_str()) }),
        (NodeIndex::from(3),
        UpdatedSkeletonNode::Edge{ path_to_bottom: PathToBottom::from("1".repeat(250).as_str())})],
)]
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/148)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 275 at r1](https://reviewable.io/reviews/starkware-libs/committer/148#-Nyp44gD0FAwops8K-iT:-Nyy81EK2E8WwdU9-wth:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/8e7b83da2ebd8c630680596140876d5c3e1ca8db/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L275)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah, right
I meant:
2. case where the root is a leaf (I want the `root.is_leaf()` case covered)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 288 at r1](https://reviewable.io/reviews/starkware-libs/committer/148#-Nyp4Ntg4j7tWRD0D7sV:-Nyy4Er90aZ3FrywjIP-:b-d9bhed) ([raw file](https://github.com/starkware-libs/committer/blob/8e7b83da2ebd8c630680596140876d5c3e1ca8db/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L288)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we want the `Clone` property  on the basic types of size O(1), but *not* on the tree types. `skeleton_tree.clone()` is a red flag. remove the `Clone` from just the tree type (which contains a hashmap, right?), implement it only for tests, and see if compilation fails?
if it doesn't, great; if it does, revert your change and add a TODO to fix... we really shouldn't be cloning trees
</blockquote></details>

As discussed - there is no Tree struct with a `clone` trait.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 306 at r2](https://reviewable.io/reviews/starkware-libs/committer/148#-NyuBuaV1OA-x3MkPeRb:-Nyy4C_RAkWlPFU3zG8F:bg0tm9k) ([raw file](https://github.com/starkware-libs/committer/blob/6350763e7cdf11d68e514253ba93ecd0fd0c8272/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L306)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

duplicated case (or did I miss some tiny difference)?
</blockquote></details>

My bad.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/148#-:-NyyB8Sx4eswEdmg4Hig:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
