### PR TITLE
build: impl mock test utils

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/314)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
* **#316** <a href="https://app.graphite.dev/github/pr/starkware-libs/committer/316?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#314** <a href="https://app.graphite.dev/github/pr/starkware-libs/committer/314?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/314)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/internal_test_utils.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/committer/314#-O20-8Jk6pEWqkL0gYob:-O20-8Jk6pEWqkL0gYoc:b-7vv0a9) ([raw file](https://github.com/starkware-libs/committer/blob/1e92f7bf514ad476a1563d5491f9a57e2bd079ba/crates/committer/src/patricia_merkle_tree/internal_test_utils.rs#L26)):*
> ```XML
> use rstest::{fixture, rstest};
> #[derive(Debug, PartialEq, Clone, Copy, Default, Eq)]
> pub(crate) struct MockLeaf(pub(crate) Felt);
> ```

newline after `use`s



_Suggestion:_
```XML
use rstest::{fixture, rstest};

#[derive(Debug, PartialEq, Clone, Copy, Default, Eq)]
pub(crate) struct MockLeaf(pub(crate) Felt);
```
___
*[`crates/committer/src/patricia_merkle_tree/internal_test_utils.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/committer/314#-O20-CpU0P8FOaVR9qep:-O20-CpU0P8FOaVR9qeq:but1v90) ([raw file](https://github.com/starkware-libs/committer/blob/1e92f7bf514ad476a1563d5491f9a57e2bd079ba/crates/committer/src/patricia_merkle_tree/internal_test_utils.rs#L32)):*
> ```XML
>         StorageValue(self.0.to_bytes_be().to_vec())
>     }
>     fn get_prefix(&self) -> Vec<u8> {
> ```

newline between function impls



_Suggestion:_
```XML
    }

    fn get_prefix(&self) -> Vec<u8> {
```
___
*[`crates/committer/src/patricia_merkle_tree/internal_test_utils.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/committer/314#-O20-PRm5szE_ysP0TCL:-O20-PRm5szE_ysP0TCM:bpoaz2o) ([raw file](https://github.com/starkware-libs/committer/blob/1e92f7bf514ad476a1563d5491f9a57e2bd079ba/crates/committer/src/patricia_merkle_tree/internal_test_utils.rs#L70)):*
> ```XML
>             .0;
>         Ok(Self(leaf_val))
>     }
> ```

how does this differ from the default implementation?
if it doesn't, you should be able to just delete this



_Code quote:_
```XML
    fn from_modifications(
        index: &NodeIndex,
        leaf_modifications: Arc<LeafModifications<Self>>,
    ) -> LeafResult<Self> {
        let leaf_val = leaf_modifications
            .get(index)
            .expect("Leaf not found in modifications")
            .0;
        Ok(Self(leaf_val))
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/internal_test_utils.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/committer/314#-O20-VRs18wAY2oSMmLd:-O20-VRt7kp9zoDGaRKz:biwt184) ([raw file](https://github.com/starkware-libs/committer/blob/1e92f7bf514ad476a1563d5491f9a57e2bd079ba/crates/committer/src/patricia_merkle_tree/internal_test_utils.rs#L75)):*
> ```XML
> generate_trie_config!(OriginalSkeletonMockTrieConfig, MockLeaf);
> 
> struct MockHash;
> ```

it's not a hash, it's a hash function



_Suggestion:_
```XML
MockHashFunction
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/314)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/internal_test_utils.rs` line 26 at r3](https://reviewable.io/reviews/starkware-libs/committer/314#-O20-8Jk6pEWqkL0gYob:-O207wESB_VTgAxWDvT5:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/1e92f7bf514ad476a1563d5491f9a57e2bd079ba/crates/committer/src/patricia_merkle_tree/internal_test_utils.rs#L26)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newline after `use`s
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/internal_test_utils.rs` line 32 at r3](https://reviewable.io/reviews/starkware-libs/committer/314#-O20-CpU0P8FOaVR9qep:-O207zrKDuWl9lkbCxPw:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/1e92f7bf514ad476a1563d5491f9a57e2bd079ba/crates/committer/src/patricia_merkle_tree/internal_test_utils.rs#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newline between function impls
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/internal_test_utils.rs` line 70 at r3](https://reviewable.io/reviews/starkware-libs/committer/314#-O20-PRm5szE_ysP0TCL:-O20862O6IFqLM5t1NpU:b-pz1xva) ([raw file](https://github.com/starkware-libs/committer/blob/1e92f7bf514ad476a1563d5491f9a57e2bd079ba/crates/committer/src/patricia_merkle_tree/internal_test_utils.rs#L70)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how does this differ from the default implementation?
if it doesn't, you should be able to just delete this
</blockquote></details>

I haven't noticed that we have one.
___
*[`crates/committer/src/patricia_merkle_tree/internal_test_utils.rs` line 75 at r3](https://reviewable.io/reviews/starkware-libs/committer/314#-O20-VRs18wAY2oSMmLd:-O208M__43y6Y-R-Rgla:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/1e92f7bf514ad476a1563d5491f9a57e2bd079ba/crates/committer/src/patricia_merkle_tree/internal_test_utils.rs#L75)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it's not a hash, it's a hash function
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/314#-:-O20BBsi8xXvA0YbPXH-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
