### PR TITLE
fix: wrong handling of insert return value

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/186)

### CODE REVIEW

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/186)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/committer/186#-NzT7shG4u3Rk8Haq3IM:-NzT7shHBrTWnrIwF3Dr:bpyzff4) ([raw file](https://github.com/starkware-libs/committer/blob/78f333910b3ab9734b63fec6235715d2dc906c42/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L76)):*
> ```XML
>                 };
> 
>                 let _ = updated_skeleton_tree
> ```

No need

**Review by TzahiTaub — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/186)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/committer/186#-NzTIE_W146R_iwmlR5S:-NzTIE_W146R_iwmlR5T:bc2f7g3) ([raw file](https://github.com/starkware-libs/committer/blob/78f333910b3ab9734b63fec6235715d2dc906c42/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L79)):*
> ```XML
>                     .skeleton_tree
>                     .insert(NodeIndex::ROOT, new_node)
>                     .map(|_| panic!("Root node already exists in the updated skeleton tree"));
> ```

WDYT on this?



_Suggestion:_
```XML
updated_skeleton_tree
    .skeleton_tree
    .insert(NodeIndex::ROOT, new_node)
    .map_or((), |_| {
        unreachable!("Root node already exists in the updated skeleton tree")
    })
```

**Review by TzahiTaub — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/186)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/committer/186#-NzTIE_W146R_iwmlR5S:-NzTIlUPCugLrvsF1hb2:bawpjav) ([raw file](https://github.com/starkware-libs/committer/blob/78f333910b3ab9734b63fec6235715d2dc906c42/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L79)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

WDYT on this?
</blockquote></details>

panic instead of unreachable

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/186)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/committer/186#-NzTIE_W146R_iwmlR5S:-NzTKDRN5KkYTgrngSnC:bb7f2mf) ([raw file](https://github.com/starkware-libs/committer/blob/78f333910b3ab9734b63fec6235715d2dc906c42/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L79)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

panic instead of unreachable
</blockquote></details>

done

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/186#-:-NzTMixd-RiEc-g8xb9M:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
