### PR TITLE
fix: bug in lca

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/194)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/194)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/committer/194#-NzY40A_Bc9tDvZ4uk8J:-NzY40A_Bc9tDvZ4uk8K:b-fh9u4t) ([raw file](https://github.com/starkware-libs/committer/blob/52fbadb30e86411a4ef097d5e6c522167b8f3ac5/crates/committer/src/patricia_merkle_tree/types.rs#L112)):*
> ```XML
>         if post_common_prefix_len == 0 && self < other {
>             return *self;
>         }
> ```

please add a short comment above this block explaining what does this `if` indicate (`self` is an ancestor of `other`?)



_Code quote:_
```XML
        if post_common_prefix_len == 0 && self < other {
            return *self;
        }
```
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/committer/194#-NzY3NrV6bu9oVAX_Qnh:-NzY3NrV6bu9oVAX_Qni:b1jeqp5) ([raw file](https://github.com/starkware-libs/committer/blob/52fbadb30e86411a4ef097d5e6c522167b8f3ac5/crates/committer/src/patricia_merkle_tree/types_test.rs#L55)):*
> ```XML
> #[case(U256([9,0]), U256([12,0]), U256([1,0]))]
> #[case(U256([1,0]), U256([2,0]), U256([1,0]))]
> #[case(U256([2,0]), U256([1,0]), U256([1,0]))]
> ```

The order of the u128s [may depend on the architecture of the system](https://github.com/nlordell/ethnum-rs/blob/main/src/uint.rs#L34-L44).
Use `U256::new(x)` instead of `U256([x, 0])`



_Code quote:_
```XML
#[case(U256([1,0]), U256([1,0]), U256([1,0]))]
#[case(U256([2,0]), U256([5,0]), U256([2,0]))]
#[case(U256([5,0]), U256([2,0]), U256([2,0]))]
#[case(U256([8,0]), U256([10,0]), U256([2,0]))]
#[case(U256([9,0]), U256([12,0]), U256([1,0]))]
#[case(U256([1,0]), U256([2,0]), U256([1,0]))]
#[case(U256([2,0]), U256([1,0]), U256([1,0]))]
```
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/committer/194#-NzY3me410SNI0SKjPw2:-NzY3me410SNI0SKjPw3:bg51ar2) ([raw file](https://github.com/starkware-libs/committer/blob/52fbadb30e86411a4ef097d5e6c522167b8f3ac5/crates/committer/src/patricia_merkle_tree/types_test.rs#L59)):*
> ```XML
>     U256::from_str_hex("0x200000000000000000000000000000000000000000000000000000000000000").unwrap(),
>     U256::from_str_hex("0x800000000000000000000000000000000000000000000000000000000000000").unwrap(),
>     U256::from_str_hex("0x200000000000000000000000000000000000000000000000000000000000000").unwrap()
> ```

this case is a bit difficult to read; can you use `U256::from_words` and use bit-shifting to describe the high value?



_Code quote:_
```XML
    U256::from_str_hex("0x200000000000000000000000000000000000000000000000000000000000000").unwrap(),
    U256::from_str_hex("0x800000000000000000000000000000000000000000000000000000000000000").unwrap(),
    U256::from_str_hex("0x200000000000000000000000000000000000000000000000000000000000000").unwrap()
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/194)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/committer/194#-NzY40A_Bc9tDvZ4uk8J:-NzYG1gs98Pe7rVjIZ6E:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/52fbadb30e86411a4ef097d5e6c522167b8f3ac5/crates/committer/src/patricia_merkle_tree/types.rs#L112)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a short comment above this block explaining what does this `if` indicate (`self` is an ancestor of `other`?)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 55 at r1](https://reviewable.io/reviews/starkware-libs/committer/194#-NzY3NrV6bu9oVAX_Qnh:-NzYFhMjELoU-riv4y0e:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/52fbadb30e86411a4ef097d5e6c522167b8f3ac5/crates/committer/src/patricia_merkle_tree/types_test.rs#L55)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

The order of the u128s [may depend on the architecture of the system](https://github.com/nlordell/ethnum-rs/blob/main/src/uint.rs#L34-L44).
Use `U256::new(x)` instead of `U256([x, 0])`
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/committer/194#-NzY3me410SNI0SKjPw2:-NzYFgTPC41D5XNqa4br:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/52fbadb30e86411a4ef097d5e6c522167b8f3ac5/crates/committer/src/patricia_merkle_tree/types_test.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this case is a bit difficult to read; can you use `U256::from_words` and use bit-shifting to describe the high value?
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/194)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/committer/194#-NzYKlL8BUWCx7dXl9mh:-NzYKlL8BUWCx7dXl9mi:b-l9xhgj) ([raw file](https://github.com/starkware-libs/committer/blob/4f0d5c6ad9a9b64a84c222112fa3b5b70bfadb8a/crates/committer/src/patricia_merkle_tree/types_test.rs#L51)):*
> ```XML
> #[case(U256::new(1), U256::new(1), U256::new(1))]
> #[case(U256::new(2), U256::new(5), U256::new(2))]
> #[case(U256::new(5), U256([2,0]), U256([2,0]))]
> ```

still need `new` here



_Code quote:_
```XML
U256([2,0]), U256([2,0]))]
```
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/committer/194#-NzYKvpaBFgj_KcLmI10:-NzYKvpaBFgj_KcLmI11:b-31e1qv) ([raw file](https://github.com/starkware-libs/committer/blob/4f0d5c6ad9a9b64a84c222112fa3b5b70bfadb8a/crates/committer/src/patricia_merkle_tree/types_test.rs#L63)):*
> ```XML
> #[case(
>     U256::from_words(6<<121, 12109832645278165874326859176438297),
>     U256::from_words(7<<121, 34269583569287659876592876529763453),
> ```

what are these `low` values?



_Code quote:_
```XML
    U256::from_words(6<<121, 12109832645278165874326859176438297),
    U256::from_words(7<<121, 34269583569287659876592876529763453),
```
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 64 at r2](https://reviewable.io/reviews/starkware-libs/committer/194#-NzYKzmGEZ7PyZeZy9Nt:-NzYKzmH0PXWJbtEE6us:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/4f0d5c6ad9a9b64a84c222112fa3b5b70bfadb8a/crates/committer/src/patricia_merkle_tree/types_test.rs#L64)):*
> ```XML
>     U256::from_words(6<<121, 12109832645278165874326859176438297),
>     U256::from_words(7<<121, 34269583569287659876592876529763453),
>     U256([3,0])
> ```





_Suggestion:_
```XML
U256::new(3)
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/194)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/committer/194#-NzYKvpaBFgj_KcLmI10:-NzYMjd16dPH9G1LK8uf:bf0vk4t) ([raw file](https://github.com/starkware-libs/committer/blob/4f0d5c6ad9a9b64a84c222112fa3b5b70bfadb8a/crates/committer/src/patricia_merkle_tree/types_test.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what are these `low` values?
</blockquote></details>

Just some random values, the idea is that it doesn't matter

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/194)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/committer/194#-NzYKlL8BUWCx7dXl9mh:-NzYNwD8Bx-YjUT84dyB:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/4f0d5c6ad9a9b64a84c222112fa3b5b70bfadb8a/crates/committer/src/patricia_merkle_tree/types_test.rs#L51)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

still need `new` here
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/194#-:-NzYQMR08wxzyjfD6fP6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/194)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 93 at r4](https://reviewable.io/reviews/starkware-libs/committer/194#-NzYTvJ3Cae83_1wMVUq:-NzYTvJ3Cae83_1wMVUr:b194b31) ([raw file](https://github.com/starkware-libs/committer/blob/aa621c90d5943ba30f313167e461a5cd91ba1384/crates/committer/src/patricia_merkle_tree/types.rs#L93)):*
> ```XML
> 
>     pub(crate) fn is_ancestor_of(&self, descendant: &NodeIndex) -> bool {
>         self.bit_length() < descendant.bit_length()
> ```

question: is self not a descendant of self?
please rename function to `is_strict_ancestor_of` just for clarity.

On the other hand, the only use case I see would benefit from a weak inequality... maybe change to `<=` and rename function to `is_ancestor_or_equal`?



_Code quote:_
```XML
self.bit_length() < descendant.bit_length()
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 94 at r4](https://reviewable.io/reviews/starkware-libs/committer/194#-NzYTgj_6EpusMEqXpjz:-NzYTgj_6EpusMEqXpk-:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/aa621c90d5943ba30f313167e461a5cd91ba1384/crates/committer/src/patricia_merkle_tree/types.rs#L94)):*
> ```XML
>     pub(crate) fn is_ancestor_of(&self, descendant: &NodeIndex) -> bool {
>         self.bit_length() < descendant.bit_length()
>             && *self == *descendant >> (descendant.bit_length() - self.bit_length())
> ```





_Suggestion:_
```XML
        let (self_bits, descendant_bits) = (self.bit_length(), descendant.bit_length());
        self_bits < descendent_bits && *self == *descendant >> (descendant_bits - self_bits)
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 105 at r4](https://reviewable.io/reviews/starkware-libs/committer/194#-NzYUPHl3BFK5-QL7pIC:-NzYUPHl3BFK5-QL7pID:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/aa621c90d5943ba30f313167e461a5cd91ba1384/crates/committer/src/patricia_merkle_tree/types.rs#L105)):*
> ```XML
>         if self.is_ancestor_of(other) {
>             return *self;
>         }
> ```





_Suggestion:_
```XML
        // If self equal to / is an ancestor of other, return self.
        if self.is_ancestor_or_equal(other) {
            return *self;
        }
```

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/194)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/committer/194#-NzbG24h8fgBsO71HfgX:-NzbG24h8fgBsO71HfgY:bpydt00) ([raw file](https://github.com/starkware-libs/committer/blob/aa621c90d5943ba30f313167e461a5cd91ba1384/crates/committer/src/patricia_merkle_tree/types_test.rs#L49)):*
> ```XML
> 
> #[rstest]
> #[case(U256::new(1), U256::new(1), U256::new(1))]
> ```

Shorter macro



_Suggestion:_
```XML
uint!(
```

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/194)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 105 at r4](https://reviewable.io/reviews/starkware-libs/committer/194#-NzbKxZZ1x7nbtyd1cS9:-NzbKxZZ1x7nbtyd1cSA:bf1olx2) ([raw file](https://github.com/starkware-libs/committer/blob/027c5b4ad82175d857e5741c4a81cf8db7a0803e/crates/committer/src/patricia_merkle_tree/types.rs#L105)):*
> ```XML
>         } else {
>             *self >> (bit_length - other_bit_length)
>         };
> ```

This is the only fix needed. Please remove the rest of the additions.



_Suggestion:_
```XML
        // Bring self and other to a common (low) height.
        let (adapted_self, adapter_other) = if self < other {
            (*self, *other >> (other_bit_length - bit_length))
        } else {
            (*self >> (bit_length - other_bit_length), *other)
        };
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/194)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 93 at r4](https://reviewable.io/reviews/starkware-libs/committer/194#-NzYTvJ3Cae83_1wMVUq:-NzbTgZD42FslShNTHqU:b-w5ckpu) ([raw file](https://github.com/starkware-libs/committer/blob/aa621c90d5943ba30f313167e461a5cd91ba1384/crates/committer/src/patricia_merkle_tree/types.rs#L93)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

question: is self not a descendant of self?
please rename function to `is_strict_ancestor_of` just for clarity.

On the other hand, the only use case I see would benefit from a weak inequality... maybe change to `<=` and rename function to `is_ancestor_or_equal`?
</blockquote></details>

Not relevant anymore.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 94 at r4](https://reviewable.io/reviews/starkware-libs/committer/194#-NzYTgj_6EpusMEqXpjz:-NzbTlOV3hNnVpHgfRn4:b-w5ckpu) ([raw file](https://github.com/starkware-libs/committer/blob/aa621c90d5943ba30f313167e461a5cd91ba1384/crates/committer/src/patricia_merkle_tree/types.rs#L94)):*
> ```XML
>     pub(crate) fn is_ancestor_of(&self, descendant: &NodeIndex) -> bool {
>         self.bit_length() < descendant.bit_length()
>             && *self == *descendant >> (descendant.bit_length() - self.bit_length())
> ```

Not relevant anymore.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 105 at r4](https://reviewable.io/reviews/starkware-libs/committer/194#-NzYUPHl3BFK5-QL7pIC:-NzbTmbC2-ebdKx1Vybg:b-w5ckpu) ([raw file](https://github.com/starkware-libs/committer/blob/aa621c90d5943ba30f313167e461a5cd91ba1384/crates/committer/src/patricia_merkle_tree/types.rs#L105)):*
> ```XML
>         if self.is_ancestor_of(other) {
>             return *self;
>         }
> ```

Not relevant anymore.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 105 at r4](https://reviewable.io/reviews/starkware-libs/committer/194#-NzbKxZZ1x7nbtyd1cS9:-NzbTpAaDbCLjXqit0_F:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/027c5b4ad82175d857e5741c4a81cf8db7a0803e/crates/committer/src/patricia_merkle_tree/types.rs#L105)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

This is the only fix needed. Please remove the rest of the additions.
</blockquote></details>

Done.

**Comment by aner-starkware** [comment]
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/committer/194#-NzbG24h8fgBsO71HfgX:-NzbU6RC9on0f9RGZK2s:b-fcg3wd) ([raw file](https://github.com/starkware-libs/committer/blob/aa621c90d5943ba30f313167e461a5cd91ba1384/crates/committer/src/patricia_merkle_tree/types_test.rs#L49)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Shorter macro
</blockquote></details>

This macro works from strings, it's less clear imo.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/194)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/194)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 101 at r5](https://reviewable.io/reviews/starkware-libs/committer/194#-Nzbc0C25lr_St_68lUE:-Nzbc0C25lr_St_68lUF:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/e9fbe3682dfe007fe888909c25c87abdf9ed12a3/crates/committer/src/patricia_merkle_tree/types.rs#L101)):*
> ```XML
>         let other_bit_length = other.bit_length();
>         // Bring self and other to a common (low) height.
>         let (adapted_self, adapter_other) = if self < other {
> ```





_Suggestion:_
```XML
adapted_other
```

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/194#-:-NzbdS8f1FhuIDNcld95:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
