### PR TITLE
fix: move from tokio join to spawn to fix parallelism

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/156)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/156)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @yoavGrs)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/committer/156#-Nyz9KHvCQHDdfVTxzIY:-Nyz9KHvCQHDdfVTxzIZ:b-6panna) ([raw file](https://github.com/starkware-libs/committer/blob/2a992f94e7ac9eb9f5648eaa3720b9afd0fbe24e/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L35)):*
> ```XML
>         H: HashFunction + 'a + 'static,
>         TH: TreeHashFunction<LeafDataImpl, H> + 'static,
>     >(
> ```

this doesn't work (needed for the leaf_modifications)?
asking



_Suggestion:_
```XML
    async fn create<
        H: HashFunction + 'static,
        TH: TreeHashFunction<LeafDataImpl, H> + 'static,
    >(
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/committer/156#-Nyz9CFm9lSFrDmM5_Ef:-Nyz9CFm9lSFrDmM5_Eg:b-s2go2f) ([raw file](https://github.com/starkware-libs/committer/blob/2a992f94e7ac9eb9f5648eaa3720b9afd0fbe24e/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L37)):*
> ```XML
>     >(
>         updated_skeleton: impl UpdatedSkeletonTree + 'static,
>         leaf_modifications: &'a LeafModifications<LeafDataImpl>,
> ```

why does the lifespan here depend on the lifespan of `H`?



_Code quote:_
```XML
&'a
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/committer/156#-Nyz9v7n1z2FvfDHRG-K:-Nyz9v7n1z2FvfDHRG-L:bu4lgl3) ([raw file](https://github.com/starkware-libs/committer/blob/2a992f94e7ac9eb9f5648eaa3720b9afd0fbe24e/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L156)):*
> ```XML
>                     right_hash: right_hash
>                         .await
>                         .expect("right hash computation did not execute correctly")?,
> ```

do not `expect` here; the result could be a `JoinError` or something? please add a variant of `FilledTreeError` that can handle the `Err` variant of `await`



_Suggestion:_
```XML
                    left_hash: left_hash.await??,
                    right_hash: right_hash.await??,
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/committer/156#-NyzAHx06DMHLXio1OQr:-NyzAHx06DMHLXio1OQs:bshdasb) ([raw file](https://github.com/starkware-libs/committer/blob/2a992f94e7ac9eb9f5648eaa3720b9afd0fbe24e/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L209)):*
> ```XML
>         updated_skeleton: impl UpdatedSkeletonTree + 'static,
>         leaf_modifications: &'a LeafModifications<LeafDataImpl>,
>     ) -> Result<Self, FilledTreeError<LeafDataImpl>> {
> ```

same question as above about `'a`: I don't understand why leaf_modifications is coupled with the `H` type



_Code quote:_
```XML
    async fn create<
        'a,
        H: HashFunction + 'a + 'static,
        TH: TreeHashFunction<LeafDataImpl, H> + 'static,
    >(
        updated_skeleton: impl UpdatedSkeletonTree + 'static,
        leaf_modifications: &'a LeafModifications<LeafDataImpl>,
    ) -> Result<Self, FilledTreeError<LeafDataImpl>> {
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/committer/156#-NyzASZw62iOL_gHwKME:-NyzASZw62iOL_gHwKMF:b8s9d00) ([raw file](https://github.com/starkware-libs/committer/blob/2a992f94e7ac9eb9f5648eaa3720b9afd0fbe24e/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L218)):*
> ```XML
>             Arc::new(updated_skeleton),
>             NodeIndex::ROOT,
>             Arc::new(leaf_modifications.clone()),
> ```

this clone is expensive and unecessary - you don't need the leaf modifications after this point.
consider changing the input from `&'a LeafModifications<LeafDataImpl>` (reference) to `LeafModifications<LeafDataImpl>` (transfer ownership), if it works it seems better IMO



_Suggestion:_
```XML
leaf_modifications
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/156)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/committer/156#-Nyz9KHvCQHDdfVTxzIY:-Nz7lXPx5OlyUZ7-py7S:b-9uitwz) ([raw file](https://github.com/starkware-libs/committer/blob/2a992f94e7ac9eb9f5648eaa3720b9afd0fbe24e/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this doesn't work (needed for the leaf_modifications)?
asking
</blockquote></details>

`H` no longer exists.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 37 at r2](https://reviewable.io/reviews/starkware-libs/committer/156#-Nyz9CFm9lSFrDmM5_Ef:-Nz7lE1G6LPRq9SLgOdX:b-g1m8ia) ([raw file](https://github.com/starkware-libs/committer/blob/2a992f94e7ac9eb9f5648eaa3720b9afd0fbe24e/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L37)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why does the lifespan here depend on the lifespan of `H`?
</blockquote></details>

I don't know, I don't really understand lifespans so well.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/committer/156#-Nyz9v7n1z2FvfDHRG-K:-Nz7kX8e0Re2w_BB4fqE:b5x432w) ([raw file](https://github.com/starkware-libs/committer/blob/2a992f94e7ac9eb9f5648eaa3720b9afd0fbe24e/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L156)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do not `expect` here; the result could be a `JoinError` or something? please add a variant of `FilledTreeError` that can handle the `Err` variant of `await`
</blockquote></details>

Yes, the result could be a `JoinError`, but doesn't the expect just unwrap and then return the inner error? Isn't it the better way to handle this specific error in this case?
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 209 at r2](https://reviewable.io/reviews/starkware-libs/committer/156#-NyzAHx06DMHLXio1OQr:-Nz7lOca0o-em4wT_2QX:b-ya81ng) ([raw file](https://github.com/starkware-libs/committer/blob/2a992f94e7ac9eb9f5648eaa3720b9afd0fbe24e/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L209)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same question as above about `'a`: I don't understand why leaf_modifications is coupled with the `H` type
</blockquote></details>

Same as above
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/committer/156#-NyzASZw62iOL_gHwKME:-Nz7kGfZ0T38gJI_y6PY:buz8x2v) ([raw file](https://github.com/starkware-libs/committer/blob/2a992f94e7ac9eb9f5648eaa3720b9afd0fbe24e/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L218)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this clone is expensive and unecessary - you don't need the leaf modifications after this point.
consider changing the input from `&'a LeafModifications<LeafDataImpl>` (reference) to `LeafModifications<LeafDataImpl>` (transfer ownership), if it works it seems better IMO
</blockquote></details>

Apparently, there is some borrowing issue. I replaced the clone here with an `Arc::clone` above.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/156)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @yoavGrs)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 156 at r2](https://reviewable.io/reviews/starkware-libs/committer/156#-Nyz9v7n1z2FvfDHRG-K:-Nz870imDFWMN13QKi5K:bwmv69e) ([raw file](https://github.com/starkware-libs/committer/blob/2a992f94e7ac9eb9f5648eaa3720b9afd0fbe24e/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L156)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Yes, the result could be a `JoinError`, but doesn't the expect just unwrap and then return the inner error? Isn't it the better way to handle this specific error in this case?
</blockquote></details>

`expect` panics on error; this may be what we want but I'd prefer to let the calling code decide to panic if need be. `await??` is better IMO
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/committer/156#-NyzASZw62iOL_gHwKME:-Nz87TqC28LCFhldJYsF:bv8frgu) ([raw file](https://github.com/starkware-libs/committer/blob/2a992f94e7ac9eb9f5648eaa3720b9afd0fbe24e/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L218)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Apparently, there is some borrowing issue. I replaced the clone here with an `Arc::clone` above.
</blockquote></details>

I still see a clone on the leaf modifications here
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 124 at r3](https://reviewable.io/reviews/starkware-libs/committer/156#-Nz87EW83XIBjiEyeDV1:-Nz87EW9CnNbsiV4AgPw:bdawer7) ([raw file](https://github.com/starkware-libs/committer/blob/72b49246e2a68289fb8d34e6e9f49f0f141ea2fb/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L124)):*
> ```XML
>         TH: TreeHashFunction<LeafDataImpl> + 'static,
>     {
>         let binding = Arc::clone(&updated_skeleton);
> ```

this is an O(1) operation, right? no hashmap is being cloned here?



_Code quote:_
```XML
let binding = Arc::clone(&updated_skeleton);
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/156)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 218 at r2](https://reviewable.io/reviews/starkware-libs/committer/156#-NyzASZw62iOL_gHwKME:-Nz8SNr90Lw-jm0Xflxt:b-mi54xa) ([raw file](https://github.com/starkware-libs/committer/blob/2a992f94e7ac9eb9f5648eaa3720b9afd0fbe24e/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L218)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I still see a clone on the leaf modifications here
</blockquote></details>

Right, sorry, I was looking at a different `.clone()`
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 124 at r3](https://reviewable.io/reviews/starkware-libs/committer/156#-Nz87EW83XIBjiEyeDV1:-Nz8PNwD4V2pOWECG6YX:b-wsnm5f) ([raw file](https://github.com/starkware-libs/committer/blob/72b49246e2a68289fb8d34e6e9f49f0f141ea2fb/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L124)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is an O(1) operation, right? no hashmap is being cloned here?
</blockquote></details>

IIUC, that is the point of Arc::clone.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/156#-:-Nz8TD5wBKeVPdk7j25m:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
