### PR TITLE
refactor: removed the tree height parameter to rust and added a regression test

### PR DESCRIPTION
**Pull request by nimrod-starkware**
…ssion test

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/189)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/189)* status: 0 of 6 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/189#-NzTJImZ40kIk6e7XKfo:-NzTJImZ40kIk6e7XKfp:bn3xe3j) (no related file):*
python side [PR](https://reviewable.io/reviews/starkware-industries/starkware/35146)

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/189)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/committer/189#-NzTKH_a2nIivFCFEzqm:-NzTKH_a2nIivFCFEzqn:bk7ca42) ([raw file](https://github.com/starkware-libs/committer/blob/b6d60ef691e1ace1fae6afbbac5860f1513e4ba5/crates/committer_cli/src/tests/python_tests.rs#L155)):*
> ```XML
> fn get_tree_height() -> String {
>     format!("{}", u8::from(TreeHeight::MAX))
> }
> ```

wouldn't it be better to add `derive_more::Display` in the `#[derive]` attribute of `TreeHeight`? then you could do something like this



_Suggestion:_
```XML
fn get_tree_height() -> String {
    TreeHeight::MAX.into()
}
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/189)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/committer/189#-NzTKH_a2nIivFCFEzqm:-NzTNo377XLzSKQ0DiYc:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b6d60ef691e1ace1fae6afbbac5860f1513e4ba5/crates/committer_cli/src/tests/python_tests.rs#L155)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

wouldn't it be better to add `derive_more::Display` in the `#[derive]` attribute of `TreeHeight`? then you could do something like this
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/189#-:-NzTPkP02rmHk0jUC4td:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
