### PR TITLE
chore!: move updated skeleton factory function to updated skeleton tr…

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
…ee trait

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/124)

### CODE REVIEW

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/124)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/committer/124#-NyKdewo97kiwL8GWf13:-NyKdewo97kiwL8GWf14:bxq9oi2) ([raw file](https://github.com/starkware-libs/committer/blob/d0bfb8267e2198a402fb5215c1e5bb8272b7809d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L1)):*
> ```XML
> use ethnum::U256;
> ```

Move this entire file to `crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` in a following PR
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/committer/124#-NyKdozh5BdaZ0ajOohB:-NyKdozh5BdaZ0ajOohC:bcyyzj9) ([raw file](https://github.com/starkware-libs/committer/blob/ea45f5dd2f735caeeaf951ab05ab362b5d9ca492/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L37)):*
> ```XML
> 
> impl OriginalSkeletonTree for OriginalSkeletonTreeImpl {
>     fn create_tree(
> ```

Rename as in the new UpdatedTree func for consistency



_Suggestion:_
```XML
create(
```

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/124)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/124)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/committer/124#-NyKdozh5BdaZ0ajOohB:-NyKjWWE8xQiDtf_l6zY:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/ea45f5dd2f735caeeaf951ab05ab362b5d9ca492/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L37)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Rename as in the new UpdatedTree func for consistency
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/124)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/committer/124#-NyKdewo97kiwL8GWf13:-NyKkrY553DagnazpLkH:b2vthj2) ([raw file](https://github.com/starkware-libs/committer/blob/d0bfb8267e2198a402fb5215c1e5bb8272b7809d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L1)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Move this entire file to `crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` in a following PR
</blockquote></details>

done ([here](https://reviewable.io/reviews/starkware-libs/committer/127))

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/124#-:-NyKmdOsAX7RCN95iXkY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @nimrod-starkware)

**Pull request merged**
