### PR TITLE
chore(skeleton): remove Leaf variant from OriginalSkeletonNode

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/158)

### CODE REVIEW

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/158)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/158#-Nz-Tbqq9XrqXxkh7yuy:-Nz-Tbqq9XrqXxkh7yuz:brhjadz) (no related file):*
Summary:
1. No Leaf in OriginalSkeleton (because unchanged leaves use the Sibling variant, and for changed leaves, we use the `leaf_modifications` and don't care about what they were originally.
2. A Leaf in UpdatedSkeleton means a leaf with new data (not a deleted one - as such leaf won't appear in the skeleton) - so the internal `skeleton_leaf` eunm is removed from it.
3. A new Leaf variant in TempSkeleton (the enum used during the computation of the UpdatedSkeleton) - created according to he `leaf_indices` that is derived from the `leaf_modifications`.

___
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/committer/158#-Nz-W0o74jl4KZ5coI4m:-Nz-W0o74jl4KZ5coI4n:bicrida) ([raw file](https://github.com/starkware-libs/committer/blob/a196506c83de772acb74a99c89caab74dd6ee124/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L127)):*
> ```XML
>                         TempSkeletonNode::Original(_) => {
>                             unreachable!("node is not an Original variant.")
>                         }
> ```

Either this, or two nested matches below (one for TempSkeleton and a nested one for the `TempSkeletonNode::Original` variant.



_Code quote:_
```XML
                        TempSkeletonNode::Empty => unreachable!("Unexpected empty node."),
                        TempSkeletonNode::Original(_) => {
                            unreachable!("node is not an Original variant.")
                        }
```

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/158)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/committer/158#-Nz20QWz7c1SoAe_HWQq:-Nz20QX-Bm6t0gXEm06x:bmrqeug) ([raw file](https://github.com/starkware-libs/committer/blob/ef88a6eae25af5ad18ae70fe0016cbc3078e9f58/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L8)):*
> ```XML
> #[derive(thiserror::Error, Debug)]
> pub enum FilledTreeError<L: LeafData> {
>     #[error("Deleted leaf at index {0:?} appears in the skeleton tree.")]
> ```

`#[error("Deleted leaf at index {0:?} appears in the updated skeleton tree.")]`



_Code quote:_
```XML
#[error("Deleted leaf at index {0:?} appears in the skeleton tree.")]
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/committer/158#-Nz21Uz_BPrcwpVX_d4q:-Nz21Uz_BPrcwpVX_d4r:b-pybxz2) ([raw file](https://github.com/starkware-libs/committer/blob/ef88a6eae25af5ad18ae70fe0016cbc3078e9f58/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L18)):*
> ```XML
>     Empty,
>     Leaf,
>     #[allow(dead_code)]
> ```

is that needed?



_Code quote:_
```XML
#[allow(dead_code)]
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/158)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/158#-Nz-Tbqq9XrqXxkh7yuy:-Nz2BNPl3EBFhvQbiTzl:b-8d3wr) (no related file):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Summary:
1. No Leaf in OriginalSkeleton (because unchanged leaves use the Sibling variant, and for changed leaves, we use the `leaf_modifications` and don't care about what they were originally.
2. A Leaf in UpdatedSkeleton means a leaf with new data (not a deleted one - as such leaf won't appear in the skeleton) - so the internal `skeleton_leaf` eunm is removed from it.
3. A new Leaf variant in TempSkeleton (the enum used during the computation of the UpdatedSkeleton) - created according to he `leaf_indices` that is derived from the `leaf_modifications`.
</blockquote></details>

about (2): if you delete a leaf it will appear in the state diff, and thus appear in the leaf modifications. isn't that an issue?

___
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/committer/158#-Nz-W0o74jl4KZ5coI4m:-Nz2A7x42gn6swGkNywH:ba1jfb) ([raw file](https://github.com/starkware-libs/committer/blob/a196506c83de772acb74a99c89caab74dd6ee124/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L127)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Either this, or two nested matches below (one for TempSkeleton and a nested one for the `TempSkeletonNode::Original` variant.
</blockquote></details>

third option:
```
if node == TempSkeletonNode::Leaf {
    assert!(
        self.skeleton_tree.contains_key(&index),
        "Leaf index {index:?} doesn't appear in the skeleton."
    );
    continue;
}
unreachable!("No empty or original nodes possible here.");
```
fourth option:
```
assert_eq!(node, TempSkeletonNode::Leaf, "No empty or original nodes possible here.");
assert!(
    self.skeleton_tree.contains_key(&index),
    "Leaf index {index:?} doesn't appear in the skeleton."
);
continue;
```
IDC though, current way is fine
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/committer/158#-Nz2B97VE1lyTKSB78cB:-Nz2B97VE1lyTKSB78cC:b-q4k7h4) ([raw file](https://github.com/starkware-libs/committer/blob/ef88a6eae25af5ad18ae70fe0016cbc3078e9f58/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L56)):*
> ```XML
>             .filter(|(_, leaf)| !leaf.is_zero())
>             .map(|(index, _)| (*index, UpdatedSkeletonNode::Leaf))
>             .collect();
> ```

I'm confused:
you *can* get a zero leaf with this method, right? if a leaf is modified from non-zero to zero, it will appear in the leaf modifications, no?



_Code quote:_
```XML
        let mut _skeleton_tree: HashMap<NodeIndex, UpdatedSkeletonNode> = leaf_modifications
            .iter()
            .filter(|(_, leaf)| !leaf.is_zero())
            .map(|(index, _)| (*index, UpdatedSkeletonNode::Leaf))
            .collect();
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/158)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/158#-Nz-Tbqq9XrqXxkh7yuy:-Nz2EiYQ8I6ME6uC9LYM:b2mz23s) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

about (2): if you delete a leaf it will appear in the state diff, and thus appear in the leaf modifications. isn't that an issue?
</blockquote></details>

No, in the create function of the Updated tree, I start with filtering the modifications leaves. So during the computations we have `leaf_indices` that is exactly the keys of the `leaf_modifications` (i.e., modified and deleted leaves) to guide us to the subtrees that have changed, and the initial `self.skeleton_tree` (the final mapping) that is initialized with only the modified leaves - so it's used to determine if a leaf is modified or deleted.

___
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 8 at r2](https://reviewable.io/reviews/starkware-libs/committer/158#-Nz20QWz7c1SoAe_HWQq:-Nz2GId-CCARTCyji5q-:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/ef88a6eae25af5ad18ae70fe0016cbc3078e9f58/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L8)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

`#[error("Deleted leaf at index {0:?} appears in the updated skeleton tree.")]`
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 127 at r1](https://reviewable.io/reviews/starkware-libs/committer/158#-Nz-W0o74jl4KZ5coI4m:-Nz2HOqV0JmH3y7tX7Wp:bi6ad1d) ([raw file](https://github.com/starkware-libs/committer/blob/a196506c83de772acb74a99c89caab74dd6ee124/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L127)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

third option:
```
if node == TempSkeletonNode::Leaf {
    assert!(
        self.skeleton_tree.contains_key(&index),
        "Leaf index {index:?} doesn't appear in the skeleton."
    );
    continue;
}
unreachable!("No empty or original nodes possible here.");
```
fourth option:
```
assert_eq!(node, TempSkeletonNode::Leaf, "No empty or original nodes possible here.");
assert!(
    self.skeleton_tree.contains_key(&index),
    "Leaf index {index:?} doesn't appear in the skeleton."
);
continue;
```
IDC though, current way is fine
</blockquote></details>

Then I'm leaving it as is. I prefer the `match` as it makes compiler errors in case of variant changes in the Temp enum, as opposed to the if/else approach that will only (if lucky) fail at runtime.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/committer/158#-Nz21Uz_BPrcwpVX_d4q:-Nz2GQT02f7MRMbqE4yG:bwi457j) ([raw file](https://github.com/starkware-libs/committer/blob/ef88a6eae25af5ad18ae70fe0016cbc3078e9f58/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L18)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

is that needed?
</blockquote></details>

Not anymore.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 56 at r2](https://reviewable.io/reviews/starkware-libs/committer/158#-Nz2B97VE1lyTKSB78cB:-Nz2GaJh5TjaPiAiCAmq:b-kb5w3f) ([raw file](https://github.com/starkware-libs/committer/blob/ef88a6eae25af5ad18ae70fe0016cbc3078e9f58/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I'm confused:
you *can* get a zero leaf with this method, right? if a leaf is modified from non-zero to zero, it will appear in the leaf modifications, no?
</blockquote></details>

Yes, it will appear in the modifications, but won't appear in the `_skeleton_tree`. We need both (as a deleted leaf effects the tree structure, we need to traverse towards it). See reply above.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/158#-:-Nz2RFnkD8HGfSll8mzT:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/158#-:-Nz2RMLmD1RJ0tDyaOiU:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
