### PR TITLE
refactor: no need to deserialize leaf siblings - all we need is the hash

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
python side [PR](https://reviewable.io/reviews/starkware-industries/starkware/35526)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310#-:-O1q445m3uatXMY0wxmJ:bn3zwk9)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @TzahiTaub)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1qdruo1PQIRklckVXS:-O1qdruo1PQIRklckVXT:b-cutung) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L209)):*
> ```XML
>                         !subtree.is_unmodified(),
>                         "Unexpectedly deserialized leaf sibling."
>                     );
> ```

I understand why this would be unexpected, but is it an unrecoverable error?



_Code quote:_
```XML
                    assert!(
                        !subtree.is_unmodified(),
                        "Unexpectedly deserialized leaf sibling."
                    );
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1qe4Mt6wPS__YA9ojL:-O1qe4Mt6wPS__YA9ojM:b-r6tauw) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L219)):*
> ```XML
>                     if let Some(ref mut leaves) = previous_leaves {
>                         leaves.insert(subtree.root_index, previous_leaf);
>                     }
> ```

is the `else` case here an unrecoverable error?
if so please add a TODO to panic here on `else` (maybe even just call `expect` on `previous_leaves`)



_Code quote:_
```XML
                    if let Some(ref mut leaves) = previous_leaves {
                        leaves.insert(subtree.root_index, previous_leaf);
                    }
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1qeOZ98IxBv80Rr8zB:-O1qeOZ98IxBv80Rr8zC:bagl8fy) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L347)):*
> ```XML
>         should_fetch_modified_leaves: bool,
>     ) {
>         if !subtree.is_leaf() || (should_fetch_modified_leaves && !subtree.is_unmodified()) {
> ```

can you explain what is the logical change here?



_Code quote:_
```XML
if !subtree.is_leaf() || (should_fetch_modified_leaves && !subtree.is_unmodified()) {
```

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1qe4Mt6wPS__YA9ojL:-O1qmg2iATBNrmryabAT:bh8ufkb) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L219)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is the `else` case here an unrecoverable error?
if so please add a TODO to panic here on `else` (maybe even just call `expect` on `previous_leaves`)
</blockquote></details>

It's not an error, for storage trees without the trivial modifications flag, we don't want the previous leaves of modifications. It's only an error if `config.compare_modified_leaves()` is True right? Maybe we should assert this at the beginning of the function.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1qe4Mt6wPS__YA9ojL:-O1qoCqV8oxMg2cOPjgj:bwzipwj) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L219)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

It's not an error, for storage trees without the trivial modifications flag, we don't want the previous leaves of modifications. It's only an error if `config.compare_modified_leaves()` is True right? Maybe we should assert this at the beginning of the function.
</blockquote></details>

OK, so not a business logic error anyway? I wouldn't want this config to cause new panics, so I'm unblocking

**Review by TzahiTaub — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1qdruo1PQIRklckVXS:-O1tysawEzXvRSFJZxce:b-ys950g) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L209)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I understand why this would be unexpected, but is it an unrecoverable error?
</blockquote></details>

I added this as a sanity check to make sure that we don't deserialize a leaf sibling...
We assume that leaf siblings do not exist in storage, so if we actually get a leaf sibling, we can't know if the deserialization has been done correctly.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1qe4Mt6wPS__YA9ojL:-O1u-JRKEs8xGPYzY3T1:btuq1n9) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L219)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

OK, so not a business logic error anyway? I wouldn't want this config to cause new panics, so I'm unblocking
</blockquote></details>

not exactly.
`leaves` is not none in the case that we want also to return the previous leaves at the modified indices. It's independent of `config.compare_modified_leaves()` configuration.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 347 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1qeOZ98IxBv80Rr8zB:-O1u0D-YEcCWmCJtL_9w:bxrgxwv) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L347)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you explain what is the logical change here?
</blockquote></details>

Now we no longer assume that we can deserialize leaf siblings. (they do not exist in storage)
This function decides whether we should deserialize the next subtree or not.
If it's an inner node, we always have to deserialize.
If it's a leaf sibling, we don't really need (and can't - since we don't have it in storage) - the hash is enough.
If it's a modified leaf, then it depends on `should_fetch_modified_leaves` flag.

The change is that previously we deserialized a leaf sibling iff we deserialized a modified leaf.
Now, in any case, we don't deserialize a leaf sibling.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1qdruo1PQIRklckVXS:-O1ud0DA7asFcjMIxi8i:bgglu6x) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L209)):*
> so if we actually get a leaf sibling, we can't know if the deserialization has been done correctly.

how can we incorrectly deserialize a leaf?
if it's not in storage we will get a missing key error from storage (in the future, everything should exist in storage anyway, just a matter of deciding to read or not); 
but if we don't get a missing key error, how will the deserialization be "done incorrectly"?
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1ud_77AFQhlrRnGLGa:-O1ud_77AFQhlrRnGLGb:b-z4unu) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L217)):*
> ```XML
>                         log_trivial_modification!(subtree.root_index, previous_leaf);
>                     }
>                     if let Some(ref mut leaves) = previous_leaves {
> ```

is this comment correct? if so please add it



_Suggestion:_
```XML
                    }

                    // If previous values of modified leaves are required, add this leaf.
                    if let Some(ref mut leaves) = previous_leaves {
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1ud_77AFQhlrRnGLGa:-O1ueWAt0FvvWBflSSiD:bbblhuc) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L217)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this comment correct? if so please add it
</blockquote></details>

~required~ requested

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1qdruo1PQIRklckVXS:-O1vMLmYC9e-qAbdtRyy:b5y35o6) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L209)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

> so if we actually get a leaf sibling, we can't know if the deserialization has been done correctly.

how can we incorrectly deserialize a leaf?
if it's not in storage we will get a missing key error from storage (in the future, everything should exist in storage anyway, just a matter of deciding to read or not); 
but if we don't get a missing key error, how will the deserialization be "done incorrectly"?
</blockquote></details>

you are right.
i added this assert to make sure that if we deserialize a leaf it's not a sibling. do you want me to remove this check?
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 217 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1ud_77AFQhlrRnGLGa:-O1vMf_65JnJ_IGgzySo:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L217)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

~required~ requested
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1qdruo1PQIRklckVXS:-O1vQk8IETwBygy7KHhU:b-2cr98e) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L209)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

you are right.
i added this assert to make sure that if we deserialize a leaf it's not a sibling. do you want me to remove this check?
</blockquote></details>

keep the check but just log a warning if the subtree is modified

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1qe4Mt6wPS__YA9ojL:-O1vRxVC-TX1q8OCqsun:bahhhab) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L219)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

not exactly.
`leaves` is not none in the case that we want also to return the previous leaves at the modified indices. It's independent of `config.compare_modified_leaves()` configuration.
</blockquote></details>

It's not indeoendent. If `config.compare_modified_leaves()` is True, then `previous_leaves` shouldn't be None in any case  (and if it is, it's an error), doesn't it? If it's False, then it should be None for one Tree and False for another.

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 219 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1qe4Mt6wPS__YA9ojL:-O1vVuBDAKyhonEixp1T:b1iwvam) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L219)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

It's not indeoendent. If `config.compare_modified_leaves()` is True, then `previous_leaves` shouldn't be None in any case  (and if it is, it's an error), doesn't it? If it's False, then it should be None for one Tree and False for another.
</blockquote></details>

Let's take the storage tries for example: `config.compare_modified_leaves()` is True, but `previous_leaves` is none.
the variable `previous_leaves` is used and returned when `create_and_get_previous_leaves` is called

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 209 at r1](https://reviewable.io/reviews/starkware-libs/committer/310#-O1qdruo1PQIRklckVXS:-O1v_IOs6fX7pLf-IzVV:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/017fb050f89edbb7aec471a262469179802330fb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L209)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

keep the check but just log a warning if the subtree is modified
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/310)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
