### PR TITLE
refactor(skeleton): split OriginalSkeletonTree impls

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/95)

### CODE REVIEW

**Review by TzahiTaub — COMMENTED** [review]
OriginalSkeletonTreeImpl definition moved to `tree.rs`. It delegates its methods to the create_tree and compute_updated_skeleton_tree modules (last moved from create_tree)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/95#-:-NxBvKJ79-evQ86KgmtZ:bh53j5g)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @amosStarkware and @nimrod-starkware)

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/95#-:-NxCGw5N1TLMIqivYQj0:bnfp4nl)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/95)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/committer/95#-NxCvqYx5rAmU2iRbmGd:-NxCvqYx5rAmU2iRbmGe:b-shwvck) ([raw file](https://github.com/starkware-libs/committer/blob/795cb12de8512ebc279a437e1aa7ae285588d3da/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L10)):*
> ```XML
> use crate::patricia_merkle_tree::updated_skeleton_tree::tree::UpdatedSkeletonTreeImpl;
> 
> use super::tree::OriginalSkeletonTreeResult;
> ```

please use full import

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/95)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 10 at r2](https://reviewable.io/reviews/starkware-libs/committer/95#-NxCvqYx5rAmU2iRbmGd:-NxD1_HB9vuB5vze_vjB:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/795cb12de8512ebc279a437e1aa7ae285588d3da/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L10)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please use full import
</blockquote></details>

Done.

**Review by amosStarkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/95)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
