### PR TITLE
fix: possible fix

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/263)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/263)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/committer/263#-O0jCESlC8qv0fGdLyN5:-O0jCESlC8qv0fGdLyN6:b-j2c21r) ([raw file](https://github.com/starkware-libs/committer/blob/3bebfc7f57f3a4a1a32c724494120819429511fc/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L102)):*
> ```XML
>             );
>         }
>         is_map_empty || has_empty_tree_root_hash
> ```

how about this?
is it logically equivalent?
```
        let is_map_empty = self.skeleton_tree.is_empty();
        match self.skeleton_tree.get(&NodeIndex::ROOT) {
            Some(UpdatedSkeletonNode::UnmodifiedSubTree(root_hash)) => root_hash == HashOutput::ROOT_OF_EMPTY_TREE,
            Some(_modified_root) => is_map_empty,
            None => {
                assert!(is_map_empty, "Non-empty tree must have a root node.");
                true
            }
        }
```



_Suggestion:_
```XML
        let is_map_empty = self.skeleton_tree.is_empty();
        match self.skeleton_tree.get(&NodeIndex::ROOT) {
            Some(UpdatedSkeletonNode::UnmodifiedSubTree(root_hash)) => root_hash == HashOutput::ROOT_OF_EMPTY_TREE,
            Some(_modified_root) => is_map_empty,
            None => {
                assert!(is_map_empty, "Non-empty tree must have a root node.");
                true
            }
        }
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/263)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/committer/263#-O0jCESlC8qv0fGdLyN5:-O0mNqkKB5l2NMIdXFHe:bvmo2j0) ([raw file](https://github.com/starkware-libs/committer/blob/3bebfc7f57f3a4a1a32c724494120819429511fc/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L102)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how about this?
is it logically equivalent?
```
        let is_map_empty = self.skeleton_tree.is_empty();
        match self.skeleton_tree.get(&NodeIndex::ROOT) {
            Some(UpdatedSkeletonNode::UnmodifiedSubTree(root_hash)) => root_hash == HashOutput::ROOT_OF_EMPTY_TREE,
            Some(_modified_root) => is_map_empty,
            None => {
                assert!(is_map_empty, "Non-empty tree must have a root node.");
                true
            }
        }
```
</blockquote></details>

Yes, I think it's equivalent; which way do you think is better?

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/263)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/committer/263#-O0mQbmt7bCHppz4If1v:-O0mQbmt7bCHppz4If1w:byg1iw9) ([raw file](https://github.com/starkware-libs/committer/blob/0959e5abb3e27901a3c8406ccc3523e4beda8a73/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L142)):*
> ```XML
>     assert_eq!(updated_skeleton_tree.skeleton_tree, expected_skeleton_tree);
> }
> ```

The test fails without the fix

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/263)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/committer/263#-O0jCESlC8qv0fGdLyN5:-O0mVzdLAAkkrJiQV3kv:b-l0r1yd) ([raw file](https://github.com/starkware-libs/committer/blob/3bebfc7f57f3a4a1a32c724494120819429511fc/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L102)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Yes, I think it's equivalent; which way do you think is better?
</blockquote></details>

my way (less lines).
Although, it may be a good idea to add a docstring explaining in words when this function returns true and when it doesn't
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/committer/263#-O0mQbmt7bCHppz4If1v:-O0mWFjGB0dAE_yCzfNQ:biv6jks) ([raw file](https://github.com/starkware-libs/committer/blob/0959e5abb3e27901a3c8406ccc3523e4beda8a73/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L142)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

The test fails without the fix
</blockquote></details>

can you add a test case where we have a modification that deletes a (already empty) leaf? or will this fail the current PR

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/263)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 102 at r1](https://reviewable.io/reviews/starkware-libs/committer/263#-O0jCESlC8qv0fGdLyN5:-O0mYLj1-5UkaCBpB_mp:bpwyan5) ([raw file](https://github.com/starkware-libs/committer/blob/3bebfc7f57f3a4a1a32c724494120819429511fc/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L102)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

my way (less lines).
Although, it may be a good idea to add a docstring explaining in words when this function returns true and when it doesn't
</blockquote></details>

Done.
There is a docstring in the trait, so I added a comment (with '//')
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 142 at r2](https://reviewable.io/reviews/starkware-libs/committer/263#-O0mQbmt7bCHppz4If1v:-O0mYzQ88GZQqzqLBVaW:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/0959e5abb3e27901a3c8406ccc3523e4beda8a73/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L142)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you add a test case where we have a modification that deletes a (already empty) leaf? or will this fail the current PR
</blockquote></details>

Done

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/263#-:-O0meVpU1K1Es6OkD_y5:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
