### PR TITLE
build: add get_root_hash for filled tree

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/31)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/31#-:-Nv6c6ue9csLNKyhd_hz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/committer/31#-Nv6c-eq6SvdKomHzUyk:-Nv6c-eq6SvdKomHzUyl:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/6b6dada8b15aab49a120d015ae871a3745393ed4/crates/committer/src/patricia_merkle_tree/filled_tree.rs#L35)):*
> ```XML
>     fn get_root_hash(&self) -> Result<HashOutput, FilledTreeError> {
>         match self.tree_map.get(&NodeIndex::root_index()) {
>             Some(root_node) => Ok(root_node.lock().expect("Lock poisned.").hash),
> ```

typo



_Code quote:_
```XML
poisned
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/31)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @aner-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/31)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`Cargo.toml` line 19 at r3](https://reviewable.io/reviews/starkware-libs/committer/31#-Nv78GHP6_7QfNI_K3hm:-Nv78GHP6_7QfNI_K3hn:b-oxwbeb) ([raw file](https://github.com/starkware-libs/committer/blob/436b95672b5a6dcadfdeb24a413c301550fc8640/Cargo.toml#L19)):*
> ```TOML
> rstest = "0.17.0"
> starknet-types-core = { version = "0.0.11", features = ["hash"] }
> derive_more = "0.99.17"
> ```

lexicographic order of dependencies



_Suggestion:_
```TOML
derive_more = "0.99.17"
pretty_assertions = "1.2.1"
rstest = "0.17.0"
starknet-types-core = { version = "0.0.11", features = ["hash"] }
```
___
*[`crates/committer/Cargo.toml` line 18 at r3](https://reviewable.io/reviews/starkware-libs/committer/31#-Nv78LRX-F8qu6RO-8DH:-Nv78LRX-F8qu6RO-8DI:b-mjb8nb) ([raw file](https://github.com/starkware-libs/committer/blob/436b95672b5a6dcadfdeb24a413c301550fc8640/crates/committer/Cargo.toml#L18)):*
> ```TOML
> [dependencies]
> starknet-types-core.workspace = true
> derive_more.workspace = true
> ```

alphabetize... sorry, forgot before



_Suggestion:_
```TOML
derive_more.workspace = true
starknet-types-core.workspace = true
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/31)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`Cargo.toml` line 19 at r3](https://reviewable.io/reviews/starkware-libs/committer/31#-Nv78GHP6_7QfNI_K3hm:-Nv7A3rt9jo4jRqr3lTK:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/436b95672b5a6dcadfdeb24a413c301550fc8640/Cargo.toml#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

lexicographic order of dependencies
</blockquote></details>

Done.
___
*[`crates/committer/Cargo.toml` line 18 at r3](https://reviewable.io/reviews/starkware-libs/committer/31#-Nv78LRX-F8qu6RO-8DH:-Nv7A34c9dgXvDxTabJB:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/436b95672b5a6dcadfdeb24a413c301550fc8640/crates/committer/Cargo.toml#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

alphabetize... sorry, forgot before
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/31)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
