### PR TITLE
test(skeleton): tests for Updated_skeletonTree create

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/209)

### CODE REVIEW

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/209)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-Nzwh4je72rRH6Fw7GKQ:-Nzwh4je72rRH6Fw7GKR:bkprgfq) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L30)):*
> ```XML
> fn initial_updated_skeleton(
>     #[default(&[])] original_skeleton: &[(NodeIndex, OriginalSkeletonNode)],
>     #[default(&[])] leaf_modifications: &[(NodeIndex, u8)],
> ```

Replaced the U256 with the more convinient NodeINdex (as I usually use NodeIndex::FIRST_LEAF) - caused a few adjustments in the rest of this module.



_Code quote:_
```XML
[(NodeIndex
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/209)* status: all files reviewed, 13 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxOPi9BJ5nf1PUXG6Q:-NzxOPi9BJ5nf1PUXG6R:b189vq5) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/test_utils.rs#L125)):*
> ```XML
>     crate::patricia_merkle_tree::updated_skeleton_tree::tree::UpdatedSkeletonTreeImpl,
> };
> #[cfg(test)]
> ```

why is this needed? the entire module should be gated; remove the `cfg`s and move the `use`s to the top.
(I know you're not the first; I would rather not make the issue worse. if there is a compilation issue with this please confer with @AvivYossef-starkware ; if it's out of scope of this PR then nvm)



_Code quote:_
```XML
#[cfg(test)]
use {
    crate::patricia_merkle_tree::original_skeleton_tree::node::OriginalSkeletonNode,
    crate::patricia_merkle_tree::updated_skeleton_tree::node::UpdatedSkeletonNode,
    crate::patricia_merkle_tree::updated_skeleton_tree::tree::UpdatedSkeletonTreeImpl,
};
#[cfg(test)]
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxQUjN6I1lLYUJICz3:-NzxQUjN6I1lLYUJICz4:b-su3pii) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/test_utils.rs#L126)):*
> ```XML
> };
> #[cfg(test)]
> pub(crate) fn get_initial_updated_skeleton(
> ```

docstring please.
what is an "initial updated skeleton"?



_Code quote:_
```XML
get_initial_updated_skeleton
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxOvCR5nvx4B9OVNS1:-NzxOvCR5nvx4B9OVNS2:b-5blb4m) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/test_utils.rs#L134)):*
> ```XML
>             .iter()
>             .filter(|(_, leaf_val)| *leaf_val != 0)
>             .map(|(index, _)| (*index, UpdatedSkeletonNode::Leaf))
> ```

if you use `filter_map` is it less lines? non-blocking



_Code quote:_
```XML
            .filter(|(_, leaf_val)| *leaf_val != 0)
            .map(|(index, _)| (*index, UpdatedSkeletonNode::Leaf))
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxPINCD6-hksv2jAkL:-NzxPINCD6-hksv2jAkM:b-n9iabu) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L206)):*
> ```XML
>     #[case] expected_node: TempSkeletonNode,
>     #[case] expected_skeleton_additions: &[(NodeIndex, UpdatedSkeletonNode)],
>     #[with(&[], _leaf_modifications)] mut initial_updated_skeleton: UpdatedSkeletonTreeImpl,
> ```

are you sure clippy doesn't allow removing the leading underscores...? you *are* using this variable in an attribute macro



_Code quote:_
```XML
    #[case] _leaf_modifications: &[(NodeIndex, u8)],
    #[case] expected_node: TempSkeletonNode,
    #[case] expected_skeleton_additions: &[(NodeIndex, UpdatedSkeletonNode)],
    #[with(&[], _leaf_modifications)] mut initial_updated_skeleton: UpdatedSkeletonTreeImpl,
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxQDS_9lMUUabVg9iP:-NzxQDS_9lMUUabVg9iQ:b-h1j3wx) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L24)):*
> ```XML
> #[rstest]
> #[should_panic]
> #[case::empty_to_empty_illegal_modifications(&[], &[(NodeIndex::FIRST_LEAF, 0)], &[])]
> ```

why should this panic?
this is a special case of "no diff"; we said this morning we want to support this.



_Code quote:_
```XML
#[should_panic]
#[case::empty_to_empty_illegal_modifications(&[], &[(NodeIndex::FIRST_LEAF, 0)], &[])]
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxQsOBEarE9sswK3qg:-NzxQsOBEarE9sswK3qh:b-kfb7rd) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L28)):*
> ```XML
>     &[],
>     &[(NodeIndex::FIRST_LEAF, 1)],
>     &[(NodeIndex::ROOT, UpdatedSkeletonNode::Edge(PathToBottom::from("0".repeat(251).as_str())))],
> ```

no magic numbers; use the constant tree height



_Code quote:_
```XML
251
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxQwZU85KprqsG_aO7:-NzxQwZU85KprqsG_aO8:b-kfb7rd) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L35)):*
> ```XML
>     &([
>         (NodeIndex::FIRST_LEAF >> 1, UpdatedSkeletonNode::Binary),
>         (NodeIndex::ROOT, UpdatedSkeletonNode::Edge(PathToBottom::from("0".repeat(250).as_str()))),
> ```

no magic numbers; use the constant tree height



_Code quote:_
```XML
250
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxR-4g33vBI-yRiv72:-NzxR-4g33vBI-yRiv73:b-8y65z7) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L41)):*
> ```XML
>     &[
>         (NodeIndex::ROOT,
>         OriginalSkeletonNode::Edge(PathToBottom::from("0".repeat(251).as_str())),
> ```

no magic numbers; use the constant tree height (I know it's old, sorry)



_Code quote:_
```XML
251
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxRF9Y2dEHQ2wqINsQ:-NzxRF9Y2dEHQ2wqINsR:b-kfb7rd) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L49)):*
> ```XML
>     &[
>         (NodeIndex::ROOT,
>         OriginalSkeletonNode::Edge(PathToBottom::from("0".repeat(251).as_str())),
> ```

no magic numbers; use the constant tree height



_Code quote:_
```XML
251
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxRIh3BVzzk_Qksmsu:-NzxRIh42CfaG5wyFZ8G:b-kfb7rd) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L56)):*
> ```XML
>     ],
>     &[
>         (NodeIndex::ROOT, UpdatedSkeletonNode::Edge(PathToBottom::from("0".repeat(250).as_str()))),
> ```

no magic numbers; use the constant tree height



_Code quote:_
```XML
250
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxRMSLDdDyPH6GtiLw:-NzxRMSLDdDyPH6GtiLx:b-kfb7rd) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L64)):*
> ```XML
>     &[
>         (NodeIndex::ROOT,
>         OriginalSkeletonNode::Edge(PathToBottom::from("0".repeat(251).as_str())),
> ```

no magic numbers; use the constant tree height



_Code quote:_
```XML
251
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxRNdj1K4x2UWln9zx:-NzxRNdj1K4x2UWln9zy:b-kfb7rd) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L71)):*
> ```XML
>     ],
>     &[
>         (NodeIndex::ROOT, UpdatedSkeletonNode::Edge(PathToBottom::from(("0".repeat(250)+"1").as_str()))),
> ```

no magic numbers; use the constant tree height



_Code quote:_
```XML
250
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxPetZ7hfWdV0hTczu:-NzxPetZ7hfWdV0hTczv:b-n1iufw) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L76)):*
> ```XML
> )]
> 
> fn test_updated_skeleton_tree_impl_create(
> ```

delete newline



_Suggestion:_
```XML
)]
fn test_updated_skeleton_tree_impl_create(
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/209)* status: all files reviewed, 13 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxOPi9BJ5nf1PUXG6Q:-NzxRpMO8wzQfwrNe6fw:bq91d3b) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/test_utils.rs#L125)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this needed? the entire module should be gated; remove the `cfg`s and move the `use`s to the top.
(I know you're not the first; I would rather not make the issue worse. if there is a compilation issue with this please confer with @AvivYossef-starkware ; if it's out of scope of this PR then nvm)
</blockquote></details>

I opened Pr to split between test and testing
https://github.com/starkware-libs/committer/pull/211#issuecomment-2156525519

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/209)* status: all files reviewed, 13 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxOPi9BJ5nf1PUXG6Q:-NzxSGmMC8PHHQM4eGfB:bnq9oez) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/test_utils.rs#L125)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

I opened Pr to split between test and testing
https://github.com/starkware-libs/committer/pull/211#issuecomment-2156525519
</blockquote></details>

https://github.com/starkware-libs/committer/pull/211#issuecomment-2156525519

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/209)* status: all files reviewed, 13 unresolved discussions (waiting on @AvivYossef-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxOPi9BJ5nf1PUXG6Q:-NzxUdbFEVcX2jrdpztB:b-rdhhmt) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/test_utils.rs#L125)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

https://github.com/starkware-libs/committer/pull/211#issuecomment-2156525519
</blockquote></details>

ping me when it's merged and you rebased?

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/209)* status: all files reviewed, 11 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 206 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxPINCD6-hksv2jAkL:-O-G6smaAla9LdhayBGN:b-tokstv) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L206)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

are you sure clippy doesn't allow removing the leading underscores...? you *are* using this variable in an attribute macro
</blockquote></details>

Yep (it's not just clippy, it's a warning in the builtin compiler lints)
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 24 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxQDS_9lMUUabVg9iP:-O-GKtLC9zVR6bMW2u-m:b-hi43qv) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L24)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why should this panic?
this is a special case of "no diff"; we said this morning we want to support this.
</blockquote></details>

Added support (hopefully for all cases) - + added two tests.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxQsOBEarE9sswK3qg:-O-GMa4D9sgAFNMkjNQr:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L28)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no magic numbers; use the constant tree height
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 35 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxQwZU85KprqsG_aO7:-O-GMaRfACCjQX_M2wWr:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L35)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no magic numbers; use the constant tree height
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxR-4g33vBI-yRiv72:-O-GMamd6WIT7-iipZyZ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no magic numbers; use the constant tree height (I know it's old, sorry)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxRF9Y2dEHQ2wqINsQ:-O-GMb4O7c17UNbmS72-:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no magic numbers; use the constant tree height
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxRIh3BVzzk_Qksmsu:-O-GMbPE32m3OlXU5ZEF:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no magic numbers; use the constant tree height
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 64 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxRMSLDdDyPH6GtiLw:-O-GMbiV3vvlsgy-n-o8:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L64)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no magic numbers; use the constant tree height
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxRNdj1K4x2UWln9zx:-O-GMc3G6Ny5DxOgvNFZ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L71)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no magic numbers; use the constant tree height
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxPetZ7hfWdV0hTczu:-O-GMdqe-oJ9s6hl-KQv:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L76)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete newline
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 126 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxQUjN6I1lLYUJICz3:-O-G5fJQ2Cj1h59W2Vx7:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/test_utils.rs#L126)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

docstring please.
what is an "initial updated skeleton"?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 134 at r1](https://reviewable.io/reviews/starkware-libs/committer/209#-NzxOvCR5nvx4B9OVNS1:-O-G6E2YD-WIi_r0DiVZ:bm65e89) ([raw file](https://github.com/starkware-libs/committer/blob/02c1a04ee24521ad08a82524cdef7564e1677659/crates/committer/src/patricia_merkle_tree/test_utils.rs#L134)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you use `filter_map` is it less lines? non-blocking
</blockquote></details>

Nope, unless I'm doing it wrong.
```
 .filter_map(|(index, leaf_val)| {
      if *leaf_val != 0 {
           Some((*index, UpdatedSkeletonNode::Leaf))
       } else {
            None
})
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/209)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/Cargo.toml` line 37 at r2](https://reviewable.io/reviews/starkware-libs/committer/209#-O-GeEYY2NEDHavJdnxL:-O-GeEYY2NEDHavJdnxM:bo8agpk) ([raw file](https://github.com/starkware-libs/committer/blob/a03b1f42879a5e88369d13accf4af3919bc9c50a/crates/committer/Cargo.toml#L37)):*
> ```TOML
> 
> [target.'cfg(test)'.features]
> default = ["testing"]
> ```

@TzahiTaub @AvivYossef-starkware on second thought I think this should be removed... every module should be explicitly marked as Tzahi did below



_Code quote:_
```TOML
[target.'cfg(test)'.features]
default = ["testing"]
```
___
*[`crates/committer/src/patricia_merkle_tree.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/committer/209#-O-Gdyp8-vGrNW1kLSmL:-O-Gdyp8-vGrNW1kLSmM:b6k0x4w) ([raw file](https://github.com/starkware-libs/committer/blob/a03b1f42879a5e88369d13accf4af3919bc9c50a/crates/committer/src/patricia_merkle_tree.rs#L11)):*
> ```XML
> pub mod internal_test_utils;
> 
> #[cfg(any(feature = "testing", test))]
> ```

IIUC this makes @AvivYossef-starkware 's work redundant... please sync
@AvivYossef-starkware now that i think of it, adding a cargo rule to couple `test` and `testing` is not as good as explicitly marking each module with the correct gate...



_Code quote:_
```XML
#[cfg(any(feature = "testing", test))]
```
___
*[`crates/committer/src/patricia_merkle_tree/internal_test_utils.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/committer/209#-O-GeTGJ-pNghCDQUCng:-O-GeTGJ-pNghCDQUCnh:b-rtagwg) ([raw file](https://github.com/starkware-libs/committer/blob/a03b1f42879a5e88369d13accf4af3919bc9c50a/crates/committer/src/patricia_merkle_tree/internal_test_utils.rs#L95)):*
> ```XML
> }
> 
> #[cfg(test)]
> ```

delete



_Code quote:_
```XML
#[cfg(test)]
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/209)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/committer/Cargo.toml` line 37 at r2](https://reviewable.io/reviews/starkware-libs/committer/209#-O-GeEYY2NEDHavJdnxL:-O-Gk47P7bqbbdunVY5Z:b-l3dohr) ([raw file](https://github.com/starkware-libs/committer/blob/a03b1f42879a5e88369d13accf4af3919bc9c50a/crates/committer/Cargo.toml#L37)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@TzahiTaub @AvivYossef-starkware on second thought I think this should be removed... every module should be explicitly marked as Tzahi did below
</blockquote></details>

See comment below (unblock please).
___
*[`crates/committer/src/patricia_merkle_tree.rs` line 11 at r2](https://reviewable.io/reviews/starkware-libs/committer/209#-O-Gdyp8-vGrNW1kLSmL:-O-GjapC9jtBIWZVawjS:b-se03ur) ([raw file](https://github.com/starkware-libs/committer/blob/a03b1f42879a5e88369d13accf4af3919bc9c50a/crates/committer/src/patricia_merkle_tree.rs#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

IIUC this makes @AvivYossef-starkware 's work redundant... please sync
@AvivYossef-starkware now that i think of it, adding a cargo rule to couple `test` and `testing` is not as good as explicitly marking each module with the correct gate...
</blockquote></details>

Talked with @AvivYossef-starkware , the change he did (the `target cfg(rest)`) is not working as expected and doesn't match the docs. I think handling this issue should be done in a separate PR dedicated for this. Can you unblock here?
___
*[`crates/committer/src/patricia_merkle_tree/internal_test_utils.rs` line 95 at r2](https://reviewable.io/reviews/starkware-libs/committer/209#-O-GeTGJ-pNghCDQUCng:-O-GkJzX3PPByrXbe6sW:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/a03b1f42879a5e88369d13accf4af3919bc9c50a/crates/committer/src/patricia_merkle_tree/internal_test_utils.rs#L95)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/209#-:-O-Gr34E6oDDkv0Lc-Cq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
