### PR TITLE
fix: post only benchmarks that regressed or improved

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/265)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/265)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/265)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

___
*[`.github/workflows/ci.yml` line 172 at r2](https://reviewable.io/reviews/starkware-libs/committer/265#-O0rZIeG64CFs2Dqxxhz:-O0rZIeG64CFs2Dqxxi-:bqlavdy) ([raw file](https://github.com/starkware-libs/committer/blob/c77e60ec7c746e90f1c3509b391214a372602b30/.github/workflows/ci.yml#L172)):*
> ```YAML
>                 fi;
>               done
>       - run: echo BENCHES_RESULT=$(cat bench_new.txt) >> $GITHUB_ENV
> ```

can you extract this logic to a bash script in the repo, and invoke the script here?
would prefer keeping the ci.yml thin



_Code quote:_
```YAML
      # Benchmark the new code, splitting the benchmarks.
      # TODO: split the output file instead.
      - run: cat benchmarks_list.txt |
              while read line; do
                cargo bench $line > ${line}.txt;
                sed -i '/'"${line}"'/,$!d' ${line}.txt;
              done

      # Prepare the results for posting comment.
      - run: echo "Benchmark movements:" > bench_new.txt
      - run: cat benchmarks_list.txt |
              while read line; do
                if grep -q "regressed" ${line}.txt; then
                  echo "**${line} performance regressed!**" >> bench_new.txt;
                  cat ${line}.txt >> bench_new.txt;
                elif grep -q "improved" ${line}.txt; then
                  echo "_${line} performance improved_ :smiley_cat:" >> bench_new.txt;
                  cat ${line}.txt >> bench_new.txt;
                fi;
              done
      - run: echo BENCHES_RESULT=$(cat bench_new.txt) >> $GITHUB_ENV
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/265)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`.github/workflows/ci.yml` line 172 at r2](https://reviewable.io/reviews/starkware-libs/committer/265#-O0rZIeG64CFs2Dqxxhz:-O0sJOy48TA9hP2EFfUl:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/c77e60ec7c746e90f1c3509b391214a372602b30/.github/workflows/ci.yml#L172)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you extract this logic to a bash script in the repo, and invoke the script here?
would prefer keeping the ci.yml thin
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/265)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer_cli/benches/bench_split_and_prepare_post.sh` line 3 at r3](https://reviewable.io/reviews/starkware-libs/committer/265#-O0t1Vg9-pcJBxZm05SC:-O0t1Vg9-pcJBxZm05SD:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/7f84000b4271c8e6cab7c09c74bf0f1840a2c109/crates/committer_cli/benches/bench_split_and_prepare_post.sh#L3)):*
> ```Shell
> # Benchmark the new code, splitting the benchmarks
> # TODO: split the output file instead.
> cat ${1} |
> ```





_Suggestion:_
```Shell
#!/bin/env bash

set -e

# Benchmark the new code, splitting the benchmarks
# TODO: split the output file instead.
cat ${1} |
```

**Comment by aner-starkware** [comment]
*[`crates/committer_cli/benches/bench_split_and_prepare_post.sh` line 3 at r3](https://reviewable.io/reviews/starkware-libs/committer/265#-O0t1Vg9-pcJBxZm05SC:-O0tqjYfAu21ir8zWB8n:basl5hx) ([raw file](https://github.com/starkware-libs/committer/blob/7f84000b4271c8e6cab7c09c74bf0f1840a2c109/crates/committer_cli/benches/bench_split_and_prepare_post.sh#L3)):*
> ```Shell
> # Benchmark the new code, splitting the benchmarks
> # TODO: split the output file instead.
> cat ${1} |
> ```

What is it?

**Comment by aner-starkware** [comment]
*[`crates/committer_cli/benches/bench_split_and_prepare_post.sh` line 3 at r3](https://reviewable.io/reviews/starkware-libs/committer/265#-O0t1Vg9-pcJBxZm05SC:-O0tuYo62reA5OJcEAGe:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7f84000b4271c8e6cab7c09c74bf0f1840a2c109/crates/committer_cli/benches/bench_split_and_prepare_post.sh#L3)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

What is it?
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/265#-:-O0wUm-j5-LHFbCqJdUY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/committer_cli/benches/bench_split_and_prepare_post.sh` line 3 at r3](https://reviewable.io/reviews/starkware-libs/committer/265#-O0t1Vg9-pcJBxZm05SC:-O0wUfDtBcQofanvG7T7:bfsz0i6) ([raw file](https://github.com/starkware-libs/committer/blob/7f84000b4271c8e6cab7c09c74bf0f1840a2c109/crates/committer_cli/benches/bench_split_and_prepare_post.sh#L3)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`set -e` should stop and exit on first error

**Pull request merged**
