### PR TITLE
fix: create of empty tree

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/255)

### CODE REVIEW

**Review by AvivYossef-starkware — COMMENTED** [review]
python side https://github.com/starkware-industries/starkware/pull/35343

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/255#-:-O0cDnzb71-v6h9EWyYZ:b-kkwcxx)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/255)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cQYny7rJZXkgwss4O:-O0cQYny7rJZXkgwss4P:bm7ezo8) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L214)):*
> ```XML
>             root_hash: HashOutput::ROOT_OF_EMPTY_TREE,
>         })
>     }
> ```

This function cannot fail. Then IMO it should not return `Result`



_Suggestion:_
```XML
    fn create_empty() -> Self {
        Self {
            tree_map: HashMap::new(),
            root_hash: HashOutput::ROOT_OF_EMPTY_TREE,
        }
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 230 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cQmWF41WxCBOqkktk:-O0cQmWF41WxCBOqkktl:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L230)):*
> ```XML
> 
>         if updated_skeleton.is_empty() {
>             return Self::create_empty();
> ```





_Suggestion:_
```XML
return Ok(Self::create_empty());
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cPFRR-P2WeGVME4Id:-O0cPFRR-P2WeGVME4Ie:bwm7wmb) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs#L256)):*
> ```XML
>         HashOutput::ROOT_OF_EMPTY_TREE,
>         &[NodeIndex::FIRST_LEAF],
>         &OriginalSkeletonContractsTrieConfig,
> ```

Why this config?
The modifications are for a storage trie.



_Suggestion:_
```XML
OriginalSkeletonStorageTrieConfig::new(leaf_modifications, false)
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs` line 260 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cPvV10YDy2_7Fzfmv:-O0cPvV10YDy2_7Fzfmw:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs#L260)):*
> ```XML
>     .unwrap();
> 
>     // Create an updated skeleton tree with a single leaf that is deleted
> ```





_Suggestion:_
```XML
// Create an updated skeleton tree with a single leaf that is deleted.
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cP3gjDRK0YFrCzpKF:-O0cP3gjDRK0YFrCzpKG:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs#L279)):*
> ```XML
>     assert!(filled_tree_map.is_empty());
>     let root_hash = filled_tree.get_root_hash();
>     assert!(root_hash == HashOutput(Felt::ZERO));
> ```





_Suggestion:_
```XML
assert!(root_hash == HashOutput::ROOT_OF_EMPTY_TREE);
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/255)* status: all files reviewed, 8 unresolved discussions (waiting on @AvivYossef-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cctps8MW47fI553M9:-O0cctps8MW47fI553MA:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs#L247)):*
> ```XML
> 
> #[tokio::test(flavor = "multi_thread")]
> /// Test the case where trying to delete a leaf that does not exist in the tree.
> ```





_Suggestion:_
```XML
Test that deleting a leaf that does not exist in the tree succeeds.
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs` line 249 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0ccmpRBMw6VkMAo-de:-O0ccmpRBMw6VkMAo-df:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs#L249)):*
> ```XML
> /// Test the case where trying to delete a leaf that does not exist in the tree.
> async fn test_delete_leaf_from_empty_tree() {
>     // Crate an empty original skeleton tree with a single leaf modified.
> ```

typo



_Suggestion:_
```XML
Create
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs` line 266 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cf2Ab5AuNkGdYHVlz:-O0cf2Ab5AuNkGdYHVm-:b-z9rfoe) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs#L266)):*
> ```XML
> 
>     let leaf_modifications =
>         HashMap::from([(NodeIndex::FIRST_LEAF, StarknetStorageValue(Felt::ZERO))]);
> ```

for clarity (two modification maps)



_Suggestion:_
```XML
    let skeleton_modifications = HashMap::from([(NodeIndex::FIRST_LEAF, SkeletonLeaf::Zero)]);
    let updated_skeleton_tree =
        UpdatedSkeletonTreeImpl::create(&mut original_skeleton_tree, &modifications).unwrap();

    let leaf_modifications =
        HashMap::from([(NodeIndex::FIRST_LEAF, StarknetStorageValue(Felt::ZERO))]);
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/255)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 214 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cQYny7rJZXkgwss4O:-O0cRkre9mLiARgx7XDp:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L214)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

This function cannot fail. Then IMO it should not return `Result`
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 230 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cQmWF41WxCBOqkktk:-O0cbb2h8Di6zZic-lXT:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L230)):*
> ```XML
> 
>         if updated_skeleton.is_empty() {
>             return Self::create_empty();
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs` line 247 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cctps8MW47fI553M9:-O0ch9HR-KNJfs4rmiLm:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs#L247)):*
> ```XML
> 
> #[tokio::test(flavor = "multi_thread")]
> /// Test the case where trying to delete a leaf that does not exist in the tree.
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cPFRR-P2WeGVME4Id:-O0cgyc901uGTvc_4vl9:bdmef4k) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs#L256)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Why this config?
The modifications are for a storage trie.
</blockquote></details>

Plz let me know if it's ok now, I'm not really understand what is tree config and why its needed
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs` line 260 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cPvV10YDy2_7Fzfmv:-O0chDu12FNBJ4ikg7qR:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs#L260)):*
> ```XML
>     .unwrap();
> 
>     // Create an updated skeleton tree with a single leaf that is deleted
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs` line 266 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cf2Ab5AuNkGdYHVlz:-O0chULz2kMgLZaS9wFO:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs#L266)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

for clarity (two modification maps)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs` line 279 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cP3gjDRK0YFrCzpKF:-O0chbGDEMrkbH3PpTi8:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs#L279)):*
> ```XML
>     assert!(filled_tree_map.is_empty());
>     let root_hash = filled_tree.get_root_hash();
>     assert!(root_hash == HashOutput(Felt::ZERO));
> ```

Done.

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/255#-:-O0cnIVJ6NYS4YBPcaAF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs` line 256 at r1](https://reviewable.io/reviews/starkware-libs/committer/255#-O0cPFRR-P2WeGVME4Id:-O0cml-eEC9d_MtYqaLt:b-hgkuv0) ([raw file](https://github.com/starkware-libs/committer/blob/0967be95495be2715c0034a068fcea3ee3271eb9/crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs#L256)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Plz let me know if it's ok now, I'm not really understand what is tree config and why its needed
</blockquote></details>

it's fine :)
it's a user configuration that will configure whether to log out a warning or not when enocuntering a trivial state diff.
for each tree type we have different configuration

**Pull request merged**
