### PR TITLE
test: test_tree_with_sibling_nodes

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/53)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/53)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/committer/53#-NwDxS1b7WEqxBaVLaXO:-NwDxS1b7WEqxBaVLaXP:b8e283w) ([raw file](https://github.com/starkware-libs/committer/blob/a8978751fba69103a19b461148a59f0f38eb09b5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L185)):*
> ```XML
> ///            \            
> ///         i=35: leaf   
> ///            v=1    
> ```

PTAL at `create_X_entry_for_testing` functions (for `X` in `{binary, edge, leaf}`).
These test utils are for filled nodes, but it would help if you create helper functions for skeleton nodes as well - will be useful here, may reduce boilerplate and lines in this current test
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 198 at r2](https://reviewable.io/reviews/starkware-libs/committer/53#-NwDxhl45xhyV5FFCdQr:-NwDxhl45xhyV5FFCdQs:b-rpzews) ([raw file](https://github.com/starkware-libs/committer/blob/a8978751fba69103a19b461148a59f0f38eb09b5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L198)):*
> ```XML
>         },
>     );
>     // A sibling node with hash value 0x2955a96b09495fb2ce4ed65cf679c54e54aefc2c6972d7f3042590000bb7543
> ```

redundant comment IMO, and it's a shame to write the hash value several times (comment maintenance).
non blocking



_Code quote:_
```XML
// A sibling node with hash value 0x2955a96b09495fb2ce4ed65cf679c54e54aefc2c6972d7f3042590000bb7543
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 216 at r2](https://reviewable.io/reviews/starkware-libs/committer/53#-NwDxvQJ4PgHGDq6-5Pr:-NwDxvQJ4PgHGDq6-5Ps:bjdqao8) ([raw file](https://github.com/starkware-libs/committer/blob/a8978751fba69103a19b461148a59f0f38eb09b5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L216)):*
> ```XML
>         },
>     );
>     // A sibling node with hash value 0x39eb7b85bcc9deac314406d6b73154b09b008f8af05e2f58ab623f4201d0b88
> ```

redundant



_Code quote:_
```XML
// A sibling node with hash value 0x39eb7b85bcc9deac314406d6b73154b09b008f8af05e2f58ab623f4201d0b88
```

**Comment by aner-starkware** [comment]
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/committer/53#-NwDxS1b7WEqxBaVLaXO:-NwEjURqCLOx6d3-I-eL:b-326nr6) ([raw file](https://github.com/starkware-libs/committer/blob/a8978751fba69103a19b461148a59f0f38eb09b5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L185)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

PTAL at `create_X_entry_for_testing` functions (for `X` in `{binary, edge, leaf}`).
These test utils are for filled nodes, but it would help if you create helper functions for skeleton nodes as well - will be useful here, may reduce boilerplate and lines in this current test
</blockquote></details>

Like this? Should I modify the test above the same way?

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/53)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @aner-starkware, and @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/node.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/committer/53#-NwEvzzx5M5VSnHmIKGe:-NwEvzzx5M5VSnHmIKGf:b-4b65k) ([raw file](https://github.com/starkware-libs/committer/blob/b95795a49a45275086be6de889da841eefb06df1/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/node.rs#L6)):*
> ```XML
> 
> #[allow(dead_code)]
> #[derive(Clone, Copy)]
> ```

since you had to add the derive I'm guessing this code isn't dead anymore? non-blocking



_Suggestion:_
```XML
#[derive(Clone, Copy)]
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/committer/53#-NwDxS1b7WEqxBaVLaXO:-NwEvsNG7B0BNJbo8UFK:b-m4hj4x) ([raw file](https://github.com/starkware-libs/committer/blob/a8978751fba69103a19b461148a59f0f38eb09b5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L185)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Like this? Should I modify the test above the same way?
</blockquote></details>

if it makes sense and reduces boilerplate, yes please :)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/53#-:-NwEw5DO-Gf4pdL7V66L:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @aner-starkware, and @AvivYossef-starkware)

**Comment by aner-starkware** [comment]
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/node.rs` line 6 at r3](https://reviewable.io/reviews/starkware-libs/committer/53#-NwEvzzx5M5VSnHmIKGe:-NwF-wceBhoheYsK5dQU:bm6v7zq) ([raw file](https://github.com/starkware-libs/committer/blob/b95795a49a45275086be6de889da841eefb06df1/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/node.rs#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

since you had to add the derive I'm guessing this code isn't dead anymore? non-blocking
</blockquote></details>

I used it in a test, so I don't think it would have been related, but actually, I didn't need the clone in the end.

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/53)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @AvivYossef-starkware, and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs` line 185 at r2](https://reviewable.io/reviews/starkware-libs/committer/53#-NwDxS1b7WEqxBaVLaXO:-NwF0y966d5IypqHxPeq:bm3yqt3) ([raw file](https://github.com/starkware-libs/committer/blob/a8978751fba69103a19b461148a59f0f38eb09b5/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs#L185)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if it makes sense and reduces boilerplate, yes please :)
</blockquote></details>

OK, done.

**Pull request merged**
