### PR TITLE
feat(block_hash): read and write from file

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/231)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/231)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @TzahiTaub, and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/231#-O-fqc631eQ98fVFgNRq:-O-fqc631eQ98fVFgNRr:biqgy) (no related file):*
python side PR? this is an API change for the CLI

___
___
*[`crates/committer_cli/src/main.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/committer/231#-O-fpzIuC6zPsBGlpEOF:-O-fpzIuC6zPsBGlpEOG:b-cktnp4) ([raw file](https://github.com/starkware-libs/committer/blob/46ce7b7b7447ba6ea08d73cfa84f5e3a7c869ac8/crates/committer_cli/src/main.rs#L60)):*
> ```XML
> 
> #[derive(Debug, Args)]
> struct GlobalOptions {}
> ```

try this and see if it works (i.e. the input args are as before)?
better code reuse



_Suggestion:_
```XML
enum Command {
    /// Calculates commitments needed for the block hash.
    BlockHashCommitments {
        #[clap(flatten)]
        io_args: IoArgs,
    },
    /// Given previous state tree skeleton and a state diff, computes the new commitment.
    Commit {
        #[clap(flatten)]
        io_args: IoArgs,
    },
    PythonTest {
        /// Test name.
        #[clap(long)]
        test_name: String,

        /// Test inputs as a json.
        #[clap(long)]
        inputs: Option<String>,
    },
}

#[derive(Debug, Args)]
struct IoArgs {
    /// File path to input.
    #[clap(long, short = 'i', default_value = "stdin")]
    input_path: String,

    /// File path to output.
    #[clap(long, short = 'o', default_value = "stdout")]
    output_path: String,
}

#[derive(Debug, Args)]
struct GlobalOptions {}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/231)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @TzahiTaub, and @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/231#-O-fqc631eQ98fVFgNRq:-O-fqmhlEcI9VuGj6SFh:b-mgoy9v) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

python side PR? this is an API change for the CLI
</blockquote></details>

nvm, found it

___

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/231)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer_cli/src/main.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/committer/231#-O-fpzIuC6zPsBGlpEOF:-O-jMVpP6YtF0qwDsVd-:b-yinutb) ([raw file](https://github.com/starkware-libs/committer/blob/46ce7b7b7447ba6ea08d73cfa84f5e3a7c869ac8/crates/committer_cli/src/main.rs#L60)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

try this and see if it works (i.e. the input args are as before)?
better code reuse
</blockquote></details>

Nice!
done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/231#-:-O-k4KMFBnyvBi2TuTJM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @TzahiTaub)

**Pull request merged**
