### PR TITLE
chore(skeleton): update_edge_node in updated_skeleton

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/164)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/164)* status: all files reviewed, 7 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz7K6dm9cjcNTLkQIv1:-Nz7K6dm9cjcNTLkQIv2:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/789ea3650a4d2c80fb1588b6480055cd7692752b/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L104)):*
> ```XML
>     pub(crate) fn is_left_descendant(&self) -> bool {
>         self.path.0 >> (self.length.0 - 1) == 0
>     }
> ```





_Suggestion:_
```XML
    /// Returns true iff the first step on the path is to the left.
    pub(crate) fn is_left_descendant(&self) -> bool {
        self.path.0 >> (self.length.0 - 1) == 0
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz7KHx37vnPOfWybLR4:-Nz7KHx37vnPOfWybLR5:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/789ea3650a4d2c80fb1588b6480055cd7692752b/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L113)):*
> ```XML
>     }
> 
>     /// Returns the path after removing the first step (the edge from the path's origin node).
> ```





_Suggestion:_
```XML
/// Returns the path after removing the first steps (the edges from the path's origin node).
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz7K-oj2in4ZVuZOVDc:-Nz7K-oj2in4ZVuZOVDd:bu0cjh) ([raw file](https://github.com/starkware-libs/committer/blob/789ea3650a4d2c80fb1588b6480055cd7692752b/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L116)):*
> ```XML
>     pub(crate) fn remove_first_edges(&self, n_edges: EdgePathLength) -> Result<Self, &str> {
>         if self.length < n_edges {
>             return Err("Tried to remove more edges than the path has.");
> ```

do not use a `str` error type - define a proper enum variant in some error enum



_Code quote:_
```XML
    pub(crate) fn remove_first_edges(&self, n_edges: EdgePathLength) -> Result<Self, &str> {
        if self.length < n_edges {
            return Err("Tried to remove more edges than the path has.");
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 343 at r2](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz7NLek4oUTHOfddKD6:-Nz7NLek4oUTHOfddKD7:b-c4t0jy) ([raw file](https://github.com/starkware-libs/committer/blob/789ea3650a4d2c80fb1588b6480055cd7692752b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L343)):*
> ```XML
> 
>         let bottom_index = path_to_bottom.bottom_index(*root_index);
>         let path_to_new_bottom = get_path_to_lca(root_index, &[leaves_lca_index, bottom_index]);
> ```

does `get_path_to_lca` work if the input indices are not of the same height?



_Code quote:_
```XML
let path_to_new_bottom = get_path_to_lca(root_index, &[leaves_lca_index, bottom_index]);
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 343 at r2](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz7NcHB3lkbtmoPN0OE:-Nz7NcHB3lkbtmoPN0OF:b-pya76j) ([raw file](https://github.com/starkware-libs/committer/blob/789ea3650a4d2c80fb1588b6480055cd7692752b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L343)):*
> ```XML
> 
>         let bottom_index = path_to_bottom.bottom_index(*root_index);
>         let path_to_new_bottom = get_path_to_lca(root_index, &[leaves_lca_index, bottom_index]);
> ```

don't you need specific logic if `leaves_lca_index == bottom_index`?
i.e. all leaves are in the bottom's subtree?
if you don't handle it, seems to me like you would be trying to add an edge node of path length 0



_Code quote:_
```XML
        let leaves_lca_index = path_to_leaves_lca.bottom_index(*root_index);

        let bottom_index = path_to_bottom.bottom_index(*root_index);
        let path_to_new_bottom = get_path_to_lca(root_index, &[leaves_lca_index, bottom_index]);
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 346 at r2](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz7NrVX1j7hSQ9G3Ce7:-Nz7NrVX1j7hSQ9G3Ce8:b2zhvgw) ([raw file](https://github.com/starkware-libs/committer/blob/789ea3650a4d2c80fb1588b6480055cd7692752b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L346)):*
> ```XML
> 
>         let new_bottom_index = path_to_new_bottom.bottom_index(*root_index);
>         let fake_original_new_bottom_node = OriginalSkeletonNode::Edge(
> ```

three adjectives on this noun (fake + original + new),
and some would say they are contradictive (fake + original).
this name may make sense, but please add a short comment above it explaining what this is



_Code quote:_
```XML
fake_original_new_bottom_node
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 447 at r2](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz7SvdA5mtjDeRlyX8-:-Nz7SvdA5mtjDeRlyX80:b-1vdjof) ([raw file](https://github.com/starkware-libs/committer/blob/789ea3650a4d2c80fb1588b6480055cd7692752b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L447)):*
> ```XML
>     TempSkeletonNode::Original(OriginalSkeletonNode::Edge(PathToBottom::RIGHT_CHILD)),
>     &[],
> )]
> ```

please add a test case where the root is an edge leading to a bottom node `B`, and the LCA of the modified leaves is also `B` (related to my above question about the case where `leaves_lca_index == bottom_index`)

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/164)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 104 at r2](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz7K6dm9cjcNTLkQIv1:-Nz7d6kS3FeA8EWcXnAK:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/789ea3650a4d2c80fb1588b6480055cd7692752b/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L104)):*
> ```XML
>     pub(crate) fn is_left_descendant(&self) -> bool {
>         self.path.0 >> (self.length.0 - 1) == 0
>     }
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 113 at r2](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz7KHx37vnPOfWybLR4:-Nz7dBEG1Hf8OeIwt1SC:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/789ea3650a4d2c80fb1588b6480055cd7692752b/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L113)):*
> ```XML
>     }
> 
>     /// Returns the path after removing the first step (the edge from the path's origin node).
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz7K-oj2in4ZVuZOVDc:-Nz7f84x0BQ0LBLocIRx:b-ilz5bi) ([raw file](https://github.com/starkware-libs/committer/blob/789ea3650a4d2c80fb1588b6480055cd7692752b/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L116)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do not use a `str` error type - define a proper enum variant in some error enum
</blockquote></details>

Is this OK?
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 343 at r2](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz7NLek4oUTHOfddKD6:-Nz7fTRi5uGY7SiOybK3:b-p6ul4g) ([raw file](https://github.com/starkware-libs/committer/blob/789ea3650a4d2c80fb1588b6480055cd7692752b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L343)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does `get_path_to_lca` work if the input indices are not of the same height?
</blockquote></details>

It does actually, but the doc implies otherwise - it doesn't really have to be leaves, we just need the first and last indices in the array to be the leftmost and rightmost of the entire array. Changing the docs.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 343 at r2](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz7NcHB3lkbtmoPN0OE:-Nz7kEBEC7nb6Zv1Bpxu:bbmkc) ([raw file](https://github.com/starkware-libs/committer/blob/789ea3650a4d2c80fb1588b6480055cd7692752b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L343)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't you need specific logic if `leaves_lca_index == bottom_index`?
i.e. all leaves are in the bottom's subtree?
if you don't handle it, seems to me like you would be trying to add an edge node of path length 0
</blockquote></details>

Right, it's easy to miss these edge cases in the original code :/ . Changed the assertion in remove_first_edges from PathToBottom to not allow a trial length 0 edge - this assertion would have caught this scenario if it would have happen.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 346 at r2](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz7NrVX1j7hSQ9G3Ce7:-Nz7hE8MCyWKYyG7LUfA:b-ilz5bi) ([raw file](https://github.com/starkware-libs/committer/blob/789ea3650a4d2c80fb1588b6480055cd7692752b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L346)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

three adjectives on this noun (fake + original + new),
and some would say they are contradictive (fake + original).
this name may make sense, but please add a short comment above it explaining what this is
</blockquote></details>

Is this OK?
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 447 at r2](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz7SvdA5mtjDeRlyX8-:-Nz7npgkCj4HNG9lXEli:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/789ea3650a4d2c80fb1588b6480055cd7692752b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L447)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a test case where the root is an edge leading to a bottom node `B`, and the LCA of the modified leaves is also `B` (related to my above question about the case where `leaves_lca_index == bottom_index`)
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/164)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 457 at r3](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz88HAm9AUpui4asP9H:-Nz88HAm9AUpui4asP9I:btn3rof) ([raw file](https://github.com/starkware-libs/committer/blob/0b354c174379f4c063177f45341baf9d19a919a2/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L457)):*
> ```XML
>     TempSkeletonNode::Original(OriginalSkeletonNode::Edge(PathToBottom::LEFT_CHILD)),
>     &[(NodeIndex::FIRST_LEAF>>1, UpdatedSkeletonNode::Binary)],
> )]
> ```

IIUC: the original tree was
```
        E
       /
      B
    /   \
  NZ     NZ
```
the updated tree topology is identical to the input topology. why would you expect the the `expected_skeleton_additions` to be non-empty?



_Code quote:_
```XML
#[case::orig_edge_with_modified_leaves_beneath_bottom(
    &(NodeIndex::FIRST_LEAF>>2),
    vec![
        (NodeIndex::FIRST_LEAF>>2, OriginalSkeletonNode::Edge(PathToBottom::LEFT_CHILD)),
        (NodeIndex::FIRST_LEAF>>1, OriginalSkeletonNode::Binary),
    ],
    &[(U256::from(NodeIndex::FIRST_LEAF), 1), (U256::from(NodeIndex::FIRST_LEAF+1.into()), 1)],
    TempSkeletonNode::Original(OriginalSkeletonNode::Edge(PathToBottom::LEFT_CHILD)),
    &[(NodeIndex::FIRST_LEAF>>1, UpdatedSkeletonNode::Binary)],
)]
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/164)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 457 at r3](https://reviewable.io/reviews/starkware-libs/committer/164#-Nz88HAm9AUpui4asP9H:-Nz893GNB5VhJCOsjSpK:b6tcscv) ([raw file](https://github.com/starkware-libs/committer/blob/0b354c174379f4c063177f45341baf9d19a919a2/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L457)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

IIUC: the original tree was
```
        E
       /
      B
    /   \
  NZ     NZ
```
the updated tree topology is identical to the input topology. why would you expect the the `expected_skeleton_additions` to be non-empty?
</blockquote></details>

The additions means - nodes fianlized during the tested function execution. The initial finalize nodes are leaves, siblings and unmodified bottoms. All Binary or Edge nodes are finalized during the compute... module functions. This binary is finalized when handling the Edge node parent, as we finalize bottom nodes.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/164#-:-Nz8B8MkAyVW5b6p68kv:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
