### PR TITLE
build: basic code changes for using rayon

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/38)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/38)* status: all files reviewed, 8 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/Cargo.toml` line 19 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRepspAiT5iZTm863p:-NvRepspAiT5iZTm863q:b4001g7) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/Cargo.toml#L19)):*
> ```TOML
> derive_more.workspace = true
> starknet-types-core.workspace = true
> rayon.workspace = true
> ```

ascending order (looking for an auto-formatter to do it for us...)



_Suggestion:_
```TOML
derive_more.workspace = true
rayon.workspace = true
starknet-types-core.workspace = true
```
___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRfV3TCPz1x_NO1gr1:-NvRfV3TCPz1x_NO1gr2:bvgsn1a) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/src/patricia_merkle_tree/errors.rs#L8)):*
> ```XML
> pub(crate) enum UpdatedSkeletonTreeError {
>     MissingNode,
>     PoisonedLock,
> ```

to add a description



_Suggestion:_
```XML
PoisonedLock(String)
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRf_pp31sH9pYuOJ1Q:-NvRf_pp31sH9pYuOJ1R:b-2w9bh) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L63)):*
> ```XML
>         &self,
>         index: NodeIndex,
>         output_map: Arc<RwLock<HashMap<NodeIndex, Mutex<FilledNode<L>>>>>,
> ```

needed?
didn't we say we wanted internal mutability so we *don't* have to lock like this?
if we need it, why do we need the hashmap's values to be wrapped in a mutex?



_Code quote:_
```XML
Arc<RwLock<
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRfGQ43pDfCSCVt1Ub:-NvRfGQ43pDfCSCVt1Uc:b-6ivwl6) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L93)):*
> ```XML
>                 });
>                 let hash_value = TH::compute_node_hash(data.clone());
>                 let mut write_locked_map = output_map.write().expect("RwLock poisoned");
> ```

you don't want to panic here; you want to return an error



_Suggestion:_
```XML
output_map.write().map_err(UpdatedSkeletonTreeError::PoisonedLock("Failed to take write lock."))?
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRfogy34B3tzDvIHOT:-NvRfogy34B3tzDvIHOU:b1yvow2) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L112)):*
> ```XML
>                 });
>                 let hash_value = TH::compute_node_hash(data.clone());
>                 let mut write_locked_map = output_map.write().expect("RwLock poisoned");
> ```

error, no expect (see above)



_Code quote:_
```XML
output_map.write().expect("RwLock poisoned")
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRfsCC5NXZSVxoReGl:-NvRfsCC5NXZSVxoReGm:b1yvow2) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L125)):*
> ```XML
>             UpdatedSkeletonNode::Leaf(node_data) => {
>                 let hash_value = TH::compute_node_hash(NodeData::Leaf(node_data.clone()));
>                 let mut write_locked_map = output_map.write().expect("RwLock poisoned");
> ```

error, no expect (see above)



_Code quote:_
```XML
output_map.write().expect("RwLock poisoned");
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRg5Y6-5AOTltEDWlA:-NvRg5Y6-5AOTltEDWlB:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L154)):*
> ```XML
>             Ok(filled_tree_map) => match filled_tree_map.into_inner() {
>                 Ok(filled_tree_map) => Ok(FilledTreeImpl::new(filled_tree_map)),
>                 Err(_) => Err(UpdatedSkeletonTreeError::PoisonedLock),
> ```





_Suggestion:_
```XML
Err(UpdatedSkeletonTreeError::PoisonedLock("Cannot take filled tree map."))
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRgHZyCFLLwCaOncxs:-NvRgHZyCFLLwCaOncxt:bgcb6fx) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L156)):*
> ```XML
>                 Err(_) => Err(UpdatedSkeletonTreeError::PoisonedLock),
>             },
>             Err(_) => Err(UpdatedSkeletonTreeError::PoisonedLock),
> ```

this is not a poisoned lock error: you are trying to unwrap an `Arc`. define a new variant for it



_Code quote:_
```XML
Err(UpdatedSkeletonTreeError::PoisonedLock)
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/38)* status: all files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/Cargo.toml` line 19 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRepspAiT5iZTm863p:-NvVODLG0E2s2fynQFVg:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/Cargo.toml#L19)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ascending order (looking for an auto-formatter to do it for us...)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRfV3TCPz1x_NO1gr1:-NvVOG0t080r2QlNF1up:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/src/patricia_merkle_tree/errors.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

to add a description
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRf_pp31sH9pYuOJ1Q:-NvTSQeB0tjj_MUdiyXs:bfmxmv3) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

needed?
didn't we say we wanted internal mutability so we *don't* have to lock like this?
if we need it, why do we need the hashmap's values to be wrapped in a mutex?
</blockquote></details>

Yes, it's still WIP (added TODOs), but IIUC, this is how we'll get internal mutability - the RwLock can be used so that several threads can read the hashmap without locking, in which case the locking is only on the internal element via the mutex.
To change it to internal mutability, we need to create the hashmap structure in advance (so I guess first, we should decide where it's created with @TzahiTaub ).
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 93 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRfGQ43pDfCSCVt1Ub:-NvVOAGF5Rw1xddsrkVr:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L93)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you don't want to panic here; you want to return an error
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 112 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRfogy34B3tzDvIHOT:-NvVHF3R8TR4PmrH3ffQ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L112)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

error, no expect (see above)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 125 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRfsCC5NXZSVxoReGl:-NvVHEUW7daD763ghXlK:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L125)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

error, no expect (see above)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 154 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRg5Y6-5AOTltEDWlA:-NvVOBTT4ZIXY7lfQixR:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L154)):*
> ```XML
>             Ok(filled_tree_map) => match filled_tree_map.into_inner() {
>                 Ok(filled_tree_map) => Ok(FilledTreeImpl::new(filled_tree_map)),
>                 Err(_) => Err(UpdatedSkeletonTreeError::PoisonedLock),
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs` line 156 at r1](https://reviewable.io/reviews/starkware-libs/committer/38#-NvRgHZyCFLLwCaOncxs:-NvVGqH35HY2tW_s_fPB:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d7d873d3cd0b84563261c6be2e19a6701d90dfdb/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs#L156)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is not a poisoned lock error: you are trying to unwrap an `Arc`. define a new variant for it
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/38#-:-NvVYRZI9bA2NbkHHLiA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/38)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/38)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/38)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/38)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
