### PR TITLE
feat: read and write from file in commit command

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/249)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/249)* status: all files reviewed, 3 unresolved discussions (waiting on @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/249#-O0JdUlK267d38Q5ch4b:-O0JdUlK267d38Q5ch4c:b-hly2zx) (no related file):*
python side PR?

___
___
*[`crates/committer_cli/src/main.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/committer/249#-O0JdE6F2mnCGWeYM1no:-O0JdE6F2mnCGWeYM1np:bor0qhj) ([raw file](https://github.com/starkware-libs/committer/blob/aba029d6c3fb10e8ed7d6d92b488a6736b3b578f/crates/committer_cli/src/main.rs#L97)):*
> ```XML
> 
>             // Print test's output.
>             print!("{}", output);
> ```

is this still required?



_Code quote:_
```XML
print!("{}", output);
```
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/committer/249#-O0JdMXT9MnchqdgFazX:-O0JdMXU4kO6cSSRjkof:b45h) ([raw file](https://github.com/starkware-libs/committer/blob/aba029d6c3fb10e8ed7d6d92b488a6736b3b578f/crates/committer_cli/src/tests/benchmark_tests.rs#L20)):*
> ```XML
> // and to include the expected output.
> const FLOW_TEST_INPUT: &str = include_str!("../../benches/committer_flow_inputs.json");
> const OUTPUT_PATH: &str = "output_path";
> ```





_Suggestion:_
```XML
benchmark_output.txt
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/249)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/249#-O0JdUlK267d38Q5ch4b:-O0JdaFb7I9E-8Fkuhzp:bwpvxm1) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

python side PR?
</blockquote></details>

ah, found it

___

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/249)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/249)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/committer_cli/src/main.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/committer/249#-O0JdE6F2mnCGWeYM1no:-O0OPcQQE8TDr3t1SNAw:b-nn1b96) ([raw file](https://github.com/starkware-libs/committer/blob/aba029d6c3fb10e8ed7d6d92b488a6736b3b578f/crates/committer_cli/src/main.rs#L97)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

Yes.
In the python side `run_committer_test` still takes stdout.
</blockquote></details>

please add a todo to remove this when a unified IO mechanism is used on the python side

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/249)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/src/main.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/committer/249#-O0JdE6F2mnCGWeYM1no:-O0d40Aj5VMRtn6JshLQ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/aba029d6c3fb10e8ed7d6d92b488a6736b3b578f/crates/committer_cli/src/main.rs#L97)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a todo to remove this when a unified IO mechanism is used on the python side
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/249#-:-O0d5-zVEBMMJT3lsdWf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
