### PR TITLE
chore: add documentation

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/15)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/15)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/skeleton_node.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/committer/15#-NucU9En1SGl-ZuHRMG7:-NucU9En1SGl-ZuHRMG8:b-6cnoem) ([raw file](https://github.com/starkware-libs/committer/blob/e99b0181b488e760f31fe0053301f9652d54ad63/crates/committer/src/patricia_merkle_tree/skeleton_node.rs#L12)):*
> ```XML
>     Sibling(HashOutput),
>     Leaf(L),
>     Empty,
> ```

@TzahiTaub How should I describe `Empty`?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/15)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/skeleton_tree.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/committer/15#-NurKnRA6I8rP-esQsLd:-NurKnRA6I8rP-esQsLe:b-2uw822) ([raw file](https://github.com/starkware-libs/committer/blob/e99b0181b488e760f31fe0053301f9652d54ad63/crates/committer/src/patricia_merkle_tree/skeleton_tree.rs#L10)):*
> ```XML
> 
> /// Consider a Patricia-Merkle Tree which should be updated with new leaves.
> /// CurrentSkeletonTree represents the structure of the subtree which will be modified in the
> ```

so we can rename the trait without having to remember to update a doc



_Suggestion:_
```XML
This trait
```
___
*[`crates/committer/src/patricia_merkle_tree/skeleton_tree.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/committer/15#-NurKxdMDKr2J503TRVv:-NurKxdMDKr2J503TRVw:b-2uw822) ([raw file](https://github.com/starkware-libs/committer/blob/e99b0181b488e760f31fe0053301f9652d54ad63/crates/committer/src/patricia_merkle_tree/skeleton_tree.rs#L23)):*
> ```XML
> 
> /// Consider a Patricia-Merkle Tree which has been updated with new leaves.
> /// UpdatedSkeletonTree represents the structure of the subtree which was modified in the update.
> ```

so we can rename the trait without having to remember to update a doc



_Suggestion:_
```XML
This trait 
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/15)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/skeleton_tree.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/committer/15#-NurKnRA6I8rP-esQsLd:-NurR6hQ6WxTRZDjdpeb:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e99b0181b488e760f31fe0053301f9652d54ad63/crates/committer/src/patricia_merkle_tree/skeleton_tree.rs#L10)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so we can rename the trait without having to remember to update a doc
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/skeleton_tree.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/committer/15#-NurKxdMDKr2J503TRVv:-NurR9Az-EvaFXCpdhZs:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e99b0181b488e760f31fe0053301f9652d54ad63/crates/committer/src/patricia_merkle_tree/skeleton_tree.rs#L23)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so we can rename the trait without having to remember to update a doc
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/15)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

**Pull request merged**
