### PR TITLE
chore: adding CLI interface

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/22)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/22)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/22#-Nuz4aiE4wn2uBMxF8I7:-Nuz4aiE4wn2uBMxF8I8:b-aoc6bq) (no related file):*
based on [this](https://reviewable.io/reviews/starkware-libs/committer/16)

___

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/22)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/Cargo.toml` line 17 at r3](https://reviewable.io/reviews/starkware-libs/committer/22#-Nuz5217C0goCzih9s9z:-Nuz5217C0goCzih9sA-:becyvrl) ([raw file](https://github.com/starkware-libs/committer/blob/5548c9331deb76b43d58c013d971eb9479ddf603/crates/committer/Cargo.toml#L17)):*
> ```TOML
> [dependencies]
> starknet-types-core = "0.0.11"
> starknet_api = "0.12.0-dev.0"
> ```

`udeps` should have failed [here](https://reviewable.io/reviews/starkware-libs/committer/11), as we don't use starknet-api since then. Investigating separately



_Code quote:_
```TOML
starknet_api = "0.12.0-dev.0"
```

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/22)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer_cli/src/main.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/committer/22#-Nv0eJKuBw9kPlkTzqH5:-Nv0eJKuBw9kPlkTzqH6:b6nrqyv) ([raw file](https://github.com/starkware-libs/committer/blob/e036c6564c91053632a34d47d3094ed62e34a603/crates/committer_cli/src/main.rs#L29)):*
> ```XML
>         /// The version of the class hash.
>         #[clap(long)]
>         class_hash_version: u8,
> ```

I think that it should accept it as a string that will later be converted to Felt.
PTAL [here](https://github.com/starkware-industries/starkware/blob/dev/src/starkware/starknet/definitions/constants.py#L97). Currently this is the input when hashing.
___
*[`crates/committer_cli/src/main.rs` line 61 at r4](https://reviewable.io/reviews/starkware-libs/committer/22#-Nv0elkuDgdSVyo6tKua:-Nv0elkuDgdSVyo6tKub:bjxg0rt) ([raw file](https://github.com/starkware-libs/committer/blob/e036c6564c91053632a34d47d3094ed62e34a603/crates/committer_cli/src/main.rs#L61)):*
> ```XML
> }
> 
> #[derive(Debug, Args)]
> ```

please remove prefixes logic

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/22)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer_cli/src/main.rs` line 29 at r4](https://reviewable.io/reviews/starkware-libs/committer/22#-Nv0eJKuBw9kPlkTzqH5:-Nv0yKXY-u0-eanAVgnf:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e036c6564c91053632a34d47d3094ed62e34a603/crates/committer_cli/src/main.rs#L29)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I think that it should accept it as a string that will later be converted to Felt.
PTAL [here](https://github.com/starkware-industries/starkware/blob/dev/src/starkware/starknet/definitions/constants.py#L97). Currently this is the input when hashing.
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/main.rs` line 61 at r4](https://reviewable.io/reviews/starkware-libs/committer/22#-Nv0elkuDgdSVyo6tKua:-Nv0yL9-8d0JnCZj6YHB:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e036c6564c91053632a34d47d3094ed62e34a603/crates/committer_cli/src/main.rs#L61)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

please remove prefixes logic
</blockquote></details>

Done.

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/22)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`Cargo.toml` line 17 at r6](https://reviewable.io/reviews/starkware-libs/committer/22#-Nv7UAFlBa1W7TbvBv2o:-Nv7UAFlBa1W7TbvBv2p:bfqrefl) ([raw file](https://github.com/starkware-libs/committer/blob/5fb041382187c510b678cd4fb44b39b986982fd9/Cargo.toml#L17)):*
> ```TOML
> [workspace.dependencies]
> clap = { version = "4.5.4", features = ["cargo", "derive"] }
> derive_more = "0.99.17"
> ```

Is this used?
___
*[`crates/committer_cli/src/main.rs` line 9 at r6](https://reviewable.io/reviews/starkware-libs/committer/22#-Nv7VMID4y12uK_rmwBN:-Nv7VMID4y12uK_rmwBO:baqxdba) ([raw file](https://github.com/starkware-libs/committer/blob/5fb041382187c510b678cd4fb44b39b986982fd9/crates/committer_cli/src/main.rs#L9)):*
> ```XML
> pub struct CommitterCliArgs {
>     #[clap(flatten)]
>     global_opts: GlobalOpts,
> ```

Needed to run the CLI to understand what this means...



_Suggestion:_
```XML
 global_options: GlobalOptions
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/22)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`Cargo.toml` line 17 at r6](https://reviewable.io/reviews/starkware-libs/committer/22#-Nv7UAFlBa1W7TbvBv2o:-Nv7X4ryAEReiP4m9-4A:bu3sman) ([raw file](https://github.com/starkware-libs/committer/blob/5fb041382187c510b678cd4fb44b39b986982fd9/Cargo.toml#L17)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Is this used?
</blockquote></details>

[yes](https://github.com/starkware-libs/committer/blob/main/crates/committer/src/types.rs#L3)
___
*[`crates/committer_cli/src/main.rs` line 9 at r6](https://reviewable.io/reviews/starkware-libs/committer/22#-Nv7VMID4y12uK_rmwBN:-Nv7X7kt7-xBBh580dyP:b-ettcox) ([raw file](https://github.com/starkware-libs/committer/blob/5fb041382187c510b678cd4fb44b39b986982fd9/crates/committer_cli/src/main.rs#L9)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Needed to run the CLI to understand what this means...
</blockquote></details>

currently not in use; this is the struct where we will add options that are common to all commands.
if we see there is no such thing, we will delete this struct

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/22#-:-Nv87yxV3iwtlRemmmSK:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/22#-:-NvAdPlKDyd6IPqGFx29:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

**Pull request merged**
