### PR TITLE
chore(ci): better clippy lints, deny unwrap() outside of tests

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/34)

### CODE REVIEW

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/34)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`scripts/clippy.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/committer/34#-Nv7XL5R1xjF88qDuHrO:-Nv7XL5R1xjF88qDuHrP:bvstkw6) ([raw file](https://github.com/starkware-libs/committer/blob/16d198ae0f934365783f1d3fbc031a61b4b544c8/scripts/clippy.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> cargo clippy "$@" --all-targets --all-features
> ```

Can you explain why you removed these? I have no idea what they do

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/34)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

___
*[`scripts/clippy.sh` line 3 at r1](https://reviewable.io/reviews/starkware-libs/committer/34#-Nv7XL5R1xjF88qDuHrO:-Nv7Y3ii-T28nTbt1iJu:bg4h2og) ([raw file](https://github.com/starkware-libs/committer/blob/16d198ae0f934365783f1d3fbc031a61b4b544c8/scripts/clippy.sh#L3)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Can you explain why you removed these? I have no idea what they do
</blockquote></details>

they already exist and are enforced in cargo.toml:
```
[workspace.lints.rust]
warnings = "deny"
future-incompatible = "deny"
nonstandard-style = "deny"
rust-2018-idioms = "deny"
unused = "deny"
```
the `unused` lint, for example, fails the CI if you define an unused variable.
this doesn't change behavior - what i changed is
1. single point of truth for lints (in cargo.toml)
2. added `unwrap_used` in the clippy lints
3. added a `clippy.toml` file so we can get `allow-unwrap-in-tests = true`, which is required if we want to use `unwrap` in tests (we do, no reason not to)

IDK what these are:
```
future-incompatible = "deny"
nonstandard-style = "deny"
rust-2018-idioms = "deny"
```

... but they are copied over from the blockifier repo, so no changes there. we can decide to remove them if we want

**Review by TzahiTaub — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/34)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/34#-:-Nv86f6lDiZbrR00_6mJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/34)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
