### PR TITLE
refactor: remove usage of current contract state leaves

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/253)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
monday item - https://starkware.monday.com/boards/6234683038/pulses/6845456133

This item will have another PR which will remove from python and rust the input of current contract state leaves.
This PR involves the logic changes (we no longer use that input, but it still exists)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/253#-:-O0O1-0q0yT1p974lGtv:besy86p)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @TzahiTaub)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/253)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 538 at r2](https://reviewable.io/reviews/starkware-libs/committer/253#-O0OQPOD189ccBilyQ6O:-O0OQPOD189ccBilyQ6P:bdka4ay) ([raw file](https://github.com/starkware-libs/committer/blob/a2e59e6670513a5a4bdc77760c635ba96d17b746/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L538)):*
> ```XML
>     // Assumes path is 0.
>     let length = SubTreeHeight::ACTUAL_HEIGHT.0 - subtree_height.0;
>     let new_root = old_root + u128::from(length);
> ```

unless `length` is `usize` I don't think the explicit cast is needed. non-blocking



_Suggestion:_
```XML
old_root + length
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/committer/253#-O0OQbJdAKjANuD0THGr:-O0OQbJdAKjANuD0THGs:b-51i8n0) ([raw file](https://github.com/starkware-libs/committer/blob/a2e59e6670513a5a4bdc77760c635ba96d17b746/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L24)):*
> ```XML
> 
> pub(crate) trait OriginalSkeletonForest {
>     fn create(
> ```

docstring (now that the return type is unclear).
no need to doc the implementation
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/committer/253#-O0ORLbcA4n1ZIBac9AV:-O0ORLbcA4n1ZIBac9AW:b-wainh1) ([raw file](https://github.com/starkware-libs/committer/blob/a2e59e6670513a5a4bdc77760c635ba96d17b746/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L85)):*
> ```XML
>     }
> 
>     fn create_contracts_trie(
> ```

docstring (new return type)



_Code quote:_
```XML
fn create_contracts_trie(
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/committer/253#-O0ORhoP1lR5T3ys713v:-O0ORhoP1lR5T3ys713w:b-cwpbt0) ([raw file](https://github.com/starkware-libs/committer/blob/a2e59e6670513a5a4bdc77760c635ba96d17b746/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L74)):*
> ```XML
> ///               *         B                       B     E
> ///              /                                 / \     \
> ///             303                               NZ  47   UB
> ```

can you tl;dr what these changes are?



_Code quote:_
```XML
// This test assumes for simplicity that hash is addition (i.e hash(a,b) = a + b).
///                                Old forest structure:
///
///                      Global tree:                Classes tree:
///
///                      248 + 861                     248 + 155
///                         /                             /
///                       ...                           ...
///                       /                             /
///                      /                             /
///                     861                          155
///                    /   \                         /
///                   305  556                     154
///                  /       \                     /  \
///                 304      554                  80   74
///                /   \     /  \                /  \    \
///               303   1  277  277             33  47    72
///
/// Modified leaves (full) indices: [8, 14, 15]  ##  Modified leaves (full) indices: [8, 14, 15]
///
///
///         Contracts #6, #7:                                  Contract #0:
///
///                248 + 29                                    248 + 55
///                   /                                           /
///                 ...                                         ...
///                 /                                           /
///                /                                           /
///               29                                          55
///             /    \                                      /    \
///           13      16                                  35      20
///          /      /    \                               /  \       \
///         12      5     11                            17  18       *
///        /  \      \   /  \                          /  \   \        \
///       10   2      3  4   7                        8    9  16       15
///
///   Modified leaves (full) indices: [8, 11, 13]  ##  Modified leaves (full) indices: [8, 10, 13]
///
///                             Expected skeleton forest:
///                 Global tree:                Classes tree:
///
///                    B                                 E
///                  /   \                              /
///                 E     E                            B
///                /       \                         /   \
///               *         B                       B     E
///              /                                 / \     \
///             303                               NZ  47   UB
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/253)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 538 at r2](https://reviewable.io/reviews/starkware-libs/committer/253#-O0OQPOD189ccBilyQ6O:-O0OVwvp9arlAXHuhtIc:b-wt83cm) ([raw file](https://github.com/starkware-libs/committer/blob/a2e59e6670513a5a4bdc77760c635ba96d17b746/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L538)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

unless `length` is `usize` I don't think the explicit cast is needed. non-blocking
</blockquote></details>

It actually doesn't work :(
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/committer/253#-O0OQbJdAKjANuD0THGr:-O0OWnz0Eytlj9FxSwrd:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/a2e59e6670513a5a4bdc77760c635ba96d17b746/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L24)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

docstring (now that the return type is unclear).
no need to doc the implementation
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/committer/253#-O0ORLbcA4n1ZIBac9AV:-O0OX3mO6s-nOFo9QywM:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/a2e59e6670513a5a4bdc77760c635ba96d17b746/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L85)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

docstring (new return type)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 74 at r2](https://reviewable.io/reviews/starkware-libs/committer/253#-O0ORhoP1lR5T3ys713v:-O0OX4weDdMVkdvux71M:b-b2c4h5) ([raw file](https://github.com/starkware-libs/committer/blob/a2e59e6670513a5a4bdc77760c635ba96d17b746/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L74)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you tl;dr what these changes are?
</blockquote></details>

Previously, the test was not good in the sense that all trees were unrelated. The contracts trie very much depend on the storage tries. I changed the test that will reflect that. It didn't reflect that dependency previously because the contract trie's leaves were given explicitly. Now it's not given but computed when running.

If it's not clear, let me know

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/253)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/committer/253#-O0OQbJdAKjANuD0THGr:-O0OjMOx4aBp7RRmYv89:b-kpyh6x) ([raw file](https://github.com/starkware-libs/committer/blob/a2e59e6670513a5a4bdc77760c635ba96d17b746/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L24)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you documented the implementation; please doc in the trait definition

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/253)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 24 at r2](https://reviewable.io/reviews/starkware-libs/committer/253#-O0OQbJdAKjANuD0THGr:-O0Oktht5nSCzPyj38rF:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/a2e59e6670513a5a4bdc77760c635ba96d17b746/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L24)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you documented the implementation; please doc in the trait definition
</blockquote></details>

Done

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/253#-:-O0OmsrS7CHTzXkxGDT4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/253)* status: all files reviewed, 6 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/block_committer/commit.rs` line 27 at r3](https://reviewable.io/reviews/starkware-libs/committer/253#-O0OlEDc9_M-aak2QS5N:-O0OlEDc9_M-aak2QS5O:bjq66h2) ([raw file](https://github.com/starkware-libs/committer/blob/d80549f2142eb938a68a6c9e5e9e606ac59cfe50/crates/committer/src/block_committer/commit.rs#L27)):*
> ```XML
> #[allow(dead_code)]
> pub async fn commit_block(input: Input) -> BlockCommitmentResult<FilledForestImpl> {
>     let (mut original_forest, current_contracts_trie_leaves) =
> ```

I find it easier to understand because we have the `original` name concept throughout the code. 



_Suggestion:_
```XML
original_contracts_trie_leaves
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/committer/253#-O0OnKPvEuVifq1zc-AP:-O0OnKPw-0ouwferzRru:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/1a75fe7db7149ae1ceb9d8e02680e39b1910c499/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L26)):*
> ```XML
>     /// Created an original skeleton forest includes the storage tries of the modified contracts,
>     /// the classes trie and the contracts trie. Returns also the previous contract states which
>     /// are needed to compute the contract state tree.
> ```





_Suggestion:_
```XML
    /// Creates an original skeleton forest that includes the storage tries of the modified contracts,
    /// the classes trie and the contracts trie. Additionally, returns the original contract states that
    /// are needed to compute the contract state tree.
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 55 at r4](https://reviewable.io/reviews/starkware-libs/committer/253#-O0Op_Nj7sVd5cMP0UMv:-O0Op_Nj7sVd5cMP0UMw:b3kre) ([raw file](https://github.com/starkware-libs/committer/blob/1a75fe7db7149ae1ceb9d8e02680e39b1910c499/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L55)):*
> ```XML
>     {
>         let accessed_addresses = state_diff.accessed_addresses();
>         let (contracts_state_trie, current_contracts_trie_leaves) =
> ```

?



_Suggestion:_
```XML
original_contracts_trie_leaves
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 89 at r4](https://reviewable.io/reviews/starkware-libs/committer/253#-O0OpjONDk7bnYH6vARf:-O0OpjONDk7bnYH6vARg:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/1a75fe7db7149ae1ceb9d8e02680e39b1910c499/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L89)):*
> ```XML
> 
>     /// Creates the contracts trie original skeleton.
>     /// Returns also the previous contract states of the modified contracts.
> ```





_Suggestion:_
```XML
 Also (or additionally) returns the previous contracts state of the modified contracts.
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/committer/253#-O0P1Vir64kIHwd7Yh4l:-O0P1Vir64kIHwd7Yh4m:bsy750j) ([raw file](https://github.com/starkware-libs/committer/blob/1a75fe7db7149ae1ceb9d8e02680e39b1910c499/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L32)):*
> ```XML
> ///                      Global tree:                Classes tree:
> ///
> ///                      248 + 861                     248 + 155
> ```

Hopefully clearer



_Suggestion:_
```XML
// This test assumes for simplicity that hash is addition (i.e hash(a,b) = a + b).
// I.e., the value of a binary node is the sum of its children's values, and the value of an edge node is the 
// sum of its path, bottom value and path length.
///                                Old forest structure:
///
///                      Global tree:                Classes tree:
///
///                    248 + 861 + 0                    248 + 155 + 0
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/committer/253#-O0P1jXg-J9OBUTALi1F:-O0P1jXg-J9OBUTALi1G:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/1a75fe7db7149ae1ceb9d8e02680e39b1910c499/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L50)):*
> ```XML
> ///         Contracts #6, #7:                                  Contract #0:
> ///
> ///                248 + 29                                    248 + 55
> ```





_Suggestion:_
```XML
/                248 + 29 + 0                                    248 + 55 + 0
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/253)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 26 at r4](https://reviewable.io/reviews/starkware-libs/committer/253#-O0OnKPvEuVifq1zc-AP:-O0bqS4i7e2sbeya0F6P:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/1a75fe7db7149ae1ceb9d8e02680e39b1910c499/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L26)):*
> ```XML
>     /// Created an original skeleton forest includes the storage tries of the modified contracts,
>     /// the classes trie and the contracts trie. Returns also the previous contract states which
>     /// are needed to compute the contract state tree.
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/committer/253#-O0P1Vir64kIHwd7Yh4l:-O0bq2UL0eb5A84Y0tsA:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/1a75fe7db7149ae1ceb9d8e02680e39b1910c499/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L32)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Hopefully clearer
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 50 at r4](https://reviewable.io/reviews/starkware-libs/committer/253#-O0P1jXg-J9OBUTALi1F:-O0bq2lZAKMEKrgM2ezr:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/1a75fe7db7149ae1ceb9d8e02680e39b1910c499/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L50)):*
> ```XML
> ///         Contracts #6, #7:                                  Contract #0:
> ///
> ///                248 + 29                                    248 + 55
> ```

Done.

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/253)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/committer/253#-O0P1Vir64kIHwd7Yh4l:-O0bvy2b3DnXokCG6-6a:b79934d) ([raw file](https://github.com/starkware-libs/committer/blob/1a75fe7db7149ae1ceb9d8e02680e39b1910c499/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L32)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Needs the additional explanation in the docstring above as well.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 234 at r5](https://reviewable.io/reviews/starkware-libs/committer/253#-O0bwFdm27YR_bKcpzLA:-O0bwFdm27YR_bKcpzLB:bpzmfnb) ([raw file](https://github.com/starkware-libs/committer/blob/f995ec57dab8f9a49eb3a846d89ad60720d60acc/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L234)):*
> ```XML
>     #[case] expected_forest: OriginalSkeletonForestImpl<OriginalSkeletonTreeImpl>,
> ) {
>     let (actual_forest, current_contracts_trie_leaves) = OriginalSkeletonForestImpl::create(
> ```

Please search and replace for `curren_contract`



_Suggestion:_
```XML
original_contracts_trie_leaves
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/253)* status: 2 of 12 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 32 at r4](https://reviewable.io/reviews/starkware-libs/committer/253#-O0P1Vir64kIHwd7Yh4l:-O0bxjyrC5eWC_6H_X8r:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/1a75fe7db7149ae1ceb9d8e02680e39b1910c499/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L32)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Needs the additional explanation in the docstring above as well.
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 234 at r5](https://reviewable.io/reviews/starkware-libs/committer/253#-O0bwFdm27YR_bKcpzLA:-O0bxkS-9jSfO6ba8L0C:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f995ec57dab8f9a49eb3a846d89ad60720d60acc/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L234)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Please search and replace for `curren_contract`
</blockquote></details>

Done.

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/253#-:-O0cAN-c83rrqmv8X-DI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

**Pull request merged**
