### PR TITLE
build: add root hash field to filled tree

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/207)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/207)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/committer/207#-Nzw4hML5sOxZHOqsORY:-Nzw4hML5sOxZHOqsORZ:b-v3rx1t) ([raw file](https://github.com/starkware-libs/committer/blob/20d2d9e5c589bf547f78d57a2e6ab5c9f22bd175/crates/committer_cli/src/tests/utils/random_structs.rs#L190)):*
> ```XML
>         Self {
>             tree_map: nodes.into_iter().collect(),
>             root_hash: HashOutput::ROOT_OF_EMPTY_TREE,
> ```

why not `HashOutput::random(rng, HashOutput::MAX)` or something?



_Code quote:_
```XML
HashOutput::ROOT_OF_EMPTY_TREE
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 13 files at r2, 5 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/207)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/node.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/committer/207#-NzwKoPTA-FjqW2ab-Pq:-NzwKoPTA-FjqW2ab-Pr:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/5cf4e53c478155993c3c7ffb94f00b620e7762f3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/node.rs#L9)):*
> ```XML
>     Binary,
>     Edge(PathToBottom),
>     // Represents a root of a subtree where non of it's descendants has changed.
> ```

typo



_Suggestion:_
```XML
none 
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/node.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/committer/207#-NzwKw1CCMQE0XYhcrFd:-NzwKw1CCMQE0XYhcrFe:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/5cf4e53c478155993c3c7ffb94f00b620e7762f3/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/node.rs#L9)):*
> ```XML
>     Binary,
>     Edge(PathToBottom),
>     // Represents a root of a subtree where non of it's descendants has changed.
> ```

typo



_Suggestion:_
```XML
none
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/committer/207#-NzwKzbhEjeiRlMeBk1m:-NzwKzbhEjeiRlMeBk1n:b-uuws8u) ([raw file](https://github.com/starkware-libs/committer/blob/5cf4e53c478155993c3c7ffb94f00b620e7762f3/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L67)):*
> ```XML
>                     }
>                     OriginalSkeletonNode::UnmodifiedSubTree(_) => {
>                         unreachable!("Root node cannot be an unmodified.")
> ```

grammar



_Suggestion:_
```XML
be unmodified
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/207)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/committer/207#-NzwKzbhEjeiRlMeBk1m:-NzwLiaR5Wwub7dsMAYP:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/5cf4e53c478155993c3c7ffb94f00b620e7762f3/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L67)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

grammar
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 190 at r1](https://reviewable.io/reviews/starkware-libs/committer/207#-Nzw4hML5sOxZHOqsORY:-NzwLkJLAMTT2CuOSkNj:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/20d2d9e5c589bf547f78d57a2e6ab5c9f22bd175/crates/committer_cli/src/tests/utils/random_structs.rs#L190)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why not `HashOutput::random(rng, HashOutput::MAX)` or something?
</blockquote></details>

Done

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/207#-:-NzwMNPe0xnFVfzIShB9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
