### PR TITLE
refactor: deserializer for expected facts

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/294)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/294)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/committer/294#-O1Muqi87Ph2Fmv4b8YE:-O1Muqi87Ph2Fmv4b8YF:b-bv6duk) ([raw file](https://github.com/starkware-libs/committer/blob/f18283e387b184bb943573d82708ad74c1799ec9/crates/committer_cli/src/tests/benchmark_tests.rs#L31)):*
> ```XML
>     }
> }
> #[derive(Deserialize)]
> ```

newlines



_Suggestion:_
```XML
struct FactMap(Map<String, Value>);

impl<'de> Deserialize<'de> for FactMap {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(Self(
            serde_json::from_str(&String::deserialize(deserializer)?).unwrap(),
        ))
    }
}

#[derive(Deserialize)]
```
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/committer/294#-O1MvJ_S9yhlC_fzp1C9:-O1MvJ_S9yhlC_fzp1CA:b-nterq) ([raw file](https://github.com/starkware-libs/committer/blob/f18283e387b184bb943573d82708ad74c1799ec9/crates/committer_cli/src/tests/benchmark_tests.rs#L37)):*
> ```XML
>     contract_classes_root: String,
>     expected_facts: FactMap,
> }
> ```

if you apply this change, and change the signature of `commit` to accept `InputImpl` instead of string, does it just work? seems bad to mix a struct with both serialized and structured data



_Suggestion:_
```XML
struct CommitterRegressionInput {
    committer_input: InputImpl,
    contract_states_root: String,
    contract_classes_root: String,
    expected_facts: FactMap,
}
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/294)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/294)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/committer/294#-O1Muqi87Ph2Fmv4b8YE:-O1N5Byn8G-FncKgY75V:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f18283e387b184bb943573d82708ad74c1799ec9/crates/committer_cli/src/tests/benchmark_tests.rs#L31)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newlines
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/committer/294#-O1MvJ_S9yhlC_fzp1C9:-O1N1YG3BajxXQrl2tgh:b-ldq8wq) ([raw file](https://github.com/starkware-libs/committer/blob/f18283e387b184bb943573d82708ad74c1799ec9/crates/committer_cli/src/tests/benchmark_tests.rs#L37)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you apply this change, and change the signature of `commit` to accept `InputImpl` instead of string, does it just work? seems bad to mix a struct with both serialized and structured data
</blockquote></details>

But `commit` is part of our production code, so this refactor would become significantly more complicated. I can try to do it, but I don't think it belongs in this PR.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/294#-:-O1NBdfLDKE-kX1ZKtXT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/committer/294#-O1MvJ_S9yhlC_fzp1C9:-O1NBLrM0wAdesowlPWp:bnz5xzh) ([raw file](https://github.com/starkware-libs/committer/blob/f18283e387b184bb943573d82708ad74c1799ec9/crates/committer_cli/src/tests/benchmark_tests.rs#L37)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

But `commit` is part of our production code, so this refactor would become significantly more complicated. I can try to do it, but I don't think it belongs in this PR.
</blockquote></details>

right, out of scope.
why would it be so hard though? the deserialization will move up the stack in the committer CLI crate, python will send the same data

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/294)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 37 at r1](https://reviewable.io/reviews/starkware-libs/committer/294#-O1MvJ_S9yhlC_fzp1C9:-O1NBkZi6Zyuxaw3GW_t:b-f6020s) ([raw file](https://github.com/starkware-libs/committer/blob/f18283e387b184bb943573d82708ad74c1799ec9/crates/committer_cli/src/tests/benchmark_tests.rs#L37)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

right, out of scope.
why would it be so hard though? the deserialization will move up the stack in the committer CLI crate, python will send the same data
</blockquote></details>

It might be simple, but it's hard to say before I try. I added a TODO, and will try it tomorrow. I should mention that a side effect of this will be that deserialization will not be part of the benchmarking (currently, it is benchmarked).

**Pull request merged**
