### PR TITLE
build: adding get_leaves method to original skeleton tree

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/242)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/242)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/committer/242#-O0D_kOj47ywEEDqY75g:-O0D_kOj47ywEEDqY75h:b-b7tzug) ([raw file](https://github.com/starkware-libs/committer/blob/f36c15a041a3efb5284c824302ea2ac316a7346c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L53)):*
> ```XML
>         path_to_bottom: &PathToBottom,
>         bottom_hash: HashOutput,
>     ) -> (Self, Vec<&NodeIndex>) {
> ```

add a docstring documenting the return type



_Code quote:_
```XML
    fn get_bottom_subtree(
        &self,
        path_to_bottom: &PathToBottom,
        bottom_hash: HashOutput,
    ) -> (Self, Vec<&NodeIndex>) {
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/committer/242#-O0DaSlx1WDA6szxeoAh:-O0DaSlx1WDA6szxeoAi:b69l94t) ([raw file](https://github.com/starkware-libs/committer/blob/f36c15a041a3efb5284c824302ea2ac316a7346c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L163)):*
> ```XML
>                                 .collect::<HashMap<NodeIndex, L>>(),
>                         );
>                     }
> ```

why do you need to add zero-leaves...? what are "abandoned indices"?



_Code quote:_
```XML
                    if let Some(ref mut leaves) = previous_leaves {
                        leaves.extend(
                            abandoned_indices
                                .iter()
                                .map(|idx| (**idx, L::default()))
                                .collect::<HashMap<NodeIndex, L>>(),
                        );
                    }
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/committer/242#-O0Davnl5FyxRRHOYdYJ:-O0Davnl5FyxRRHOYdYK:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/f36c15a041a3efb5284c824302ea2ac316a7346c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L258)):*
> ```XML
>         sorted_leaf_indices: &[NodeIndex],
>         config: &impl OriginalSkeletonTreeConfig<L>,
>     ) -> OriginalSkeletonTreeResult<(Self, HashMap<NodeIndex, L>)> {
> ```





_Suggestion:_
```XML
LeafModifications<L>
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 280 at r2](https://reviewable.io/reviews/starkware-libs/committer/242#-O0Db2i25upFzrxLpMke:-O0Db2i25upFzrxLpMkf:bdpc6vw) ([raw file](https://github.com/starkware-libs/committer/blob/f36c15a041a3efb5284c824302ea2ac316a7346c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L280)):*
> ```XML
>                     .collect(),
>             ));
>         }
> ```

there is some duplication here with the above `create_impl`; please implement and use a utility function (private method on this type?)



_Code quote:_
```XML
        if sorted_leaf_indices.is_empty() {
            return Ok((
                Self {
                    nodes: HashMap::from([(
                        NodeIndex::ROOT,
                        OriginalSkeletonNode::UnmodifiedSubTree(root_hash),
                    )]),
                },
                HashMap::new(),
            ));
        }
        if root_hash == HashOutput::ROOT_OF_EMPTY_TREE {
            return Ok((
                Self {
                    nodes: HashMap::new(),
                },
                sorted_leaf_indices
                    .iter()
                    .map(|idx| (*idx, L::default()))
                    .collect(),
            ));
        }
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/242)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 53 at r2](https://reviewable.io/reviews/starkware-libs/committer/242#-O0D_kOj47ywEEDqY75g:-O0DflhY84t_HpGxc4Sa:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f36c15a041a3efb5284c824302ea2ac316a7346c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L53)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add a docstring documenting the return type
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 258 at r2](https://reviewable.io/reviews/starkware-libs/committer/242#-O0Davnl5FyxRRHOYdYJ:-O0DfNg83z4lJ39xNUcJ:b-tjthu3) ([raw file](https://github.com/starkware-libs/committer/blob/f36c15a041a3efb5284c824302ea2ac316a7346c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L258)):*
> ```XML
>         sorted_leaf_indices: &[NodeIndex],
>         config: &impl OriginalSkeletonTreeConfig<L>,
>     ) -> OriginalSkeletonTreeResult<(Self, HashMap<NodeIndex, L>)> {
> ```

I think it may be misleading; the return value is not the modifications but the previous leaves. The name may confuse
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 280 at r2](https://reviewable.io/reviews/starkware-libs/committer/242#-O0Db2i25upFzrxLpMke:-O0DiwEU0WU6R2xbgE4Z:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f36c15a041a3efb5284c824302ea2ac316a7346c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L280)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there is some duplication here with the above `create_impl`; please implement and use a utility function (private method on this type?)
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/242)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/committer/242#-O0DaSlx1WDA6szxeoAh:-O0DlvaK3PSjt32Bb4s1:bofnpet) ([raw file](https://github.com/starkware-libs/committer/blob/f36c15a041a3efb5284c824302ea2ac316a7346c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L163)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need to add zero-leaves...? what are "abandoned indices"?
</blockquote></details>

rename to `previously_empty_leaf_indices`
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/committer/242#-O0Dm3ki0iST2-YKLYZ1:-O0Dm3ki0iST2-YKLYZ2:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/cb812d63799f9111f77c6becd47ac6a5d0a136ed/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L51)):*
> ```XML
>     /// Returns the bottom subtree which is referred from `self` by the given path. When creating
>     /// the bottom subtree some indices that were modified under `self` are not modified under the
>     /// bottom subtree. These indices are returned as well.
> ```





_Suggestion:_
```XML
bottom subtree (leaves that were previously empty).
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 387 at r3](https://reviewable.io/reviews/starkware-libs/committer/242#-O0Dlq41BLpBHMghcntH:-O0Dlq41BLpBHMghcntI:b-l6mkjh) ([raw file](https://github.com/starkware-libs/committer/blob/cb812d63799f9111f77c6becd47ac6a5d0a136ed/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L387)):*
> ```XML
> 
>     // Get the bottom subtree.
>     let (subtree, abandoned_indices) =
> ```

rename



_Code quote:_
```XML
abandoned_indices
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 556 at r3](https://reviewable.io/reviews/starkware-libs/committer/242#-O0Dls9s1-WDczuY6RKI:-O0Dls9s1-WDczuY6RKJ:b-l6mkjh) ([raw file](https://github.com/starkware-libs/committer/blob/cb812d63799f9111f77c6becd47ac6a5d0a136ed/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L556)):*
> ```XML
> }
> 
> fn create_abandoned_indices<'a>(
> ```

rename



_Code quote:_
```XML
abandoned_indices
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/242)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 163 at r2](https://reviewable.io/reviews/starkware-libs/committer/242#-O0DaSlx1WDA6szxeoAh:-O0Dowoy-NJBv3FIBNvM:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f36c15a041a3efb5284c824302ea2ac316a7346c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L163)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rename to `previously_empty_leaf_indices`
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 51 at r3](https://reviewable.io/reviews/starkware-libs/committer/242#-O0Dm3ki0iST2-YKLYZ1:-O0Doxmw1suLONaOf1p9:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/cb812d63799f9111f77c6becd47ac6a5d0a136ed/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L51)):*
> ```XML
>     /// Returns the bottom subtree which is referred from `self` by the given path. When creating
>     /// the bottom subtree some indices that were modified under `self` are not modified under the
>     /// bottom subtree. These indices are returned as well.
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 387 at r3](https://reviewable.io/reviews/starkware-libs/committer/242#-O0Dlq41BLpBHMghcntH:-O0DpCYt1hNLNRzEZMmL:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/cb812d63799f9111f77c6becd47ac6a5d0a136ed/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L387)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 556 at r3](https://reviewable.io/reviews/starkware-libs/committer/242#-O0Dls9s1-WDczuY6RKI:-O0DpDTZ1wWh0lt2sYBj:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/cb812d63799f9111f77c6becd47ac6a5d0a136ed/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L556)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rename
</blockquote></details>

Done.

**Pull request merged**
