### PR TITLE
chore: move to Tokio :D

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/55)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/55)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @ittaysw)

___
*[`Cargo.toml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/committer/55#-NwDvhuL-cDdvzj1A8Uq:-NwDvhuL-cDdvzj1A8Ur:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/0b3c7e2ad49c4c4de07767581515b73cfa82adf4/Cargo.toml#L18)):*
> ```TOML
> bisection = "0.1.0"
> async-recursion = "1.1.0"
> clap = { version = "4.5.4", features = ["cargo", "derive"] }
> ```





_Suggestion:_
```TOML
async-recursion = "1.1.0"
bisection = "0.1.0"
clap = { version = "4.5.4", features = ["cargo", "derive"] }
```
___
*[`crates/committer/Cargo.toml` line 19 at r1](https://reviewable.io/reviews/starkware-libs/committer/55#-NwDvm8U4VUxPUq_2GCa:-NwDvm8U4VUxPUq_2GCb:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/0b3c7e2ad49c4c4de07767581515b73cfa82adf4/crates/committer/Cargo.toml#L19)):*
> ```TOML
> bisection.workspace = true
> async-recursion.workspace = true
> derive_more.workspace = true
> ```





_Suggestion:_
```TOML
async-recursion.workspace = true
bisection.workspace = true
derive_more.workspace = true
```
___
*[`crates/committer/Cargo.toml` line 24 at r1](https://reviewable.io/reviews/starkware-libs/committer/55#-NwDvoVFBjwvjpU0dTsE:-NwDvoVFBjwvjpU0dTsF:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/0b3c7e2ad49c4c4de07767581515b73cfa82adf4/crates/committer/Cargo.toml#L24)):*
> ```TOML
> starknet-types-core.workspace = true
> thiserror.workspace = true
> tokio = { version = "1", features = ["full"] }
> ```





_Suggestion:_
```TOML
tokio.workspace = true
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/55)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @ittaysw)

___
*[`Cargo.toml` line 18 at r1](https://reviewable.io/reviews/starkware-libs/committer/55#-NwDvhuL-cDdvzj1A8Uq:-NwEtZlB3vWcu0cJBNWC:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/0b3c7e2ad49c4c4de07767581515b73cfa82adf4/Cargo.toml#L18)):*
> ```TOML
> bisection = "0.1.0"
> async-recursion = "1.1.0"
> clap = { version = "4.5.4", features = ["cargo", "derive"] }
> ```

Done.
___
*[`crates/committer/Cargo.toml` line 19 at r1](https://reviewable.io/reviews/starkware-libs/committer/55#-NwDvm8U4VUxPUq_2GCa:-NwEtZJd6IPkpYSA823x:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/0b3c7e2ad49c4c4de07767581515b73cfa82adf4/crates/committer/Cargo.toml#L19)):*
> ```TOML
> bisection.workspace = true
> async-recursion.workspace = true
> derive_more.workspace = true
> ```

Done.
___
*[`crates/committer/Cargo.toml` line 24 at r1](https://reviewable.io/reviews/starkware-libs/committer/55#-NwDvoVFBjwvjpU0dTsE:-NwEtYHH9N1GNV9Tlzso:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/0b3c7e2ad49c4c4de07767581515b73cfa82adf4/crates/committer/Cargo.toml#L24)):*
> ```TOML
> starknet-types-core.workspace = true
> thiserror.workspace = true
> tokio = { version = "1", features = ["full"] }
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/55#-:-NwEwDsm1iZ4ZyG90QGp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @ittaysw)

**Review by ittaysw — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/55#-:-NwIRAD4-Nb7fbcSS2im:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
