### PR TITLE
refactor: define a wrapper for sorted_leaf_indices

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/261)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/261)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/committer/261#-O0iJlmfAz_B0NPdDMJ-:-O0iJlmfAz_B0NPdDMJ0:b-bv6duk) ([raw file](https://github.com/starkware-libs/committer/blob/d0137330f7492d627b28c64bbd6cb7c59561f81b/crates/committer/src/patricia_merkle_tree/types.rs#L244)):*
> ```XML
>     pub(crate) fn divide_at_index(&self, idx: usize) -> [Self; 2] {
>         [Self(&self.0[..idx]), Self(&self.0[idx..])]
>     }
> ```

newlines



_Suggestion:_
```XML
    /// Creates a new instance by sorting the given indices.
    pub(crate) fn new(indices: &'a mut [NodeIndex]) -> Self {
        indices.sort();
        Self(indices)
    }
    
    /// Returns a subslice of the indices stored at self, at the range [leftmost_idx, rightmost_idx).
    pub(crate) fn subslice(&self, leftmost_idx: usize, rightmost_idx: usize) -> Self {
        Self(&self.0[leftmost_idx..rightmost_idx])
    }
    
    /// Divides the slice held by self into two instances. One holds the range [0, idx), the
    /// other holds the range [idx, len(self)).
    pub(crate) fn divide_at_index(&self, idx: usize) -> [Self; 2] {
        [Self(&self.0[..idx]), Self(&self.0[idx..])]
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/committer/261#-O0iURKZ5Oko9x3jtnwd:-O0iURKZ5Oko9x3jtnwe:bh9mvus) ([raw file](https://github.com/starkware-libs/committer/blob/d0137330f7492d627b28c64bbd6cb7c59561f81b/crates/committer/src/patricia_merkle_tree/types.rs#L264)):*
> ```XML
>     pub(crate) fn last(&self) -> Option<&'a NodeIndex> {
>         self.0.last()
>     }
> ```

can you use `derive_more` to get these for "free"?



_Code quote:_
```XML
    pub(crate) fn contains(&self, value: &NodeIndex) -> bool {
        self.0.contains(value)
    }

    pub(crate) fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    pub(crate) fn len(&self) -> usize {
        self.0.len()
    }

    pub(crate) fn last(&self) -> Option<&'a NodeIndex> {
        self.0.last()
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/committer/261#-O0iVTw24VzstyuNkhUG:-O0iVTw24VzstyuNkhUH:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/d0137330f7492d627b28c64bbd6cb7c59561f81b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs#L57)):*
> ```XML
>         subtree_indices.get_indices()[0]
>             .get_lca(subtree_indices.last().expect("Unexpected empty array"))
>     };
> ```





_Suggestion:_
```XML
    }
    let first_index = subtree_indices.get_indices()[0];
    let lca = if subtree_indices.len() == 1 {
        first_index
    } else {
        first_index
            .get_lca(subtree_indices.last().expect("Unexpected empty array"))
    };
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/261)* status: 8 of 11 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 244 at r2](https://reviewable.io/reviews/starkware-libs/committer/261#-O0iJlmfAz_B0NPdDMJ-:-O0mRJwg0CafaHDgQuYz:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d0137330f7492d627b28c64bbd6cb7c59561f81b/crates/committer/src/patricia_merkle_tree/types.rs#L244)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newlines
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 264 at r2](https://reviewable.io/reviews/starkware-libs/committer/261#-O0iURKZ5Oko9x3jtnwd:-O0mReamCTz-_1LO9LCV:bfy46z0) ([raw file](https://github.com/starkware-libs/committer/blob/d0137330f7492d627b28c64bbd6cb7c59561f81b/crates/committer/src/patricia_merkle_tree/types.rs#L264)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you use `derive_more` to get these for "free"?
</blockquote></details>

dont think so; it doesn't appear [here](https://crates.io/crates/derive_more/0.99.18) 
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/committer/261#-O0i2G9iAlc3DTxxiGmu:-O0i2G9iAlc3DTxxiGmv:b-9v70dp) ([raw file](https://github.com/starkware-libs/committer/blob/f3e660aee995a36ea34d6def8abd80c33ceb2744/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L56)):*
> ```XML
>         path_to_bottom: &PathToBottom,
>         bottom_hash: HashOutput,
>     ) -> (Self, Vec<&NodeIndex>) {
> ```

maybe this return value is better?



_Suggestion:_
```XML
SortedLeafIndices
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/committer/261#-O0iVTw24VzstyuNkhUG:-O0mSpVP5UizKyiHNg2Z:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d0137330f7492d627b28c64bbd6cb7c59561f81b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs#L57)):*
> ```XML
>         subtree_indices.get_indices()[0]
>             .get_lca(subtree_indices.last().expect("Unexpected empty array"))
>     };
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/261)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 267 at r4](https://reviewable.io/reviews/starkware-libs/committer/261#-O0mUJv0B1dvAL6J1YA9:-O0mUJv0B1dvAL6J1YAA:b-l5o40b) ([raw file](https://github.com/starkware-libs/committer/blob/f593de2a0699626f0ec621ea7441be973929d541/crates/committer/src/patricia_merkle_tree/types.rs#L267)):*
> ```XML
>     pub(crate) fn last(&self) -> Option<&'a NodeIndex> {
>         self.0.last()
>     }
> ```

doesn't the compiler infer the lifetime from `&self`? non-blocking



_Suggestion:_
```XML
    pub(crate) fn get_indices(&self) -> &[NodeIndex] {
        self.0
    }

    pub(crate) fn contains(&self, value: &NodeIndex) -> bool {
        self.0.contains(value)
    }

    pub(crate) fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    pub(crate) fn len(&self) -> usize {
        self.0.len()
    }

    pub(crate) fn last(&self) -> Option<&NodeIndex> {
        self.0.last()
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 271 at r4](https://reviewable.io/reviews/starkware-libs/committer/261#-O0mU34d8uzXhw7W4tIG:-O0mU34d8uzXhw7W4tIH:bl9gech) ([raw file](https://github.com/starkware-libs/committer/blob/f593de2a0699626f0ec621ea7441be973929d541/crates/committer/src/patricia_merkle_tree/types.rs#L271)):*
> ```XML
>     pub(crate) fn first(&self) -> NodeIndex {
>         self.0[0]
>     }
> ```

this can panic but `last` cannot; please align APIs



_Suggestion:_
```XML
    pub(crate) fn first(&self) -> Option<NodeIndex> {
        self.0[0]
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/committer/261#-O0i2G9iAlc3DTxxiGmu:-O0mUcuh9fepFBIg3hHU:b-app7ju) ([raw file](https://github.com/starkware-libs/committer/blob/f3e660aee995a36ea34d6def8abd80c33ceb2744/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L56)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

maybe this return value is better?
</blockquote></details>

yes, but in a separate PR... this will require implementing a more complex method on `SortedLeafIndices` to construct the sorted output in a safe manner (we don't want a `new_unchecked` method, and we don't want to waste time re-sorting an already sorted slice)
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/committer/261#-O0iVTw24VzstyuNkhUG:-O0mUTVx-RYg_cntO8EZ:b-s4iqoq) ([raw file](https://github.com/starkware-libs/committer/blob/d0137330f7492d627b28c64bbd6cb7c59561f81b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs#L57)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no, you still call`first()` twice

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/261)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 267 at r4](https://reviewable.io/reviews/starkware-libs/committer/261#-O0mUJv0B1dvAL6J1YA9:-O0mav8E51JSASbBSei1:b-7nubvm) ([raw file](https://github.com/starkware-libs/committer/blob/f593de2a0699626f0ec621ea7441be973929d541/crates/committer/src/patricia_merkle_tree/types.rs#L267)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

doesn't the compiler infer the lifetime from `&self`? non-blocking
</blockquote></details>

it does only for `fn last`
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 271 at r4](https://reviewable.io/reviews/starkware-libs/committer/261#-O0mU34d8uzXhw7W4tIG:-O0mb3Ye0OuyCfR3vb06:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f593de2a0699626f0ec621ea7441be973929d541/crates/committer/src/patricia_merkle_tree/types.rs#L271)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this can panic but `last` cannot; please align APIs
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs` line 57 at r2](https://reviewable.io/reviews/starkware-libs/committer/261#-O0iVTw24VzstyuNkhUG:-O0mbv7LCtEDBfLnWUHc:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d0137330f7492d627b28c64bbd6cb7c59561f81b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs#L57)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, you still call`first()` twice
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/261#-:-O0mg4PU0JOiRMdIJzJA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
