### PR TITLE
chore(skeleton): common split_leaves function

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/112)

### CODE REVIEW

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/112)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/112#-Nxgs2fj4pkqc6GS6eFh:-Nxgs2fj4pkqc6GS6eFi:b-6vo54r) (no related file):*
Waiting for @nimrod-starkware to fix a test, but can still be reviewed.

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/112)* status: all files reviewed, 12 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxguXzT0PiJ3fwA0ld6:-NxguXzU3DozAKAJJYhD:byyxpks) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/types.rs#L45)):*
> ```XML
>     pub const ROOT: Self = Self(U256::ONE);
> 
>     #[allow(clippy::as_conversions)]
> ```

where is there an `as` here?



_Code quote:_
```XML
#[allow(clippy::as_conversions)]
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxguLhx1vGv0Y7rT_nK:-NxguLhx1vGv0Y7rT_nL:bjyc1er) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/types.rs#L46)):*
> ```XML
> 
>     #[allow(clippy::as_conversions)]
>     pub const _FIRST_LEAF: Self = Self(U256::from_words(1_u128 << (Self::BITS - 1 - 128), 0));
> ```

so... `from_words` is `const` on U256, but `lsh` is not?
bummer



_Code quote:_
```XML
pub const _FIRST_LEAF: Self = Self(U256::from_words(1_u128 << (Self::BITS - 1 - 128), 0));
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxguS9MDie8utETQIKo:-NxguS9MDie8utETQIKp:bq9dc1g) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/types.rs#L46)):*
> ```XML
> 
>     #[allow(clippy::as_conversions)]
>     pub const _FIRST_LEAF: Self = Self(U256::from_words(1_u128 << (Self::BITS - 1 - 128), 0));
> ```

remove the underscore - if you want this to be private, remove the `pub`



_Suggestion:_
```XML
const FIRST_LEAF
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-Nxgvvn41KRCPx2WT90c:-Nxgvvn41KRCPx2WT90d:bcmhguw) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L51)):*
> ```XML
>         split_leaves(&self.tree_height, root_index, leaf_indices)
>             .iter()
>             .all(|x| !x.is_empty())
> ```

for clarity



_Suggestion:_
```XML
.all(|leaves_in_side| !leaves_in_side.is_empty())
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxgvBRXARUtWwCKcPoK:-NxgvBRXARUtWwCKcPoL:b27on51) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs#L9)):*
> ```XML
> pub mod utils_test;
> 
> pub(crate) fn get_node_height(tree_height: &TreeHeight, index: &NodeIndex) -> TreeHeight {
> ```

docstring (the name is confusing)
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs` line 43 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-Nxgw5_QA-8lTm1Ohs8S:-Nxgw5_QA-8lTm1Ohs8T:bge7dvc) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs#L43)):*
> ```XML
>             .last()
>             .expect("leaf_indices unexpectedly empty.");
>         assert_descendant(last_leaf);
> ```

redundant variable (non-blocking)



_Suggestion:_
```XML
        assert_descendant(leaf_indices
            .last()
            .expect("leaf_indices unexpectedly empty.")
        );
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-Nxgvjev7LlpAoH2k9hm:-Nxgvjev7LlpAoH2k9hn:b-26a6or) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs#L46)):*
> ```XML
>     }
> 
>     let right_child_index = (*root_index << 1) + 1.into();
> ```

isn't this what was originally written?



_Suggestion:_
```XML
NodeIndex::ROOT
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxgxT-C9XhafXjz6LV6:-NxgxT-C9XhafXjz6LV7:bh8f948) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs#L13)):*
> ```XML
>     if jump == U256::ZERO {
>         jump = (U256::MAX - start) / size_u256;
>     }
> ```

this "feature" is not used, right?



_Suggestion:_
```XML
/// Creates an array of increasing random U256 numbers, with jumps of up to 'jump' between two
/// consecutive numbers.
fn create_increasing_random_array(size: usize, start: U256, jump: U256) -> Vec<U256> {
    let size_u256: U256 = size.try_into().unwrap();
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxgwQ8A2ZW4TQar6dqR:-NxgwQ8A2ZW4TQar6dqS:bbsfhwc) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs#L36)):*
> ```XML
> #[should_panic]
> #[case::small_tree_not_descendant(
>         3_u8, uint!("2"), &[uint!("8"), uint!("10"), uint!("14")], &[], &[])]
> ```

no auto-format in macros (like `#[case]` attributes)...
please try to conform to "correct" formatting manually



_Suggestion:_
```XML
#[case::small_tree_one_side(
    3_u8, U256::ONE, &[uint!("8"), uint!("10"), uint!("11")],
    &[uint!("8"), uint!("10"), uint!("11")], &[]
)]
#[case::small_tree_two_sides(
    3_u8, U256::ONE, &[uint!("8"), uint!("10"), uint!("14")],
    &[uint!("8"), uint!("10")], &[uint!("14")]
)]
#[should_panic]
#[case::small_tree_wrong_height(
    3_u8, U256::ONE, &[uint!("8"), uint!("10"), uint!("16")], &[], &[]
)]
#[should_panic]
#[case::small_tree_not_descendant(
    3_u8, uint!("2"), &[uint!("8"), uint!("10"), uint!("14")], &[], &[]
)]
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxgwMWv7KtRPbjmv-Ag:-NxgwMWv7KtRPbjmv-Ah:b-fgj26b) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs#L38)):*
> ```XML
>         3_u8, uint!("2"), &[uint!("8"), uint!("10"), uint!("14")], &[], &[])]
> 
> fn test_split_leaves(
> ```

remove newline



_Suggestion:_
```XML
        3_u8, uint!("2"), &[uint!("8"), uint!("10"), uint!("14")], &[], &[])]
fn test_split_leaves(
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxgwvXk0eMzMo1atZPK:-NxgwvXk0eMzMo1atZPL:b-fgj26b) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs#L58)):*
> ```XML
> #[rstest]
> 
> fn test_split_leaves_big_tree() {
> ```

remove newline



_Suggestion:_
```XML
#[rstest]
fn test_split_leaves_big_tree() {
```

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/112)* status: all files reviewed, 13 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxhKHEsE2PPp3wzMsRD:-NxhKHEsE2PPp3wzMsRE:b-vnmpb5) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs#L17)):*
> ```XML
> /// * The leaf indices array is sorted.
> /// * All leaves are descendants of the root.
> pub(crate) fn split_leaves<'a>(
> ```

this implementation is prettier and more concise - is it less efficient?
if not, please use it



_Code quote:_
```XML
pub(crate) fn split_leaves<'a>(
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/112)* status: all files reviewed, 11 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxguXzT0PiJ3fwA0ld6:-Nxhzpma5jYIVDHyeMwT:bfrhmth) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/types.rs#L45)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where is there an `as` here?
</blockquote></details>

Oops, copy leftovers.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxguLhx1vGv0Y7rT_nK:-Nxhzta83nB-ErPAMWvA:bfj6i98) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/types.rs#L46)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so... `from_words` is `const` on U256, but `lsh` is not?
bummer
</blockquote></details>

Yes, that's what Yoni noticed.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxguS9MDie8utETQIKo:-Nxi-1SwBvq-mDZnwV5R:b5t1hxb) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/types.rs#L46)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove the underscore - if you want this to be private, remove the `pub`
</blockquote></details>

It's just for this PR as it's not used (test only). Will be used in the following. Prefer I bypass the warning?
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs` line 51 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-Nxgvvn41KRCPx2WT90c:-Nxi-RazCCSJW7icbwYN:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs#L51)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

for clarity
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxgvBRXARUtWwCKcPoK:-Nxi-_2w-iPtK9R7fX2j:b-ilz5bi) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

docstring (the name is confusing)
</blockquote></details>

Is this OK?
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxhKHEsE2PPp3wzMsRD:-Nxi1bsS3kFQbmi4I5zv:b3gtfut) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs#L17)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

this implementation is prettier and more concise - is it less efficient?
if not, please use it
</blockquote></details>

Do you mean the implementation that was in `create_tree`? It's still here (at the bottom). I just added assertions that the first and last leaves are actual descendants of the given root.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-Nxgvjev7LlpAoH2k9hm:-Nxi085H1n_c3ST_nfAt:b-scalzn) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs#L46)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

isn't this what was originally written?
</blockquote></details>

I don't know, but IMO it makes sense to add 1 to the left son to get the right son and less sense to add ROOT to i.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxgxT-C9XhafXjz6LV6:-Nxi0MNL2zRzxYYLtSv3:b8qc3dm) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this "feature" is not used, right?
</blockquote></details>

Yep, not ATM. Removed.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxgwQ8A2ZW4TQar6dqR:-Nxi0pXhCd6XXcYLlWTT:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no auto-format in macros (like `#[case]` attributes)...
please try to conform to "correct" formatting manually
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxgwMWv7KtRPbjmv-Ag:-Nxi0qUc3qm87HvRJTxc:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs#L38)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove newline
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxgwvXk0eMzMo1atZPK:-Nxi0te446bV4FDTgl0p:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove newline
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/112#-:-NxiOZgZ3JsyOX_Dcn9n:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxguS9MDie8utETQIKo:-NxiOFXK86jInBmIOZDG:bvg8moj) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/types.rs#L46)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

It's just for this PR as it's not used (test only). Will be used in the following. Prefer I bypass the warning?
</blockquote></details>

ah... ok I didn't realise the ocmpiler caught you. unblocking, either way is fine

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/112)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/112#-Nxgs2fj4pkqc6GS6eFh:-NxlLeGCEz0CUxwKkRTS:b-j2bb76) (no related file):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Waiting for @nimrod-starkware to fix a test, but can still be reviewed.
</blockquote></details>

[PR](https://github.com/starkware-libs/committer/pull/114) that fixes the test

___

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/112)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/112)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/committer/112#-NxhKHEsE2PPp3wzMsRD:-Nxv8Rw-3liJjAVp1U66:b-onzf8l) ([raw file](https://github.com/starkware-libs/committer/blob/34bb228bc7dca16de1f58c6f25037a65789115e1/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs#L17)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Do you mean the implementation that was in `create_tree`? It's still here (at the bottom). I just added assertions that the first and last leaves are actual descendants of the given root.
</blockquote></details>

oh ok, removed block.
consider making `assert_descendant` a separate function

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/112)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 8 of 8 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/112)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by amosStarkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/112)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
