### PR TITLE
chore(skeleton): update_node_in_nonempty_tree in updated_skeleton

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/162)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/162)* status: all files reviewed, 5 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/committer/162#-Nz2VRQJ9gqZcrCTPNB2:-Nz2VRQJ9gqZcrCTPNB3:b-ga8bwx) ([raw file](https://github.com/starkware-libs/committer/blob/b1fce0411ef54feb70838a5d2655064f32966c6f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L135)):*
> ```XML
>             );
>             return TempSkeletonNode::Original(original_node);
>         }
> ```

suggestion: (a) use `match` and (b) print out the node index in `panic`



_Suggestion:_
```XML
        if leaf_indices.is_empty() {
            match original_node {
                OriginalSkeletonNode::Binary => panic!(
                    "An original binary node (at index {root_index}) without leaf modifications should produce a sibling."
                ),
                OriginalSkeletonNode::UnmodifiedBottom(_) => panic!(
                    "An unmodified bottom (at index {root_index}) must have an original edge parent without leaf modifications."
                )
                OriginalSkeletonNode::Edge(_)
                | OriginalSkeletonNode::LeafOrBinarySibling(_)
                | OriginalSkeletonNode::Leaf => return TempSkeletonNode::Original(original_node);
            }
        }
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/committer/162#-Nz2Z1ez6q1G5ZGWVA5i:-Nz2Z1ez6q1G5ZGWVA5j:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/b1fce0411ef54feb70838a5d2655064f32966c6f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L204)):*
> ```XML
>                     OriginalSkeletonNode::LeafOrBinarySibling(_)
>                     | OriginalSkeletonNode::UnmodifiedBottom(_) => {
>                         // Unmodified nodes are finalized upon updated skeleton creation.
> ```





_Suggestion:_
```XML
Unmodified nodes are finalized in the initial phase of updated skeleton creation.
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/committer/162#-Nz2_cU01JVqicu5XZiZ:-Nz2_cU01JVqicu5XZi_:b-giezzf) ([raw file](https://github.com/starkware-libs/committer/blob/b1fce0411ef54feb70838a5d2655064f32966c6f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L384)):*
> ```XML
>     ],
> )]
> fn test_update_node_in_nonempty_tree(
> ```

what about test cases for edges? you covered leaves and binary nodes
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/committer/162#-Nz2Za8x4R2ukICh_tdr:-Nz2Za8x4R2ukICh_tds:bhy5pk4) ([raw file](https://github.com/starkware-libs/committer/blob/b1fce0411ef54feb70838a5d2655064f32966c6f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L387)):*
> ```XML
>     #[case] root_index: &NodeIndex,
>     #[case] mut original_skeleton: HashMap<NodeIndex, OriginalSkeletonNode>,
>     #[case] leaf_modifications: &[(U256, u8)],
> ```

all of your `#[case]`s do `U256::from(NodeIndex::from(...`, no point in converting to U256 and back again...
or do you need it for the `updated_skeleton` fixture? (non-blocking)



_Suggestion:_
```XML
#[case] leaf_modifications: &[(NodeIndex, u8)],
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/committer/162#-Nz2_oluBQDhoumWh2sW:-Nz2_oluBQDhoumWh2sX:bm0nn2f) ([raw file](https://github.com/starkware-libs/committer/blob/b1fce0411ef54feb70838a5d2655064f32966c6f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L82)):*
> ```XML
>                             },
>                         )
>                     }),
> ```

no need for panic, just filter during your map (I used a `flat_map` to skip unwanted values, maybe you can find a less hack way without panic)



_Suggestion:_
```XML
                    .flat_map(|(index, node)| {
                        match node {
                            OriginalSkeletonNode::LeafOrBinarySibling(hash) => {
                                [(*index, UpdatedSkeletonNode::Sibling(*hash))].iter()
                            }
                            OriginalSkeletonNode::UnmodifiedBottom(hash) => {
                                [(*index, UpdatedSkeletonNode::UnmodifiedBottom(*hash))].iter(),
                            }
                            OriginalSkeletonNode::Binary
                            | OriginalSkeletonNode::Edge(_)
                            | OriginalSkeletonNode::Leaf => [].iter()
                        },
                    }),
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/162)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 135 at r1](https://reviewable.io/reviews/starkware-libs/committer/162#-Nz2VRQJ9gqZcrCTPNB2:-Nz2q_o62RpI7iWwox6S:bam7vo8) ([raw file](https://github.com/starkware-libs/committer/blob/b1fce0411ef54feb70838a5d2655064f32966c6f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L135)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

suggestion: (a) use `match` and (b) print out the node index in `panic`
</blockquote></details>

Hopefully, I didn't over-comment.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/committer/162#-Nz2Z1ez6q1G5ZGWVA5i:-Nz2igKS-O1fU0EK4ZxT:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b1fce0411ef54feb70838a5d2655064f32966c6f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L204)):*
> ```XML
>                     OriginalSkeletonNode::LeafOrBinarySibling(_)
>                     | OriginalSkeletonNode::UnmodifiedBottom(_) => {
>                         // Unmodified nodes are finalized upon updated skeleton creation.
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 384 at r1](https://reviewable.io/reviews/starkware-libs/committer/162#-Nz2_cU01JVqicu5XZiZ:-Nz2ing2-Pfi9Q5CL0zl:b-yan1b) ([raw file](https://github.com/starkware-libs/committer/blob/b1fce0411ef54feb70838a5d2655064f32966c6f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L384)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what about test cases for edges? you covered leaves and binary nodes
</blockquote></details>

This is currently not implemented (`update_edge_node`). Will be added in the following PR.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 387 at r1](https://reviewable.io/reviews/starkware-libs/committer/162#-Nz2Za8x4R2ukICh_tdr:-Nz2jniKBZvcub3fCizM:b-whx4yb) ([raw file](https://github.com/starkware-libs/committer/blob/b1fce0411ef54feb70838a5d2655064f32966c6f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L387)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

all of your `#[case]`s do `U256::from(NodeIndex::from(...`, no point in converting to U256 and back again...
or do you need it for the `updated_skeleton` fixture? (non-blocking)
</blockquote></details>

They are U256 because of the usage in the `updated_skeleton` fixture. I want the input their to be U256 because it's simpler for basic examples. I have to use NodeIndex here to get to the FIrstLeaf because of the hardcoded TreeHeight limitation we have ATM, otherwise, I would have used small indices here as well.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 82 at r1](https://reviewable.io/reviews/starkware-libs/committer/162#-Nz2_oluBQDhoumWh2sW:-Nz2oWpm8T1aein-fTbn:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b1fce0411ef54feb70838a5d2655064f32966c6f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L82)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no need for panic, just filter during your map (I used a `flat_map` to skip unwanted values, maybe you can find a less hack way without panic)
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/162)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/committer/162#-Nz2Z1ez6q1G5ZGWVA5i:-Nz2rpuM08M_ksL3ajJR:b-g3x89v) ([raw file](https://github.com/starkware-libs/committer/blob/b1fce0411ef54feb70838a5d2655064f32966c6f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L204)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

in line 184, yes.
here, no

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/162)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 204 at r1](https://reviewable.io/reviews/starkware-libs/committer/162#-Nz2Z1ez6q1G5ZGWVA5i:-Nz30V6b7YSBEqQeyO2a:b-nj5xqp) ([raw file](https://github.com/starkware-libs/committer/blob/b1fce0411ef54feb70838a5d2655064f32966c6f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L204)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

in line 184, yes.
here, no
</blockquote></details>

Now done :|

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/162#-:-Nz3FGVoEVZu9il-5yWY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
