### PR TITLE
test: add single tree flow test

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/206)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/206)* status: all files reviewed, 8 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/committer/206#-NzwQGnY8ZQ3CH5s_VwG:-NzwQGnY8ZQ3CH5s_VwH:bpy9pp0) ([raw file](https://github.com/starkware-libs/committer/blob/777eacd8a778783565bac217cbcefbb693a3489c/crates/committer/src/patricia_merkle_tree/test_utils.rs#L40)):*
> ```XML
> use crate::patricia_merkle_tree::node_data::leaf::{LeafDataImpl, LeafModifications};
> 
> use super::updated_skeleton_tree::hash_function::TreeHashFunctionImpl;
> ```

move all of these imports to the top of the module



_Code quote:_
```XML
use crate::patricia_merkle_tree::filled_tree::tree::{FilledTree, FilledTreeImpl};
use crate::patricia_merkle_tree::original_skeleton_tree::tree::{
    OriginalSkeletonTree, OriginalSkeletonTreeImpl,
};
use crate::patricia_merkle_tree::types::NodeIndex;
use crate::patricia_merkle_tree::updated_skeleton_tree::tree::{
    UpdatedSkeletonTree, UpdatedSkeletonTreeImpl,
};

use crate::patricia_merkle_tree::node_data::leaf::{LeafDataImpl, LeafModifications};

use super::updated_skeleton_tree::hash_function::TreeHashFunctionImpl;
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/committer/206#-NzwQNWP3wNl4Q_p6IqF:-NzwQNWP3wNl4Q_p6IqG:b700jw8) ([raw file](https://github.com/starkware-libs/committer/blob/777eacd8a778783565bac217cbcefbb693a3489c/crates/committer/src/patricia_merkle_tree/test_utils.rs#L74)):*
> ```XML
> 
> #[cfg(test)]
> impl NodeIndex {
> ```

why are there `cfg(test)`s here? this is a test utils module; it should already be gated.
@AvivYossef-starkware can you TAL please?



_Code quote:_
```XML
#[cfg(test)]
use crate::patricia_merkle_tree::types::SubTreeHeight;

#[cfg(test)]
impl NodeIndex {
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 151 at r1](https://reviewable.io/reviews/starkware-libs/committer/206#-NzwRbyR-0UL8uxvQCWJ:-NzwRbyR-0UL8uxvQCWK:bjymoed) ([raw file](https://github.com/starkware-libs/committer/blob/777eacd8a778783565bac217cbcefbb693a3489c/crates/committer/src/patricia_merkle_tree/test_utils.rs#L151)):*
> ```XML
>     root_hash: HashOutput,
> ) -> String {
>     //Move from leaf number to actual index
> ```

punctuation, space after `//` (non-blocking)



_Suggestion:_
```XML
// Move from leaf number to actual index.
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/committer/206#-NzwRZag75Lvmydeo7fo:-NzwRZahEvFZpFGmEaXT:b3runn7) ([raw file](https://github.com/starkware-libs/committer/blob/777eacd8a778783565bac217cbcefbb693a3489c/crates/committer/src/patricia_merkle_tree/test_utils.rs#L155)):*
> ```XML
>         .into_iter()
>         .map(|(k, v)| (NodeIndex::FIRST_LEAF + k, v))
>         .collect::<HashMap<NodeIndex, LeafDataImpl>>();
> ```

aren't the input indices already in full-index format...?



_Code quote:_
```XML
    //Move from leaf number to actual index
    let leaf_modifications = leaf_modifications
        .into_iter()
        .map(|(k, v)| (NodeIndex::FIRST_LEAF + k, v))
        .collect::<HashMap<NodeIndex, LeafDataImpl>>();
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/committer/206#-NzwRpUI1Ok8WhbPl6Zj:-NzwRpUI1Ok8WhbPl6Zk:b-ptb30m) ([raw file](https://github.com/starkware-libs/committer/blob/777eacd8a778783565bac217cbcefbb693a3489c/crates/committer/src/patricia_merkle_tree/test_utils.rs#L170)):*
> ```XML
>             &leaf_modifications,
>         )
>         .expect("Failed to create the updated skeleton tree");
> ```

if you add `impl<L: LeafData> Form<LeafModifications<L>> for LeafModifications<SkeletonLeaf>`, this change below will work



_Suggestion:_
```XML
    let updated_skeleton: UpdatedSkeletonTreeImpl =
        UpdatedSkeletonTree::create(
            &mut original_skeleton,
            &leaf_modifications.into(),
        )
        .expect("Failed to create the updated skeleton tree");
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 183 at r1](https://reviewable.io/reviews/starkware-libs/committer/206#-NzwS0nz68dGBCzWVE9_:-NzwS0nz68dGBCzWVE9a:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/777eacd8a778783565bac217cbcefbb693a3489c/crates/committer/src/patricia_merkle_tree/test_utils.rs#L183)):*
> ```XML
>     // Serialize the hash result
> 
>     hash_result.0.to_hex()
> ```





_Suggestion:_
```XML
    // Serialize the hash result.
    hash_result.0.to_hex()
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/committer/206#-NzwS2lF690kI73rqozZ:-NzwS2lF690kI73rqoz_:b-npqgn) ([raw file](https://github.com/starkware-libs/committer/blob/777eacd8a778783565bac217cbcefbb693a3489c/crates/committer/src/patricia_merkle_tree/test_utils.rs#L185)):*
> ```XML
>     hash_result.0.to_hex()
> 
>     // TODO(Aner, 9/6/24): Serlialize the storage modifications
> ```

is this in the next PR?



_Code quote:_
```XML
 // TODO(Aner, 9/6/24): Serlialize the storage modification
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 173 at r1](https://reviewable.io/reviews/starkware-libs/committer/206#-NzwSAvq7xCn6kirByt1:-NzwSAvq7xCn6kirByt2:b-kt24hk) ([raw file](https://github.com/starkware-libs/committer/blob/777eacd8a778783565bac217cbcefbb693a3489c/crates/committer_cli/src/tests/python_tests.rs#L173)):*
> ```XML
>                 let output =
>                     rust_single_tree_flow_test(leaf_modifications, storage, root_hash).await;
>                 //3. Serialize and return output
> ```

space after `//` + punctuation



_Suggestion:_
```XML
                // 1. Get and deserialize input.
                let input: HashMap<String, String> =
                    serde_json::from_str(Self::non_optional_input(input)?)?;
                let (leaf_modifications, storage, root_hash) =
                    parse_input_single_storage_tree_flow_test(input);
                // 2. Run the test.
                let output =
                    rust_single_tree_flow_test(leaf_modifications, storage, root_hash).await;
                // 3. Serialize and return output.
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/206)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/committer/206#-NzwQGnY8ZQ3CH5s_VwG:-NzwmMbyErXGRD2bHR69:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/777eacd8a778783565bac217cbcefbb693a3489c/crates/committer/src/patricia_merkle_tree/test_utils.rs#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move all of these imports to the top of the module
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 155 at r1](https://reviewable.io/reviews/starkware-libs/committer/206#-NzwRZag75Lvmydeo7fo:-NzwjzxAE-94rwB0YGbQ:b7ff69y) ([raw file](https://github.com/starkware-libs/committer/blob/777eacd8a778783565bac217cbcefbb693a3489c/crates/committer/src/patricia_merkle_tree/test_utils.rs#L155)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

aren't the input indices already in full-index format...?
</blockquote></details>

No, the indices from python are in leaf index format.
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/committer/206#-NzwS2lF690kI73rqozZ:-Nzwkz4P7HE775C9BEAz:bb77ufg) ([raw file](https://github.com/starkware-libs/committer/blob/777eacd8a778783565bac217cbcefbb693a3489c/crates/committer/src/patricia_merkle_tree/test_utils.rs#L185)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this in the next PR?
</blockquote></details>

Yes.

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/206)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 170 at r1](https://reviewable.io/reviews/starkware-libs/committer/206#-NzwRpUI1Ok8WhbPl6Zj:-NzxC80MBD4rbbVG8RC3:bq3bpow) ([raw file](https://github.com/starkware-libs/committer/blob/777eacd8a778783565bac217cbcefbb693a3489c/crates/committer/src/patricia_merkle_tree/test_utils.rs#L170)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you add `impl<L: LeafData> Form<LeafModifications<L>> for LeafModifications<SkeletonLeaf>`, this change below will work
</blockquote></details>

Compiler issue problems here; if solved in the other PR, I'll change it here afterwards.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/206)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/committer/206#-NzxTjQWBrbrVZThp_A5:-NzxTjQXDfBlFvkrJkSW:b-rb3vid) ([raw file](https://github.com/starkware-libs/committer/blob/777eacd8a778783565bac217cbcefbb693a3489c/crates/committer/src/patricia_merkle_tree/test_utils.rs#L166)):*
> ```XML
>     // Update the tree with the new data.
>     let updated_skeleton: UpdatedSkeletonTreeImpl =
>         UpdatedSkeletonTree::create_from_modifications_data(
> ```

is this function still used? it isn't in the [PR that implemented it](https://reviewable.io/reviews/starkware-libs/committer/204)



_Code quote:_
```XML
create_from_modifications_data
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/committer/206#-NzxTGkz6vvTA1QvoQ3D:-NzxTGkz6vvTA1QvoQ3E:b-ostruw) ([raw file](https://github.com/starkware-libs/committer/blob/3a406dda55333da1db8a4b00f56c3f4508b99b90/crates/committer/src/patricia_merkle_tree/test_utils.rs#L29)):*
> ```XML
> #[cfg(test)]
> use crate::patricia_merkle_tree::types::SubTreeHeight;
> use crate::patricia_merkle_tree::updated_skeleton_tree::hash_function::TreeHashFunctionImpl;
> ```

please rebase over [this](https://reviewable.io/reviews/starkware-libs/committer/211) and remove the `cfg(test)`



_Code quote:_
```XML
#[cfg(test)]
use crate::patricia_merkle_tree::types::SubTreeHeight;
use crate::patricia_merkle_tree::updated_skeleton_tree::hash_function::TreeHashFunctionImpl;
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/206)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/external_test_utils.rs` line 67 at r4](https://reviewable.io/reviews/starkware-libs/committer/206#-O-0Jztd1GfO3oM7tSBm:-O-0Jztd1GfO3oM7tSBn:b-3nt55r) ([raw file](https://github.com/starkware-libs/committer/blob/939f6f41f09a83e9fa50d6ec0f5f7b38f23ba3b7/crates/committer/src/patricia_merkle_tree/external_test_utils.rs#L67)):*
> ```XML
> }
> 
> pub async fn rust_single_tree_flow_test(
> ```

i know this isn't your code but it's not in the CLI crate so remove the `rust` prefix



_Suggestion:_
```XML
single_tree_flow_test
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/206)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 166 at r1](https://reviewable.io/reviews/starkware-libs/committer/206#-NzxTjQWBrbrVZThp_A5:-O-08Fbu0GqdonDjoozw:b-xu2edu) ([raw file](https://github.com/starkware-libs/committer/blob/777eacd8a778783565bac217cbcefbb693a3489c/crates/committer/src/patricia_merkle_tree/test_utils.rs#L166)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this function still used? it isn't in the [PR that implemented it](https://reviewable.io/reviews/starkware-libs/committer/204)
</blockquote></details>

Done. I'm using the regular `create` now, with the necessary transform inline.
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 29 at r3](https://reviewable.io/reviews/starkware-libs/committer/206#-NzxTGkz6vvTA1QvoQ3D:-O-0nwpEBZC1L_IY_rFc:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3a406dda55333da1db8a4b00f56c3f4508b99b90/crates/committer/src/patricia_merkle_tree/test_utils.rs#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please rebase over [this](https://reviewable.io/reviews/starkware-libs/committer/211) and remove the `cfg(test)`
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/206#-:-O-1-4Ls6tKbPtfS8Q62:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
