### PR TITLE
refactor: change the hierarchy between test and testing

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
Separate between test and testing. Now, the test depends on testing, meaning that cfg(test) also compiles the testing file, 
but testing does not include a test file.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/211)

### CODE REVIEW

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/211)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/Cargo.toml` line 27 at r1](https://reviewable.io/reviews/starkware-libs/committer/211#-Nzx8Adt2u0hg3Jt0a5l:-Nzx8Adu8LGxp6Kismjo:bvpx1t4) ([raw file](https://github.com/starkware-libs/committer/blob/5f0105f8441679d4d4424c5ba92e4c15bdbee429/crates/committer/Cargo.toml#L27)):*
> ```TOML
> hex.workspace = true
> rand.workspace = true
> rstest.workspace = true
> ```

its removed since its only dev-dependencies but we couldn't remove it until today since testing and test was mixed

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/211)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/committer/211#-NzxSdEN6APHsxuBdZLe:-NzxSdEN6APHsxuBdZLf:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/e4411d06e8be3882f44607d9a00e84448519b9c3/crates/committer/src/patricia_merkle_tree.rs#L12)):*
> ```XML
> 
> #[cfg(feature = "testing")]
> pub mod testing_utils;
> ```





_Suggestion:_
```XML
#[cfg(test)]
pub mod internal_test_utils;

#[cfg(feature = "testing")]
pub mod external_test_utils;
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/211#-:-NzxUizK9WXoYRqAk43u:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/211)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
