### PR TITLE
fix: tree hash function for compiled class hash tree

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/230)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/230)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/committer/230#-O-alMV_4H3mI7lXT4qc:-O-alMV_4H3mI7lXT4qd:b-5b75f5) ([raw file](https://github.com/starkware-libs/committer/blob/7636741770d6be1b14fbfb66bebc6e5d1b77f253/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L72)):*
> ```XML
>             ),
>             NodeData::Leaf(leaf_data) => Self::compute_leaf_hash(leaf_data),
>         }
> ```

duplicated code.
add a `fn compute_node_hash_with_inner_hash_function<H: HashFunction>` function in the `impl TreeHashFunctionImpl` block, and use it, three times.

I think the compiler should be fine with using `Self::compute_leaf_hash` from the `impl TreeHashFunctionImpl` block because you implement the trait below; if not, extract the common logic to a standalone function



_Code quote:_
```XML
    fn compute_node_hash(node_data: &NodeData<ContractState>) -> HashOutput {
        match node_data {
            NodeData::Binary(BinaryData {
                left_hash,
                right_hash,
            }) => HashOutput(Pedersen::hash(&left_hash.0.into(), &right_hash.0.into()).into()),
            NodeData::Edge(EdgeData {
                bottom_hash: hash_output,
                path_to_bottom: PathToBottom { path, length, .. },
            }) => HashOutput(
                Felt::from(Pedersen::hash(
                    &hash_output.0.into(),
                    &Felt::from(path).into(),
                )) + Felt::from(*length),
            ),
            NodeData::Leaf(leaf_data) => Self::compute_leaf_hash(leaf_data),
        }
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/230)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 72 at r1](https://reviewable.io/reviews/starkware-libs/committer/230#-O-alMV_4H3mI7lXT4qc:-O-atY4T-vnZcdWYnLAz:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7636741770d6be1b14fbfb66bebc6e5d1b77f253/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L72)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

duplicated code.
add a `fn compute_node_hash_with_inner_hash_function<H: HashFunction>` function in the `impl TreeHashFunctionImpl` block, and use it, three times.

I think the compiler should be fine with using `Self::compute_leaf_hash` from the `impl TreeHashFunctionImpl` block because you implement the trait below; if not, extract the common logic to a standalone function
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/230)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/committer/230#-O-auhSWBg4bT4kNRK5-:-O-av8nl15bbkBNoUz_Z:ban60dr) ([raw file](https://github.com/starkware-libs/committer/blob/141120f54f64c203bbf8e8eaee182e3aba660ce1/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L47)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

both `Pedersen` and `Poseidon` implement this trait
</blockquote></details>

you can use the `hash(Felt, Felt) -> Felt` API of `StarkHash` to hash your input

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/230)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/committer/230#-O-avPDz3-xqw-sAlyfP:-O-avPDz3-xqw-sAlyfQ:bxm9tg6) ([raw file](https://github.com/starkware-libs/committer/blob/141120f54f64c203bbf8e8eaee182e3aba660ce1/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L47)):*
> ```XML
>     fn compute_node_hash(node_data: &NodeData<L>) -> HashOutput;
> 
>     fn compute_node_hash_with_inner_hash_function<H: HashFunction>(
> ```

docstring is now relevant for the `compute_node_hash_with_inner_hash_function` function



_Suggestion:_
```XML
    fn compute_node_hash(node_data: &NodeData<L>) -> HashOutput;

    /// The default implementation for internal nodes is based on the following reference:
    /// https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/starknet-state/#trie_construction
    fn compute_node_hash_with_inner_hash_function<H: HashFunction>(
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/230)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/committer/230#-O-auVtj14ik_roThDRi:-O-bA6Mc6u8K3CR2PmMG:b-pnhr4h) ([raw file](https://github.com/starkware-libs/committer/blob/141120f54f64c203bbf8e8eaee182e3aba660ce1/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete (see below, there's a similar trait in starknet_types_core)
</blockquote></details>

See below.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/committer/230#-O-avPDz3-xqw-sAlyfP:-O-b9AupCchs9_cBqcD_:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/141120f54f64c203bbf8e8eaee182e3aba660ce1/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L47)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

docstring is now relevant for the `compute_node_hash_with_inner_hash_function` function
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/committer/230#-O-auhSWBg4bT4kNRK5-:-O-b9Y8DCRnY4nfzsbMq:b-24ko7n) ([raw file](https://github.com/starkware-libs/committer/blob/141120f54f64c203bbf8e8eaee182e3aba660ce1/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L47)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you can use the `hash(Felt, Felt) -> Felt` API of `StarkHash` to hash your input
</blockquote></details>

But this uses different structs than ours, which undermines the idea of wrapping their Felt with our Felt/HashOutput.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/230)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 47 at r2](https://reviewable.io/reviews/starkware-libs/committer/230#-O-auhSWBg4bT4kNRK5-:-O-boxxk3X4jx1MIb_7b:bdaek36) ([raw file](https://github.com/starkware-libs/committer/blob/141120f54f64c203bbf8e8eaee182e3aba660ce1/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L47)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

But this uses different structs than ours, which undermines the idea of wrapping their Felt with our Felt/HashOutput.
</blockquote></details>

good point
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/committer/230#-O-bop2G51nbykmiXMAf:-O-bop2G51nbykmiXMAg:bgw50w8) ([raw file](https://github.com/starkware-libs/committer/blob/d8990492c99cb0748b5a9d5ad4d32a429e5628e9/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L44)):*
> ```XML
>     fn compute_node_hash(node_data: &NodeData<L>) -> HashOutput;
> 
>     /// Computes the hash for the given node data.
> ```

I only meant the two lines explaining the default implementation



_Suggestion:_
```XML
    /// Computes the hash for the given node data.
    fn compute_node_hash(node_data: &NodeData<L>) -> HashOutput;
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/230)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 44 at r3](https://reviewable.io/reviews/starkware-libs/committer/230#-O-bop2G51nbykmiXMAf:-O-d_C-o00Pq3MFZZNiP:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d8990492c99cb0748b5a9d5ad4d32a429e5628e9/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L44)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I only meant the two lines explaining the default implementation
</blockquote></details>

Done.

**Pull request merged**
