### PR TITLE
test(skeleton): get_random_u256

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 5 at r2](https://reviewable.io/reviews/starkware-libs/committer/111#-NxgrK9d9smIeeGLvTr-:-NxgrK9d9smIeeGLvTr0:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/21d95309fc89bfb1798fd8e72d526b89aef5429a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L5)):*
> ```XML
> use rstest::rstest;
> 
> ///Generates a random U256 number between low and high (inclusive).
> ```





_Suggestion:_
```XML
/// Generates 
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/committer/111#-Nxgrzrv5a5cXIQRzBG8:-Nxgrzrv5a5cXIQRzBG9:b-hrlxnf) ([raw file](https://github.com/starkware-libs/committer/blob/21d95309fc89bfb1798fd8e72d526b89aef5429a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L13)):*
> ```XML
>     } else {
>         high_of_low
>     };
> ```

if `low == 1` and `high == 2^128`, then `low_of_high == 0` and `low_of_low > low_of_high` is true.
then, `new_high_of_low` will be 1.
this means that `new_high` will be selected from `[1, 1]`, so it will always be exactly `1`, right?
we will reach the `else` case below, i.e.
```
U256::from_words(1, rand::thread_rng().gen_range(1..=0))
```
... which should not compile / panic.

Am I missing something?

why not:
1. assert that `high_of_low <= high_of_high` (should always be true if low <= high).
2. randomize a `new_high` value in `[high_of_low, high_of_high]`
3. if `high_of_low == new_high`, randomize `new_low` in `[low_of_low, 2^128)`
4. elif `high_of_high == new_high`...
5. else randomize in `[0, 2^128)`

?



_Code quote:_
```XML
    let new_high_of_low = if low_of_low > low_of_high {
        high_of_low + 1
    } else {
        high_of_low
    };
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/committer/111#-NxgtVWp58VksWbtf3x3:-NxgtVWp58VksWbtf3x4:bdhlj1m) ([raw file](https://github.com/starkware-libs/committer/blob/21d95309fc89bfb1798fd8e72d526b89aef5429a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L34)):*
> ```XML
> #[case(U256::ZERO, U256::ONE)]
> #[case((U256::ONE<<128)-U256::ONE, U256::ONE << 128)]
> #[case(U256::ONE<<128, (U256::ONE << 128)+U256::ONE)]
> ```

add this case please (I think the test should fail ATM...)



_Suggestion:_
```XML
#[case(U256::ZERO, U256::ZERO)]
#[case(U256::ZERO, U256::ONE)]
#[case((U256::ONE<<128)-U256::ONE, U256::ONE << 128)]
#[case(U256::ONE<<128, (U256::ONE << 128)+U256::ONE)]
#[case(U256::ONE, U256::ONE << 128)]
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/committer/111#-Nxgrzrv5a5cXIQRzBG8:-Nxh2VEpC7CHSlDMTUYe:b-eydjmu) ([raw file](https://github.com/starkware-libs/committer/blob/21d95309fc89bfb1798fd8e72d526b89aef5429a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if `low == 1` and `high == 2^128`, then `low_of_high == 0` and `low_of_low > low_of_high` is true.
then, `new_high_of_low` will be 1.
this means that `new_high` will be selected from `[1, 1]`, so it will always be exactly `1`, right?
we will reach the `else` case below, i.e.
```
U256::from_words(1, rand::thread_rng().gen_range(1..=0))
```
... which should not compile / panic.

Am I missing something?

why not:
1. assert that `high_of_low <= high_of_high` (should always be true if low <= high).
2. randomize a `new_high` value in `[high_of_low, high_of_high]`
3. if `high_of_low == new_high`, randomize `new_low` in `[low_of_low, 2^128)`
4. elif `high_of_high == new_high`...
5. else randomize in `[0, 2^128)`

?
</blockquote></details>

We will reach the inner else, i.e., `U256::from_words(1, rand::thread_rng().gen_range(0..=2^128))` (see added test case below that passes).
Do I still need to understand the difference between your proposal to mine? :) 
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 34 at r2](https://reviewable.io/reviews/starkware-libs/committer/111#-NxgtVWp58VksWbtf3x3:-Nxh2BVb7Byk_g-j6oHn:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/21d95309fc89bfb1798fd8e72d526b89aef5429a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add this case please (I think the test should fail ATM...)
</blockquote></details>

Done.

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/committer/111#-Nxgrzrv5a5cXIQRzBG8:-Nxh3ZMzAsIIxrFvghMV:bq4bs9p) ([raw file](https://github.com/starkware-libs/committer/blob/21d95309fc89bfb1798fd8e72d526b89aef5429a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L13)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

We will reach the inner else, i.e., `U256::from_words(1, rand::thread_rng().gen_range(0..=2^128))` (see added test case below that passes).
Do I still need to understand the difference between your proposal to mine? :)
</blockquote></details>

Wait, rethinking.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/committer/111#-NxhGkK_2acVlhOH91tf:-NxhGkKa0qytxE6gNNum:b-jnk928) ([raw file](https://github.com/starkware-libs/committer/blob/b9e1bdcd4e04a468f0c4323efee8abcc18da45a7/crates/committer/src/patricia_merkle_tree/test_utils.rs#L37)):*
> ```XML
> #[case(U256::ONE<<128, (U256::ONE << 128)+U256::ONE)]
> 
> fn test_get_random_u256(#[case] low: U256, #[case] high: U256) {
> ```

If you think the test utils need tests - why not add a separate file (`test_utils_test`? it's even funny)?
non blocking



_Code quote:_
```XML
fn test_get_random_u256(#[case] low: U256, #[case] high: U256) {
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/committer/111#-Nxgrzrv5a5cXIQRzBG8:-Nxh6HPw-Hr2v-PGsfcU:biqzfmv) ([raw file](https://github.com/starkware-libs/committer/blob/21d95309fc89bfb1798fd8e72d526b89aef5429a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L13)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Wait, rethinking.
</blockquote></details>

Yep, made simplified confusing examples. I don't like step 2 in your proposal because in your example - we'll get a 50% chance to get 2^128 as the returned value even though the range is huge. Made it a bit more complicated with if else's to get ~ uniform randomness...
Regreting I've started this thing.
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 37 at r3](https://reviewable.io/reviews/starkware-libs/committer/111#-NxhGkK_2acVlhOH91tf:-NxhJOCz8Zswsf4WMYem:b-bl8ltb) ([raw file](https://github.com/starkware-libs/committer/blob/b9e1bdcd4e04a468f0c4323efee8abcc18da45a7/crates/committer/src/patricia_merkle_tree/test_utils.rs#L37)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

If you think the test utils need tests - why not add a separate file (`test_utils_test`? it's even funny)?
non blocking
</blockquote></details>

Because in general this looks like an endless procedure, I specifically want to test this function because it's damn confusing, but I hope there won't be any other tests.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/committer/111#-Nxgrzrv5a5cXIQRzBG8:-Nxhg9XyDWmGQMcpEg8Y:brckukn) ([raw file](https://github.com/starkware-libs/committer/blob/21d95309fc89bfb1798fd8e72d526b89aef5429a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L13)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Yep, made simplified confusing examples. I don't like step 2 in your proposal because in your example - we'll get a 50% chance to get 2^128 as the returned value even though the range is huge. Made it a bit more complicated with if else's to get ~ uniform randomness...
Regreting I've started this thing.
</blockquote></details>

consider switching to `BigUint`?
there is a [randomization trait](https://doc.rust-lang.org/num/num/bigint/trait.RandBigInt.html), and I believe this crate has a `U256` type...
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/committer/111#-NxheifKE66BFEl_SHQu:-NxheifKE66BFEl_SHQv:bf5j4gf) ([raw file](https://github.com/starkware-libs/committer/blob/e0a83facaa20638b7ce786186fcc26bfdbc5bdb5/crates/committer/src/patricia_merkle_tree/test_utils.rs#L9)):*
> ```XML
>     let (mut high_of_low, low_of_low) = low.into_words();
>     let (mut high_of_high, low_of_high) = high.into_words();
>     assert!(high_of_low <= high_of_high);
> ```

if you need this, add this restriction to the docstring



_Code quote:_
```XML
assert!(high_of_low <= high_of_high);
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/committer/111#-NxhfEcB74668LmqGssV:-NxhfEcB74668LmqGssW:bs381lc) ([raw file](https://github.com/starkware-libs/committer/blob/e0a83facaa20638b7ce786186fcc26bfdbc5bdb5/crates/committer/src/patricia_merkle_tree/test_utils.rs#L21)):*
> ```XML
>         let diff = high - low;
>         let upper_bound = if diff > u128::MAX {
>             assert!(low_of_high >= low_of_low);
> ```

this is implicit...



_Code quote:_
```XML
assert!(low_of_high >= low_of_low);
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 25 at r4](https://reviewable.io/reviews/starkware-libs/committer/111#-NxhfZ3q0Vik8YOSQ5kh:-NxhfZ3q0Vik8YOSQ5ki:becq2dm) ([raw file](https://github.com/starkware-libs/committer/blob/e0a83facaa20638b7ce786186fcc26bfdbc5bdb5/crates/committer/src/patricia_merkle_tree/test_utils.rs#L25)):*
> ```XML
>         } else {
>             u128::try_from(diff).unwrap()
>         };
> ```

as `high_of_high == high_of_low + 1`, if `high - low > u128::MAX` then the inequality `low_of_high >= low_of_low` is implied; no need to assert it.
and then, what you're actually doing here is a `min` operation, right?

... and then, what if `low=0` and `high=2^129-1`? we will get `high_of_high==1`, and `low_of_high==u128::MAX`; there are `2*u128::MAX-1` possible numbers in the range but it seems you give an upper bound of `u128::MAX` in this case, so numbers in `[2^128, 2^129)` will never be sampled...



_Suggestion:_
```XML
        let diff = high - low;
        let upper_bound = u128::try_from(
            min(U256::from(u128::MAX), high - low)
        ).unwrap();
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/committer/111#-Nxgrzrv5a5cXIQRzBG8:-Nxhz8hc-wLIEnAzQ3_2:bozb6k9) ([raw file](https://github.com/starkware-libs/committer/blob/21d95309fc89bfb1798fd8e72d526b89aef5429a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider switching to `BigUint`?
there is a [randomization trait](https://doc.rust-lang.org/num/num/bigint/trait.RandBigInt.html), and I believe this crate has a `U256` type...
</blockquote></details>

If the last change seems right (I think it is), let's consider this in a future PR?
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 9 at r4](https://reviewable.io/reviews/starkware-libs/committer/111#-NxheifKE66BFEl_SHQu:-NxhzLhZDSGyXdbVtnTW:b2nhktp) ([raw file](https://github.com/starkware-libs/committer/blob/e0a83facaa20638b7ce786186fcc26bfdbc5bdb5/crates/committer/src/patricia_merkle_tree/test_utils.rs#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you need this, add this restriction to the docstring
</blockquote></details>

OK.
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/committer/111#-NxhfEcB74668LmqGssV:-Nxhw_Ee5znmpl35aJtM:b-5x2i9t) ([raw file](https://github.com/starkware-libs/committer/blob/e0a83facaa20638b7ce786186fcc26bfdbc5bdb5/crates/committer/src/patricia_merkle_tree/test_utils.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is implicit...
</blockquote></details>

Yes, made that as a sanity check. Removed.
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 25 at r4](https://reviewable.io/reviews/starkware-libs/committer/111#-NxhfZ3q0Vik8YOSQ5kh:-Nxhz4I9AntpmyKmdVb_:b-w6c5yh) ([raw file](https://github.com/starkware-libs/committer/blob/e0a83facaa20638b7ce786186fcc26bfdbc5bdb5/crates/committer/src/patricia_merkle_tree/test_utils.rs#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

as `high_of_high == high_of_low + 1`, if `high - low > u128::MAX` then the inequality `low_of_high >= low_of_low` is implied; no need to assert it.
and then, what you're actually doing here is a `min` operation, right?

... and then, what if `low=0` and `high=2^129-1`? we will get `high_of_high==1`, and `low_of_high==u128::MAX`; there are `2*u128::MAX-1` possible numbers in the range but it seems you give an upper bound of `u128::MAX` in this case, so numbers in `[2^128, 2^129)` will never be sampled...
</blockquote></details>

Good job, now it's more succinct.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 13 at r2](https://reviewable.io/reviews/starkware-libs/committer/111#-Nxgrzrv5a5cXIQRzBG8:-NxiO1PV5zhLD6Rxbzkn:b-nz3eqi) ([raw file](https://github.com/starkware-libs/committer/blob/21d95309fc89bfb1798fd8e72d526b89aef5429a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L13)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

If the last change seems right (I think it is), let's consider this in a future PR?
</blockquote></details>

not uniform I think (see below, I may have a solution...)
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 33 at r5](https://reviewable.io/reviews/starkware-libs/committer/111#-NxiNi3aCBuRlFVsAf-w:-NxiNi3aCBuRlFVsAf-x:b-qextlq) ([raw file](https://github.com/starkware-libs/committer/blob/949ad6c8722d886ab5dcd71a5af852cdf37522de/crates/committer/src/patricia_merkle_tree/test_utils.rs#L33)):*
> ```XML
>         rand::thread_rng().gen_range(high_of_low..=high_of_high),
>         new_low,
>     )
> ```

if `low==u128::MAX` and `high==u128::MAX+1` this will always output `u128::MAX+1`, right? this is incorrect (unless the "lower bound is exclusive, upper bound is inclusive" behavior is consistent... haven't checked).
How about this?



_Suggestion:_
```XML
    let upper_bound = u128::try_from(min(U256::from(u128::MAX), high - low)).unwrap();
    if upper_bound < u128::MAX {
        let delta = rand::thread_rng().gen_range(0..upper_bound);
        return low + delta;
    }
    
    // Randomize with low_low=0 and high_high=u128::MAX until the value
    // is in range.
    // Setting low_low to 0 and high_high to u128::MAX can only increase the
    // sample domain by u128::MAX. As high-low>=u128::MAX, the expected 
    // number of samples until the loops breaks is bound from above by 2.
    let randomize = || {
        U256::from_words(
            rand::thread_rng().gen_range(high_of_low..=high_of_high),
            rand::thread_rng().gen_range(0..=u128::MAX)
        )
    }
    let mut result = randomize();
    while result < low || result > high {
        result = randomize();
    }
    result
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 33 at r5](https://reviewable.io/reviews/starkware-libs/committer/111#-NxiNi3aCBuRlFVsAf-w:-NxmSGWf4niKp2Bytn4v:b-pi1oi6) ([raw file](https://github.com/starkware-libs/committer/blob/949ad6c8722d886ab5dcd71a5af852cdf37522de/crates/committer/src/patricia_merkle_tree/test_utils.rs#L33)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if `low==u128::MAX` and `high==u128::MAX+1` this will always output `u128::MAX+1`, right? this is incorrect (unless the "lower bound is exclusive, upper bound is inclusive" behavior is consistent... haven't checked).
How about this?
</blockquote></details>

Good enough for me. It's not exactly 2, as for example, if `low=u128::MAX` and `high=1<<129` the expected number of samples is 3 as if `new_high=0b10` (as of high) or `new_high=0` (as of low) there is 1/2**128 chance to succeed with the sampling, and you need to have `new_high=1`. But good enough for us.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 33 at r5](https://reviewable.io/reviews/starkware-libs/committer/111#-NxiNi3aCBuRlFVsAf-w:-NxqsPHx2LwpcXc1IIMM:b-ermffg) ([raw file](https://github.com/starkware-libs/committer/blob/949ad6c8722d886ab5dcd71a5af852cdf37522de/crates/committer/src/patricia_merkle_tree/test_utils.rs#L33)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Good enough for me. It's not exactly 2, as for example, if `low=u128::MAX` and `high=1<<129` the expected number of samples is 3 as if `new_high=0b10` (as of high) or `new_high=0` (as of low) there is 1/2**128 chance to succeed with the sampling, and you need to have `new_high=1`. But good enough for us.
</blockquote></details>

ah, you're right.
but I still think it's better because the current implementation is not the uniform distribution (right? or is my analysis wrong?),
and better to have a uniform distribution with O(1) runtime in expectation, than a distribution that is non-uniform in an non-intuitive way.
Do you agree?
if so please swap implementation

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 33 at r5](https://reviewable.io/reviews/starkware-libs/committer/111#-NxiNi3aCBuRlFVsAf-w:-NyF5afSBXKAFOugDtCZ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/949ad6c8722d886ab5dcd71a5af852cdf37522de/crates/committer/src/patricia_merkle_tree/test_utils.rs#L33)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah, you're right.
but I still think it's better because the current implementation is not the uniform distribution (right? or is my analysis wrong?),
and better to have a uniform distribution with O(1) runtime in expectation, than a distribution that is non-uniform in an non-intuitive way.
Do you agree?
if so please swap implementation
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 10 at r6](https://reviewable.io/reviews/starkware-libs/committer/111#-NyF5wuZCpanOtdh61RW:-NyF5wu_8WF6EO0gJOI5:b-8udbbo) ([raw file](https://github.com/starkware-libs/committer/blob/d2f0500bef31c06b4f902946eb6884c3307db87e/crates/committer/src/patricia_merkle_tree/test_utils.rs#L10)):*
> ```XML
>     let high_of_low = low.high();
>     let high_of_high = high.high();
>     assert!(high_of_low <= high_of_high);
> ```

more to the point, and can catch more cases



_Suggestion:_
```XML
    assert!(low <= high);
    let high_of_low = low.high();
    let high_of_high = high.high();
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 24 at r6](https://reviewable.io/reviews/starkware-libs/committer/111#-NyF6HRb6bOn4c3u5j9r:-NyF6HRb6bOn4c3u5j9s:bau9ja3) ([raw file](https://github.com/starkware-libs/committer/blob/d2f0500bef31c06b4f902946eb6884c3307db87e/crates/committer/src/patricia_merkle_tree/test_utils.rs#L24)):*
> ```XML
>     // valid result for high bits in (high_of_low, high_of_high) or high_of_high == high_of_low + 1)
>     // and every possible low 128 bits value is valid when either the high bits equal high_of_high,
>     // or high_of_low).
> ```

didn't exactly understand the explanation, maybe this is clearer? WDYT?
non blocking



_Suggestion:_
```XML
    // As high-low>u128::MAX, the expected number of samples until the loops breaks is bound from
    // above by 3 (worst case if when high=k*2^128 and low=((k-1)*2^128)-1, and there is a 1/3 
    // chance to sample a new high value with over 1/2^128 chance for a valid low value).
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 40 at r6](https://reviewable.io/reviews/starkware-libs/committer/111#-NyF717O142rEM6Tf2JS:-NyF717O142rEM6Tf2JT:bk1i6ft) ([raw file](https://github.com/starkware-libs/committer/blob/d2f0500bef31c06b4f902946eb6884c3307db87e/crates/committer/src/patricia_merkle_tree/test_utils.rs#L40)):*
> ```XML
> #[rstest]
> #[should_panic]
> #[case(U256::ZERO, U256::ZERO)]
> ```

the `should_panic` attribute applies only to this single case?



_Code quote:_
```XML
#[should_panic]
#[case(U256::ZERO, U256::ZERO)]
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 24 at r6](https://reviewable.io/reviews/starkware-libs/committer/111#-NyF6HRb6bOn4c3u5j9r:-NyF7hAd-NGJ_xZ3l3Ve:b-8wp19g) ([raw file](https://github.com/starkware-libs/committer/blob/d2f0500bef31c06b4f902946eb6884c3307db87e/crates/committer/src/patricia_merkle_tree/test_utils.rs#L24)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

didn't exactly understand the explanation, maybe this is clearer? WDYT?
non blocking
</blockquote></details>

I'm not sure it's clear why this is the worst case, I tried to explain the two possibilities (also where high and low  "high's" differ in a single bit and not two as in your example).
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 40 at r6](https://reviewable.io/reviews/starkware-libs/committer/111#-NyF717O142rEM6Tf2JS:-NyF7Ub5DpCmeScLjZP6:b-6h7pex) ([raw file](https://github.com/starkware-libs/committer/blob/d2f0500bef31c06b4f902946eb6884c3307db87e/crates/committer/src/patricia_merkle_tree/test_utils.rs#L40)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the `should_panic` attribute applies only to this single case?
</blockquote></details>

Yes, otherwise it would have failed.

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 10 at r6](https://reviewable.io/reviews/starkware-libs/committer/111#-NyF5wuZCpanOtdh61RW:-NyF8dfz6y9YJUhn4M7c:b32vhw) ([raw file](https://github.com/starkware-libs/committer/blob/d2f0500bef31c06b4f902946eb6884c3307db87e/crates/committer/src/patricia_merkle_tree/test_utils.rs#L10)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

more to the point, and can catch more cases
</blockquote></details>

:)

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 24 at r6](https://reviewable.io/reviews/starkware-libs/committer/111#-NyF6HRb6bOn4c3u5j9r:-NyF9I2yCmpDWDjwY7ED:b-yw8ca2) ([raw file](https://github.com/starkware-libs/committer/blob/d2f0500bef31c06b4f902946eb6884c3307db87e/crates/committer/src/patricia_merkle_tree/test_utils.rs#L24)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I'm not sure it's clear why this is the worst case, I tried to explain the two possibilities (also where high and low  "high's" differ in a single bit and not two as in your example).
</blockquote></details>

Any better?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 8 at r8](https://reviewable.io/reviews/starkware-libs/committer/111#-NyF9gP7CKrAfMcQPCmx:-NyF9gP7CKrAfMcQPCmy:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/bdc8a2145a853d860834b884525fabeaf55730f9/crates/committer/src/patricia_merkle_tree/test_utils.rs#L8)):*
> ```XML
> /// Panics if low > high.
> pub(crate) fn get_random_u256(low: U256, high: U256) -> U256 {
>     assert!(low <= high);
> ```





_Suggestion:_
```XML
assert!(low < high);
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 8 at r8](https://reviewable.io/reviews/starkware-libs/committer/111#-NyF9gP7CKrAfMcQPCmx:-NyF9qfE2ZnWT0q86K0l:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/bdc8a2145a853d860834b884525fabeaf55730f9/crates/committer/src/patricia_merkle_tree/test_utils.rs#L8)):*
> ```XML
> /// Panics if low > high.
> pub(crate) fn get_random_u256(low: U256, high: U256) -> U256 {
>     assert!(low <= high);
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/111#-:-NyF9wa-2KcbL51mhIdc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
