### PR TITLE
chore: adding thiserror crate and storage error

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/41)

### CODE REVIEW

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/41)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware)

___
*[`Cargo.lock` line 734 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-Nva-kJn08QEA08Mg4WP:-Nva-kJoCGYVgg1jESc8:bdzoyf) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/Cargo.lock#L734)):*
> ```TOML
> version = "0.52.5"
> source = "registry+https://github.com/rust-lang/crates.io-index"
> checksum = "bec47e5bfd1bff0eeaf6d8b485cc1074891a197ab4225d504cb7a1ab88b02bf0"
> ```

all changes in `Cargo.lock` are automatic, right? you didn't change anything manually



_Code quote:_
```TOML
checksum = "bec47e5bfd1bff0eeaf6d8b485cc1074891a197ab4225d504cb7a1ab88b02bf0"
```
___
*[`Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-NvXCM6n00aExp3ZoFza:-NvXCM6n00aExp3ZoFzb:b8co6i6) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/Cargo.toml#L21)):*
> ```TOML
> rstest = "0.17.0"
> starknet-types-core = { version = "0.0.11", features = ["hash"] }
> thiserror = "1.0.24"
> ```

we would like newest version: `thiserror = "1.0.58"`
right @dorimedini-starkware ?



_Code quote:_
```TOML
thiserror = "1.0.24"
```
___
*[`crates/committer/src/storage/errors.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-Nva07R8-cNmMKObmnRD:-Nva07R96WgkPb3qPuKu:b-kiff6i) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/crates/committer/src/storage/errors.rs#L1)):*
> ```XML
> use std::fmt::Debug;
> ```

Are you sure this import is needed?



_Code quote:_
```XML
use std::fmt::Debug;
```
___
*[`crates/committer/src/storage/errors.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-Nva0Spa5i-P8LR6u61Z:-Nva0Spa5i-P8LR6u61_:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/crates/committer/src/storage/errors.rs#L11)):*
> ```XML
>     #[error("The key {:?} does not exist in storage.", 0)]
>     KeyNotExist(StorageKey),
> }
> ```





_Suggestion:_
```XML
#[allow(dead_code)]
#[derive(Debug, Error)]
pub(crate) enum StorageError {
    #[error("Key {storage_key:?} does not exist.")]
    MissingKey { storage_key: StorageKey },
}
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/41)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-NvXCM6n00aExp3ZoFza:-Nva2l4b7w7HPRiCyOSr:b2nign6) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/Cargo.toml#L21)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

we would like newest version: `thiserror = "1.0.58"`
right @dorimedini-starkware ?
</blockquote></details>

yes
___
*[`crates/committer/src/storage/errors.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-Nva321K8-4AryImA-qv:-Nva321K8-4AryImA-qw:b-vmia1j) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/crates/committer/src/storage/errors.rs#L6)):*
> ```XML
> use thiserror::Error;
> 
> #[derive(Debug, Error)]
> ```

if you drop the `:?` below you won't need the `Debug` IIUC



_Suggestion:_
```XML
#[derive(Error)]
```
___
*[`crates/committer/src/storage/errors.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-Nva2twI9URB3CeRUNIE:-Nva2twI9URB3CeRUNIF:bl3eytl) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/crates/committer/src/storage/errors.rs#L9)):*
> ```XML
> #[allow(dead_code)]
> pub(crate) enum StorageError {
>     #[error("The key {:?} does not exist in storage.", 0)]
> ```

1. move the `0` to the string
2. drop the `:?`, I don't think it's needed



_Suggestion:_
```XML
#[error("The key {0} does not exist in storage.")]
```
___
*[`crates/committer/src/storage/errors.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-Nva0Spa5i-P8LR6u61Z:-Nva387dC3DU5nwrBzap:b-xufqd) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/crates/committer/src/storage/errors.rs#L11)):*
> ```XML
>     #[error("The key {:?} does not exist in storage.", 0)]
>     KeyNotExist(StorageKey),
> }
> ```

@amosStarkware I disagree about the struct, a tuple struct is fine here.
if another field is added to `MissingKey` then we can convert to struct

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/41)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/storage/errors.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-Nva0Spa5i-P8LR6u61Z:-Nva4NVy-JOIXmgIGJhJ:btviunp) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/crates/committer/src/storage/errors.rs#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@amosStarkware I disagree about the struct, a tuple struct is fine here.
if another field is added to `MissingKey` then we can convert to struct
</blockquote></details>

Ok ,so this please



_Code snippet:_
```XML
#[allow(dead_code)]
#[derive(Debug, Error)]
pub(crate) enum StorageError {
    #[error("Key {:?} does not exist.", 0)]
    KeyNotExist(StorageKey),
}
```

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/41)* status: all files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/storage/errors.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-Nva0Spa5i-P8LR6u61Z:-Nva50cEDgsKe74zSMwy:bk1sfau) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/crates/committer/src/storage/errors.rs#L11)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Ok ,so this please
</blockquote></details>

with `MissingKey` instead of `KeyNotExist`

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/41)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`Cargo.lock` line 734 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-Nva-kJn08QEA08Mg4WP:-NveVsJL6PvAt1XjDlHv:b-wiefmk) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/Cargo.lock#L734)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

all changes in `Cargo.lock` are automatic, right? you didn't change anything manually
</blockquote></details>

yes, its automatically generated
___
*[`Cargo.toml` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-NvXCM6n00aExp3ZoFza:-NveW2JhDFWwcu09ZLe_:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/Cargo.toml#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes
</blockquote></details>

Done.
___
*[`crates/committer/src/storage/errors.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-Nva07R8-cNmMKObmnRD:-NveWEjdA_zRguzVMoV4:b-74le34) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/crates/committer/src/storage/errors.rs#L1)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Are you sure this import is needed?
</blockquote></details>

it wasn't needed. removed it
___
*[`crates/committer/src/storage/errors.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-Nva321K8-4AryImA-qv:-NveYSbJBV9JAllWn7mB:bst53kz) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/crates/committer/src/storage/errors.rs#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you drop the `:?` below you won't need the `Debug` IIUC
</blockquote></details>

this_error requires to derive debug (or Display) as well
`pub trait Error: Debug + Display {` 
(from this_error source code)
___
*[`crates/committer/src/storage/errors.rs` line 9 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-Nva2twI9URB3CeRUNIE:-NveZ7dAEMEGlPuZZw9u:b3zxozp) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/crates/committer/src/storage/errors.rs#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. move the `0` to the string
2. drop the `:?`, I don't think it's needed
</blockquote></details>

1. done
2. cannot compile if i drop it. 
IIUC `{0}` will work if it derives `Display` and `{0:?}` works because it derives `Debug`
___
*[`crates/committer/src/storage/errors.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/41#-Nva0Spa5i-P8LR6u61Z:-NveZ7ATEaTToXnofCe_:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/bca5d7b199278760f9df9ced31473ae25d770f56/crates/committer/src/storage/errors.rs#L11)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

with `MissingKey` instead of `KeyNotExist`
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/41#-:-Nvf2uwO1au6F-t8G6fC:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware)

**Review by amosStarkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/41)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/41)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/41)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
