### PR TITLE
test: add full committer flow benchmarking

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/236)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/236#-:-O-oiP6309xvZq73sz0l:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer_cli/benches/committer_bench.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/236#-O-ohvCZ-OPxS0lD9_Fo:-O-ohvCZ-OPxS0lD9_Fp:b-sbi0zc) ([raw file](https://github.com/starkware-libs/committer/blob/f3c1340dbfc6e05e83f6d8bafe420a0329cb5915/crates/committer_cli/benches/committer_bench.rs#L21)):*
> ```XML
> 
> pub fn single_tree_flow_benchmark(criterion: &mut Criterion) {
>     let input: &str = include_str!("../inputs.json");
> ```

I prefer `include_str!` invocations to be at the top. non-blocking (style)



_Suggestion:_
```XML
const CONCURRENCY_MODE: bool = true;
const SINGLE_TREE_INPUT: &str = include_str!("../inputs.json");
const FLOW_TEST_INPUT: &str = include_str!("../inputs_committer_flow.json");

pub fn single_tree_flow_benchmark(criterion: &mut Criterion) {
```
___
*[`crates/committer_cli/benches/committer_bench.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/committer/236#-O-oiG8yCBt62_CuOWdJ:-O-oiG8yCBt62_CuOWdK:byr4ffv) ([raw file](https://github.com/starkware-libs/committer/blob/f3c1340dbfc6e05e83f6d8bafe420a0329cb5915/crates/committer_cli/benches/committer_bench.rs#L67)):*
> ```XML
>             runtime.block_on(commit(input));
>         })
>     });
> ```

see above



_Suggestion:_
```XML
    let runtime = match CONCURRENCY_MODE {
        true => tokio::runtime::Builder::new_multi_thread().build().unwrap(),
        false => tokio::runtime::Builder::new_current_thread()
            .build()
            .unwrap(),
    };

    criterion.bench_function("full_committer_flow", |benchmark| {
        benchmark.iter(|| {
            runtime.block_on(commit(FLOW_TEST_INPUT));
        })
    });
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/236)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Comment by aner-starkware** [comment]
Sorry, didn't see the :lgtm:, already pushed another commit into this PR :(

**Review by aner-starkware — COMMENTED** [review]
OK, passes the CI

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/236#-:-O-qHDCO7ds7glsra_4q:b-5sfo1r)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/236#-:-O-qd-qv-S5m1etNI7ay:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

___
*[`.github/workflows/ci.yml` line 108 at r3](https://reviewable.io/reviews/starkware-libs/committer/236#-O-qcgAw0eLp0PM-CQzz:-O-qcgAw0eLp0PM-CR--:b-yssmck) ([raw file](https://github.com/starkware-libs/committer/blob/ddd9a8e78779db14976d831681fa52cb4409bd38/.github/workflows/ci.yml#L108)):*
> ```YAML
>       - uses: 'google-github-actions/setup-gcloud@v2'
>       - run: gcloud storage cp gs://committer-products-external/tree_flow_inputs.json ./crates/committer_cli/benches/tree_flow_inputs.json
>       - run: gcloud storage cp gs://committer-products-external/committer_flow_inputs.json ./crates/committer_cli/benches/committer_flow_inputs.json
> ```

is this cached..? non-blocking, but want to know



_Code quote:_
```YAML
      - run: gcloud storage cp gs://committer-products-external/tree_flow_inputs.json ./crates/committer_cli/benches/tree_flow_inputs.json
      - run: gcloud storage cp gs://committer-products-external/committer_flow_inputs.json ./crates/committer_cli/benches/committer_flow_inputs.json
```

**Pull request merged**
