### PR TITLE
build: creating upper tree as part of the original skeleton forest

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/93)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/93)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/93#-Nx7sQ3d1Hk27ogqDQK9:-Nx7sQ3d1Hk27ogqDQKA:b-bdcfun) ([raw file](https://github.com/starkware-libs/committer/blob/4702036b670472a228cd73eb0f2848ae870c909c/crates/committer/src/patricia_merkle_tree/types.rs#L61)):*
> ```XML
>     ) -> Self {
>         Self(U256::from(2_u8) << tree_height.0) + Self::from(address.0)
>     }
> ```

add a unit test please.
note:
in a tree of height 1 (i.e., a root and two leaves), the node index of leaf `0` should be `2`, right?
so you want `1 << height + leaf_index`, not `2 << height + leaf_index`



_Code quote:_
```XML
    pub(crate) fn from_contract_address(
        address: &ContractAddress,
        tree_height: &TreeHeight,
    ) -> Self {
        Self(U256::from(2_u8) << tree_height.0) + Self::from(address.0)
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/committer/93#-Nx7syiOAoZ6EFN_aVTk:-Nx7syiOAoZ6EFN_aVTl:b1l4o9x) ([raw file](https://github.com/starkware-libs/committer/blob/4702036b670472a228cd73eb0f2848ae870c909c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L29)):*
> ```XML
>     contract_states: HashMap<ContractAddress, T>,
>     leaf_data: PhantomData<L>,
> }
> ```

actually, you will have different tree types here.
`T` is a tree with leaf type `L`, so it cannot be both a tree of `StarknetStorageValue`s and of `ContractState`s



_Suggestion:_
```XML
pub(crate) struct OriginalSkeletonForest<
    StateLeaf: LeafData + std::clone::Clone,
    GlobalLeaf: LeafData + std::clone::Clone,
    StateTree: OriginalSkeletonTree<StateLeaf>,
    GlobalTree: OriginalSkeletonTree<GlobalLeaf>,
> {
    // TODO(Nimrod): Add compiled class tree.
    #[allow(dead_code)]
    global_state_tree: GlobalTree,
    #[allow(dead_code)]
    contract_states: HashMap<ContractAddress, StateTree>,
    state_leaf_data: PhantomData<StateLeaf>,
    global_leaf_data: PhantomData<GlobalLeaf>,
}
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/committer/93#-Nx7tk-15b3-Tu8UbR6U:-Nx7tk-15b3-Tu8UbR6V:bb4irbr) ([raw file](https://github.com/starkware-libs/committer/blob/4702036b670472a228cd73eb0f2848ae870c909c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L32)):*
> ```XML
> 
> #[allow(dead_code)]
> pub(crate) fn create_original_skeleton_forest<
> ```

please add a unit test for this - some simple input with a verifiable skeleton forest



_Code quote:_
```XML
fn create_original_skeleton_forest
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/committer/93#-Nx7tWXq-nlKkop_RTpX:-Nx7tWXrAGTOIT6vV8kW:b-vahw63) ([raw file](https://github.com/starkware-libs/committer/blob/4702036b670472a228cd73eb0f2848ae870c909c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L58)):*
> ```XML
>         contract_states,
>         leaf_data: PhantomData,
>     })
> ```

you may end up with more phantom data... please implement a `new` method on the original skeleton forest



_Suggestion:_
```XML
    Ok(OriginalSkeletonForest::new(
        global_state_tree,
        contract_states,
    ))
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/93)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/93#-Nx7sQ3d1Hk27ogqDQK9:-NxBSkCq2PnqiqKBYeaA:b68kd1w) ([raw file](https://github.com/starkware-libs/committer/blob/4702036b670472a228cd73eb0f2848ae870c909c/crates/committer/src/patricia_merkle_tree/types.rs#L61)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add a unit test please.
note:
in a tree of height 1 (i.e., a root and two leaves), the node index of leaf `0` should be `2`, right?
so you want `1 << height + leaf_index`, not `2 << height + leaf_index`
</blockquote></details>

Changed to `1 << height + leaf_index`.
are the unit tests needed? it's exactly the same logic as in `from_starknet_storage_key`.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/committer/93#-Nx7syiOAoZ6EFN_aVTk:-NxBVImU5E5NlVQ5wJ6Z:bab9muj) ([raw file](https://github.com/starkware-libs/committer/blob/4702036b670472a228cd73eb0f2848ae870c909c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

actually, you will have different tree types here.
`T` is a tree with leaf type `L`, so it cannot be both a tree of `StarknetStorageValue`s and of `ContractState`s
</blockquote></details>

At the current implementation, `LeafDataImpl` is the only implementation for `LeafData` trait. It's an enum that can hold all three types of leaves. 
So if the generic type L refers to `LeafDataImpl`, then `T: OriginalSkeletonTree<L>` can work for all trees.

Maybe we should divide the `LeafDataImpl` enum into 3 structs that each will implement `LeafData`? And then I think your suggestion will make more sense
@amosStarkware WDYT?
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/committer/93#-Nx7tk-15b3-Tu8UbR6U:-NxBsziM4GWcT5a7nM6Z:b-d7bhn0) ([raw file](https://github.com/starkware-libs/committer/blob/4702036b670472a228cd73eb0f2848ae870c909c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a unit test for this - some simple input with a verifiable skeleton forest
</blockquote></details>

will do
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/committer/93#-Nx7tWXq-nlKkop_RTpX:-NxBtLWh262GXso5fXxv:b-d7bhn0) ([raw file](https://github.com/starkware-libs/committer/blob/4702036b670472a228cd73eb0f2848ae870c909c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you may end up with more phantom data... please implement a `new` method on the original skeleton forest
</blockquote></details>

will do

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/93)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/93#-Nx7sQ3d1Hk27ogqDQK9:-NxC8PfU9ZaVPvxHK1L2:b-k6obi8) ([raw file](https://github.com/starkware-libs/committer/blob/4702036b670472a228cd73eb0f2848ae870c909c/crates/committer/src/patricia_merkle_tree/types.rs#L61)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Changed to `1 << height + leaf_index`.
are the unit tests needed? it's exactly the same logic as in `from_starknet_storage_key`.
</blockquote></details>

did you push? I still see `2_u8`
and you can parametrize the test of `from_starknet_storage_key` to also try from contract address (use `#[values(true, false)] from_contract_address: bool` and an `if`-`else` in the test)
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/committer/93#-Nx7syiOAoZ6EFN_aVTk:-NxC8HCB8FvDpTLR5KQr:b47oe9q) ([raw file](https://github.com/starkware-libs/committer/blob/4702036b670472a228cd73eb0f2848ae870c909c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L29)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

At the current implementation, `LeafDataImpl` is the only implementation for `LeafData` trait. It's an enum that can hold all three types of leaves. 
So if the generic type L refers to `LeafDataImpl`, then `T: OriginalSkeletonTree<L>` can work for all trees.

Maybe we should divide the `LeafDataImpl` enum into 3 structs that each will implement `LeafData`? And then I think your suggestion will make more sense
@amosStarkware WDYT?
</blockquote></details>

ah, right - leaf data is generic and the implementation is designed to be generic as well.
lgtm, unblocking

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/93)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/93#-Nx7sQ3d1Hk27ogqDQK9:-NxCH93M7h37ofa48MoH:bpo3uyl) ([raw file](https://github.com/starkware-libs/committer/blob/4702036b670472a228cd73eb0f2848ae870c909c/crates/committer/src/patricia_merkle_tree/types.rs#L61)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

did you push? I still see `2_u8`
and you can parametrize the test of `from_starknet_storage_key` to also try from contract address (use `#[values(true, false)] from_contract_address: bool` and an `if`-`else` in the test)
</blockquote></details>

sorry, i didn't push yet. i'm writing some tests.
will add test for both cases as you suggested

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/93)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/committer/93#-Nx7tk-15b3-Tu8UbR6U:-NxC_MX9BQiARWa90pV3:bb7f2mf) ([raw file](https://github.com/starkware-libs/committer/blob/4702036b670472a228cd73eb0f2848ae870c909c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L32)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

will do
</blockquote></details>

done
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/committer/93#-Nx7tWXq-nlKkop_RTpX:-NxC_NkA1ZE3SOmFrZgC:bb7f2mf) ([raw file](https://github.com/starkware-libs/committer/blob/4702036b670472a228cd73eb0f2848ae870c909c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L58)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

will do
</blockquote></details>

done

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/93)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/93#-Nx7sQ3d1Hk27ogqDQK9:-NxCf7-8-t3jvTQQQqY3:bb7f2mf) ([raw file](https://github.com/starkware-libs/committer/blob/4702036b670472a228cd73eb0f2848ae870c909c/crates/committer/src/patricia_merkle_tree/types.rs#L61)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

sorry, i didn't push yet. i'm writing some tests.
will add test for both cases as you suggested
</blockquote></details>

done

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/93)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 107 at r6](https://reviewable.io/reviews/starkware-libs/committer/93#-NxCeKGC7pGCngUcYUyS:-NxCeKGC7pGCngUcYUyT:bnpgcg3) ([raw file](https://github.com/starkware-libs/committer/blob/f772b3d96c750bb926af994736f9722402a8ccfa/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L107)):*
> ```XML
>                 (1, &[8, 10, 13]),
>             ]),
>         },
> ```

add `impl Default for StateDiff`, then you can do this:



_Suggestion:_
```XML
        state_diff: StateDiff {
            current_contract_state_leaves: create_contract_leaves(&[
                (3, 29),
                (5, 29),
                (6, 29),
                (1, 55),
            ]),
            storage_updates: create_storage_updates(&[
                (3, &[8, 11, 13]),
                (5, &[8, 11, 13]),
                (6, &[8, 11, 13]),
                (1, &[8, 10, 13]),
            ]),
            ..Default::default()
        },
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 131 at r6](https://reviewable.io/reviews/starkware-libs/committer/93#-NxCex1A-4qL68oNXhOd:-NxCex1A-4qL68oNXhOe:b-kkcml2) ([raw file](https://github.com/starkware-libs/committer/blob/f772b3d96c750bb926af994736f9722402a8ccfa/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L131)):*
> ```XML
>                 (NodeIndex::from(15), OriginalSkeletonNode::LeafOrBinarySibling(HashOutput(Felt::from(54_u128))))
>             ]),
>             tree_height: TreeHeight(3) },
> ```

define helper methods for this (don't we already have them? please check),
and use them in all trees you construct here



_Suggestion:_
```XML
        global_state_tree: create_original_skeleton_for_testing(
            [
                create_binary_skeleton_node(1),
                create_edge_skeleton_node(2, 0, 2),
                create_edge_skeleton_node(3, 1, 1),
                create_binary_skeleton_node(7),
                create_leaf_or_binary_sibling_skeleton_node(8, 152),
                create_leaf_or_binary_sibling_skeleton_node(15, 54)
            ],
            3
        ),
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 254 at r6](https://reviewable.io/reviews/starkware-libs/committer/93#-NxCft4T9M0GrIdeT0iU:-NxCft4T9M0GrIdeT0iV:b9slb6i) ([raw file](https://github.com/starkware-libs/committer/blob/f772b3d96c750bb926af994736f9722402a8ccfa/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L254)):*
> ```XML
> 
>     
> )]
> ```

formatting... not sure what needs to be fixed here but it looks wrong



_Code quote:_
```XML
        leaf_data: std::marker::PhantomData,
        }



)]
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/93)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 107 at r6](https://reviewable.io/reviews/starkware-libs/committer/93#-NxCeKGC7pGCngUcYUyS:-NxCiRYy2YFV4ChXjfye:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f772b3d96c750bb926af994736f9722402a8ccfa/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L107)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add `impl Default for StateDiff`, then you can do this:
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 131 at r6](https://reviewable.io/reviews/starkware-libs/committer/93#-NxCex1A-4qL68oNXhOd:-NxCr2jmD1uUIsAJnR7H:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f772b3d96c750bb926af994736f9722402a8ccfa/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L131)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

define helper methods for this (don't we already have them? please check),
and use them in all trees you construct here
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 254 at r6](https://reviewable.io/reviews/starkware-libs/committer/93#-NxCft4T9M0GrIdeT0iU:-NxCiWCZ3nJNROX3VNn_:b-7vbkrc) ([raw file](https://github.com/starkware-libs/committer/blob/f772b3d96c750bb926af994736f9722402a8ccfa/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L254)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

formatting... not sure what needs to be fixed here but it looks wrong
</blockquote></details>

fixed. (the format script passes)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/93)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 106 at r8](https://reviewable.io/reviews/starkware-libs/committer/93#-NxD8EBW0tlWEgx-Jo4b:-NxD8EBW0tlWEgx-Jo4c:b-lvcnzz) ([raw file](https://github.com/starkware-libs/committer/blob/85ea13044ff202fb1f2852ad4de90ea434fcba86/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L106)):*
> ```XML
>                 (6, &[8, 11, 13]),
>                 (1, &[8, 10, 13]),
>             ]),..Default::default()
> ```

format script cannot (will not?) catch formatting issues inside macros... do not trust the formatter when defining `#[case]`s



_Suggestion:_
```XML
]),
..Default::default()
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/93)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 106 at r8](https://reviewable.io/reviews/starkware-libs/committer/93#-NxD8EBW0tlWEgx-Jo4b:-NxD9IZp5QFenUSxYa-2:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/85ea13044ff202fb1f2852ad4de90ea434fcba86/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L106)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

format script cannot (will not?) catch formatting issues inside macros... do not trust the formatter when defining `#[case]`s
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/93#-:-NxEiCkY7tVcn7AMvfOV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
