### PR TITLE
feat!: remove HashFunction trait

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/153)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/153)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/153#-Nyu9sEr9XG-uumEDlDs:-Nyu9sEs3mmT3zEQsSCf:b25lit) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/35083)

___

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/153#-:-Nz1y5uL4cXhbjbQ_HnR:bnfp4nl)* status: 7 of 13 files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

**Comment by aner-starkware** [comment]
:lgtm:

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/153)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/committer/153#-Nz2fT9M9gHJl9deKo1l:-Nz2fT9N953stsNkqXKU:b-740hj) ([raw file](https://github.com/starkware-libs/committer/blob/52fec33568dae227a088771ccd384a01ec72e51e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L26)):*
> ```XML
> pub const CONTRACT_STATE_HASH_VERSION: Felt = Felt::ZERO;
> // The hex string corresponding to b'CONTRACT_CLASS_LEAF_V0' in big-endian.
> pub const CONTRACT_CLASS_LEAF_V0: &str = "0x434f4e54524143545f434c4153535f4c4541465f5630";
> ```

Not sure if the consts are a part of the impl here. If yes (seems to be the case) - move them inside the impl. If not, move the doc of the impl below them, right above the impl block.



_Code quote:_
```XML
/// Implementation of TreeHashFunction. The implementation is based on the following reference:
/// https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/starknet-state/#trie_construction
// TODO(Aner, 11/4/24): Verify the correctness of the implementation.
pub const CONTRACT_STATE_HASH_VERSION: Felt = Felt::ZERO;
// The hex string corresponding to b'CONTRACT_CLASS_LEAF_V0' in big-endian.
pub const CONTRACT_CLASS_LEAF_V0: &str = "0x434f4e54524143545f434c4153535f4c4541465f5630";
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/153)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/committer/153#-Nz2fT9M9gHJl9deKo1l:-Nz2mCya11C_QQ0EvuB5:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/52fec33568dae227a088771ccd384a01ec72e51e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L26)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Not sure if the consts are a part of the impl here. If yes (seems to be the case) - move them inside the impl. If not, move the doc of the impl below them, right above the impl block.
</blockquote></details>

Done.

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/153#-:-Nz3FK-e9aOfmM4MeOoy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
