### PR TITLE
refactor: add parse_and_commit

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/309)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/309)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer_cli/benches/committer_bench.rs` line 69 at r1](https://reviewable.io/reviews/starkware-libs/committer/309#-O1qHYwb0KCV6R-a56cW:-O1qHYwb0KCV6R-a56cX:b-rtagwg) ([raw file](https://github.com/starkware-libs/committer/blob/70dd03f96c318d35b559e74bd56e9fbb66607574/crates/committer_cli/benches/committer_bench.rs#L69)):*
> ```XML
>     //     let committer_input = parse_input(input_str).expect("Failed to parse the given input.");
>     //     commit(committer_input, OUTPUT_PATH.to_owned()).await;
>     // }
> ```

delete
___
*[`crates/committer_cli/src/main.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/committer/309#-O1qHhzzBqKtVU9JlsqY:-O1qHhzzBqKtVU9JlsqZ:b4dgq0v) ([raw file](https://github.com/starkware-libs/committer/blob/70dd03f96c318d35b559e74bd56e9fbb66607574/crates/committer_cli/src/main.rs#L74)):*
> ```XML
>     match args.command {
>         Command::Commit { output_path } => {
>             // TODO(Aner, 15/7/24): try moving read_from_stdin into function.
> ```

not sure this is really important; current method seems fine. your call



_Code quote:_
```XML
// TODO(Aner, 15/7/24): try moving read_from_stdin into function.
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/309#-:-O1qgA9mAE0GPco1-Pn9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/309)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

**Review by aner-starkware — COMMENTED** [review]
Python side: https://reviewable.io/reviews/starkware-industries/starkware/35461#-

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/309#-:-O1qgxUy3GA4Hbo2y9AH:b674bke)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer_cli/src/main.rs` line 74 at r1](https://reviewable.io/reviews/starkware-libs/committer/309#-O1qHhzzBqKtVU9JlsqY:-O1qfCotBRckk7bItsde:b-n0ra7o) ([raw file](https://github.com/starkware-libs/committer/blob/70dd03f96c318d35b559e74bd56e9fbb66607574/crates/committer_cli/src/main.rs#L74)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not sure this is really important; current method seems fine. your call
</blockquote></details>

I'll look into it today\tomorrow; if I don't find a good solution, I'll just delete the TODO.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/309)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/309)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
