### PR TITLE
build: add hash test

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/77)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/77)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/committer/77#-Nwn5a5LAlvDh1IXLnHA:-Nwn5a5LAlvDh1IXLnHB:b-qd9uy1) ([raw file](https://github.com/starkware-libs/committer/blob/0d47b129662dc79ea849bf98d29a6a77b0dbec02/crates/committer_cli/src/tests/python_tests.rs#L58)):*
> ```XML
>                 let y = hash_input
>                     .get("y")
>                     .expect("Failed to get value for key 'y'");
> ```

for consistency, move these into `test_hash_function` (like how `example_test` fetches x and y)



_Code quote:_
```XML
                let x = hash_input
                    .get("x")
                    .expect("Failed to get value for key 'x'");
                let y = hash_input
                    .get("y")
                    .expect("Failed to get value for key 'y'");
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/77)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 58 at r1](https://reviewable.io/reviews/starkware-libs/committer/77#-Nwn5a5LAlvDh1IXLnHA:-NwnAlkd90jdE5pN1KDM:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/0d47b129662dc79ea849bf98d29a6a77b0dbec02/crates/committer_cli/src/tests/python_tests.rs#L58)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

for consistency, move these into `test_hash_function` (like how `example_test` fetches x and y)
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2, 2 of 3 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/77#-:-NwnBjYr2gjt_LRIgd0G:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/77)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
