### PR TITLE
test: add function that parse python input to flow test

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178)* status: all files reviewed, 6 unresolved discussions (waiting on @aner-starkware and @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzORxr26hFRGSzEFohj:-NzORxr26hFRGSzEFohk:byuurpp) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L118)):*
> ```XML
> }
> 
> #[allow(clippy::unwrap_used)]
> ```

why allow this?



_Code quote:_
```XML
#[allow(clippy::unwrap_used)]
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOS1xe4bE83hFp7UBV:-NzOS1xe4bE83hFp7UBW:br3ffbx) ([raw file](https://github.com/starkware-libs/committer/blob/2b9c2761926a1169c2b7d39eea892539120b6140/crates/committer_cli/src/tests/python_tests.rs#L29)):*
> ```XML
> use std::{collections::HashMap, io};
> use thiserror;
> ```

restore newline
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOS4UY8PmO1843LCfp:-NzOS4UY8PmO1843LCfq:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/python_tests.rs#L88)):*
> ```XML
>             "filled_forest_output" => Ok(Self::FilledForestOutput),
>             "tree_test" => Ok(Self::ComputeHashSingleTree),
>             "Serialize_to_rust_committer_flow_test" => Ok(Self::SerializeForRustCommitterFlowTest),
> ```





_Suggestion:_
```XML
serialize
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOS7go6SRhb1aezHkl:-NzOS7go6SRhb1aezHkm:b-75ywm7) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/python_tests.rs#L95)):*
> ```XML
> 
> impl PythonTest {
>     #[allow(clippy::unwrap_used)]
> ```

why is this needed?



_Code quote:_
```XML
#[allow(clippy::unwrap_used)]
```
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOSG8p6XfPicxKiVLh:-NzOSG8p6XfPicxKiVLi:b1oi1xa) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/utils/parse_from_python.rs#L15)):*
> ```XML
> #[allow(clippy::unwrap_used)]
> /// Parse input for single tree flow test.
> pub fn parse_input_single_tree_flow_test(
> ```

when moving code, open a separate PR for the move, so there are no changes to review
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOSYp63ZaFt2VJOfXn:-NzOSYp63ZaFt2VJOfXo:b-xuhuv5) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/utils/parse_from_python.rs#L36)):*
> ```XML
>             (
>                 NodeIndex::new(U256::from(*k)),
>                 LeafDataImpl::StorageValue(Felt::from_hex(v).unwrap()),
> ```

what about other tree types? compiled class trie, contract trie?
this code will not deserialize it correctly...
or is this only for a specific flow test?



_Code quote:_
```XML
LeafDataImpl::StorageValue(Felt::from_hex(v).unwrap())
```

**Review by aner-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178)* status: all files reviewed, 10 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOqHeC58iTWuEEEwAO:-NzOqHeD0wz5bBM1gTcz:bjspkj5) (no related file):*
Please do not base on my PR (as it needs to be based on your PR)

___
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOtiHzEVRcoESlUxNJ:-NzOtiHzEVRcoESlUxNK:b-547y4v) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/python_tests.rs#L161)):*
> ```XML
> fn serialize_for_rust_committer_flow_test(input: HashMap<String, String>) -> String {
>     parse_input_single_tree_flow_test(input);
>     "Success".to_string()
> ```

Does this test correctness in any way? Maybe format the returned result and check for consistency on the Python side, e.g.,
```
format!(
"tree_height: {:?}, leaf_modification: {:?}, storage: {:?}, root_hash: {:?}",
tree_height, leaf_modifications_formated, storage_formated, root_hash.0.to_hex()
)
```



_Code quote:_
```XML
    parse_input_single_tree_flow_test(input);
    "Success".to_string()
```
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOSG8p6XfPicxKiVLh:-NzOqXokBGEEMJCUUjZ9:b-v3at6a) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/utils/parse_from_python.rs#L15)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

when moving code, open a separate PR for the move, so there are no changes to review
</blockquote></details>

This code is new, the "moved part" is only the signature
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOqsjpD0cTFT4h-CJp:-NzOqsjpD0cTFT4h-CJq:beksccp) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/utils/parse_from_python.rs#L30)):*
> ```XML
>     let leaf_modifications_json = input.get("leaf_modifications").unwrap();
>     let leaf_modifications_map =
>         serde_json::from_str::<HashMap<u128, &str>>(leaf_modifications_json).unwrap();
> ```

This errs ("number out of range" error)  when trees have height 251



_Code quote:_
```XML
    let leaf_modifications_map =
        serde_json::from_str::<HashMap<u128, &str>>(leaf_modifications_json).unwrap();
```
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOSYp63ZaFt2VJOfXn:-NzOqfjE4HW5hTZw9HSr:b32n3sl) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/utils/parse_from_python.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what about other tree types? compiled class trie, contract trie?
this code will not deserialize it correctly...
or is this only for a specific flow test?
</blockquote></details>

Let's make the first tree type work; the rest should be easy to do after that.
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzP1gBH4oIxnrd2u76k:-NzP1gBH4oIxnrd2u76l:bnhrk1b) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/utils/parse_from_python.rs#L49)):*
> ```XML
>                 (
>                     StorageKey(Felt::from_hex(k).unwrap().to_bytes_be().to_vec()),
>                     StorageValue(Felt::from_hex(v).unwrap().to_bytes_be().to_vec()),
> ```

The values here don't generally fit into a Felt, so I think this conversion will most likely err.



_Code quote:_
```XML
                    StorageKey(Felt::from_hex(k).unwrap().to_bytes_be().to_vec()),
                    StorageValue(Felt::from_hex(v).unwrap().to_bytes_be().to_vec()),
```

**Review by aner-starkware — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 3 of 8 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178)* status: all files reviewed, 5 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

**Review by aner-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178)* status: all files reviewed, 5 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

**Comment by aner-starkware** [comment]
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/committer/178#-NzbzgV173Cu9uOwCPcC:-NzbzgV173Cu9uOwCPcD:byp18fd) ([raw file](https://github.com/starkware-libs/committer/blob/291ff4b5c89cc5258939855bd0bb2ded40bbcb54/crates/committer_cli/src/tests/utils/parse_from_python.rs#L20)):*
> ```XML
>     input: HashMap<String, String>,
> ) -> (
>     TreeHeight,
> ```

Remove

**Comment by aner-starkware** [comment]
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 27 at r5](https://reviewable.io/reviews/starkware-libs/committer/178#-Nzc--qHCT19QfhHuHV_:-Nzc--qHCT19QfhHuHVa:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/291ff4b5c89cc5258939855bd0bb2ded40bbcb54/crates/committer_cli/src/tests/utils/parse_from_python.rs#L27)):*
> ```XML
>     // Fetch tree height.
>     let tree_height_str = input.get("tree_height").unwrap();
>     let tree_height = TreeHeight(tree_height_str.parse::<u8>().unwrap());
> ```

**Comment by aner-starkware** [comment]
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 63 at r5](https://reviewable.io/reviews/starkware-libs/committer/178#-Nzc-7PL2lAQMNrEGHCp:-Nzc-7PL2lAQMNrEGHCq:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/291ff4b5c89cc5258939855bd0bb2ded40bbcb54/crates/committer_cli/src/tests/utils/parse_from_python.rs#L63)):*
> ```XML
>     let root_hash = HashOutput(Felt::from_hex(input.get("root_hash").unwrap()).unwrap());
> 
>     (tree_height, leaf_modifications, map_storage, root_hash)
> ```





_Suggestion:_
```XML
(leaf_modifications, map_storage, root_hash)
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178)* status: 5 of 9 files reviewed, 8 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOqHeC58iTWuEEEwAO:-NzRcxgV94UujoZLwoa1:b3px6ho) (no related file):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Please do not base on my PR (as it needs to be based on your PR)
</blockquote></details>

Thanks, changed.

___
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 29 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOS1xe4bE83hFp7UBV:-NzRdQVs1a11f3iZgqGu:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/2b9c2761926a1169c2b7d39eea892539120b6140/crates/committer_cli/src/tests/python_tests.rs#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

restore newline
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOS4UY8PmO1843LCfp:-NzRdaCEEOl5t1KPlnwU:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/python_tests.rs#L88)):*
> ```XML
>             "filled_forest_output" => Ok(Self::FilledForestOutput),
>             "tree_test" => Ok(Self::ComputeHashSingleTree),
>             "Serialize_to_rust_committer_flow_test" => Ok(Self::SerializeForRustCommitterFlowTest),
> ```

Done.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOS7go6SRhb1aezHkl:-NzRdhGl9d5H23eZnM3z:b-lkd8gn) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/python_tests.rs#L95)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

Not needed here
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 161 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOtiHzEVRcoESlUxNJ:-NzReeEA8V41P6OuRJ57:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/python_tests.rs#L161)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Does this test correctness in any way? Maybe format the returned result and check for consistency on the Python side, e.g.,
```
format!(
"tree_height: {:?}, leaf_modification: {:?}, storage: {:?}, root_hash: {:?}",
tree_height, leaf_modifications_formated, storage_formated, root_hash.0.to_hex()
)
```
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOSG8p6XfPicxKiVLh:-NzSARi1BjuMkF6z4oC_:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/utils/parse_from_python.rs#L15)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

This code is new, the "moved part" is only the signature
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOqsjpD0cTFT4h-CJp:-NzRhcTp8S1Vn6TGuEnL:bhx71hr) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/utils/parse_from_python.rs#L30)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

This errs ("number out of range" error)  when trees have height 251
</blockquote></details>

Thanks, I change it to cast from hex.
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOSYp63ZaFt2VJOfXn:-NzRexzz9IDqadNSjQRH:b-kraodx) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/utils/parse_from_python.rs#L36)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Let's make the first tree type work; the rest should be easy to do after that.
</blockquote></details>

It's specific for a storage tree.
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzP1gBH4oIxnrd2u76k:-NzRgBm5A8WmcIagasCu:bieqs5g) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/utils/parse_from_python.rs#L49)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

The values here don't generally fit into a Felt, so I think this conversion will most likely err.
</blockquote></details>

Thanks, I found better way using hex::decode()
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 20 at r5](https://reviewable.io/reviews/starkware-libs/committer/178#-NzbzgV173Cu9uOwCPcC:-Nzc-Ajf8pJFeggPI__0:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/291ff4b5c89cc5258939855bd0bb2ded40bbcb54/crates/committer_cli/src/tests/utils/parse_from_python.rs#L20)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 27 at r5](https://reviewable.io/reviews/starkware-libs/committer/178#-Nzc--qHCT19QfhHuHV_:-Nzc-ATsDGrtrmQYmZ9R:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/291ff4b5c89cc5258939855bd0bb2ded40bbcb54/crates/committer_cli/src/tests/utils/parse_from_python.rs#L27)):*
> ```XML
>     // Fetch tree height.
>     let tree_height_str = input.get("tree_height").unwrap();
>     let tree_height = TreeHeight(tree_height_str.parse::<u8>().unwrap());
> ```

Done.
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 63 at r5](https://reviewable.io/reviews/starkware-libs/committer/178#-Nzc-7PL2lAQMNrEGHCp:-Nzc-DP95OCoEaYITEwg:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/291ff4b5c89cc5258939855bd0bb2ded40bbcb54/crates/committer_cli/src/tests/utils/parse_from_python.rs#L63)):*
> ```XML
>     let root_hash = HashOutput(Felt::from_hex(input.get("root_hash").unwrap()).unwrap());
> 
>     (tree_height, leaf_modifications, map_storage, root_hash)
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 118 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzORxr26hFRGSzEFohj:-NzRd1kt-tlhhX-vWxKG:b-bczerx) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L118)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why allow this?
</blockquote></details>

Since it is a function for Python testing, if it panics, it gives a better error message that way.

**Comment by aner-starkware** [comment]
*[`crates/committer_cli/src/tests/python_tests.rs` line 163 at r5](https://reviewable.io/reviews/starkware-libs/committer/178#-Nzc-XlU-cIJmcmtwyQi:-Nzc-XlU-cIJmcmtwyQj:b-sew8l9) ([raw file](https://github.com/starkware-libs/committer/blob/291ff4b5c89cc5258939855bd0bb2ded40bbcb54/crates/committer_cli/src/tests/python_tests.rs#L163)):*
> ```XML
>         storage.storage,
>         root_hash.0.to_hex()
>     )
> ```

Remove the tree height



_Suggestion:_
```XML
    format!(
        "leaf_modification: {:?}, storage: {:?}, root_hash: {:?}",
        leaf_modifications_to_print,
        storage.storage,
        root_hash.0.to_hex()
    )
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178)* status: 5 of 9 files reviewed, 9 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 163 at r5](https://reviewable.io/reviews/starkware-libs/committer/178#-Nzc-XlU-cIJmcmtwyQi:-Nzc04xM4aFhF5AL0Qn9:bx922lj) ([raw file](https://github.com/starkware-libs/committer/blob/291ff4b5c89cc5258939855bd0bb2ded40bbcb54/crates/committer_cli/src/tests/python_tests.rs#L163)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Remove the tree height
</blockquote></details>

I removed it

**Review by aner-starkware — APPROVED** [review]
> Reviewed 2 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178)* status: 7 of 9 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 153 at r6](https://reviewable.io/reviews/starkware-libs/committer/178#-NzcMIJd9jUSkbJ5xbyF:-NzcMIJd9jUSkbJ5xbyG:baipb7w) ([raw file](https://github.com/starkware-libs/committer/blob/07a518f0ed1c9a24027b0872320207ca7b10785c/crates/committer_cli/src/tests/python_tests.rs#L153)):*
> ```XML
> fn serialize_for_rust_committer_flow_test(input: HashMap<String, String>) -> String {
>     let (leaf_modifications, storage, root_hash) = parse_input_single_tree_flow_test(input);
>     // Serialize the leaf modifications to an object that can serialize.
> ```

this is a confusing sentence as it is now



_Suggestion:_
```XML
// Serialize the leaf modifications to an object that can JSON-serialized.
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 159 at r6](https://reviewable.io/reviews/starkware-libs/committer/178#-NzcMOTdEzTEq87ocNdj:-NzcMOTdEzTEq87ocNdk:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/07a518f0ed1c9a24027b0872320207ca7b10785c/crates/committer_cli/src/tests/python_tests.rs#L159)):*
> ```XML
>         .collect();
> 
>     // crate a json to compare with the python expected.
> ```





_Suggestion:_
```XML
Create a json string to compare with the expected string in python.
```
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOSYp63ZaFt2VJOfXn:-NzcLpSECv-UAlFpkQdD:b-acmgwq) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/utils/parse_from_python.rs#L36)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

It's specific for a storage tree.
</blockquote></details>

but you are deserializing python input here, correct?
so the storage object you return should be just that - a storage 
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 15 at r6](https://reviewable.io/reviews/starkware-libs/committer/178#-NzcLUY37YmnXAJnrkeA:-NzcLUY37YmnXAJnrkeB:b-4fdj3i) ([raw file](https://github.com/starkware-libs/committer/blob/07a518f0ed1c9a24027b0872320207ca7b10785c/crates/committer_cli/src/tests/utils/parse_from_python.rs#L15)):*
> ```XML
> 
> #[allow(clippy::unwrap_used)]
> /// Parse input for single tree flow test.
> ```

document return values



_Suggestion:_
```XML
/// Parse input for single tree flow test.
/// Returns the leaf modifications, fetched nodes (in storage) and the root hash.
```
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 21 at r6](https://reviewable.io/reviews/starkware-libs/committer/178#-NzcLPr2B1Lh8D9exLlM:-NzcLPr2B1Lh8D9exLlN:b-xylxst) ([raw file](https://github.com/starkware-libs/committer/blob/07a518f0ed1c9a24027b0872320207ca7b10785c/crates/committer_cli/src/tests/utils/parse_from_python.rs#L21)):*
> ```XML
>     LeafModifications<LeafDataImpl>,
>     MapStorage,
>     HashOutput, //root_hash
> ```

return values should be documented in the docstring (see above)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 153 at r6](https://reviewable.io/reviews/starkware-libs/committer/178#-NzcMIJd9jUSkbJ5xbyF:-NzcYAiN3vXCydZVDrRM:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/07a518f0ed1c9a24027b0872320207ca7b10785c/crates/committer_cli/src/tests/python_tests.rs#L153)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is a confusing sentence as it is now
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 159 at r6](https://reviewable.io/reviews/starkware-libs/committer/178#-NzcMOTdEzTEq87ocNdj:-NzcYFxp57Lw41cbogHY:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/07a518f0ed1c9a24027b0872320207ca7b10785c/crates/committer_cli/src/tests/python_tests.rs#L159)):*
> ```XML
>         .collect();
> 
>     // crate a json to compare with the python expected.
> ```

Done.
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOSYp63ZaFt2VJOfXn:-NzcZ7Zj3GIVTpcTwUa9:b7x3rnl) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/utils/parse_from_python.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

but you are deserializing python input here, correct?
so the storage object you return should be just that - a storage
</blockquote></details>

I don't think I understand. 
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 15 at r6](https://reviewable.io/reviews/starkware-libs/committer/178#-NzcLUY37YmnXAJnrkeA:-NzcZZqX3sLSegesj79S:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/07a518f0ed1c9a24027b0872320207ca7b10785c/crates/committer_cli/src/tests/utils/parse_from_python.rs#L15)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

document return values
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 21 at r6](https://reviewable.io/reviews/starkware-libs/committer/178#-NzcLPr2B1Lh8D9exLlM:-NzcZbiD1TFQ-a631ZIu:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/07a518f0ed1c9a24027b0872320207ca7b10785c/crates/committer_cli/src/tests/utils/parse_from_python.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

return values should be documented in the docstring (see above)
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 36 at r1](https://reviewable.io/reviews/starkware-libs/committer/178#-NzOSYp63ZaFt2VJOfXn:-NzceTdvAhVUgF83xC2I:bg5ilfh) ([raw file](https://github.com/starkware-libs/committer/blob/e03a9cbfec975fb7db3ad30ff98de2e123ec7c9a/crates/committer_cli/src/tests/utils/parse_from_python.rs#L36)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

I don't think I understand.
</blockquote></details>

whoops
forgot to delete the reply, my mistake... this is fine
___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 21 at r6](https://reviewable.io/reviews/starkware-libs/committer/178#-NzcLPr2B1Lh8D9exLlM:-NzceOvFCaCalfC-TEWr:b-l38fiz) ([raw file](https://github.com/starkware-libs/committer/blob/07a518f0ed1c9a24027b0872320207ca7b10785c/crates/committer_cli/src/tests/utils/parse_from_python.rs#L21)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not yet, delete this `//root_hash` you have here

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/src/tests/utils/parse_from_python.rs` line 21 at r6](https://reviewable.io/reviews/starkware-libs/committer/178#-NzcLPr2B1Lh8D9exLlM:-NzchoFf2tpWTdRbq_gO:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/07a518f0ed1c9a24027b0872320207ca7b10785c/crates/committer_cli/src/tests/utils/parse_from_python.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not yet, delete this `//root_hash` you have here
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178#-:-Nzckiqf3gtTKmMGr7cm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/178)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
