### PR TITLE
refactor: commit classes trie concurrently

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/315)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/315)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/315#-O2-zElJ0ZJGbey2eq4A:-O2-zElJ0ZJGbey2eq4B:bpigt5k) ([raw file](https://github.com/starkware-libs/committer/blob/52b93d46dee7c02f2102183f3ae4ad53c17d7bd1/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L61)):*
> ```XML
>             Arc::new(updated_forest.classes_trie),
>             Arc::new(classes_updates),
>         );
> ```

does the task start running the moment it's created?
in python, task `t` will not start running until someone `await`s it;
perhaps you need to add this task to the `JoinSet` below?
And maybe better to create a top-level JoinSet with two tasks: one for the contracts tree and one for the classes tree (contracts tree JoinSet will have many storage tree tasks - i.e. it opens an inner JoinSet).
WDYT?

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/315)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/315#-O2-zElJ0ZJGbey2eq4A:-O23pJ_A8Ssa9nEqe1CL:bg1yixj) ([raw file](https://github.com/starkware-libs/committer/blob/52b93d46dee7c02f2102183f3ae4ad53c17d7bd1/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L61)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does the task start running the moment it's created?
in python, task `t` will not start running until someone `await`s it;
perhaps you need to add this task to the `JoinSet` below?
And maybe better to create a top-level JoinSet with two tasks: one for the contracts tree and one for the classes tree (contracts tree JoinSet will have many storage tree tasks - i.e. it opens an inner JoinSet).
WDYT?
</blockquote></details>

good catch!
it didn't start running; now it starts immediately when using `tokio::spawn.`
is there any benefit to having two joinsets?

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/315#-O2-zElJ0ZJGbey2eq4A:-O23r6-Z6os2HDAVw2c2:b-ptif70) ([raw file](https://github.com/starkware-libs/committer/blob/52b93d46dee7c02f2102183f3ae4ad53c17d7bd1/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L61)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

good catch!
it didn't start running; now it starts immediately when using `tokio::spawn.`
is there any benefit to having two joinsets?
</blockquote></details>

one inside the other, I think:
```
await JoinSet(class_trie_commitment_task, contract_trie_commitment_task)
```
where `contract_tree_commitment_task` is:
1. opening a `JoinSet` with all storage tries
2. awaiting them all
3. computing the contract trie

however, if `tokio::spawn` already starts the task then this current way is fine.
I'm only concerned about work stealing: if `tokio::spawn` moves context from current function to `ClassesTrie::create`, then you will start working on the classes trie before the other task(s) are spawned.

Maybe better to create both `class_trie_commitment_task` and `contract_trie_commitment_task` without them actually running, and then open a `JoinSet` for the two of them?

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/315#-O2-zElJ0ZJGbey2eq4A:-O23zQWTAzkQ0VdF3MPb:baayiy9) ([raw file](https://github.com/starkware-libs/committer/blob/52b93d46dee7c02f2102183f3ae4ad53c17d7bd1/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L61)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

one inside the other, I think:
```
await JoinSet(class_trie_commitment_task, contract_trie_commitment_task)
```
where `contract_tree_commitment_task` is:
1. opening a `JoinSet` with all storage tries
2. awaiting them all
3. computing the contract trie

however, if `tokio::spawn` already starts the task then this current way is fine.
I'm only concerned about work stealing: if `tokio::spawn` moves context from current function to `ClassesTrie::create`, then you will start working on the classes trie before the other task(s) are spawned.

Maybe better to create both `class_trie_commitment_task` and `contract_trie_commitment_task` without them actually running, and then open a `JoinSet` for the two of them?
</blockquote></details>

is that better now?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/315)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/315#-O2-zElJ0ZJGbey2eq4A:-O248BL0BigiiTLVDUN3:bvxwja4) ([raw file](https://github.com/starkware-libs/committer/blob/52b93d46dee7c02f2102183f3ae4ad53c17d7bd1/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L61)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

is that better now?
</blockquote></details>

see below, maybe it's clearer
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/committer/315#-O246gAT3x4e1ZEzNQGl:-O246gAT3x4e1ZEzNQGm:b-vqux5v) ([raw file](https://github.com/starkware-libs/committer/blob/e91c9a6d3c669f7b6ba3f402c2161c0829cd506e/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L102)):*
> ```XML
>             Arc::new(contracts_trie_modifications),
>         );
>         let (classes_trie, contracts_trie) = join!(classes_trie_task, contracts_trie_task);
> ```

1. IIRC `join!` doesn't work as we would expect here, please confer with @aner-starkware 
2. Now, as I understand it, you (a) compute storage tries, and (b) in parallel, compute the classes and the contracts tries. (a) and (b) are *sequential*. However, the classes trie computation is orthogonal to the storage/contract trie computations... execution tree should look something like this:
```
await join(
   task { compute(classes_trie) },
   task {
      await join(
         task { compute(storage_trie) } for storage_trie in storage_tries
      );
      task { compute(contract_trie) }
   }
)
```
it currently looks like this:
```
await join(
   task { compute(storage_trie) } for storage_trie in storage_tries
);
await join(
   task { compute(contract_trie) },
   task { compute(classes_trie) },
)
```



_Code quote:_
```XML
        let classes_trie_task = ClassesTrie::create::<TH>(
            Arc::new(updated_forest.classes_trie),
            Arc::new(classes_updates),
        );
        let contracts_trie_task = ContractsTrie::create::<TH>(
            Arc::new(updated_forest.contracts_trie),
            Arc::new(contracts_trie_modifications),
        );
        let (classes_trie, contracts_trie) = join!(classes_trie_task, contracts_trie_task);
```

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/315)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/committer/315#-O24G4wP9NKqd2wLgVAn:-O24G4wP9NKqd2wLgVAo:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/5a8daeb2efc6971d0deccf0a0ce0091a3712772b/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L65)):*
> ```XML
>         let mut contracts_trie_modifications = HashMap::new();
>         let mut filled_storage_tries = HashMap::new();
>         let mut tasks = JoinSet::new();
> ```





_Suggestion:_
```XML
contracts_state_tasks
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/committer/315#-O246gAT3x4e1ZEzNQGl:-O24H2to40UWexD0DZl6:b-sgi4yv) ([raw file](https://github.com/starkware-libs/committer/blob/e91c9a6d3c669f7b6ba3f402c2161c0829cd506e/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L102)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. IIRC `join!` doesn't work as we would expect here, please confer with @aner-starkware 
2. Now, as I understand it, you (a) compute storage tries, and (b) in parallel, compute the classes and the contracts tries. (a) and (b) are *sequential*. However, the classes trie computation is orthogonal to the storage/contract trie computations... execution tree should look something like this:
```
await join(
   task { compute(classes_trie) },
   task {
      await join(
         task { compute(storage_trie) } for storage_trie in storage_tries
      );
      task { compute(contract_trie) }
   }
)
```
it currently looks like this:
```
await join(
   task { compute(storage_trie) } for storage_trie in storage_tries
);
await join(
   task { compute(contract_trie) },
   task { compute(classes_trie) },
)
```
</blockquote></details>

Does the `join` call order matter to anything? I would assume only the tasks creation order (the `spawn` call) is important.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/315)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/committer/315#-O246gAT3x4e1ZEzNQGl:-O24ICuCCS06IGRMTR2g:bu8kb15) ([raw file](https://github.com/starkware-libs/committer/blob/e91c9a6d3c669f7b6ba3f402c2161c0829cd506e/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L102)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Does the `join` call order matter to anything? I would assume only the tasks creation order (the `spawn` call) is important.
</blockquote></details>

the `tasks.join_next().await` above matters, it blocks (so class trie and contract trie tasks are only spawned after all storage tries are complete)

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/315)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/committer/315#-O24IEC4-yxSROSD48aO:-O24IEC59Yh2kFIXZlen:bvgqu42) ([raw file](https://github.com/starkware-libs/committer/blob/e91c9a6d3c669f7b6ba3f402c2161c0829cd506e/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L97)):*
> ```XML
>             Arc::new(updated_forest.classes_trie),
>             Arc::new(classes_updates),
>         );
> ```

This seems worst to me unless I'm missing something. Now we don't start computing the classes tri until after the storage tries computation finishes.



_Code quote:_
```XML
        let classes_trie_task = ClassesTrie::create::<TH>(
            Arc::new(updated_forest.classes_trie),
            Arc::new(classes_updates),
        );
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/315)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/315#-O2-zElJ0ZJGbey2eq4A:-O24KN1jAGWDE1KKKDbU:b-ku81gt) ([raw file](https://github.com/starkware-libs/committer/blob/52b93d46dee7c02f2102183f3ae4ad53c17d7bd1/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L61)):*
> I'm only concerned about work stealing: if `tokio::spawn` moves context from current function to `ClassesTrie::create`, then you will start working on the classes trie before the other task(s) are spawned.

The `spawn` creates another task (which I guess will run on another core if we have more than one). The main thread will spawn the tasks for the storage tries and I think it will run in parallel, no?
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/committer/315#-O24IEC4-yxSROSD48aO:-O24KT9Z4xswr0qgJz5J:b-cstnkg) ([raw file](https://github.com/starkware-libs/committer/blob/e91c9a6d3c669f7b6ba3f402c2161c0829cd506e/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L97)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

This seems worst to me unless I'm missing something. Now we don't start computing the classes tri until after the storage tries computation finishes.
</blockquote></details>

I agree
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 102 at r3](https://reviewable.io/reviews/starkware-libs/committer/315#-O246gAT3x4e1ZEzNQGl:-O24I9Pp2_NzQpTtQA2l:bg3or9u) ([raw file](https://github.com/starkware-libs/committer/blob/e91c9a6d3c669f7b6ba3f402c2161c0829cd506e/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L102)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

the `tasks.join_next().await` above matters, it blocks (so class trie and contract trie tasks are only spawned after all storage tries are complete)
</blockquote></details>

you are right; the `join!` runs both tasks concurrently but not in parallel.

How about now?

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/315)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/315#-O2-zElJ0ZJGbey2eq4A:-O24LLpj3OjtMFrlL9_l:b325kt5) ([raw file](https://github.com/starkware-libs/committer/blob/52b93d46dee7c02f2102183f3ae4ad53c17d7bd1/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L61)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

> I'm only concerned about work stealing: if `tokio::spawn` moves context from current function to `ClassesTrie::create`, then you will start working on the classes trie before the other task(s) are spawned.

The `spawn` creates another task (which I guess will run on another core if we have more than one). The main thread will spawn the tasks for the storage tries and I think it will run in parallel, no?
</blockquote></details>

ohh now i understand... the classes trie on it's own may use more than one core..

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/315)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/315)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/315#-:-O250TI95bKU3O3hX7MM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
