### PR TITLE
fix: patricia height should be 251

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/210)

### CODE REVIEW

**Review by AvivYossef-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/210)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/committer/210#-NzwwJhS2ls3Mou042EJ:-NzwwJhS2ls3Mou042EK:b-igd4wm) ([raw file](https://github.com/starkware-libs/committer/blob/5a5f293a26d97e723ea7b2af1733c7b4b1206353/crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs#L31)):*
> ```XML
>                     class_hash.0.to_fixed_hex_string(),
>                     storage_root_hash.0.to_fixed_hex_string(),
>                     SubTreeHeight::ACTUAL_HEIGHT,
> ```

In python 
value = b'{"contract\_hash": "02f8d7478ae5d25bfc41e5c5ae39f151d865a7cf1c10478bc10575ec7e66d558", "storage\_commitment\_tree": {"root": "db40135479680cd47cbe3facc5cab34974e3544dad2f8ae8a87dcced06e9b068", "height": 251}, "nonce": "0x0"}'

Here I think that rust will print -  height:  SubTreeHeight(251)



_Code snippet:_
```XML
I think that you should change it to  SubTreeHeight::ACTUAL_HEIGHT.0
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/210)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/committer/210#-NzwwJhS2ls3Mou042EJ:-NzwxQEdBfElbBqjopKI:bxa57sk) ([raw file](https://github.com/starkware-libs/committer/blob/5a5f293a26d97e723ea7b2af1733c7b4b1206353/crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs#L31)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

In python 
value = b'{"contract\_hash": "02f8d7478ae5d25bfc41e5c5ae39f151d865a7cf1c10478bc10575ec7e66d558", "storage\_commitment\_tree": {"root": "db40135479680cd47cbe3facc5cab34974e3544dad2f8ae8a87dcced06e9b068", "height": 251}, "nonce": "0x0"}'

Here I think that rust will print -  height:  SubTreeHeight(251)
</blockquote></details>

i tested it, it prints `251` like we want :)

`SubTreeHeight` derives `Display`

**Review by nimrod-starkware — COMMENTED** [review]
python side [PR](https://reviewable.io/reviews/starkware-industries/starkware/35188)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/210#-:-Nzx-D_R1JyQsoU8wpWc:bn3xh41)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by AvivYossef-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/210#-:-NzxCoHV5gKoeadywOjO:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Pull request merged**
