### PR TITLE
feat: added OriginalSkeletonInputNode enum to remove generic leaf fro…

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
…m skeleton

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/168)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/168)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/committer/168#-Nz8rHed-0RJRNrCm4R_:-Nz8rHed-0RJRNrCm4Ra:b-cd990y) ([raw file](https://github.com/starkware-libs/committer/blob/02d0628f5b51acdb2e5a6253099d1744eea9dc9c/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L111)):*
> ```XML
>         } else if value.0.len() == EDGE_BYTES {
>             return Ok(Self {
>                 hash: HashOutput(Felt::from_bytes_be_slice(&key.0)),
> ```

this wasn't used



_Code quote:_
```XML
hash: HashOutput(Felt::from_bytes_be_slice(&key.0)),
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/committer/168#-Nz8rKsj1Z7fKG-vkTJu:-Nz8rKsj1Z7fKG-vkTJv:bmf7onf) ([raw file](https://github.com/starkware-libs/committer/blob/02d0628f5b51acdb2e5a6253099d1744eea9dc9c/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L128)):*
> ```XML
>             });
>         } else {
>             // TODO(Nimrod, 5/5/2024): See if deserializing leaves data is needed somewhere.
> ```

seems that it isn't for the moment, and I can't imagine why it would be needed for the skeleton



_Code quote:_
```XML
// TODO(Nimrod, 5/5/2024): See if deserializing leaves data is needed somewhere.
```

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/168)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/committer/168#-NzMdweSAE2Wic8O5Yev:-NzMdweTB64Qb-mzGidX:bjkknc0) ([raw file](https://github.com/starkware-libs/committer/blob/d48007c62eb2204f38e986e066414fcdb37aae36/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L35)):*
> ```XML
> type FilledNodeSerializationResult = Result<StorageValue, SerializationError>;
> type OriginalSkeletonInputNodeDeserializationResult =
>     Result<OriginalSkeletonInputNode, DeserializationError>;
> ```

I think the name is too long; maybe would be better to remove it?



_Code quote:_
```XML
type OriginalSkeletonInputNodeDeserializationResult =
    Result<OriginalSkeletonInputNode, DeserializationError>;
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/committer/168#-NzMeEAi8YbJYh0IB55l:-NzMeEAi8YbJYh0IB55m:b5i434p) ([raw file](https://github.com/starkware-libs/committer/blob/d48007c62eb2204f38e986e066414fcdb37aae36/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L101)):*
> ```XML
>         key: &StorageKey,
>         value: &StorageValue,
>     ) -> OriginalSkeletonInputNodeDeserializationResult {
> ```

`Result<OriginalSkeletonInputNode, DeserializationError>`



_Code quote:_
```XML
OriginalSkeletonInputNodeDeserializationResult
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/168)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 35 at r2](https://reviewable.io/reviews/starkware-libs/committer/168#-NzMdweSAE2Wic8O5Yev:-NzN74aSDBpXLy-iwWcj:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d48007c62eb2204f38e986e066414fcdb37aae36/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L35)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I think the name is too long; maybe would be better to remove it?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 101 at r2](https://reviewable.io/reviews/starkware-libs/committer/168#-NzMeEAi8YbJYh0IB55l:-NzN75LK1rP1rt3gzlml:b-o0z11n) ([raw file](https://github.com/starkware-libs/committer/blob/d48007c62eb2204f38e986e066414fcdb37aae36/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L101)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

`Result<OriginalSkeletonInputNode, DeserializationError>`
</blockquote></details>

Done.
also remove `FilledNodeSerializationResult`, which was unused

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/168#-:-NzNM0if21jVNStBorKx:bnfp4nl)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/168#-:-NzO5vVn9P9NIV-L6f93:bnfp4nl)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 5 at r4](https://reviewable.io/reviews/starkware-libs/committer/168#-NzO15nR19im7A4y3juP:-NzO15nR19im7A4y3juQ:b7oqx6q) ([raw file](https://github.com/starkware-libs/committer/blob/15f126dfddf3f86a2581454b0da492af5467ce98/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L5)):*
> ```XML
> use crate::patricia_merkle_tree::node_data::inner_node::{EdgePathLength, PathToBottom};
> use crate::patricia_merkle_tree::node_data::leaf::LeafModifications;
> use crate::patricia_merkle_tree::original_skeleton_tree::create_tree::LeafDataImpl;
> ```

Was this an import of an import?



_Code quote:_
```XML
use crate::patricia_merkle_tree::original_skeleton_tree::create_tree::LeafDataImpl;
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/168)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 5 at r4](https://reviewable.io/reviews/starkware-libs/committer/168#-NzO15nR19im7A4y3juP:-NzO6Y2p8Zt6J45Aochl:bqcctd7) ([raw file](https://github.com/starkware-libs/committer/blob/15f126dfddf3f86a2581454b0da492af5467ce98/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L5)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Was this an import of an import?
</blockquote></details>

apparently

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/168)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/168)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 111 at r1](https://reviewable.io/reviews/starkware-libs/committer/168#-Nz8rHed-0RJRNrCm4R_:-O-VBCD29oPxeRVIyl0g:b-sxi518) ([raw file](https://github.com/starkware-libs/committer/blob/02d0628f5b51acdb2e5a6253099d1744eea9dc9c/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L111)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this wasn't used
</blockquote></details>

@dorimedini-starkware 
I think that we actually need the hash, right?
Imagine this case where the hash is addition.
         3
        /
       2
      / \
     1   1

We want the root to be 3 (not 2)

**Pull request merged**
