### PR TITLE
chore(skeleton): hide private field in EdgePathLength

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/177)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/177)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/committer/177#-NzOJEim31XdWxUUpior:-NzOJEim31XdWxUUpios:bfy3kaq) ([raw file](https://github.com/starkware-libs/committer/blob/03f6b4109602d936f68afb1e7f03ead90ae6efa0/crates/committer/src/patricia_merkle_tree/test_utils.rs#L27)):*
> ```XML
>                     .expect("String is too large"),
>             )
>             .expect("Invalid length"),
> ```

this is a test util, right? unwrap is allowed and encouraged



_Suggestion:_
```XML
.unwrap()
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/committer/177#-NzOJkceCycWWUsJI6vV:-NzOJkceCycWWUsJI6vW:bniqufg) ([raw file](https://github.com/starkware-libs/committer/blob/03f6b4109602d936f68afb1e7f03ead90ae6efa0/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L119)):*
> ```XML
>                     )
>                     .into(),
>                     length: EdgePathLength::new(value.0[EDGE_BYTES - 1]).expect("Illegal length"),
> ```

I wouldn't `expect` here, this is deserialization code, the caller should handle this error...
WDYT? non-blocking



_Suggestion:_
```XML
length: EdgePathLength::new(value.0[EDGE_BYTES - 1])?
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/177)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/committer/177#-NzOJEim31XdWxUUpior:-NzOLVmm0fghUaEybdWm:b-6emkzy) ([raw file](https://github.com/starkware-libs/committer/blob/03f6b4109602d936f68afb1e7f03ead90ae6efa0/crates/committer/src/patricia_merkle_tree/test_utils.rs#L27)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is a test util, right? unwrap is allowed and encouraged
</blockquote></details>

Tried that, getting `error: used `unwrap()` on a `Result` value` from clippy.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/committer/177#-NzOJkceCycWWUsJI6vV:-NzOLpD29kqeJmJcUolY:bqbuzqf) ([raw file](https://github.com/starkware-libs/committer/blob/03f6b4109602d936f68afb1e7f03ead90ae6efa0/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L119)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I wouldn't `expect` here, this is deserialization code, the caller should handle this error...
WDYT? non-blocking
</blockquote></details>

I think there's a lot of work we need to do to propagate errors. Is this one OK specifically for where you pointed to?

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/177)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/committer/177#-NzOJEim31XdWxUUpior:-NzOOCg16BrHJPbxJpv-:b-d847pc) ([raw file](https://github.com/starkware-libs/committer/blob/03f6b4109602d936f68afb1e7f03ead90ae6efa0/crates/committer/src/patricia_merkle_tree/test_utils.rs#L27)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Tried that, getting `error: used `unwrap()` on a `Result` value` from clippy.
</blockquote></details>

Maybe becasue this module is used with `feature="testing"` and not just `test`?

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/177#-:-NzOPNFY6toQirYJLSBd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/committer/177#-NzOJEim31XdWxUUpior:-NzOPBxHC73qD_Mq1KPx:b-2q73ua) ([raw file](https://github.com/starkware-libs/committer/blob/03f6b4109602d936f68afb1e7f03ead90ae6efa0/crates/committer/src/patricia_merkle_tree/test_utils.rs#L27)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Maybe becasue this module is used with `feature="testing"` and not just `test`?
</blockquote></details>

ah... is this needed from the cli area?

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/177)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/committer/177#-NzOJEim31XdWxUUpior:-NzOPYWb3wkptuM1UR6N:b-dbnyv8) ([raw file](https://github.com/starkware-libs/committer/blob/03f6b4109602d936f68afb1e7f03ead90ae6efa0/crates/committer/src/patricia_merkle_tree/test_utils.rs#L27)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah... is this needed from the cli area?
</blockquote></details>

@AvivYossef-starkware ?

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/177)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 27 at r1](https://reviewable.io/reviews/starkware-libs/committer/177#-NzOJEim31XdWxUUpior:-NzOQ-IU8UPWQCmkW-fF:bmhv4he) ([raw file](https://github.com/starkware-libs/committer/blob/03f6b4109602d936f68afb1e7f03ead90ae6efa0/crates/committer/src/patricia_merkle_tree/test_utils.rs#L27)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

@AvivYossef-starkware ?
</blockquote></details>

You are right. `feature="testing"`is not like a test.
However, You can use the snippet on your test function and clippy will allow use of unwrap



_Code snippet:_
```XML
#[allow(clippy::unwrap_used)]
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/177)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
