### PR TITLE
refactor: prepare for full_committer_flow benchmark

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/235)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/235)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer_cli/src/committer_runner.rs` line 0 at r1](https://reviewable.io/reviews/starkware-libs/committer/235#-O-ohRbm1ogBg1CG6Kj0:-O-ohRbm1ogBg1CG6Kj1:b-43t8ps) ([raw file](https://github.com/starkware-libs/committer/blob/d90da0ea8a37ca40ccee8ec54caf633c3975cc5d/crates/committer_cli/src/committer_runner.rs#L0)):*
please sync with @yoavGrs and put all "command" functions in the same `commands.rs` module.
"committer runner" is a python-side concept
___
*[`crates/committer_cli/src/main.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/committer/235#-O-oh-85AILea8NSmlr2:-O-oh-85AILea8NSmlr3:bjr1n7f) ([raw file](https://github.com/starkware-libs/committer/blob/d90da0ea8a37ca40ccee8ec54caf633c3975cc5d/crates/committer_cli/src/main.rs#L71)):*
> ```XML
> 
>     match args.command {
>         Command::Commit { io_args: _ } => {
> ```

you need to use the input and output files.
`forest_to_python` needs to accept an output file argument and not print to console.
this will be done in a subsequent PR? (non-blocking here)



_Code quote:_
```XML
Command::Commit { io_args: _ }
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/235)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer_cli/src/main.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/committer/235#-O-oh-85AILea8NSmlr2:-O-oq8gF2adCtzNLKajU:bhrq953) ([raw file](https://github.com/starkware-libs/committer/blob/d90da0ea8a37ca40ccee8ec54caf633c3975cc5d/crates/committer_cli/src/main.rs#L71)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you need to use the input and output files.
`forest_to_python` needs to accept an output file argument and not print to console.
this will be done in a subsequent PR? (non-blocking here)
</blockquote></details>

I'm working on it

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/235)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer_cli/src/main.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/committer/235#-O-oh-85AILea8NSmlr2:-O-owP-p5YKdMfxYqFds:b-f0n2xg) ([raw file](https://github.com/starkware-libs/committer/blob/d90da0ea8a37ca40ccee8ec54caf633c3975cc5d/crates/committer_cli/src/main.rs#L71)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I'm working on it
</blockquote></details>

ah, this is not yet ready on the python side.
@aner-starkware please add a TODO if you need this merged before Yoav is done

**Comment by aner-starkware** [comment]
*[`crates/committer_cli/src/main.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/committer/235#-O-oh-85AILea8NSmlr2:-O-pGXF50OuT8bgdik35:b-u7hztd) ([raw file](https://github.com/starkware-libs/committer/blob/d90da0ea8a37ca40ccee8ec54caf633c3975cc5d/crates/committer_cli/src/main.rs#L71)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah, this is not yet ready on the python side.
@aner-starkware please add a TODO if you need this merged before Yoav is done
</blockquote></details>

But there is already a TODO by Nimrod. This isn't directly connected with the benchmarking (which reads separately from the file).

**Comment by aner-starkware** [comment]
*[`crates/committer_cli/src/committer_runner.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/committer/235#-O-ohRbm1ogBg1CG6Kj0:-O-pyNe3DMBwNXyR3FIz:bsvjqfq) ([raw file](https://github.com/starkware-libs/committer/blob/d90da0ea8a37ca40ccee8ec54caf633c3975cc5d/crates/committer_cli/src/committer_runner.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please sync with @yoavGrs and put all "command" functions in the same `commands.rs` module.
"committer runner" is a python-side concept
</blockquote></details>

Done. These changes do not seem to be connected in a deep sense (they possibly conflict in the git sense, but nothing serious)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/235)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware, @TzahiTaub, and @yoavGrs)

___
*[`crates/committer_cli/src/committer_runner.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/committer/235#-O-ohRbm1ogBg1CG6Kj0:-O-pzRQoAfrWZsiQpuHy:b-sjnvbm) ([raw file](https://github.com/starkware-libs/committer/blob/d90da0ea8a37ca40ccee8ec54caf633c3975cc5d/crates/committer_cli/src/committer_runner.rs#L)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. These changes do not seem to be connected in a deep sense (they possibly conflict in the git sense, but nothing serious)
</blockquote></details>

there is still a module called "committer runner"
rename to `commands.rs` or something please

**Comment by aner-starkware** [comment]
*[`crates/committer_cli/src/committer_runner.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/committer/235#-O-ohRbm1ogBg1CG6Kj0:-O-q1dOI1Sv5eT0V9tGP:b1br7ey) ([raw file](https://github.com/starkware-libs/committer/blob/d90da0ea8a37ca40ccee8ec54caf633c3975cc5d/crates/committer_cli/src/committer_runner.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there is still a module called "committer runner"
rename to `commands.rs` or something please
</blockquote></details>

But it's not the command itself, it's just the committer main flow.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/235)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware, @TzahiTaub, and @yoavGrs)

___
*[`crates/committer_cli/src/committer_runner.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/committer/235#-O-ohRbm1ogBg1CG6Kj0:-O-q2ZRb7JKJXQ8pdAnT:bisd1eb) ([raw file](https://github.com/starkware-libs/committer/blob/d90da0ea8a37ca40ccee8ec54caf633c3975cc5d/crates/committer_cli/src/committer_runner.rs#L)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

But it's not the command itself, it's just the committer main flow.
</blockquote></details>

we will have two more "main flows" (there will be 3 commands in the CLI that are not python tests); they should be in the same module. they are simply the "main entry points".
the other two main flows are yoav's task

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/235)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware, @nimrod-starkware, @TzahiTaub, and @yoavGrs)

___
*[`crates/committer_cli/src/committer_runner.rs` line  at r1](https://reviewable.io/reviews/starkware-libs/committer/235#-O-ohRbm1ogBg1CG6Kj0:-O-q3WJmA2W4fsXs5aXS:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d90da0ea8a37ca40ccee8ec54caf633c3975cc5d/crates/committer_cli/src/committer_runner.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we will have two more "main flows" (there will be 3 commands in the CLI that are not python tests); they should be in the same module. they are simply the "main entry points".
the other two main flows are yoav's task
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/235#-:-O-q4Gz183625Jv0zc8-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware and @TzahiTaub)

**Pull request merged**
