### PR TITLE
build: log out a warning when encountering a trivial update

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/241)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/241)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 96 at r1](https://reviewable.io/reviews/starkware-libs/committer/241#-O04Lh18Dltyh2DefaOb:-O04Lh18Dltyh2DefaOc:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/41c48b44d114f4c843bb0a766792463be74b76b4/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L96)):*
> ```XML
>         subtrees: Vec<SubTree<'_>>,
>         storage: &impl Storage,
>         compare_modifided_leaves: bool,
> ```

typo



_Suggestion:_
```XML
modified
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/committer/241#-O04Lj5k0hQdzBdwzASu:-O04Lj5k0hQdzBdwzASv:bo4px2p) ([raw file](https://github.com/starkware-libs/committer/blob/41c48b44d114f4c843bb0a766792463be74b76b4/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L97)):*
> ```XML
>         storage: &impl Storage,
>         compare_modifided_leaves: bool,
>         leaf_modifications: &LeafModifications<L>,
> ```

these parameters are coupled: you only need leaf_modifications if compare_modified_leaves is true.
please define a config trait with a `compare_leaves_if_needed(&self) -> bool` function; implementing type should have the leaf_modifications as data (perhaps as a reference with a lifetime)



_Suggestion:_
```XML
        config: &impl OriginalSkeletonConfig,
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/committer/241#-O04MjtSDeFCiHuFgAz-:-O04MjtSDeFCiHuFgAz0:b-1yu30x) ([raw file](https://github.com/starkware-libs/committer/blob/41c48b44d114f4c843bb0a766792463be74b76b4/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L201)):*
> ```XML
>     #[case] expected_skeleton: OriginalSkeletonTreeImpl,
>     #[case] subtree_height: SubTreeHeight,
>     #[values(true, false)] compare_modified_leaves: bool,
> ```

please add a negative test (separate test, not another case) *if reading the logs is easy*, please sync with Aviv about this... non-blocking because this may be too difficult.

However, I would also like a test case in which leaves are indeed "incorrectly modified" and make sure we still pass, with both config options; is there already such a case?



_Code quote:_
```XML
#[values(true, false)] compare_modified_leaves: bool,
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/committer/241#-O04May67SXpYDH-RvVu:-O04May67SXpYDH-RvVv:byr4ffv) ([raw file](https://github.com/starkware-libs/committer/blob/41c48b44d114f4c843bb0a766792463be74b76b4/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L23)):*
> ```XML
>         leaf_modifications: &LeafModifications<L>,
>         root_hash: HashOutput,
>         compare_modified_leaves: bool,
> ```

see above



_Suggestion:_
```XML
config: &impl OriginalSkeletonConfig,
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/241)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/committer/241#-O04Lj5k0hQdzBdwzASu:-O07xRy9A2II7ouDT8Fx:bxi18i3) ([raw file](https://github.com/starkware-libs/committer/blob/41c48b44d114f4c843bb0a766792463be74b76b4/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L97)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these parameters are coupled: you only need leaf_modifications if compare_modified_leaves is true.
please define a config trait with a `compare_leaves_if_needed(&self) -> bool` function; implementing type should have the leaf_modifications as data (perhaps as a reference with a lifetime)
</blockquote></details>

what do you think of 'configuring' that with `Option<&LeafModifications<L>>`?
compare the previous leaves iff it's not none.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/committer/241#-O04MjtSDeFCiHuFgAz-:-O07y7np4riEtYszey8g:bnzmewf) ([raw file](https://github.com/starkware-libs/committer/blob/41c48b44d114f4c843bb0a766792463be74b76b4/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L201)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a negative test (separate test, not another case) *if reading the logs is easy*, please sync with Aviv about this... non-blocking because this may be too difficult.

However, I would also like a test case in which leaves are indeed "incorrectly modified" and make sure we still pass, with both config options; is there already such a case?
</blockquote></details>

I spoke with Aviv, he says it's impossible to do that in a reasonable way...
all cases of `test_create_tree` have one trivial modification. I ran locally with changing `warn!` to `println!` and saw the warnings, so I suppose it works

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/241)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/committer/241#-O04Lj5k0hQdzBdwzASu:-O087C875JG4F6UR6j9M:bllnfib) ([raw file](https://github.com/starkware-libs/committer/blob/41c48b44d114f4c843bb0a766792463be74b76b4/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L97)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

what do you think of 'configuring' that with `Option<&LeafModifications<L>>`?
compare the previous leaves iff it's not none.
</blockquote></details>

I prefer a trait object... it's not super clear from the arguments what the behavior is.
I think this function will eventually be "generic" (in the starknet-patricia crate) and I'd like the signature of the skeleton-loader function to allow more general configuration, if (a) we would want to fine-tune storage access parameters in the future and (b) if users of the patricia crate want to.

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/241)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 201 at r1](https://reviewable.io/reviews/starkware-libs/committer/241#-O04MjtSDeFCiHuFgAz-:-O087pAFA4YvfCWMfhVy:bb544qg) ([raw file](https://github.com/starkware-libs/committer/blob/41c48b44d114f4c843bb0a766792463be74b76b4/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L201)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

I spoke with Aviv, he says it's impossible to do that in a reasonable way...
all cases of `test_create_tree` have one trivial modification. I ran locally with changing `warn!` to `println!` and saw the warnings, so I suppose it works
</blockquote></details>

Aviv said he might found a good way to check the logs, I'll try to do that

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/241)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs` line 7 at r3](https://reviewable.io/reviews/starkware-libs/committer/241#-O09VWOq6hinV1loARzC:-O09VWOq6hinV1loARzD:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/c300af36fc6906cea2e890da146362678b4dc03d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L7)):*
> ```XML
> /// Configures the creation of an original skeleton tree.
> pub(crate) trait OriginalSkeletonTreeConfig<L: LeafData> {
>     /// Configures wether modified leaves should be compared to the previous leaves and log out a
> ```

typo



_Code quote:_
```XML
wether
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/committer/241#-O09WXi_B4pq2bnlVplL:-O09WXi_B4pq2bnlVplM:b-on5mpz) ([raw file](https://github.com/starkware-libs/committer/blob/c300af36fc6906cea2e890da146362678b4dc03d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L12)):*
> ```XML
> 
>     /// Returns the modifications in order to compare them.
>     fn get_modifications(&self) -> &LeafModifications<L>;
> ```

this should not be part of the config API 



_Code quote:_
```XML
    /// Returns the modifications in order to compare them.
    fn get_modifications(&self) -> &LeafModifications<L>;
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/241)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs` line 12 at r3](https://reviewable.io/reviews/starkware-libs/committer/241#-O09WXi_B4pq2bnlVplL:-O09ZLoiA_U5QSbFjg5s:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/c300af36fc6906cea2e890da146362678b4dc03d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this should not be part of the config API
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/241)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/committer/241#-O09o8_SAMyAzIxXtYF1:-O09o8_SAMyAzIxXtYF2:b-i0hjpa) ([raw file](https://github.com/starkware-libs/committer/blob/d3b3bfd78707da25bec6fe85fa14be158986ca12/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L21)):*
> ```XML
>     ) -> OriginalSkeletonTreeResult<bool>;
> }
> ```

lines below here can be greatly reduced if you implement a macro to auto-generate structs and implementations.
consider defining a single macro that accepts pairs (LEAF_TYPE, MODE) to generate everything;
or separate macros for different implementations. see what seems more maintainable

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/241)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs` line 21 at r4](https://reviewable.io/reviews/starkware-libs/committer/241#-O09o8_SAMyAzIxXtYF1:-O0CrP9r55ycqGFcJnOB:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d3b3bfd78707da25bec6fe85fa14be158986ca12/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs#L21)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

lines below here can be greatly reduced if you implement a macro to auto-generate structs and implementations.
consider defining a single macro that accepts pairs (LEAF_TYPE, MODE) to generate everything;
or separate macros for different implementations. see what seems more maintainable
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 97 at r1](https://reviewable.io/reviews/starkware-libs/committer/241#-O04Lj5k0hQdzBdwzASu:-O0CrRsTDnOqZgGXfs1-:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/41c48b44d114f4c843bb0a766792463be74b76b4/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L97)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I prefer a trait object... it's not super clear from the arguments what the behavior is.
I think this function will eventually be "generic" (in the starknet-patricia crate) and I'd like the signature of the skeleton-loader function to allow more general configuration, if (a) we would want to fine-tune storage access parameters in the future and (b) if users of the patricia crate want to.
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/committer/241#-O04May67SXpYDH-RvVu:-O0CrR_x6pl9fC0REYb_:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/41c48b44d114f4c843bb0a766792463be74b76b4/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L23)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/241)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 207 at r5](https://reviewable.io/reviews/starkware-libs/committer/241#-O0DD1Ld93wzsAdWbI4H:-O0DD1Ld93wzsAdWbI4I:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/bf889c438bc9b9400770d70b2b777ca5dd510393/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L207)):*
> ```XML
>     #[values(true, false)] compare_modified_leaves: bool,
> ) {
>     let leaf_modifications: HashMap<NodeIndex, StarknetStorageValue> = leaf_modifications
> ```





_Suggestion:_
```XML
LeafModifications<StarknetStorageValue>
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/241)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/241#-:-O0DeWUe8w_ldFZfB_Rg:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
