### PR TITLE
build: make fetch_nodes deserialize to filled node

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/239)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/239)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/committer/239#-O-ouIv6BNUsrF2QSOAY:-O-ouIv6BNUsrF2QSOAZ:b-i21g7w) ([raw file](https://github.com/starkware-libs/committer/blob/464a7c119b036f915a35e015074737bb2d1eea3d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L192)):*
> ```XML
>             });
>         }
>         let main_subtree = vec![SubTree {
> ```

move this back to the `fetch_nodes` call.
`main_subtree` should not be a vector



_Code quote:_
```XML
 vec![
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/committer/239#-O-oubtS5mJa38eqr3zY:-O-oubtS5mJa38eqr3zZ:b-bmu03h) ([raw file](https://github.com/starkware-libs/committer/blob/464a7c119b036f915a35e015074737bb2d1eea3d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L168)):*
> ```XML
>     create_binary_entry(25, 65),
>     create_binary_entry(26, 90),
>     create_binary_entry(26, 90),
> ```

this is duplicated, how is the test passing...?



_Code quote:_
```XML
    create_binary_entry(26, 90),
    create_binary_entry(26, 90),
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/committer/239#-O-ouvaD9rRCZlSqyVRX:-O-ouvaD9rRCZlSqyVRY:beu33jl) ([raw file](https://github.com/starkware-libs/committer/blob/464a7c119b036f915a35e015074737bb2d1eea3d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L229)):*
> ```XML
> pub(crate) fn create_compiled_class_leaf_entry(val: u128) -> (StorageKey, StorageValue) {
>     let leaf = CompiledClassHash(Felt::from(val));
>     (leaf.get_db_key(&leaf.0.to_bytes_be()), leaf.serialize())
> ```

can you have both `get_db_key()` and `get_db_key(&self)` define on the same type?
this should actually be `leaf.get_db_key()` if possible



_Code quote:_
```XML
leaf.get_db_key(&leaf.0.to_bytes_be()
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/committer/239#-O-ovDw9E-oXr2Ax6yJp:-O-ovDw9E-oXr2Ax6yJq:b-44wwy6) ([raw file](https://github.com/starkware-libs/committer/blob/464a7c119b036f915a35e015074737bb2d1eea3d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L59)):*
> ```XML
>         )?;
>         let classes_tree = Self::create_classes_trie(
>             &StateDiff::actual_classes_updates(&state_diff.class_hash_to_compiled_class_hash),
> ```

why is one a method, and the other an associated function? both should be methods



_Code quote:_
```XML
            &state_diff.actual_storage_updates(),
            current_contracts_trie_leaves,
            &storage,
        )?;
        let classes_tree = Self::create_classes_trie(
            &StateDiff::actual_classes_updates(&state_diff.class_hash_to_compiled_class_hash),
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/239)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 192 at r1](https://reviewable.io/reviews/starkware-libs/committer/239#-O-ouIv6BNUsrF2QSOAY:-O-pDadj3jQhbjMfUtRR:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/464a7c119b036f915a35e015074737bb2d1eea3d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L192)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move this back to the `fetch_nodes` call.
`main_subtree` should not be a vector
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 168 at r1](https://reviewable.io/reviews/starkware-libs/committer/239#-O-oubtS5mJa38eqr3zY:-O-pDdYm7gcfdy7wOrKX:b-gtow7d) ([raw file](https://github.com/starkware-libs/committer/blob/464a7c119b036f915a35e015074737bb2d1eea3d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L168)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this is duplicated, how is the test passing...?
</blockquote></details>

oops.
it passes because we don't check for duplicates when adding to the 'storage'.
removed the duplicate
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/committer/239#-O-ouvaD9rRCZlSqyVRX:-O-pENkO8xqWbno5t_gJ:b-ce7772) ([raw file](https://github.com/starkware-libs/committer/blob/464a7c119b036f915a35e015074737bb2d1eea3d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L229)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you have both `get_db_key()` and `get_db_key(&self)` define on the same type?
this should actually be `leaf.get_db_key()` if possible
</blockquote></details>

you expect that the signature of `DBObject::get_db_key` would be `fn get_db_key(&self) -> StorageKey`?
ATM it's `fn get_db_key(&self, suffix: &[u8]) -> StorageKey`
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 59 at r1](https://reviewable.io/reviews/starkware-libs/committer/239#-O-ovDw9E-oXr2Ax6yJp:-O-pF5ry40zluet8B-Z_:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/464a7c119b036f915a35e015074737bb2d1eea3d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is one a method, and the other an associated function? both should be methods
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/239#-:-O-pIPx4EXCSXmPU8FQD:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 229 at r1](https://reviewable.io/reviews/starkware-libs/committer/239#-O-ouvaD9rRCZlSqyVRX:-O-pIHe_8H9qo8KoOiKP:b-9n9td3) ([raw file](https://github.com/starkware-libs/committer/blob/464a7c119b036f915a35e015074737bb2d1eea3d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L229)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

you expect that the signature of `DBObject::get_db_key` would be `fn get_db_key(&self) -> StorageKey`?
ATM it's `fn get_db_key(&self, suffix: &[u8]) -> StorageKey`
</blockquote></details>

hmm... ok, out of scope. we can think about this later

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/239)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/239#-O-pIRZuEML1qWRv4kGU:-O-pIRZuEML1qWRv4kGV:b-hly2zx) (no related file):*
python side PR?

___

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/239)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/239#-O-pIRZuEML1qWRv4kGU:-O-pLyyq8O4owp_IpPs_:b-o9vdcb) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

python side PR?
</blockquote></details>

python side [PR](https://github.com/starkware-industries/starkware/pull/35249)

___

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/239)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/239)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/239#-O-pIRZuEML1qWRv4kGU:-O-pMLNd9_4jIKA67sZd:b-7wxo7b) (no related file):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

python side [PR](https://github.com/starkware-industries/starkware/pull/35249)
</blockquote></details>

i don't see a commit bump in that PR

___

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/239)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 394 at r4](https://reviewable.io/reviews/starkware-libs/committer/239#-O-q389o8_8Z3RLjaLVw:-O-q389o8_8Z3RLjaLVx:b354p86) ([raw file](https://github.com/starkware-libs/committer/blob/3de7eb3388f411e84fc5802b354ff0b6348f407d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L394)):*
> ```XML
> //         root_hash,
> //     );
> // }
> ```

what's this?



_Code quote:_
```XML
// #[tokio::test]
// async fn test_tree() {
//     let modifications = HashMap::from([(
//         NodeIndex::FIRST_LEAF + NodeIndex::ROOT,
//         SkeletonLeaf::NonZero,
//     )]);
//     let mut empty_original = OriginalSkeletonTreeImpl {
//         nodes: HashMap::new(),
//     };
//     let updated = UpdatedSkeletonTreeImpl::create(&mut empty_original, &modifications).unwrap();

//     let filled = FilledTreeImpl::create::<TreeHashFunctionImpl>(
//         updated,
//         HashMap::from([(
//             NodeIndex::FIRST_LEAF + NodeIndex::ROOT,
//             StarknetStorageValue(Felt::ONE),
//         )]),
//     )
//     .await
//     .unwrap();
//     let storage = MapStorage {
//         storage: filled.serialize(),
//     };
//     let root_hash = filled.get_root_hash();
//     println!("{}", storage.storage.len());
//     let _new_original = OriginalSkeletonTreeImpl::create(
//         &storage,
//         &HashMap::from([(
//             NodeIndex::FIRST_LEAF + NodeIndex::ROOT + NodeIndex::ROOT,
//             StarknetStorageValue(Felt::ONE),
//         )]),
//         root_hash,
//     );
// }
```
___
*[`crates/committer/src/storage/errors.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/committer/239#-O-q3BhwBRQY9xDXiXRM:-O-q3BhwBRQY9xDXiXRN:bv01xq0) ([raw file](https://github.com/starkware-libs/committer/blob/3de7eb3388f411e84fc5802b354ff0b6348f407d/crates/committer/src/storage/errors.rs#L12)):*
> ```XML
> pub enum StorageError {
>     #[error("The key {0:?} does not exist in storage.")]
>     MissingKey(NodeIndex),
> ```

`MissingKey` is a general error - some storage key is missing.
This should not have a NodeIndex as data - the key isn't always a node index.
If you want a more specific error add a new MissingNode variant



_Code quote:_
```XML
    #[error("The key {0:?} does not exist in storage.")]
    MissingKey(NodeIndex),
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/239)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/239#-O-pIRZuEML1qWRv4kGU:-O-pr7O36Plk7Ua3bJrp:b-r0ebyj) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

i don't see a commit bump in that PR
</blockquote></details>

now there is

___
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 394 at r4](https://reviewable.io/reviews/starkware-libs/committer/239#-O-q389o8_8Z3RLjaLVw:-O037-vWDSSd4g3In9m-:bxew7ng) ([raw file](https://github.com/starkware-libs/committer/blob/3de7eb3388f411e84fc5802b354ff0b6348f407d/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L394)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this?
</blockquote></details>

deleted that, it was for debugging.
___
*[`crates/committer/src/storage/errors.rs` line 12 at r4](https://reviewable.io/reviews/starkware-libs/committer/239#-O-q3BhwBRQY9xDXiXRM:-O0373KVBhTilkjzwt98:b-zc18sh) ([raw file](https://github.com/starkware-libs/committer/blob/3de7eb3388f411e84fc5802b354ff0b6348f407d/crates/committer/src/storage/errors.rs#L12)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`MissingKey` is a general error - some storage key is missing.
This should not have a NodeIndex as data - the key isn't always a node index.
If you want a more specific error add a new MissingNode variant
</blockquote></details>

reverted that

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/239)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/storage/errors.rs` line 8 at r6](https://reviewable.io/reviews/starkware-libs/committer/239#-O03HWSQ81OmzkocFJOz:-O03HWSQ81OmzkocFJP-:b-awmktz) ([raw file](https://github.com/starkware-libs/committer/blob/3a10bf7721274d9ba45ca1dd9e648a0b6f8e0158/crates/committer/src/storage/errors.rs#L8)):*
> ```XML
> use thiserror::Error;
> 
> use super::storage_trait::StorageKey;
> ```

don't use `super` in a non-test module



_Suggestion:_
```XML
use crate::storage::storage_trait::{StorageKey, StoragePrefix};

use serde_json;
use starknet_types_core::felt::FromStrError;
use thiserror::Error;
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/239)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/storage/errors.rs` line 8 at r6](https://reviewable.io/reviews/starkware-libs/committer/239#-O03HWSQ81OmzkocFJOz:-O03KQua4alZuivnI5wu:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3a10bf7721274d9ba45ca1dd9e648a0b6f8e0158/crates/committer/src/storage/errors.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't use `super` in a non-test module
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/239#-:-O03RRbl6yJli4Il1-w2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
