### PR TITLE
feat: push compiled binary to S3 on push to github

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/45)

### CODE REVIEW

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/45)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware, @dorimedini-starkware, @RoeiE-starkware, and @Yoni-Starkware)

___
*[`.github/workflows/ci.yml` line 91 at r2](https://reviewable.io/reviews/starkware-libs/committer/45#-NvevMtN9Aa3L7gnv8eF:-NvevMtN9Aa3L7gnv8eG:b-x8dubr) ([raw file](https://github.com/starkware-libs/committer/blob/f5d2b1a5ecf46d178c3659b25dddbb5287edba0e/.github/workflows/ci.yml#L91)):*
> ```YAML
>       - name: Get commit hash prefix
>         id: commit_prefix
>         run: echo "commit_prefix=$(echo ${{ github.event.pull_request.head.sha }} | cut -c 1-7)" >> $GITHUB_OUTPUT
> ```

Consider renaming the var to something different from the id, so that anyone who see the usage below (`steps.commit_prefix.outputs.commit_prefix`) will know which is which with ease.



_Suggestion:_
```YAML
"short_hash=
```
___
*[`.github/workflows/ci.yml` line 107 at r2](https://reviewable.io/reviews/starkware-libs/committer/45#-Nvbche37tEu2EPJa6SW:-NvesZ4K3MlzsAb6O4KI:b-r8dyx6) ([raw file](https://github.com/starkware-libs/committer/blob/f5d2b1a5ecf46d178c3659b25dddbb5287edba0e/.github/workflows/ci.yml#L107)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

path in bucket will be `<SHORT_HASH>/release/committer_cli`. WDYT @TzahiTaub ?
</blockquote></details>

SGTM. Two questions:
1. It would be nice to allow using any length of the commit hash (say from 7 chars and above) and get the right binary. We can trim a longer hash in the bazel script, so for that it is better to have the shortest "valid" hash in the bucket. See e.g., in the blockifier, they have different lengths ATM.
2. What will we do for tags? Will we use another copy for a "tag path" in the bucket, query git for the tag->hash mapping via bzael somehow, or won't allow python to point to a tag (I think we should)?

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/45)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alon-dotan-starkware, @RoeiE-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`.github/workflows/ci.yml` line 107 at r2](https://reviewable.io/reviews/starkware-libs/committer/45#-Nvbche37tEu2EPJa6SW:-Nvex7jK6xqg3MbUAltp:byfsc5n) ([raw file](https://github.com/starkware-libs/committer/blob/f5d2b1a5ecf46d178c3659b25dddbb5287edba0e/.github/workflows/ci.yml#L107)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

SGTM. Two questions:
1. It would be nice to allow using any length of the commit hash (say from 7 chars and above) and get the right binary. We can trim a longer hash in the bazel script, so for that it is better to have the shortest "valid" hash in the bucket. See e.g., in the blockifier, they have different lengths ATM.
2. What will we do for tags? Will we use another copy for a "tag path" in the bucket, query git for the tag->hash mapping via bzael somehow, or won't allow python to point to a tag (I think we should)?
</blockquote></details>

1. on it, thanks
2. good point... this seems to require more work. we can copy the gcp-push step to an on-tag-push job, but we can do that later (we are a while away from tagging)

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/45#-:-NveyLqJ2ONExF0NS0yC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware, @RoeiE-starkware, and @Yoni-Starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/45)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alon-dotan-starkware, @RoeiE-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`.github/workflows/ci.yml` line 100 at r4](https://reviewable.io/reviews/starkware-libs/committer/45#-NvfPNgv7Z6K3PGAvSaW:-NvfPNgv7Z6K3PGAvSaX:blgxn44) ([raw file](https://github.com/starkware-libs/committer/blob/23e78571cb9df79eeb7d40c03b156159206e28f0/.github/workflows/ci.yml#L100)):*
> ```YAML
>         with:
>           credentials_json: ${{ secrets.COMMITER_PRODUCTS_EXT_WRITER_JSON }}
>           service_account: "committttter-products-ext-writer@starkware-dev.iam.gserviceaccount.com"
> ```

@RoeiE-starkware I mangled the service account to check if it's needed; and `gcs-push` phase [succeeded](https://github.com/starkware-libs/committer/actions/runs/8719656002/job/23919466945) (also see the built committer CLI in the bucket).
I am removing this line



_Code quote:_
```YAML
committttter
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/45)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alon-dotan-starkware, @RoeiE-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`.github/workflows/ci.yml` line 99 at r5](https://reviewable.io/reviews/starkware-libs/committer/45#-NvfSEZ8B-m2Ul_Zb1Ud:-NvfSEZ8B-m2Ul_Zb1Ue:b-m3ojo3) ([raw file](https://github.com/starkware-libs/committer/blob/6c7199a8afa31619fced2d475759213824e78b5f/.github/workflows/ci.yml#L99)):*
> ```YAML
>         uses: "google-github-actions/auth@v2"
>         with:
>           credentials_json: "{\"a\": \"b\"}"
> ```

currently doing negative testing... will be 
```
${{ secrets.COMMITER_PRODUCTS_EXT_WRITER_JSON }}
```



_Code quote:_
```YAML
credentials_json: "{\"a\": \"b\"}"
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/45)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @alon-dotan-starkware, @RoeiE-starkware, @TzahiTaub, and @Yoni-Starkware)

___
*[`.github/workflows/ci.yml` line 99 at r5](https://reviewable.io/reviews/starkware-libs/committer/45#-NvfSEZ8B-m2Ul_Zb1Ud:-Nvg8nxE31oPstEXuoNK:btlunuv) ([raw file](https://github.com/starkware-libs/committer/blob/6c7199a8afa31619fced2d475759213824e78b5f/.github/workflows/ci.yml#L99)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

currently doing negative testing... will be 
```
${{ secrets.COMMITER_PRODUCTS_EXT_WRITER_JSON }}
```
</blockquote></details>

done ([negative test](https://github.com/starkware-libs/committer/actions/runs/8722383699/job/23928130508))

**Review by RoeiE-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/45#-:-NvhKZWi-hprtvB0H8UZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @alon-dotan-starkware and @Yoni-Starkware)

**Pull request merged**
