### PR TITLE
chore: switched to tracing crate

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/302)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
What do the three percentages represent?
Python side:
https://reviewable.io/reviews/starkware-industries/starkware/35564

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/302#-:-O2-vR8nA_bLB0mFYBWa:bkunbi2)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/302)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/committer_cli/src/tracing_utils.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/committer/302#-O2-zuW45AODm3VGQ_2H:-O2-zuW45AODm3VGQ_2I:b1k2w7v) ([raw file](https://github.com/starkware-libs/committer/blob/ff1d8cabcd3d26bf215b6d381c9d453cf8bb6b4d/crates/committer_cli/src/tracing_utils.rs#L10)):*
> ```XML
>         .with_line_number(true)
>         .init();
> }
> ```

Papyrus tracing configuration for reference (Mempool is the same, I think):
https://github.com/starkware-libs/papyrus/blob/6e59018353cc66e5f1c299481be2354c981a58ec/crates/papyrus_node/src/main.rs#L402-L410

should I copy paste?



_Code quote:_
```XML
pub fn configure_tracing() {
    fmt()
        .with_ansi(false)
        .with_target(false)
        .with_file(true)
        .with_line_number(true)
        .init();
}
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/302)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/committer_cli/src/tracing_utils.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/committer/302#-O2-zuW45AODm3VGQ_2H:-O200yp-D_swQ4eroQJa:b-rywctz) ([raw file](https://github.com/starkware-libs/committer/blob/ff1d8cabcd3d26bf215b6d381c9d453cf8bb6b4d/crates/committer_cli/src/tracing_utils.rs#L10)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Papyrus tracing configuration for reference (Mempool is the same, I think):
https://github.com/starkware-libs/papyrus/blob/6e59018353cc66e5f1c299481be2354c981a58ec/crates/papyrus_node/src/main.rs#L402-L410

should I copy paste?
</blockquote></details>

(this does not change where error logs are printed to)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/302)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer_cli/src/main.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/302#-O205vC37WnpiBI2bfaM:-O205vC37WnpiBI2bfaN:b-f43hzp) ([raw file](https://github.com/starkware-libs/committer/blob/ff1d8cabcd3d26bf215b6d381c9d453cf8bb6b4d/crates/committer_cli/src/main.rs#L61)):*
> ```XML
> async fn main() {
>     // Initialize the logger
>     configure_tracing();
> ```

how do you set the log level here?
you are conflicting with [this](https://reviewable.io/reviews/starkware-libs/committer/313)



_Code quote:_
```XML
configure_tracing();
```
___
*[`crates/committer_cli/src/tracing_utils.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/committer/302#-O2-zuW45AODm3VGQ_2H:-O20650l1EVU6drm3m1Y:b-yplpib) ([raw file](https://github.com/starkware-libs/committer/blob/ff1d8cabcd3d26bf215b6d381c9d453cf8bb6b4d/crates/committer_cli/src/tracing_utils.rs#L10)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

(this does not change where error logs are printed to)
</blockquote></details>

please add a TODO to move this - and other tracing instantiations in the monorepo - to a common location

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/302)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/src/main.rs` line 61 at r1](https://reviewable.io/reviews/starkware-libs/committer/302#-O205vC37WnpiBI2bfaM:-O3Np1Lp7mXYdZDSH5gJ:bfppyq1) ([raw file](https://github.com/starkware-libs/committer/blob/ff1d8cabcd3d26bf215b6d381c9d453cf8bb6b4d/crates/committer_cli/src/main.rs#L61)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how do you set the log level here?
you are conflicting with [this](https://reviewable.io/reviews/starkware-libs/committer/313)
</blockquote></details>

Done in sequencer PR
https://reviewable.io/reviews/starkware-libs/sequencer/291
___
*[`crates/committer_cli/src/tracing_utils.rs` line 10 at r1](https://reviewable.io/reviews/starkware-libs/committer/302#-O2-zuW45AODm3VGQ_2H:-O3MpVxo82Z3Uttuc-9Z:bfppyq1) ([raw file](https://github.com/starkware-libs/committer/blob/ff1d8cabcd3d26bf215b6d381c9d453cf8bb6b4d/crates/committer_cli/src/tracing_utils.rs#L10)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a TODO to move this - and other tracing instantiations in the monorepo - to a common location
</blockquote></details>

Done in sequencer PR
https://reviewable.io/reviews/starkware-libs/sequencer/291

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/302)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/302#-O3Wf4kw3AsLwwRSIX7e:-O3Wf4kw3AsLwwRSIX7f:b-1lk591) (no related file):*
please close this PR

___

**Pull request closed without merging**
