### PR TITLE
chore: add profile in toml for flamegraph

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/304)

### CODE REVIEW

**Comment by aner-starkware** [comment]
I suppose that this regression is only in benchmarking, and does not affect the runtime of the binary code, but:
1. Perhaps this is also not good, as we want to benchmark the real runtime
2. I don't know how to make sure that the actual runtime isn't affected by this change

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/304)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

___
*[`Cargo.toml` line 51 at r1](https://reviewable.io/reviews/starkware-libs/committer/304#-O1lkBS74Gf_A_nCLSQa:-O1lkBS74Gf_A_nCLSQb:b6kn06v) ([raw file](https://github.com/starkware-libs/committer/blob/609280dbc9b1de2cfadedb69c2ecda87421963fa/Cargo.toml#L51)):*
> ```TOML
> 
> [profile.bench]
> debug = true
> ```

this means benchmarking times will be slower, right?
consider a separate CI job that compiles without the `--release` flag



_Code quote:_
```TOML
[profile.bench]
debug = true
```

**Comment by aner-starkware** [comment]
*[`Cargo.toml` line 51 at r1](https://reviewable.io/reviews/starkware-libs/committer/304#-O1lkBS74Gf_A_nCLSQa:-O1lrCYr9Dik0vrObWK3:b-fmv17t) ([raw file](https://github.com/starkware-libs/committer/blob/609280dbc9b1de2cfadedb69c2ecda87421963fa/Cargo.toml#L51)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this means benchmarking times will be slower, right?
consider a separate CI job that compiles without the `--release` flag
</blockquote></details>

OK, I'll look into it

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/304)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`Cargo.toml` line 51 at r1](https://reviewable.io/reviews/starkware-libs/committer/304#-O1lkBS74Gf_A_nCLSQa:-O1pFd9U697zFihjETUU:b-hcjqpv) ([raw file](https://github.com/starkware-libs/committer/blob/609280dbc9b1de2cfadedb69c2ecda87421963fa/Cargo.toml#L51)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

OK, I'll look into it
</blockquote></details>

for a temporary solution it's fine now,
and one could argue we only care about the relative diff in a benchmark, not the flat time, so this may be unneeded... unblocking

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/304#-:-O1pFoDu04R106vho8mY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request closed without merging**
