### PR TITLE
refactor: implement serializable trait for filled node from exists me…

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
Refactoring: The PR involves refactoring existing code to make it compatible with the Serializable trait

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/59)

### CODE REVIEW

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/59)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/committer/59#-Nw-x4Vi-oLN8a1JmXY_:-Nw-x4Vi-oLN8a1JmXYa:bjib4f5) ([raw file](https://github.com/starkware-libs/committer/blob/1e9eb88ad712dfad37200ab7f2a9022bf91c01a7/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L32)):*
> ```XML
> pub(crate) const INNER_NODE_PREFIX: &[u8; 13] = b"patricia_node";
> 
> /// Enum to describe the serialized node.
> ```

I think that it's not needed anymore Since all types hold Vec<u8>
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 53 at r1](https://reviewable.io/reviews/starkware-libs/committer/59#-Nw-xSPC4zAQXfiLEbqe:-Nw-xSPC4zAQXfiLEbqf:byvry0m) ([raw file](https://github.com/starkware-libs/committer/blob/1e9eb88ad712dfad37200ab7f2a9022bf91c01a7/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L53)):*
> ```XML
> }
> 
> pub(crate) type FilledTreeResult<T> = Result<T, FilledTreeError>;
> ```

also not needed

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/59)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/committer/59#-Nw0-fJd4nR1gh0myNBo:-Nw0-fJd4nR1gh0myNBp:b-lswwo9) ([raw file](https://github.com/starkware-libs/committer/blob/fccc16720c0e6c7bb695eaff0eff6340c438aae1/crates/committer/src/patricia_merkle_tree/errors.rs#L8)):*
> ```XML
> use crate::patricia_merkle_tree::filled_tree::node::FilledNode;
> 
> use super::types::LeafDataTrait;
> ```

please change to `use crate::patricia_merkle_tree::types::LeafDataTrait;`
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/committer/59#-Nw00uUV9lOzdXkyEN8c:-Nw00uUV9lOzdXkyEN8d:bfxyi3f) ([raw file](https://github.com/starkware-libs/committer/blob/fccc16720c0e6c7bb695eaff0eff6340c438aae1/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L45)):*
> ```XML
>     /// - For leaf nodes: use leaf.serialize() method.
>     #[allow(dead_code)]
>     fn serialize(&self) -> Result<StorageValue, SerializationError> {
> ```

consider defining
`type FilledNodeSerializationResult = <Result<StorageValue, SerializationError>;`
and change the return value to that type.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/committer/59#-Nw01SWn4CG7ho7_sT_V:-Nw01SWn4CG7ho7_sT_W:bwdhman) ([raw file](https://github.com/starkware-libs/committer/blob/fccc16720c0e6c7bb695eaff0eff6340c438aae1/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L99)):*
> ```XML
>     /// Deserializes non-leaf nodes; if a serialized leaf node is given, the hash
>     /// is used but the data is ignored.
>     fn deserialize(key: &StorageKey, value: &StorageValue) -> Result<Self, SerializationError> {
> ```

consider defining
`type FilledNodeDeserializtionResult = <Result<FilledNode, SerializationError>;`
and change the return value to that type.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/committer/59#-Nw01n1c5PE7GSEcyBKE:-Nw01n1c5PE7GSEcyBKF:b-880ins) ([raw file](https://github.com/starkware-libs/committer/blob/fccc16720c0e6c7bb695eaff0eff6340c438aae1/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L99)):*
> ```XML
>     /// Deserializes non-leaf nodes; if a serialized leaf node is given, the hash
>     /// is used but the data is ignored.
>     fn deserialize(key: &StorageKey, value: &StorageValue) -> Result<Self, SerializationError> {
> ```

if you decide to divide (and I think you did) the `Serializable` trait into two different traits (`Serializable` , `Deserializable`), please change the return type to 
`Result<Self, DeserializationError>`

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/59)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/errors.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/committer/59#-Nw0-fJd4nR1gh0myNBo:-NwDmCLZ6OJD5iiUVwln:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/fccc16720c0e6c7bb695eaff0eff6340c438aae1/crates/committer/src/patricia_merkle_tree/errors.rs#L8)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

please change to `use crate::patricia_merkle_tree::types::LeafDataTrait;`
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 45 at r1](https://reviewable.io/reviews/starkware-libs/committer/59#-Nw00uUV9lOzdXkyEN8c:-NwDqy--54KkRJWZiRQP:bxete3e) ([raw file](https://github.com/starkware-libs/committer/blob/fccc16720c0e6c7bb695eaff0eff6340c438aae1/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L45)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

consider defining
`type FilledNodeSerializationResult = <Result<StorageValue, SerializationError>;`
and change the return value to that type.
</blockquote></details>

I defined it in node_serde instead of the trait to avoid restricting the trait's return type.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/committer/59#-Nw01SWn4CG7ho7_sT_V:-NwDpR6JB2JWO60h_U45:bxete3e) ([raw file](https://github.com/starkware-libs/committer/blob/fccc16720c0e6c7bb695eaff0eff6340c438aae1/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L99)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

consider defining
`type FilledNodeDeserializtionResult = <Result<FilledNode, SerializationError>;`
and change the return value to that type.
</blockquote></details>

I defined it in node_serde instead of the trait to avoid restricting the trait's return type.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 99 at r1](https://reviewable.io/reviews/starkware-libs/committer/59#-Nw01n1c5PE7GSEcyBKE:-NwDpwINDdEM9HuPWzHa:b-k7uc1x) ([raw file](https://github.com/starkware-libs/committer/blob/fccc16720c0e6c7bb695eaff0eff6340c438aae1/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L99)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

if you decide to divide (and I think you did) the `Serializable` trait into two different traits (`Serializable` , `Deserializable`), please change the return type to 
`Result<Self, DeserializationError>`
</blockquote></details>

I'll be splitting it in a later pull request and I'll make the necessary changes there.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/59)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/committer/59#-NwE2YteEkbRXdWLGu9E:-NwE2YteEkbRXdWLGu9F:b-or43jy) ([raw file](https://github.com/starkware-libs/committer/blob/ae793e5fed5944811e403cae8d24bfb2ddafb6e8/crates/committer/src/patricia_merkle_tree/filled_tree/node.rs#L79)):*
> ```XML
>     /// - For compiled class hashes or state tree tuples: creates a  json string
>     ///   describing the leaf and cast it into a byte vector.
>     pub(crate) fn serialize(&self) -> Result<StorageValue, SerializationError> {
> ```

you will be conflicting with [this](https://reviewable.io/reviews/starkware-libs/committer/64), please sync



_Code quote:_
```XML
pub(crate) fn serialize(&self) -> Result<StorageValue, SerializationError> {
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/committer/59#-NwE2r4x334TpidM7xjy:-NwE2r4y1xRx2Ee1dy_f:b-3614mg) ([raw file](https://github.com/starkware-libs/committer/blob/ae793e5fed5944811e403cae8d24bfb2ddafb6e8/crates/committer/src/patricia_merkle_tree/filled_tree/node.rs#L108)):*
> ```XML
>     pub(crate) fn suffix(&self) -> [u8; SERIALIZE_HASH_BYTES] {
>         self.hash.0.as_bytes()
>     }
> ```

why did you move this from node_serde.rs?



_Code quote:_
```XML
impl FilledNode<LeafData> {
    /// Returns the suffix of the filled node, represented by its hash as a byte array.
    #[allow(dead_code)]
    pub(crate) fn suffix(&self) -> [u8; SERIALIZE_HASH_BYTES] {
        self.hash.0.as_bytes()
    }
```
___
*[`crates/committer/src/storage/errors.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/committer/59#-NwE32j2-GjlsokVPpx8:-NwE32j2-GjlsokVPpx9:b-t6lynx) ([raw file](https://github.com/starkware-libs/committer/blob/ae793e5fed5944811e403cae8d24bfb2ddafb6e8/crates/committer/src/storage/errors.rs#L16)):*
> ```XML
> pub(crate) enum SerializationError {
>     #[error("Failed to deserialize the storage value")]
>     DeserializeError,
> ```

maybe add the value as data here...?



_Suggestion:_
```XML
    #[error("Failed to deserialize the storage value: {0}")]
    DeserializeError(StorageValue),
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/59)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/storage/errors.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/committer/59#-NwE32j2-GjlsokVPpx8:-NwENI6j7eJcYCzrw5zz:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/ae793e5fed5944811e403cae8d24bfb2ddafb6e8/crates/committer/src/storage/errors.rs#L16)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe add the value as data here...?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node.rs` line 79 at r2](https://reviewable.io/reviews/starkware-libs/committer/59#-NwE2YteEkbRXdWLGu9E:-NwEBHpF48FdXWHLadEE:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/ae793e5fed5944811e403cae8d24bfb2ddafb6e8/crates/committer/src/patricia_merkle_tree/filled_tree/node.rs#L79)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you will be conflicting with [this](https://reviewable.io/reviews/starkware-libs/committer/64), please sync
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node.rs` line 108 at r2](https://reviewable.io/reviews/starkware-libs/committer/59#-NwE2r4x334TpidM7xjy:-NwEL1H120c80ekpJ5PY:b-u5dwkd) ([raw file](https://github.com/starkware-libs/committer/blob/ae793e5fed5944811e403cae8d24bfb2ddafb6e8/crates/committer/src/patricia_merkle_tree/filled_tree/node.rs#L108)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why did you move this from node_serde.rs?
</blockquote></details>

Thanks, I returned it

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/59#-:-NwEgtqF2FUzEUEPSI9n:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs` line 25 at r3](https://reviewable.io/reviews/starkware-libs/committer/59#-NwEgl6V1QGc_GAzao_b:-NwEgl6V1QGc_GAzao_c:b-4pjgkn) ([raw file](https://github.com/starkware-libs/committer/blob/50ed64084034e060b0a665d26de13d6de0d81085/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs#L25)):*
> ```XML
> use std::collections::HashMap;
> #[cfg(test)]
> #[path = "original_skeleton_calc_test.rs"]
> ```

reinstate the newline



_Suggestion:_
```XML
use bisection::{bisect_left, bisect_right};
use std::collections::HashMap;

#[cfg(test)]
#[path = "original_skeleton_calc_test.rs"]
```

**Pull request merged**
