### PR TITLE
refactor: compare modified leaves configuration from python

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)

### CODE REVIEW

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/block_committer/input.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/committer/269#-O0syogH9tVdHxrPUV1e:-O0syogH9tVdHxrPUV1f:b2nhdkj) ([raw file](https://github.com/starkware-libs/committer/blob/d91b5240d43874a2c76da4687870c071dc9c7621/crates/committer/src/block_committer/input.rs#L30)):*
> ```XML
> 
> #[derive(Debug, Eq, PartialEq)]
> pub struct TrivialUpdatesConfig(pub(crate) bool);
> ```

Doc



_Code quote:_
```XML
pub struct TrivialUpdatesConfig(pub(crate) bool);
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/block_committer/input.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/committer/269#-O0syogH9tVdHxrPUV1e:-O0t1alE2StftnU1ZL70:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d91b5240d43874a2c76da4687870c071dc9c7621/crates/committer/src/block_committer/input.rs#L30)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Doc
</blockquote></details>

Done.

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/block_committer/input.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/committer/269#-O0syogH9tVdHxrPUV1e:-O0t2RbR-0qEUusP4Kpx:b-pcfph8) ([raw file](https://github.com/starkware-libs/committer/blob/d91b5240d43874a2c76da4687870c071dc9c7621/crates/committer/src/block_committer/input.rs#L30)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please add that this implies the input storage should contain the original data for the modified leaves.

**Review by TzahiTaub — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/block_committer/input.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/committer/269#-O0syogH9tVdHxrPUV1e:-O0t2opG05XzykUhQJbl:bfb01nj) ([raw file](https://github.com/starkware-libs/committer/blob/d91b5240d43874a2c76da4687870c071dc9c7621/crates/committer/src/block_committer/input.rs#L30)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Please add that this implies the input storage should contain the original data for the modified leaves.
</blockquote></details>

And it is not required otherwise.

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/block_committer/input.rs` line 30 at r1](https://reviewable.io/reviews/starkware-libs/committer/269#-O0syogH9tVdHxrPUV1e:-O0t3NlJEHAUk56sK9Bt:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d91b5240d43874a2c76da4687870c071dc9c7621/crates/committer/src/block_committer/input.rs#L30)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

And it is not required otherwise.
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/block_committer/input.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/committer/269#-O0tDJYw8Ad7J66bKmu7:-O0tDJYw8Ad7J66bKmu8:b-634nbs) ([raw file](https://github.com/starkware-libs/committer/blob/63b834a3b3c917607799c86bca1d52c8d7a69463/crates/committer/src/block_committer/input.rs#L48)):*
> ```XML
>     pub contracts_trie_root_hash: HashOutput,
>     pub classes_trie_root_hash: HashOutput,
>     pub trivial_updates_config: TrivialUpdatesConfig,
> ```

didn't you have a config *trait*?
this is part of public API, I prefer to remain generic here;
the config object should expose a `warn_on_trivial_updates() -> bool`  method.
actual boolean parsing etc. should be in the CLI crate.

As for the implementing struct, it can just have a boolean field, no need to wrap the boolean in a `TrivialUpdatesConfig` type.

Am I missing something?



_Code quote:_
```XML
pub trivial_updates_config: TrivialUpdatesConfig,
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/block_committer/input.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/committer/269#-O0tDJYw8Ad7J66bKmu7:-O0wJmtY3ltB_xLxJLYC:b-1ncv6n) ([raw file](https://github.com/starkware-libs/committer/blob/63b834a3b3c917607799c86bca1d52c8d7a69463/crates/committer/src/block_committer/input.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

didn't you have a config *trait*?
this is part of public API, I prefer to remain generic here;
the config object should expose a `warn_on_trivial_updates() -> bool`  method.
actual boolean parsing etc. should be in the CLI crate.

As for the implementing struct, it can just have a boolean field, no need to wrap the boolean in a `TrivialUpdatesConfig` type.

Am I missing something?
</blockquote></details>

The config trait we already have is created per tree for each tree separately.
The config remains part of a single tree API when calling `OriginalSkeletonTree::create`...

Do you mean to define another config trait that will have the method `warn_on_trivial_updates() -> bool` inside the CLI crate and that `Input` will have an instance of some struct the implements that trait?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/block_committer/input.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/committer/269#-O0tDJYw8Ad7J66bKmu7:-O0wUys103ge0I7h8kon:bq3sfq0) ([raw file](https://github.com/starkware-libs/committer/blob/63b834a3b3c917607799c86bca1d52c8d7a69463/crates/committer/src/block_committer/input.rs#L48)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

The config trait we already have is created per tree for each tree separately.
The config remains part of a single tree API when calling `OriginalSkeletonTree::create`...

Do you mean to define another config trait that will have the method `warn_on_trivial_updates() -> bool` inside the CLI crate and that `Input` will have an instance of some struct the implements that trait?
</blockquote></details>

what I mean is: this `Input` struct is part of the general API, right? not in the CLI crate? so it should get a config object, instead of boolean flag(s).
In the future there may be more configurable options, I want them all in a struct

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/block_committer/input.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/committer/269#-O0tDJYw8Ad7J66bKmu7:-O0wXUoG-TcpI9S7_5fI:b12sez1) ([raw file](https://github.com/starkware-libs/committer/blob/63b834a3b3c917607799c86bca1d52c8d7a69463/crates/committer/src/block_committer/input.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what I mean is: this `Input` struct is part of the general API, right? not in the CLI crate? so it should get a config object, instead of boolean flag(s).
In the future there may be more configurable options, I want them all in a struct
</blockquote></details>

Ok, I think I understand...
Do you suggest something like that?
```
pub struct Input {
    pub storage: HashMap<StorageKey, StorageValue>,
    /// All relevant information for the state diff commitment.
    pub state_diff: StateDiff,
    pub contracts_trie_root_hash: HashOutput,
    pub classes_trie_root_hash: HashOutput,
    pub config: Config,
}

pub struct Config {
warn_on_trivial_updates: bool
... other configurations will be added here in the future
}
impl Config {
fn warn_on_trivial_updates(&self) -> bool {
self.warn_on_trivial_updates
}
... more methods will be added here for additional configurations
}

```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/block_committer/input.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/committer/269#-O0tDJYw8Ad7J66bKmu7:-O0wh0XGEArrpDx968ix:b-pwn8zo) ([raw file](https://github.com/starkware-libs/committer/blob/63b834a3b3c917607799c86bca1d52c8d7a69463/crates/committer/src/block_committer/input.rs#L48)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Ok, I think I understand...
Do you suggest something like that?
```
pub struct Input {
    pub storage: HashMap<StorageKey, StorageValue>,
    /// All relevant information for the state diff commitment.
    pub state_diff: StateDiff,
    pub contracts_trie_root_hash: HashOutput,
    pub classes_trie_root_hash: HashOutput,
    pub config: Config,
}

pub struct Config {
warn_on_trivial_updates: bool
... other configurations will be added here in the future
}
impl Config {
fn warn_on_trivial_updates(&self) -> bool {
self.warn_on_trivial_updates
}
... more methods will be added here for additional configurations
}

```
</blockquote></details>

almost: split `ConfigTrait` and `Config`.
the `Input` should contain an `impl ConfigTrait` object.
Reason: the starknet forest construction may need extra configuration options that the generic patricia flow does not need; so we may decide to create a struct with more configs (i.e. for forest computation) and implement the ConfigTrait for it.

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/block_committer/input.rs` line 48 at r3](https://reviewable.io/reviews/starkware-libs/committer/269#-O0tDJYw8Ad7J66bKmu7:-O0wkAWp4it5ZTc6jyX2:b-ls0vje) ([raw file](https://github.com/starkware-libs/committer/blob/63b834a3b3c917607799c86bca1d52c8d7a69463/crates/committer/src/block_committer/input.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

almost: split `ConfigTrait` and `Config`.
the `Input` should contain an `impl ConfigTrait` object.
Reason: the starknet forest construction may need extra configuration options that the generic patricia flow does not need; so we may decide to create a struct with more configs (i.e. for forest computation) and implement the ConfigTrait for it.
</blockquote></details>

A struct can't contain an `impl` object.
`impl Trait is not allowed in field types`

Changed the `input` struct to be generic in the config type...

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: all files reviewed, 6 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/block_committer/commit.rs` line 23 at r4](https://reviewable.io/reviews/starkware-libs/committer/269#-O0women3OERTIKh7GCR:-O0women3OERTIKh7GCS:bl0m1aq) ([raw file](https://github.com/starkware-libs/committer/blob/3b9df9c24bf05344693b9724a3eab4455b231e6a/crates/committer/src/block_committer/commit.rs#L23)):*
> ```XML
> use crate::storage::map_storage::MapStorage;
> 
> use super::input::Config;
> ```

no `super` outside of test modules



_Suggestion:_
```XML
crate::block_committer::input::Config;
```
___
*[`crates/committer/src/block_committer/commit.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/committer/269#-O0wq1ro3USSr9ydRaWW:-O0wq1ro3USSr9ydRaWX:b-ly0hu2) ([raw file](https://github.com/starkware-libs/committer/blob/3b9df9c24bf05344693b9724a3eab4455b231e6a/crates/committer/src/block_committer/commit.rs#L34)):*
> ```XML
>             input.classes_trie_root_hash,
>             &input.state_diff,
>             input.config.warn_on_trivial_modifications(),
> ```

see below (don't pass the boolean around, pass a config object reference around)



_Suggestion:_
```XML
input.config,
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 0 at r4](https://reviewable.io/reviews/starkware-libs/committer/269#-O0wpM7O3QZ2Rkcux1rG:-O0wpM7O3QZ2Rkcux1rH:b-oi4np5) ([raw file](https://github.com/starkware-libs/committer/blob/3b9df9c24bf05344693b9724a3eab4455b231e6a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L0)):*
any function that accepts a boolean `warn_on..` parameter should instead accept an `impl Config` object - no need to ever have explicit access to this boolean, the only place this boolean should be accessed (via it's getter method on the trait) is when you actually check it to read leaves / compare leaves or not
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 243 at r4](https://reviewable.io/reviews/starkware-libs/committer/269#-O0wpl0vEoBmLdZXF_kF:-O0wpl0vEoBmLdZXF_kG:byr4ffv) ([raw file](https://github.com/starkware-libs/committer/blob/3b9df9c24bf05344693b9724a3eab4455b231e6a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L243)):*
> ```XML
>         input.classes_trie_root_hash,
>         &input.state_diff,
>         false,
> ```

see above



_Suggestion:_
```XML
input.config,
```
___
*[`crates/committer_cli/src/parse_input/cast.rs` line 13 at r4](https://reviewable.io/reviews/starkware-libs/committer/269#-O0wprzTB5T3C_p2Fyis:-O0wprzTB5T3C_p2Fyit:bgqx5u5) ([raw file](https://github.com/starkware-libs/committer/blob/3b9df9c24bf05344693b9724a3eab4455b231e6a/crates/committer_cli/src/parse_input/cast.rs#L13)):*
> ```XML
> use std::collections::HashMap;
> 
> impl TryFrom<RawInput> for Input<ConfigImpl> {
> ```

consider defining `type InputImpl = Input<ConfigImpl>` to reduce boilerplate (non-blocking)



_Code quote:_
```XML
Input<ConfigImpl>
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/block_committer/commit.rs` line 23 at r4](https://reviewable.io/reviews/starkware-libs/committer/269#-O0women3OERTIKh7GCR:-O0wrKNPED-5lQYUSOTJ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3b9df9c24bf05344693b9724a3eab4455b231e6a/crates/committer/src/block_committer/commit.rs#L23)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no `super` outside of test modules
</blockquote></details>

Done.
___
*[`crates/committer/src/block_committer/commit.rs` line 34 at r4](https://reviewable.io/reviews/starkware-libs/committer/269#-O0wq1ro3USSr9ydRaWW:-O0wsFZj7A4dnydm7_eU:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3b9df9c24bf05344693b9724a3eab4455b231e6a/crates/committer/src/block_committer/commit.rs#L34)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see below (don't pass the boolean around, pass a config object reference around)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line  at r4](https://reviewable.io/reviews/starkware-libs/committer/269#-O0wpM7O3QZ2Rkcux1rG:-O0wsDoYCrnYzsJ2UNIs:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3b9df9c24bf05344693b9724a3eab4455b231e6a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

any function that accepts a boolean `warn_on..` parameter should instead accept an `impl Config` object - no need to ever have explicit access to this boolean, the only place this boolean should be accessed (via it's getter method on the trait) is when you actually check it to read leaves / compare leaves or not
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 243 at r4](https://reviewable.io/reviews/starkware-libs/committer/269#-O0wpl0vEoBmLdZXF_kF:-O0wsDTg2nYvmvs15c_f:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/3b9df9c24bf05344693b9724a3eab4455b231e6a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L243)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/parse_input/cast.rs` line 13 at r4](https://reviewable.io/reviews/starkware-libs/committer/269#-O0wprzTB5T3C_p2Fyis:-O0wtLb2-u79jOtmrlJE:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/3b9df9c24bf05344693b9724a3eab4455b231e6a/crates/committer_cli/src/parse_input/cast.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

consider defining `type InputImpl = Input<ConfigImpl>` to reduce boilerplate (non-blocking)
</blockquote></details>

Done

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269#-:-O0x-iPC2yZjZFnG7NR0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> Dismissed @TzahiTaub from a discussion.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/269)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
