### PR TITLE
refactor: remove dependency between storage and starknet prefix

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/308)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/308)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs` line 40 at r1](https://reviewable.io/reviews/starkware-libs/committer/308#-O1pYrbY1X_Br3EDNQ-u:-O1pYrbY1X_Br3EDNQ-v:b-90zu3i) ([raw file](https://github.com/starkware-libs/committer/blob/109edbc2a9dc9191e4e05256a9c953f9870e8b72/crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs#L40)):*
> ```XML
>         StarknetPrefix::CompiledClassLeaf.to_storage_prefix()
>     }
> }
> ```

I suggest you give a better return type than `Vec<u8>` in `get_prefix`, how about this?
(trait definition shouldn't be here, obviously, but this is my idea)



_Suggestion:_
```XML
#[cfg(test)]
#[path = "leaf_serde_test.rs"]
pub mod leaf_serde_test;

pub trait StoragePrefix {
    fn to_bytes(&self) -> Vec<u8>;
}

impl StoragePrefix for StarknetPrefix {
    ...
}

impl DBObject for StarknetStorageValue {
    /// Serializes the value into a 32-byte vector.
    fn serialize(&self) -> StorageValue {
        StorageValue(self.0.to_bytes_be().to_vec())
    }

    fn get_prefix(&self) -> impl StoragePrefix {
        StarknetPrefix::StorageLeaf
    }
}

impl DBObject for CompiledClassHash {
    /// Creates a json string describing the leaf and casts it into a byte vector.
    fn serialize(&self) -> StorageValue {
        let json_string = format!(r#"{{"compiled_class_hash": "{}"}}"#, self.0.to_hex());
        StorageValue(json_string.into_bytes())
    }

    fn get_prefix(&self) -> impl StoragePrefix {
        StarknetPrefix::CompiledClassLeaf
    }
}
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 4 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/308)* status: all files reviewed, 5 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 238 at r3](https://reviewable.io/reviews/starkware-libs/committer/308#-O200LK02HGWxLigE-0w:-O200LK02HGWxLigE-0x:b-zbou60) ([raw file](https://github.com/starkware-libs/committer/blob/965844698c9bd357e2af9ed50f0ea948d4540cdf/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L238)):*
> ```XML
>                         L::prefix()
>                     } else {
>                         StarknetPrefix::InnerNode.to_storage_prefix()
> ```

is `calculate_subtree_roots` part of the future patricia crate?
if so, how will this work without the StarknetPrefix (starknet implementation detail)?
please add a TODO about it if you're still unsure, out of scope of the current PR anyway



_Code quote:_
```XML
StarknetPrefix::InnerNode.to_storage_prefix()
```
___
*[`crates/committer/src/storage/db_object.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/committer/308#-O200lA3Eestm2XhuaLb:-O200lA3Eestm2XhuaLc:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/965844698c9bd357e2af9ed50f0ea948d4540cdf/crates/committer/src/storage/db_object.rs#L9)):*
> ```XML
> 
>     /// Returns the storage key prefix of the DB object.
>     fn get_prefix(&self) -> Vec<u8>;
> ```





_Suggestion:_
```XML
// TODO(Aviv, 1/8/2024): Define a trait `T` for storage prefix and return `impl T` here.
fn get_prefix(&self) -> Vec<u8>;
```
___
*[`crates/committer/src/storage/db_object.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/committer/308#-O200wcFCMdlRkUIM5Rd:-O200wcFCMdlRkUIM5Re:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/965844698c9bd357e2af9ed50f0ea948d4540cdf/crates/committer/src/storage/db_object.rs#L22)):*
> ```XML
> 
>     /// The prefix used to store in DB.
>     fn prefix() -> Vec<u8>;
> ```





_Suggestion:_
```XML
    /// The prefix used to store in DB.
    // TODO(Aviv, 1/8/2024): Define a trait `T` for storage prefix and return `impl T` here.
    fn prefix() -> Vec<u8>;
```
___
*[`crates/committer/src/storage/errors.rs` line 33 at r3](https://reviewable.io/reviews/starkware-libs/committer/308#-O201-GfCk_p2A8pnz5H:-O201-GfCk_p2A8pnz5I:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/965844698c9bd357e2af9ed50f0ea948d4540cdf/crates/committer/src/storage/errors.rs#L33)):*
> ```XML
>     PathToBottomError(#[from] PathToBottomError),
>     #[error("Unexpected prefix ({0:?}) variant when deserializing a leaf.")]
>     LeafPrefixError(Vec<u8>),
> ```





_Suggestion:_
```XML
    #[error("Unexpected prefix ({0:?}) variant when deserializing a leaf.")]
    // TODO(Aviv, 1/8/2024): Define a trait `T` for storage prefix and return `impl T` here.
    LeafPrefixError(Vec<u8>),
```
___
*[`crates/committer/src/storage/storage_trait.rs` line 33 at r3](https://reviewable.io/reviews/starkware-libs/committer/308#-O2013QQEDDQj96GfX2u:-O2013QQEDDQj96GfX2v:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/965844698c9bd357e2af9ed50f0ea948d4540cdf/crates/committer/src/storage/storage_trait.rs#L33)):*
> ```XML
> }
> 
> // TODO(Aviv, 17/07/2024); Split between Storage and node specific implementation.
> ```





_Suggestion:_
```XML
// TODO(Aviv, 17/07/2024); Split between Storage prefix representation (trait) and node
//   specific implementation (enum).
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/308)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 238 at r3](https://reviewable.io/reviews/starkware-libs/committer/308#-O200LK02HGWxLigE-0w:-O202dc--CZwhUZANVg2:bhaqcoc) ([raw file](https://github.com/starkware-libs/committer/blob/965844698c9bd357e2af9ed50f0ea948d4540cdf/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L238)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is `calculate_subtree_roots` part of the future patricia crate?
if so, how will this work without the StarknetPrefix (starknet implementation detail)?
please add a TODO about it if you're still unsure, out of scope of the current PR anyway
</blockquote></details>

calculate_subtree_root is part of the committer logic. It uses StarknetPrefix only for the inner node. It should depend on the storage, as we discussed today.
I add TODO



_Code snippet:_
```XML
fn calculate_subtrees_roots<L: Leaf>(
        subtrees: &[SubTree<'a>],
        storage: &impl Storage,
    ) -> OriginalSkeletonTreeResult<Vec<FilledNode<L>>> {
```
___
*[`crates/committer/src/storage/db_object.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/committer/308#-O200lA3Eestm2XhuaLb:-O206pO69BQTV6l8ilbG:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/965844698c9bd357e2af9ed50f0ea948d4540cdf/crates/committer/src/storage/db_object.rs#L9)):*
> ```XML
> 
>     /// Returns the storage key prefix of the DB object.
>     fn get_prefix(&self) -> Vec<u8>;
> ```

Done.
___
*[`crates/committer/src/storage/db_object.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/committer/308#-O200wcFCMdlRkUIM5Rd:-O206olqCSeS7mYj4nAB:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/965844698c9bd357e2af9ed50f0ea948d4540cdf/crates/committer/src/storage/db_object.rs#L22)):*
> ```XML
> 
>     /// The prefix used to store in DB.
>     fn prefix() -> Vec<u8>;
> ```

Done.
___
*[`crates/committer/src/storage/errors.rs` line 33 at r3](https://reviewable.io/reviews/starkware-libs/committer/308#-O201-GfCk_p2A8pnz5H:-O206SAv6QZZsWiHQRwD:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/965844698c9bd357e2af9ed50f0ea948d4540cdf/crates/committer/src/storage/errors.rs#L33)):*
> ```XML
>     PathToBottomError(#[from] PathToBottomError),
>     #[error("Unexpected prefix ({0:?}) variant when deserializing a leaf.")]
>     LeafPrefixError(Vec<u8>),
> ```

Done.
___
*[`crates/committer/src/storage/storage_trait.rs` line 33 at r3](https://reviewable.io/reviews/starkware-libs/committer/308#-O2013QQEDDQj96GfX2u:-O206AKX69T1OOC7xMQc:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/965844698c9bd357e2af9ed50f0ea948d4540cdf/crates/committer/src/storage/storage_trait.rs#L33)):*
> ```XML
> }
> 
> // TODO(Aviv, 17/07/2024); Split between Storage and node specific implementation.
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/308#-:-O20B3295CVSx8s1F06b:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Comment by AvivYossef-starkware** [comment]
### Merge activity

* **Jul 17, 12:52 PM EDT**: @AvivYossef-starkware started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/starkware-libs/committer/308).

**Pull request merged**
