### PR TITLE
test(block_hash): tx data test

### PR DESCRIPTION
**Pull request by yoavGrs**
Replace block info test with tx data test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/216)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/216)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/216#-O-13W6MDwGOfBJE0W60:-O-13W6MDwGOfBJE0W61:b-698q8b) (no related file):*
why was block info removed in this pr? 

___

**Comment by yoavGrs** [comment]
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why was block info removed in this pr?
</blockquote></details>

I'm removing it in the python as well.
The relevant fields are already in the transaction output.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/216)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/216#-O-13W6MDwGOfBJE0W60:-O-15pIJ1RpCA7J2jKQV:b-krzity) (no related file):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I'm removing it in the python as well.
The relevant fields are already in the transaction output.
</blockquote></details>

please split this PR
block info deletion is unrelated to the test addition

___

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/216)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/216#-O-13W6MDwGOfBJE0W60:-O-18DGd16SO9QzU2MEL:b-896fix) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please split this PR
block info deletion is unrelated to the test addition
</blockquote></details>

Done.

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/216#-:-O-1zm5P70nLWJIwQuWf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
