### PR TITLE
chore!: remove data from skeleton leaf

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/126)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/126)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/126#-NyAX9dV7wFP2CtoFrxA:-NyAX9dV7wFP2CtoFrxB:b25fio) (no related file):*
[python side](https://reviewable.io/reviews/starkware-industries/starkware/35000)

___

**Review by AvivYossef-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/126#-:-NyEefH0-iIASk6nULbL:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/126#-:-NyKnjl777M-KSQZHeE9:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 52 at r1](https://reviewable.io/reviews/starkware-libs/committer/126#-NyKnNwF3mCP_tn-7z8l:-NyKnNwF3mCP_tn-7z8m:bgjdjdk) ([raw file](https://github.com/starkware-libs/committer/blob/6372e7ef15eb1afbb8cb527d360c37acc30cf247/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L52)):*
> ```XML
> impl LeafData for SkeletonLeaf {
>     fn is_empty(&self) -> bool {
>         matches!(self, Self::Zero)
> ```

Why macro and not `self == Self::Zero`?



_Code quote:_
```XML
 matches!(self, Self::Zero)
```

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 5 of 11 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/126)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @nimrod-starkware)

**Pull request merged**
