### PR TITLE
fix: commit non modified trees should return the same root

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/196)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/196)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @aner-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/utils/random_structs.rs` line 194 at r2](https://reviewable.io/reviews/starkware-libs/committer/196#-NzbtDUa-0kUnf1lyWZA:-NzbtDUa-0kUnf1lyWZB:b18p8pm) ([raw file](https://github.com/starkware-libs/committer/blob/626223faf2c3d5141a827bec3fc66ac4b833373d/crates/committer_cli/src/tests/utils/random_structs.rs#L194)):*
> ```XML
>             root_hash: HashOutput::ROOT_OF_EMPTY_TREE,
>         }
>     }
> ```

@AvivYossef-starkware Is that ok?
Will it break something?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/196)* status: all files reviewed, 7 unresolved discussions (waiting on @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/committer/196#-Nzbimql9bSCWsjnu4jL:-Nzbimql9bSCWsjnu4jM:b-kirg9v) ([raw file](https://github.com/starkware-libs/committer/blob/e95fa5a389d7874c3e6a064a8d6bc9326943665a/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L113)):*
> ```XML
>                         return Err(FilledTreeError::<LeafDataImpl>::MissingNode(*key));
>                     }
>                 }
> ```

why is this *always* ok if the current index is the ROOT index?
can't we have an update where only the root is updated? The root should appear in the map and `None` should cause an error, no?



_Code quote:_
```XML
                None => {
                    if *key != NodeIndex::ROOT {
                        return Err(FilledTreeError::<LeafDataImpl>::MissingNode(*key));
                    }
                }
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/committer/196#-NzbsrRECAd4kKeg9U9e:-NzbsrRECAd4kKeg9U9f:b-2weszy) ([raw file](https://github.com/starkware-libs/committer/blob/e95fa5a389d7874c3e6a064a8d6bc9326943665a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L185)):*
> ```XML
>                 nodes: HashMap::from([(
>                     NodeIndex::ROOT,
>                     OriginalSkeletonNode::LeafOrBinarySibling(root_hash),
> ```

terrible name
but this variant needs a rename...
maybe just `Unmodified`?



_Suggestion:_
```XML
UnmodifiedRootOrLeafOrBinarySibling
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 496 at r2](https://reviewable.io/reviews/starkware-libs/committer/196#-Nzbtuob4EtPTI4TVWcc:-Nzbtuob4EtPTI4TVWcd:b-4yr6dt) ([raw file](https://github.com/starkware-libs/committer/blob/626223faf2c3d5141a827bec3fc66ac4b833373d/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L496)):*
> ```XML
>     assert_eq!(updated_skeleton.skeleton_tree, expected_skeleton_tree);
> }
> #[rstest]
> ```

newline



_Suggestion:_
```XML
}

#[rstest]
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 500 at r2](https://reviewable.io/reviews/starkware-libs/committer/196#-NzbtyUt6nnnAoiA19uj:-NzbtyUt6nnnAoiA19uk:bdx5o9k) ([raw file](https://github.com/starkware-libs/committer/blob/626223faf2c3d5141a827bec3fc66ac4b833373d/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L500)):*
> ```XML
> #[case::non_empty_tree(77)]
> #[tokio::test]
> async fn test_update_non_modified_tree(#[case] root_hash: u128) {
> ```

saves lines, but no informative test title... your call, non-blocking



_Suggestion:_
```XML
#[tokio::test]
async fn test_update_non_modified_tree(#[values(0, 77)] root_hash: u128) {
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/committer/196#-NzbtfMNASQ8ccgszdkS:-NzbtfMNASQ8ccgszdkT:big1c8n) ([raw file](https://github.com/starkware-libs/committer/blob/e95fa5a389d7874c3e6a064a8d6bc9326943665a/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L56)):*
> ```XML
>                 OriginalSkeletonNode::LeafOrBinarySibling(hash) => hash,
>                 _ => panic!("A root of tree without modifications is expected to be a sibling."),
>             };
> ```

`let .. else` pattern



_Suggestion:_
```XML
            let OriginalSkeletonNode::LeafOrBinarySibling(root_hash) = original_root_node else {
                panic!("A root of tree without modifications is expected to be a sibling.");
            };
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/committer/196#-NzbtNL90j1-zyupH8Zq:-NzbtNL90j1-zyupH8Zr:bmbcpah) ([raw file](https://github.com/starkware-libs/committer/blob/e95fa5a389d7874c3e6a064a8d6bc9326943665a/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L63)):*
> ```XML
>                 )]),
>             });
>         }
> ```

move this to a separate associated function please



_Suggestion:_
```XML
        if leaf_modifications.is_empty() {
            return Self::create_unmodified(original_skeleton);
        }
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/196)* status: all files reviewed, 6 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 113 at r1](https://reviewable.io/reviews/starkware-libs/committer/196#-Nzbimql9bSCWsjnu4jL:-Nzbycy95LjqhlpSzYlB:b-mdwrbt) ([raw file](https://github.com/starkware-libs/committer/blob/e95fa5a389d7874c3e6a064a8d6bc9326943665a/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L113)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why is this *always* ok if the current index is the ROOT index?
can't we have an update where only the root is updated? The root should appear in the map and `None` should cause an error, no?
</blockquote></details>

if there were no modifications - then it's okay. We don't want to return an error, and there are no new facts to write (hash_map_out will be empty, and it's okay)

If there were some modifications, the root variant would not be `UpdatedSkeletonNode::UnmodifiedBottom` or `UpdatedSkeletonNode::Sibling`.  in that case, the root index will be inserted to the output map and it's okay.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/committer/196#-NzbsrRECAd4kKeg9U9e:-Nzbxaft1jB-uQg2aeSD:b-t5hspu) ([raw file](https://github.com/starkware-libs/committer/blob/e95fa5a389d7874c3e6a064a8d6bc9326943665a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L185)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

terrible name
but this variant needs a rename...
maybe just `Unmodified`?
</blockquote></details>

maybe `Sibling`?
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 496 at r2](https://reviewable.io/reviews/starkware-libs/committer/196#-Nzbtuob4EtPTI4TVWcc:-Nzbv0ovAAy6CICIJNiZ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/626223faf2c3d5141a827bec3fc66ac4b833373d/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L496)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newline
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/committer/196#-NzbtfMNASQ8ccgszdkS:-Nzbvtd_9JrStpXpQypq:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e95fa5a389d7874c3e6a064a8d6bc9326943665a/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`let .. else` pattern
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 63 at r1](https://reviewable.io/reviews/starkware-libs/committer/196#-NzbtNL90j1-zyupH8Zq:-NzbxDcm6UCPgEOoqcup:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e95fa5a389d7874c3e6a064a8d6bc9326943665a/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move this to a separate associated function please
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/196)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 185 at r1](https://reviewable.io/reviews/starkware-libs/committer/196#-NzbsrRECAd4kKeg9U9e:-Nzc5iN0Eywnb2MuWA2s:b4v0npg) ([raw file](https://github.com/starkware-libs/committer/blob/e95fa5a389d7874c3e6a064a8d6bc9326943665a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L185)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

maybe `Sibling`?
</blockquote></details>

no, a root is not a sibling of any node
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 425 at r3](https://reviewable.io/reviews/starkware-libs/committer/196#-Nzc5Qf_96RUdps11WgE:-Nzc5Qf_96RUdps11WgF:b-pc9trt) ([raw file](https://github.com/starkware-libs/committer/blob/45cce5b2e30103bc7af53e93b44c3d5390c7fe3b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L425)):*
> ```XML
>         } else {
>             panic!("A root of tree without modifications is expected to be a sibling.")
>         };
> ```

not `let x = if let .. else`,
just `let .. else`



_Suggestion:_
```XML
        let OriginalSkeletonNode::LeafOrBinarySibling(root_hash) = original_root_node else {
            panic!("A root of tree without modifications is expected to be a sibling.")
        };
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 429 at r3](https://reviewable.io/reviews/starkware-libs/committer/196#-Nzc4n3w8-MzKkbKyy_i:-Nzc4n3w8-MzKkbKyy_j:b90lhhf) ([raw file](https://github.com/starkware-libs/committer/blob/45cce5b2e30103bc7af53e93b44c3d5390c7fe3b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L429)):*
> ```XML
>             skeleton_tree: HashMap::from([(
>                 NodeIndex::ROOT,
>                 UpdatedSkeletonNode::Sibling(*root_hash),
> ```

this needs renaming as well - a root is not a sibling



_Code quote:_
```XML
Sibling
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/196)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 425 at r3](https://reviewable.io/reviews/starkware-libs/committer/196#-Nzc5Qf_96RUdps11WgE:-NzcG_6B4KAIyYUiCCH4:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/45cce5b2e30103bc7af53e93b44c3d5390c7fe3b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L425)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not `let x = if let .. else`,
just `let .. else`
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 429 at r3](https://reviewable.io/reviews/starkware-libs/committer/196#-Nzc4n3w8-MzKkbKyy_i:-NzcGGwF1G-mQNWN4N8T:b-uq68db) ([raw file](https://github.com/starkware-libs/committer/blob/45cce5b2e30103bc7af53e93b44c3d5390c7fe3b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L429)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this needs renaming as well - a root is not a sibling
</blockquote></details>

It's a sibling in the sense that none of its descendants has changed...

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/196)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @aner-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 429 at r3](https://reviewable.io/reviews/starkware-libs/committer/196#-Nzc4n3w8-MzKkbKyy_i:-NzcKhw49Y6tDe44auwo:b-842kll) ([raw file](https://github.com/starkware-libs/committer/blob/45cce5b2e30103bc7af53e93b44c3d5390c7fe3b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L429)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

It's a sibling in the sense that none of its descendants has changed...
</blockquote></details>

WDYT of renaming `UpdatedSkeletonNode::Sibling(HashOutput)`  => `UpdatedSkeletonNode::Unmodified(HashOutput)`?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/196)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 429 at r3](https://reviewable.io/reviews/starkware-libs/committer/196#-Nzc4n3w8-MzKkbKyy_i:-NzcOVpcAE9mKdaxFOEn:bgl6g8w) ([raw file](https://github.com/starkware-libs/committer/blob/45cce5b2e30103bc7af53e93b44c3d5390c7fe3b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L429)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

WDYT of renaming `UpdatedSkeletonNode::Sibling(HashOutput)`  => `UpdatedSkeletonNode::Unmodified(HashOutput)`?
</blockquote></details>

I'm in favor. @TzahiTaub ?

**Pull request closed without merging**
