### PR TITLE
build: impl serialize for filled tree

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/116)

### CODE REVIEW

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/116)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/committer/116#-Nxv9yyU0NNQ5NQ8avH3:-Nxv9yyV2cGjDfzrX0tf:b-gxnfpf) ([raw file](https://github.com/starkware-libs/committer/blob/1401918d2d798aee8bcbbb665e4182a7e354123d/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L17)):*
> ```XML
> pub(crate) trait FilledTree<L: LeafData> {
>     /// Serializes the tree into storage. Returns hash set of keys of the serialized nodes,
>     /// if successful.
> ```

Please add:
`/// Serializes the tree and returns the resulting storage keys and values.`



_Code quote:_
```XML
    /// Serializes the tree into storage. Returns hash set of keys of the serialized nodes,
    /// if successful.
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/committer/116#-NxvFmWhCrMYuGvLBFo3:-NxvFmWhCrMYuGvLBFo4:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/6413af5dc695b275d3fe3e14c7dbb2eb9146bd12/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L17)):*
> ```XML
> pub(crate) trait FilledTree<L: LeafData> {
>     #[allow(dead_code)]
>     fn serialize(&self) -> HashMap<StorageKey, StorageValue>;
> ```





_Code quote (i):_
```XML
fn serialize(&self) -> HashMap<StorageKey, StorageValue>;
```



_Code snippet (ii):_
```XML
fn serialize(&self) -> Result<HashMap<StorageKey, StorageValue>>;
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/committer/116#-NxvD8DICglYNdZlMg36:-NxvD8DJDv3zwS6sU0od:bdrs278) ([raw file](https://github.com/starkware-libs/committer/blob/6413af5dc695b275d3fe3e14c7dbb2eb9146bd12/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L42)):*
> ```XML
>     /// to a storage key and its serialized storage value.
>     /// This function iterates over each node in the tree, using the node's `db_key` as the hashmap key
>     /// and the result of the node's `serialize` method as the value.
> ```

please delete - no need to explain the implementation in the docstring. 



_Code quote:_
```XML
    /// Serializes the current state of the tree into a hashmap where each key-value pair corresponds
    /// to a storage key and its serialized storage value.
    /// This function iterates over each node in the tree, using the node's `db_key` as the hashmap key
    /// and the result of the node's `serialize` method as the value.
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/committer/116#-NxvFb3_9xkdqBX31HUb:-NxvFb3_9xkdqBX31HUc:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/6413af5dc695b275d3fe3e14c7dbb2eb9146bd12/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L48)):*
> ```XML
>             serialize_tree_map.insert(node.db_key(), node.serialize());
>         }
>         serialize_tree_map
> ```





_Code quote (i):_
```XML
        let mut serialize_tree_map: HashMap<StorageKey, StorageValue> = HashMap::new();
        for (_node_index, node) in self.tree_map.iter() {
            serialize_tree_map.insert(node.db_key(), node.serialize());
        }
        serialize_tree_map
```



_Code snippet (ii):_
```XML
        self.get_all_nodes()
            .iter()
            .map(|(_, node)| (node.db_key(), node.serialize()))
            .collect()
```

**Review by AvivYossef-starkware — COMMENTED** [review]
there is a separate PR for the first commit.

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/116#-:-NyFNkir-SmdsAEmeUde:b-v9m5n8)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/committer/116#-Nxv9yyU0NNQ5NQ8avH3:-NyF62Pz8U92WVQ_GqlK:b-pnhr4h) ([raw file](https://github.com/starkware-libs/committer/blob/1401918d2d798aee8bcbbb665e4182a7e354123d/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L17)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Please add:
`/// Serializes the tree and returns the resulting storage keys and values.`
</blockquote></details>

See below.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/committer/116#-NxvFmWhCrMYuGvLBFo3:-NxvGPhlEUUXO9bIcvVS:bz2n6dj) ([raw file](https://github.com/starkware-libs/committer/blob/6413af5dc695b275d3fe3e14c7dbb2eb9146bd12/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L17)):*
> ```XML
> pub(crate) trait FilledTree<L: LeafData> {
>     #[allow(dead_code)]
>     fn serialize(&self) -> HashMap<StorageKey, StorageValue>;
> ```

Why Result?
It's always successful.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/committer/116#-NxvD8DICglYNdZlMg36:-NyF6AWu0SGWNpSmJCrs:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/6413af5dc695b275d3fe3e14c7dbb2eb9146bd12/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L42)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please delete - no need to explain the implementation in the docstring.
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 48 at r1](https://reviewable.io/reviews/starkware-libs/committer/116#-NxvFb3_9xkdqBX31HUb:-NyF70qREfgv7qRZwKgh:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/6413af5dc695b275d3fe3e14c7dbb2eb9146bd12/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L48)):*
> ```XML
>             serialize_tree_map.insert(node.db_key(), node.serialize());
>         }
>         serialize_tree_map
> ```

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/116)* status: all files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/committer/116#-NyUXyQ0C9wgLtczz-Wq:-NyUXyQ0C9wgLtczz-Wr:b-pno61p) ([raw file](https://github.com/starkware-libs/committer/blob/55c75a91e65bd2cc92905d32762bcd984685d15d/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L190)):*
> ```XML
> }
> 
> impl<L: LeafData + DBObject> FilledTree<L> for FilledTreeImpl<L> {
> ```

see comment in previous PR



_Suggestion:_
```XML
<L: LeafData>
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 220 at r4](https://reviewable.io/reviews/starkware-libs/committer/116#-NyUYA-lEeJ4GOvzTRPG:-NyUYA-lEeJ4GOvzTRPH:b-r67rii) ([raw file](https://github.com/starkware-libs/committer/blob/55c75a91e65bd2cc92905d32762bcd984685d15d/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L220)):*
> ```XML
>             .iter()
>             .map(|(_, node)| (node.get_db_key(&node.suffix()), node.serialize()))
>             .collect::<HashMap<StorageKey, StorageValue>>()
> ```

are you sure you need the turbofish? compiler should know (return type)



_Suggestion:_
```XML
.collect()
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/116)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 190 at r4](https://reviewable.io/reviews/starkware-libs/committer/116#-NyUXyQ0C9wgLtczz-Wq:-NyVOIkm-7yDYwZUnZ5g:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/55c75a91e65bd2cc92905d32762bcd984685d15d/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L190)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see comment in previous PR
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 220 at r4](https://reviewable.io/reviews/starkware-libs/committer/116#-NyUYA-lEeJ4GOvzTRPG:-NyVOA_T1E4d2CX4TCAs:b-s3hmk9) ([raw file](https://github.com/starkware-libs/committer/blob/55c75a91e65bd2cc92905d32762bcd984685d15d/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L220)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

are you sure you need the turbofish? compiler should know (return type)
</blockquote></details>

Not needed.

**Review by amosStarkware — APPROVED** [review]
> Reviewed 2 of 6 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/116)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/116#-:-NyVTNnJCyBgpYgGEg8b:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
