### PR TITLE
refactor: remove tree height field from updated skeleton tree

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/191)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/191)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/191#-NzX7TOo4it3naAz5F3I:-NzX7TOo4it3naAz5F3J:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/fcb1bf07d8542a132242cde1a16fa3073ec8f22f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L41)):*
> ```XML
> pub(crate) struct UpdatedSkeletonTreeImpl {
>     pub(crate) skeleton_tree: UpdatedSkeletonNodeMap,
> }
> ```





_Suggestion:_
```XML
// TODO(Dori, 1/7/2024): Make this a tuple struct.
pub(crate) struct UpdatedSkeletonTreeImpl {
    pub(crate) skeleton_tree: UpdatedSkeletonNodeMap,
}
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/191)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/191#-NzX7TOo4it3naAz5F3I:-NzX8z0Z3bgwy9ZjGQEd:b-q6xqx7) ([raw file](https://github.com/starkware-libs/committer/blob/fcb1bf07d8542a132242cde1a16fa3073ec8f22f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L41)):*
> ```XML
> pub(crate) struct UpdatedSkeletonTreeImpl {
>     pub(crate) skeleton_tree: UpdatedSkeletonNodeMap,
> }
> ```

Done.
Should i also add a todo to `struct OriginalSkeletonTreeImpl`?
it also has only one field.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/191)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/191#-NzX7TOo4it3naAz5F3I:-NzX9vvhBC9h6a7tjM22:b-n0tjw8) ([raw file](https://github.com/starkware-libs/committer/blob/fcb1bf07d8542a132242cde1a16fa3073ec8f22f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L41)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
Should i also add a todo to `struct OriginalSkeletonTreeImpl`?
it also has only one field.
</blockquote></details>

yes please

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/191)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/191#-NzX7TOo4it3naAz5F3I:-NzXApGA0N9PYrsYMmhI:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/fcb1bf07d8542a132242cde1a16fa3073ec8f22f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes please
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/191#-:-NzXB9az9L_gBVuft1wS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
