### PR TITLE
refactor: use mock test utils in update skeleton tests

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/320)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/starkware-libs/committer/320?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#320** <a href="https://app.graphite.dev/github/pr/starkware-libs/committer/320?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#319** <a href="https://app.graphite.dev/github/pr/starkware-libs/committer/319?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#316** <a href="https://app.graphite.dev/github/pr/starkware-libs/committer/316?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#314** <a href="https://app.graphite.dev/github/pr/starkware-libs/committer/314?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#308** <a href="https://app.graphite.dev/github/pr/starkware-libs/committer/308?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AvivYossef-starkware and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/320)* status: all files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/internal_test_utils.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/committer/320#-O2OWkKWAeNsn25lYrsH:-O2OWkKWAeNsn25lYrsI:ba6wg1a) ([raw file](https://github.com/starkware-libs/committer/blob/c2be47fb499bca3d320c5b161111ad98c9b3ee71/crates/committer/src/patricia_merkle_tree/internal_test_utils.rs#L29)):*
> ```XML
> use rstest::{fixture, rstest};
> 
> use crate::patricia_merkle_tree::filled_tree::tree::FilledTreeImpl;
> ```

if you move this above the `use ethnum::U256` will it be sorted better...?



_Code quote:_
```XML
use crate::patricia_merkle_tree::filled_tree::tree::FilledTreeImpl;
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs` line 503 at r2](https://reviewable.io/reviews/starkware-libs/committer/320#-O2OWr8s4vD-6dH0Jrw8:-O2OWr8s4vD-6dH0Jrw9:b-fxzv0m) ([raw file](https://github.com/starkware-libs/committer/blob/c2be47fb499bca3d320c5b161111ad98c9b3ee71/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs#L503)):*
> ```XML
> #[tokio::test]
> async fn test_update_non_modified_storage_tree(#[case] root_hash: HashOutput) {
>     use crate::patricia_merkle_tree::internal_test_utils::OriginalSkeletonMockTrieConfig;
> ```

move to top



_Code quote:_
```XML
use crate::patricia_merkle_tree::internal_test_utils::OriginalSkeletonMockTrieConfig
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/committer/320#-O2OWu3S15OYAYsASsxw:-O2OWu3S15OYAYsASsxx:b-fxzv0m) ([raw file](https://github.com/starkware-libs/committer/blob/c2be47fb499bca3d320c5b161111ad98c9b3ee71/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L148)):*
> ```XML
> #[case::non_empty_modifications(HashMap::from([(NodeIndex::FIRST_LEAF + NodeIndex::from(7), MockLeaf::default())]))]
> fn test_updated_empty_tree(#[case] modifications: LeafModifications<MockLeaf>) {
>     use crate::patricia_merkle_tree::internal_test_utils::OriginalSkeletonMockTrieConfig;
> ```

move to top



_Code quote:_
```XML
use crate::patricia_merkle_tree::internal_test_utils::OriginalSkeletonMockTrieConfig;
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/320)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/internal_test_utils.rs` line 29 at r2](https://reviewable.io/reviews/starkware-libs/committer/320#-O2OWkKWAeNsn25lYrsH:-O2OuSYs6mB3W87rscz1:bb77ufg) ([raw file](https://github.com/starkware-libs/committer/blob/c2be47fb499bca3d320c5b161111ad98c9b3ee71/crates/committer/src/patricia_merkle_tree/internal_test_utils.rs#L29)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you move this above the `use ethnum::U256` will it be sorted better...?
</blockquote></details>

Yes.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs` line 503 at r2](https://reviewable.io/reviews/starkware-libs/committer/320#-O2OWr8s4vD-6dH0Jrw8:-O2Ougdt619nDciSEjLS:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/c2be47fb499bca3d320c5b161111ad98c9b3ee71/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs#L503)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move to top
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 148 at r2](https://reviewable.io/reviews/starkware-libs/committer/320#-O2OWu3S15OYAYsASsxw:-O2OuovR95o-qcWd0CkI:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/c2be47fb499bca3d320c5b161111ad98c9b3ee71/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L148)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move to top
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/320)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs` line 503 at r2](https://reviewable.io/reviews/starkware-libs/committer/320#-O2OWr8s4vD-6dH0Jrw8:-O2P18Hh66-DB4hlTbAg:bb7lgjf) ([raw file](https://github.com/starkware-libs/committer/blob/c2be47fb499bca3d320c5b161111ad98c9b3ee71/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs#L503)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nope

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/320)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs` line 503 at r2](https://reviewable.io/reviews/starkware-libs/committer/320#-O2OWr8s4vD-6dH0Jrw8:-O2P42674N19Pn6uq9Sv:b-80xfag) ([raw file](https://github.com/starkware-libs/committer/blob/c2be47fb499bca3d320c5b161111ad98c9b3ee71/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs#L503)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

nope
</blockquote></details>

Sorry

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/320#-:-O2UUdq5BqnLhz5wCtqu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

**Pull request merged**
