### PR TITLE
refactor: renamed tree_height => tree_heights

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/92)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/92)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/block_committer/input.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/committer/92#-Nx7e1byCrnt5sseB4lr:-Nx7jtox0dndR738i1pY:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7936c441c7efe166f93d94d55119ba2ab1caa7d7/crates/committer/src/block_committer/input.rs#L46)):*
> ```XML
>     pub storage: HashMap<StorageKey, StorageValue>,
>     pub state_diff: StateDiff,
>     // Assuming all trees have the same height.
> ```

Done.
___
*[`crates/committer_cli/src/parse_input/raw_input.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/92#-Nx7hZsW53U8nwSf9How:-Nx7jxHECl8lGftLEbvb:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/5510e3ecd84f5e0da3a9a752fb065fe3d4744be4/crates/committer_cli/src/parse_input/raw_input.rs#L11)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please move this to `Input`.
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/parse_input/raw_input.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/92#-Nx7fj3Z9XcyEVJY52m-:-Nx7kAp_4HpXP5GMQ6IS:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7936c441c7efe166f93d94d55119ba2ab1caa7d7/crates/committer_cli/src/parse_input/raw_input.rs#L13)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please remove, so we don't have duplicate documentation
</blockquote></details>

Done.

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/92)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/block_committer/input.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/committer/92#-Nx7e1byCrnt5sseB4lr:-Nx7s9AgBgyFCkQVchHP:b-3v3tv7) ([raw file](https://github.com/starkware-libs/committer/blob/7936c441c7efe166f93d94d55119ba2ab1caa7d7/crates/committer/src/block_committer/input.rs#L46)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant to delete the line `// Assuming all trees have the same height.`
___
*[`crates/committer_cli/src/parse_input/raw_input.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/92#-Nx7hZsW53U8nwSf9How:-Nx7sVVW8ScqNRVPOkiw:b-6dj8ll) ([raw file](https://github.com/starkware-libs/committer/blob/5510e3ecd84f5e0da3a9a752fb065fe3d4744be4/crates/committer_cli/src/parse_input/raw_input.rs#L11)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see it in `Input`

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/92)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/block_committer/input.rs` line 46 at r1](https://reviewable.io/reviews/starkware-libs/committer/92#-Nx7e1byCrnt5sseB4lr:-Nx7w326Aj7-gMOEx6mm:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7936c441c7efe166f93d94d55119ba2ab1caa7d7/crates/committer/src/block_committer/input.rs#L46)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I meant to delete the line `// Assuming all trees have the same height.`
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/parse_input/raw_input.rs` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/92#-Nx7hZsW53U8nwSf9How:-Nx7wG2yEPIU_cTprUj1:b4o9c75) ([raw file](https://github.com/starkware-libs/committer/blob/5510e3ecd84f5e0da3a9a752fb065fe3d4744be4/crates/committer_cli/src/parse_input/raw_input.rs#L11)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I don't see it in `Input`
</blockquote></details>

oops, sorry

**Review by amosStarkware — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/92)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
