### PR TITLE
fix: added global tree root hash and classes tree root hash as an input to the committer

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/84)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/84)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/84#-NwsnFim5k5LQSEEF3yS:-NwsnFim5k5LQSEEF3yT:b-hly2zx) (no related file):*
python side PR?

___

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/84)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/84#-NwsnFim5k5LQSEEF3yS:-Nwsy4_A4SyBAyAEAa3s:blyyjg) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

python side PR?
</blockquote></details>

[here](https://reviewable.io/reviews/starkware-industries/starkware/34855#-)

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/84#-:-Nwt8i9L5-PDJZSUPTWN:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/84)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
