### PR TITLE
build: add binary and edge node tree hash implementation

### PR DESCRIPTION
**Pull request by aner-starkware**
In preparation for main algorithm implementation

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/37)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/37)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/types.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBtn7g-2sE-OQLJjIT:-NvBtn7g-2sE-OQLJjIU:b-4kvgj6) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/types.rs#L22)):*
> ```XML
>         Self(value.into())
>     }
> }
> ```

can you make this generic?



_Suggestion:_
```XML
impl<T: Into<StarknetTypesFelt>> From<T> for Felt {
    fn from(value: T) -> Self {
        Self(value.into())
    }
}
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBuIHQ4sN5XZcYGMHn:-NvBuIHQ4sN5XZcYGMHo:b-1fjia) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L25)):*
> ```XML
>                 PedersenHashFunction::compute_hash(HashInputPair(hash_output.0, path.0)).0
>                     + Felt::from(length.0),
>             ),
> ```

these look like non-mock implementations.
I would like you to add a regression test for this (compute hashes of binary/edge nodes on the python side, copy the values explicitly into a rust test)... but it seems weird to test a test util.
Are you sure this isn't meant to be a "real" hasher? our `PedersenTreeHashFunction`?



_Code quote:_
```XML
            NodeData::Binary(BinaryData {
                left_hash,
                right_hash,
            }) => PedersenHashFunction::compute_hash(HashInputPair(left_hash.0, right_hash.0)),
            NodeData::Edge(EdgeData {
                bottom_hash: hash_output,
                path_to_bottom: PathToBottom { path, length },
            }) => HashOutput(
                PedersenHashFunction::compute_hash(HashInputPair(hash_output.0, path.0)).0
                    + Felt::from(length.0),
            ),
```

**Comment by aner-starkware** [comment]
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBuIHQ4sN5XZcYGMHn:-NvBurq82Jo4EVsKtBzZ:brt5gg1) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these look like non-mock implementations.
I would like you to add a regression test for this (compute hashes of binary/edge nodes on the python side, copy the values explicitly into a rust test)... but it seems weird to test a test util.
Are you sure this isn't meant to be a "real" hasher? our `PedersenTreeHashFunction`?
</blockquote></details>

It is supposed to be later on, right now it's not complete...

**Comment by aner-starkware** [comment]
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBuIHQ4sN5XZcYGMHn:-NvBv0OgEpKbZRJvb4GY:boqf3qr) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L25)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

It is supposed to be later on, right now it's not complete...
</blockquote></details>

I can write tests for it right now, or we can write the tests once we finish the implementation and move it into the "real" code :)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/37)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBuIHQ4sN5XZcYGMHn:-NvBuz_6C9XNioDrIvoO:bpc8ro1) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L25)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

It is supposed to be later on, right now it's not complete...
</blockquote></details>

ok, it can be incomplete, but the completed parts are production code, and should be tested.
please move to a non-test area and add regression tests for the implemented functions

**Comment by aner-starkware** [comment]
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBuIHQ4sN5XZcYGMHn:-NvBvE-M57EGWVjtHzxo:b-y1wvhm) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, it can be incomplete, but the completed parts are production code, and should be tested.
please move to a non-test area and add regression tests for the implemented functions
</blockquote></details>

Isn't it better to wait until we finish the implementation? I mean, right now I need it only for testing, and it's blocking the main algorithm PR because of that (which requires it for the testing)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/37)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBuIHQ4sN5XZcYGMHn:-NvBwS1h2Xb9jRa-NhU-:b-3mmnr2) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L25)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Isn't it better to wait until we finish the implementation? I mean, right now I need it only for testing, and it's blocking the main algorithm PR because of that (which requires it for the testing)
</blockquote></details>

No, we should be adding unit tests along with the PRs that add the building blocks of the full logic.
You will be able to use it in tests even if it's not a test util

**Comment by aner-starkware** [comment]
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBuIHQ4sN5XZcYGMHn:-NvByuwN1NBRylB9wCAN:b-m42mna) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

No, we should be adding unit tests along with the PRs that add the building blocks of the full logic.
You will be able to use it in tests even if it's not a test util
</blockquote></details>

But right now I'm using it only in a test... So at the moment it's still only a test util :grin:

**Comment by aner-starkware** [comment]
*[`crates/committer/src/types.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBtn7g-2sE-OQLJjIT:-NvBzzJy2pVgytulhRCM:b-14xa4i) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/types.rs#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you make this generic?
</blockquote></details>

```conflicting implementations of trait \`std::convert::From<types::Felt>\` for type \`types::Felt\`  
conflicting implementation in crate \`core\`:  
\- impl<T> std::convert::From<T> for T;```

**Comment by aner-starkware** [comment]
*[`crates/committer/src/types.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBtn7g-2sE-OQLJjIT:-NvC02P25IVLq8QDDTRL:b-8kmzbp) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/types.rs#L22)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

```conflicting implementations of trait \`std::convert::From<types::Felt>\` for type \`types::Felt\`  
conflicting implementation in crate \`core\`:  
\- impl<T> std::convert::From<T> for T;```
</blockquote></details>

It seems to work if I delete the `impl From<Felt\> for StarknetTypesFelt`

**Comment by aner-starkware** [comment]
*[`crates/committer/src/types.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBtn7g-2sE-OQLJjIT:-NvC0Lvk89W0S_wLWBPR:b-kvgtpf) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/types.rs#L22)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

It seems to work if I delete the `impl From<Felt\> for StarknetTypesFelt`
</blockquote></details>

scratch that - it seems to give other compilation errors

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/37)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/types.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBtn7g-2sE-OQLJjIT:-NvC2syECGVA9Vx8gfLt:bes7hyn) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/types.rs#L22)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

scratch that - it seems to give other compilation errors
</blockquote></details>

what if you delete all the other `From<T> for Felt`? there are implementations for u8, u128 and StarknetTypesFelt

**Comment by aner-starkware** [comment]
*[`crates/committer/src/types.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBtn7g-2sE-OQLJjIT:-NvC9Avk51CBBeVXj-HA:bf863dv) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/types.rs#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what if you delete all the other `From<T> for Felt`? there are implementations for u8, u128 and StarknetTypesFelt
</blockquote></details>

The problem is that it still conflicts with the `impl From<Felt> for StarknetTypesFelt` for some reason, not sure why :shrug:

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/37)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 25 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBuIHQ4sN5XZcYGMHn:-NvCCnl410GVXbFJxZMC:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/patricia_merkle_tree/test_utils.rs#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no, it's production code.
none of the code we have in this repo is used anywhere other than tests, no reason this struct would be special
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/37)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/types.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBtn7g-2sE-OQLJjIT:-NvCRkjw39GAZRnCZuQy:b-bsvpkv) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/types.rs#L22)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

The problem is that it still conflicts with the `impl From<Felt> for StarknetTypesFelt` for some reason, not sure why :shrug:
</blockquote></details>

ok... the only way to do it is if we remove the `impl From<Felt> for StarknetTypesFelt`.
if we want to convert `x: Felt` to StarknetTypesFelt we will need to use `x.0`, i.e. make `Felt`'s inner StarknetTypesFelt a `pub` field.
Unblocking, up to you ATM if it's worth it or not.
If we get too many conversion boilerplate functions I would consider doing it,
or implementing a macro for it (see new comment)
___
*[`crates/committer/src/types.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/committer/37#-NvCT22BCUcg1B2NY81k:-NvCT22BCUcg1B2NY81l:b-go5cq1) ([raw file](https://github.com/starkware-libs/committer/blob/5fd1367b2beffa6fca0ae3acce8da85738e4eab6/crates/committer/src/types.rs#L28)):*
> ```XML
>         felt.0
>     }
> }
> ```

WDYT of this option?
Currently support `StarknetTypesFelt, u128, u8` and can add more types later with minimal effort



_Suggestion:_
```XML
#[macro_export]
macro_rules! impl_froms {
    ($to:ty, $from:ty, $($other_from: ty),+) => {
        $crate::impl_froms!($to, $from);
        $crate::impl_froms!($to $(, $other_from)*);
    };

    ($to:ty, $from:ty) => {
        impl From<$from> for $to {
            fn from(value: $from) -> Self {
                Self(value.into())
            }
        }
    };
}

impl_froms!(Felt, StarknetTypesFelt, u128, u8);

impl From<Felt> for StarknetTypesFelt {
    fn from(felt: Felt) -> Self {
        felt.0
    }
}
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/committer/37#-NvCPvIF9eq-o95AZCqw:-NvCPvIF9eq-o95AZCqx:bnkilam) ([raw file](https://github.com/starkware-libs/committer/blob/5fd1367b2beffa6fca0ae3acce8da85738e4eab6/crates/committer/src/patricia_merkle_tree/types.rs#L43)):*
> ```XML
>             },
>         }
>     }
> ```

generic impl



_Suggestion:_
```XML
impl<H: HashFunction> TreeHashFunction<LeafData, H> for TreeHashFunctionImpl {
    fn compute_node_hash(node_data: NodeData<LeafData>) -> HashOutput {
        match node_data {
            NodeData::Binary(BinaryData {
                left_hash,
                right_hash,
            }) => H::compute_hash(HashInputPair(left_hash.0, right_hash.0)),
            NodeData::Edge(EdgeData {
                bottom_hash: hash_output,
                path_to_bottom: PathToBottom { path, length },
            }) => HashOutput(
                H::compute_hash(HashInputPair(hash_output.0, path.0)).0
                    + Felt::from(length.0),
            ),
            NodeData::Leaf(leaf_data) => match leaf_data {
                LeafData::StorageValue(_) => todo!(),
                LeafData::CompiledClassHash(compiled_class_hash) => {
                    HashOutput(compiled_class_hash.0)
                }
                LeafData::StateTreeTuple { .. } => {
                    todo!()
                }
            },
        }
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/committer/37#-NvCQKtfAHnhCwUSgBfh:-NvCQKtfAHnhCwUSgBfi:b-ogkj12) ([raw file](https://github.com/starkware-libs/committer/blob/5fd1367b2beffa6fca0ae3acce8da85738e4eab6/crates/committer/src/patricia_merkle_tree/types_test.rs#L47)):*
> ```XML
> #[rstest]
> #[case(Felt::ONE, Felt::TWO, 3)]
> #[case(Felt::from(0xBE_u128), Felt::from(0xA0BEE_u128), 0xB)]
> ```

please compute these 4 cases on the python side, check the result, and paste it here with an `assert_eq!` (to test for regression with existing implementation)



_Code quote:_
```XML
#[rstest]
#[case(Felt::ONE, Felt::TWO)]
#[case(Felt::from(0xBE_u128), Felt::from(0xA0BEE_u128))]
fn test_tree_hash_function_impl_binary_node(#[case] left_hash: Felt, #[case] right_hash: Felt) {
    let hash_output = TreeHashFunctionImpl::compute_node_hash(NodeData::Binary(BinaryData {
        left_hash: HashOutput(left_hash),
        right_hash: HashOutput(right_hash),
    }));
    assert_eq!(
        hash_output,
        PedersenHashFunction::compute_hash(HashInputPair(left_hash, right_hash))
    );
}

#[rstest]
#[case(Felt::ONE, Felt::TWO, 3)]
#[case(Felt::from(0xBE_u128), Felt::from(0xA0BEE_u128), 0xB)]
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/37)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/types.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/37#-NvBtn7g-2sE-OQLJjIT:-NvQtzcp2YAEgvmyEei4:b-kj76ip) ([raw file](https://github.com/starkware-libs/committer/blob/23b7312f455ecdc129d0ddd2f3342684ce9dbc1a/crates/committer/src/types.rs#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok... the only way to do it is if we remove the `impl From<Felt> for StarknetTypesFelt`.
if we want to convert `x: Felt` to StarknetTypesFelt we will need to use `x.0`, i.e. make `Felt`'s inner StarknetTypesFelt a `pub` field.
Unblocking, up to you ATM if it's worth it or not.
If we get too many conversion boilerplate functions I would consider doing it,
or implementing a macro for it (see new comment)
</blockquote></details>

Removing the `impl From<Felt> for StarknetTypesFelt` also seemed to have issues. Will try the macro solution.
___
*[`crates/committer/src/types.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/committer/37#-NvCT22BCUcg1B2NY81k:-NvQty6L-kwdSK7VL64z:b-hi6rqx) ([raw file](https://github.com/starkware-libs/committer/blob/5fd1367b2beffa6fca0ae3acce8da85738e4eab6/crates/committer/src/types.rs#L28)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

WDYT of this option?
Currently support `StarknetTypesFelt, u128, u8` and can add more types later with minimal effort
</blockquote></details>

OK, I'm not familiar with macros, so I need to read about it, might take a bit of time.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/committer/37#-NvCPvIF9eq-o95AZCqw:-NvQuo788yIOU3LKSXpZ:b2jmwas) ([raw file](https://github.com/starkware-libs/committer/blob/5fd1367b2beffa6fca0ae3acce8da85738e4eab6/crates/committer/src/patricia_merkle_tree/types.rs#L43)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

generic impl
</blockquote></details>

Doesn't compile, looking into it.
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/committer/37#-NvCQKtfAHnhCwUSgBfh:-NvQtanT7rjRJk3UBlPg:b-smd88r) ([raw file](https://github.com/starkware-libs/committer/blob/5fd1367b2beffa6fca0ae3acce8da85738e4eab6/crates/committer/src/patricia_merkle_tree/types_test.rs#L47)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please compute these 4 cases on the python side, check the result, and paste it here with an `assert_eq!` (to test for regression with existing implementation)
</blockquote></details>

Done. There's something strange here - in the python test it uses SHA256 hash for the nodes_test. Do you know why? I changed the hash_function to Pedersen and recomputed, and then the results match.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/37)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @aner-starkware)

___
*[`crates/committer/src/types.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/committer/37#-NvCT22BCUcg1B2NY81k:-NvR5UYF4hVQMu5VzgRY:b-xqvsz8) ([raw file](https://github.com/starkware-libs/committer/blob/5fd1367b2beffa6fca0ae3acce8da85738e4eab6/crates/committer/src/types.rs#L28)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

OK, I'm not familiar with macros, so I need to read about it, might take a bit of time.
</blockquote></details>

sure. LMK if you want to talk f2f.
Also, there's an example [here](https://github.com/starkware-libs/blockifier/blob/main/crates/native_blockifier/src/errors.rs#L18-L77) in the blockifier repo if you want to TAL, and available for chat about it
___
*[`crates/committer/src/types.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/committer/37#-NvR5zFR01Dy2FTdyjK4:-NvR5zFR01Dy2FTdyjK5:bx2f00b) ([raw file](https://github.com/starkware-libs/committer/blob/25d00dac00b628a3b07b79f45775691ab2c8383c/crates/committer/src/types.rs#L53)):*
> ```XML
>         StarknetTypesFelt::from_hex(hex_string)
>             .map(Self)
>             .map_err(|_| FromStrError)
> ```

`StarknetTypesFelt::from_hex` returns a result object in which the error type is identical to this method's error type. propagate it by the `?` operator, then the `StarknetTypesFelt` instance in the `Ok()` case can be converted to `Self` with `into()`



_Suggestion:_
```XML
        Ok(StarknetTypesFelt::from_hex(hex_string)?.into())
```
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 47 at r4](https://reviewable.io/reviews/starkware-libs/committer/37#-NvCQKtfAHnhCwUSgBfh:-NvR6YNRETUmr9QOuCFt:bnx9vnl) ([raw file](https://github.com/starkware-libs/committer/blob/5fd1367b2beffa6fca0ae3acce8da85738e4eab6/crates/committer/src/patricia_merkle_tree/types_test.rs#L47)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. There's something strange here - in the python test it uses SHA256 hash for the nodes_test. Do you know why? I changed the hash_function to Pedersen and recomputed, and then the results match.
</blockquote></details>

IDK why, good work though :)
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 75 at r5](https://reviewable.io/reviews/starkware-libs/committer/37#-NvR6eos-eQ577NZwWjQ:-NvR6eos-eQ577NZwWjR:b-rtagwg) ([raw file](https://github.com/starkware-libs/committer/blob/25d00dac00b628a3b07b79f45775691ab2c8383c/crates/committer/src/patricia_merkle_tree/types_test.rs#L75)):*
> ```XML
>     );
>     println!("hash_output: {:?}", hash_output);
>     println!("expected_hash: {:?}", expected_hash);
> ```

delete

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/37)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/types.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/committer/37#-NvCT22BCUcg1B2NY81k:-NvRHxJ60dRr6KfcXoyw:b-1ymizx) ([raw file](https://github.com/starkware-libs/committer/blob/5fd1367b2beffa6fca0ae3acce8da85738e4eab6/crates/committer/src/types.rs#L28)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

sure. LMK if you want to talk f2f.
Also, there's an example [here](https://github.com/starkware-libs/blockifier/blob/main/crates/native_blockifier/src/errors.rs#L18-L77) in the blockifier repo if you want to TAL, and available for chat about it
</blockquote></details>

Done. It works, but I still don't fully understand the above syntax (is it some recursive macro?). Maybe we can have a short talk.
___
*[`crates/committer/src/types.rs` line 53 at r5](https://reviewable.io/reviews/starkware-libs/committer/37#-NvR5zFR01Dy2FTdyjK4:-NvREjCE6w1ri61NJv3u:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/25d00dac00b628a3b07b79f45775691ab2c8383c/crates/committer/src/types.rs#L53)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`StarknetTypesFelt::from_hex` returns a result object in which the error type is identical to this method's error type. propagate it by the `?` operator, then the `StarknetTypesFelt` instance in the `Ok()` case can be converted to `Self` with `into()`
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 75 at r5](https://reviewable.io/reviews/starkware-libs/committer/37#-NvR6eos-eQ577NZwWjQ:-NvRErM89si4WeQwL21J:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/25d00dac00b628a3b07b79f45775691ab2c8383c/crates/committer/src/patricia_merkle_tree/types_test.rs#L75)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/37)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/committer/src/types.rs` line 28 at r4](https://reviewable.io/reviews/starkware-libs/committer/37#-NvCT22BCUcg1B2NY81k:-NvROKUY12zYyMNTHSjB:bqoq5yf) ([raw file](https://github.com/starkware-libs/committer/blob/5fd1367b2beffa6fca0ae3acce8da85738e4eab6/crates/committer/src/types.rs#L28)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done. It works, but I still don't fully understand the above syntax (is it some recursive macro?). Maybe we can have a short talk.
</blockquote></details>

Yes, it is a recursive macro :)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/37)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 43 at r4](https://reviewable.io/reviews/starkware-libs/committer/37#-NvCPvIF9eq-o95AZCqw:-NvWMYWU0uNkM_hk5OYx:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/5fd1367b2beffa6fca0ae3acce8da85738e4eab6/crates/committer/src/patricia_merkle_tree/types.rs#L43)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Doesn't compile, looking into it.
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/37#-:-NvWO_hJC97suwn9466B:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
