### PR TITLE
feat(block_hash): add tx execution info

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/193)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/193)* status: all files reviewed, 2 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/committer_cli/src/block_hash.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/committer/193#-NzXXiplDs0imcSpsBrQ:-NzXXipmDH75OTIMrOOZ:b-jg4wfn) ([raw file](https://github.com/starkware-libs/committer/blob/325548bed14b510186c6118a668cf4b9b74d5d9d/crates/committer_cli/src/block_hash.rs#L20)):*
> ```XML
>     pub l1_gas: u128,
>     pub l1_data_gas: u128,
> }
> ```

while you're here...



_Suggestion:_
```XML
pub(crate) struct BlockInfo {
    pub da_mode: bool,
    pub l1_gas_price_per_token: GasPricePerToken,
    pub l1_data_gas_price_per_token: GasPricePerToken,
}

pub(crate) type RawResourcesMapping = HashMap<String, u128>;

#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub(crate) struct GasVector {
    pub l1_gas: u128,
    pub l1_data_gas: u128,
}
```
___
*[`crates/committer_cli/src/block_hash.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/committer/193#-NzXXqLz1-d0JQDYj-RS:-NzXXqLz1-d0JQDYj-RT:b-nh4gd5) ([raw file](https://github.com/starkware-libs/committer/blob/325548bed14b510186c6118a668cf4b9b74d5d9d/crates/committer_cli/src/block_hash.rs#L33)):*
> ```XML
>     pub execution_status: TransactionExecutionStatus,
>     pub da_gas: Option<GasVector>,
> }
> ```

@AvivYossef-starkware didn't you add a total_gas field here?



_Code quote:_
```XML
#[allow(dead_code)]
#[derive(Debug, Deserialize, Serialize)]
pub(crate) struct ThinTransactionExecutionInfo {
    pub events: Vec<Event>,
    pub l2_to_l1_messages: Vec<MessageToL1>,
    pub actual_fee: Fee,
    pub actual_resources: RawResourcesMapping,
    pub execution_status: TransactionExecutionStatus,
    pub da_gas: Option<GasVector>,
}
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/193)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/committer_cli/src/block_hash.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/committer/193#-NzXXqLz1-d0JQDYj-RS:-NzcWEXw9gmgRV6g5058:b-9i1pq6) ([raw file](https://github.com/starkware-libs/committer/blob/325548bed14b510186c6118a668cf4b9b74d5d9d/crates/committer_cli/src/block_hash.rs#L33)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@AvivYossef-starkware didn't you add a total_gas field here?
</blockquote></details>

I add it , look here
https://reviewable.io/reviews/starkware-libs/blockifier/1933#-

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/193)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/src/block_hash.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/committer/193#-NzXXiplDs0imcSpsBrQ:-NzcYVbQ5AwtBQPKGO0e:b-k9qob4) ([raw file](https://github.com/starkware-libs/committer/blob/325548bed14b510186c6118a668cf4b9b74d5d9d/crates/committer_cli/src/block_hash.rs#L20)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

while you're here...
</blockquote></details>

This change was reverted.
I use only `starknet-api` objects.
___
*[`crates/committer_cli/src/block_hash.rs` line 33 at r1](https://reviewable.io/reviews/starkware-libs/committer/193#-NzXXqLz1-d0JQDYj-RS:-NzcYiJJEv0e9F4khD1s:buo9nmt) ([raw file](https://github.com/starkware-libs/committer/blob/325548bed14b510186c6118a668cf4b9b74d5d9d/crates/committer_cli/src/block_hash.rs#L33)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

I add it , look here
https://reviewable.io/reviews/starkware-libs/blockifier/1933#-
</blockquote></details>

Same here

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/193#-:-Nzce8KWAgN37fxHLgWc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
