### PR TITLE
refactor: take trivial_updates_config as an input from python

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/270)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
python side [PR](https://reviewable.io/reviews/starkware-industries/starkware/35400)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/270#-:-O0so6acCwktVzNrjy2K:bn3z7y6)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @TzahiTaub)

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/270)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/270)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/270#-:-O0xAzv8-CSLZuZfvgBe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
