### PR TITLE
test: add regression test

### PR DESCRIPTION
**Pull request by aner-starkware**
Preparing for regression test

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)

### CODE REVIEW

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/committer/277#-O1GXcI6DUVse-hyRkZh:-O1GXcI6DUVse-hyRkZi:bop4pby) ([raw file](https://github.com/starkware-libs/committer/blob/2172b346736502cd9d8dcaa2930b6dc2a0618f5b/crates/committer_cli/src/tests/benchmark_tests.rs#L51)):*
> ```XML
>     // }
>     // let expected_storage_changes = input.get("expected_storage_changes").unwrap();
>     // assert_eq!(storage_changes, expected_storage_changes);
> ```

Uncomment?



_Code quote:_
```XML
    // TODO: Assert the storage changes.
    // let storage_changes = output_map.get("storage_changes").unwrap();
    // let expected_storage_changes = input.get("expected_storage_changes").unwrap();
    // match storage_changes {
    //     Value::Object(storage_changes) => {
    //         for (key, value) in storage_changes.iter() {
    //             println!("key: {}, value: {}", key, value);
    //         }
    //     }
    //     _ => panic!("Expected storage changes to be an object."),
    // }
    // let expected_storage_changes = input.get("expected_storage_changes").unwrap();
    // assert_eq!(storage_changes, expected_storage_changes);
```
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 87 at r2](https://reviewable.io/reviews/starkware-libs/committer/277#-O1GWkjG8ph5oW46aoOn:-O1GWkjG8ph5oW46aoOo:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/2172b346736502cd9d8dcaa2930b6dc2a0618f5b/crates/committer_cli/src/tests/benchmark_tests.rs#L87)):*
> ```XML
>     );
> 
>     //Assert the storage changes.
> ```





_Suggestion:_
```XML
// Assert the storage changes.
```
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/committer/277#-O1GX-hA7BHS5r4aYNW7:-O1GX-hA7BHS5r4aYNW8:b-nwdrh4) ([raw file](https://github.com/starkware-libs/committer/blob/2172b346736502cd9d8dcaa2930b6dc2a0618f5b/crates/committer_cli/src/tests/benchmark_tests.rs#L97)):*
> ```XML
>         serde_json::from_str(input.get("expected_facts").unwrap()).unwrap();
>     let allowed_diff: HashMap<String, Value> =
>         serde_json::from_str(input.get("allowed_diff").unwrap()).unwrap();
> ```

Please remove this and its "derivatives". We want the input file to have exactly the expected hashes (i.e., remove the empty facts from them). You can then assert the two hashmaps are equal without the manual loop.



_Code quote:_
```XML
    let allowed_diff: HashMap<String, Value> =
        serde_json::from_str(input.get("allowed_diff").unwrap()).unwrap();
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 51 at r2](https://reviewable.io/reviews/starkware-libs/committer/277#-O1GXcI6DUVse-hyRkZh:-O1GcHs_93Nbh0ooGMEl:b-f3eh0u) ([raw file](https://github.com/starkware-libs/committer/blob/2172b346736502cd9d8dcaa2930b6dc2a0618f5b/crates/committer_cli/src/tests/benchmark_tests.rs#L51)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Uncomment?
</blockquote></details>

Moved to next PR.
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 97 at r2](https://reviewable.io/reviews/starkware-libs/committer/277#-O1GX-hA7BHS5r4aYNW7:-O1GcLDZ3EjE4INyKkj2:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/2172b346736502cd9d8dcaa2930b6dc2a0618f5b/crates/committer_cli/src/tests/benchmark_tests.rs#L97)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Please remove this and its "derivatives". We want the input file to have exactly the expected hashes (i.e., remove the empty facts from them). You can then assert the two hashmaps are equal without the manual loop.
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)* status: all files reviewed, 7 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer_cli/benches/committer_bench.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/committer/277#-O1H2oc51oJWe9IT2v1O:-O1H2oc51oJWe9IT2v1P:bsffj9) ([raw file](https://github.com/starkware-libs/committer/blob/e4a0c4c8a1d11689facf80cdfbaa342e8d06f19d/crates/committer_cli/benches/committer_bench.rs#L67)):*
> ```XML
>             runtime.block_on(commit(committer_input, OUTPUT_PATH.to_owned()));
>         })
>     });
> ```

more structured this way, don't you think? (non-blocking)
```
#[derive(Deserialize)]
struct RegressionInput {
    committer_input: Input,
}
```



_Suggestion:_
```XML
    let input: RegressionInput = serde_json::from_str(FLOW_TEST_INPUT).unwrap();

    //TODO(Aner, 27/06/2024): output path should be a pipe (file on memory) to avoid disk IO in the benchmark.
    criterion.bench_function("full_committer_flow", |benchmark| {
        benchmark.iter(|| {
            runtime.block_on(commit(input.committer_input, OUTPUT_PATH.to_owned()));
        })
    });
```
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/committer/277#-O1H38tHEhILul6BsOEZ:-O1H38tHEhILul6BsOE_:b-mfmxbh) ([raw file](https://github.com/starkware-libs/committer/blob/e4a0c4c8a1d11689facf80cdfbaa342e8d06f19d/crates/committer_cli/src/tests/benchmark_tests.rs#L49)):*
> ```XML
> pub async fn test_benchmark_committer_flow() {
>     let input: HashMap<String, String> = serde_json::from_str(FLOW_TEST_INPUT).unwrap();
>     let committer_input = input.get("committer_input").unwrap();
> ```

see above (RegressionInput)



_Code quote:_
```XML
    let input: HashMap<String, String> = serde_json::from_str(FLOW_TEST_INPUT).unwrap();
    let committer_input = input.get("committer_input").unwrap();
```
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/committer/277#-O1H3FgPC1P3Na9hT9CY:-O1H3FgPC1P3Na9hT9CZ:b-e1wwz6) ([raw file](https://github.com/starkware-libs/committer/blob/e4a0c4c8a1d11689facf80cdfbaa342e8d06f19d/crates/committer_cli/src/tests/benchmark_tests.rs#L64)):*
> ```XML
> 
>     let expected_contract_storage_root_hash = input.get("contract_states_root").unwrap();
>     let expected_compiled_class_root_hash = input.get("contract_classes_root").unwrap();
> ```

better in this case to define a `RegressionOutput` struct with a `derive(Deserialize)`... the `get("field_name").unwrap()` pattern "defines the object", better to do that in a struct.



_Code quote:_
```XML
    let committer_output: HashMap<String, Value> =
        serde_json::from_str(&std::fs::read_to_string(OUTPUT_PATH).unwrap()).unwrap();

    let contract_storage_root_hash = committer_output.get("contract_storage_root_hash").unwrap();
    let compiled_class_root_hash = committer_output.get("compiled_class_root_hash").unwrap();

    let expected_contract_storage_root_hash = input.get("contract_states_root").unwrap();
    let expected_compiled_class_root_hash = input.get("contract_classes_root").unwrap();
```
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/committer/277#-O1H45eqEJ1nyiwSLorf:-O1H45eqEJ1nyiwSLorg:b-dw38xr) ([raw file](https://github.com/starkware-libs/committer/blob/e4a0c4c8a1d11689facf80cdfbaa342e8d06f19d/crates/committer_cli/src/tests/benchmark_tests.rs#L83)):*
> ```XML
> 
>     let expected_storage_changes: Map<String, Value> =
>         serde_json::from_str(input.get("expected_facts").unwrap()).unwrap();
> ```

can this nested JSON string be deserialized as part of a `RegressionOutput` struct? (see above)



_Code quote:_
```XML
    let expected_storage_changes: Map<String, Value> =
        serde_json::from_str(input.get("expected_facts").unwrap()).unwrap();
```
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 90 at r3](https://reviewable.io/reviews/starkware-libs/committer/277#-O1H4K4N-XmA5EMX4I0V:-O1H4K4N-XmA5EMX4I0W:b-cgdd2v) ([raw file](https://github.com/starkware-libs/committer/blob/e4a0c4c8a1d11689facf80cdfbaa342e8d06f19d/crates/committer_cli/src/tests/benchmark_tests.rs#L90)):*
> ```XML
>         }
>         _ => panic!("Expected storage changes object to be an object."),
>     }
> ```

can't you skip this `match` by calling `unwrap()` again on `storage_changes_obj`?



_Code quote:_
```XML
    match storage_changes_obj {
        Value::Object(storage_changes) => {
            assert_eq!(storage_changes, &expected_storage_changes);
        }
        _ => panic!("Expected storage changes object to be an object."),
    }
```

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)* status: all files reviewed, 5 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/committer_cli/benches/committer_bench.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/committer/277#-O1H2oc51oJWe9IT2v1O:-O1H6hIx3v7mSR5TWS1X:b32v57) ([raw file](https://github.com/starkware-libs/committer/blob/e4a0c4c8a1d11689facf80cdfbaa342e8d06f19d/crates/committer_cli/benches/committer_bench.rs#L67)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

more structured this way, don't you think? (non-blocking)
```
#[derive(Deserialize)]
struct RegressionInput {
    committer_input: Input,
}
```
</blockquote></details>

+1

**Comment by aner-starkware** [comment]
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 90 at r3](https://reviewable.io/reviews/starkware-libs/committer/277#-O1H4K4N-XmA5EMX4I0V:-O1H72kl6ry-UIGtlTlH:ber2a9u) ([raw file](https://github.com/starkware-libs/committer/blob/e4a0c4c8a1d11689facf80cdfbaa342e8d06f19d/crates/committer_cli/src/tests/benchmark_tests.rs#L90)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can't you skip this `match` by calling `unwrap()` again on `storage_changes_obj`?
</blockquote></details>

No, Rust doesn't allow it; I can do a destructuring with `let .. else`, is it preferable? (It is shorter)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer_cli/benches/committer_bench.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/committer/277#-O1H2oc51oJWe9IT2v1O:-O1HAEH97qoJyE6Yq2EG:bw7ddjr) ([raw file](https://github.com/starkware-libs/committer/blob/e4a0c4c8a1d11689facf80cdfbaa342e8d06f19d/crates/committer_cli/benches/committer_bench.rs#L67)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

+1
</blockquote></details>

But the committer input (for `commit`) is an `&str,` not an `Input` object (that's currently done inside `commit`). 
Regarding deserializing using structs, I'll add a TODO, and open a refactor PR after fixing the regression tests. 
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 49 at r3](https://reviewable.io/reviews/starkware-libs/committer/277#-O1H38tHEhILul6BsOEZ:-O1HCP-G8BxGq9YOfCtw:b-hukn99) ([raw file](https://github.com/starkware-libs/committer/blob/e4a0c4c8a1d11689facf80cdfbaa342e8d06f19d/crates/committer_cli/src/tests/benchmark_tests.rs#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above (RegressionInput)
</blockquote></details>

Added TODO.
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 64 at r3](https://reviewable.io/reviews/starkware-libs/committer/277#-O1H3FgPC1P3Na9hT9CY:-O1HCT1u9ZteGNeTOc8k:b-hukn99) ([raw file](https://github.com/starkware-libs/committer/blob/e4a0c4c8a1d11689facf80cdfbaa342e8d06f19d/crates/committer_cli/src/tests/benchmark_tests.rs#L64)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

better in this case to define a `RegressionOutput` struct with a `derive(Deserialize)`... the `get("field_name").unwrap()` pattern "defines the object", better to do that in a struct.
</blockquote></details>

Added TODO.
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 83 at r3](https://reviewable.io/reviews/starkware-libs/committer/277#-O1H45eqEJ1nyiwSLorf:-O1HCL018XuuDsdpIFvC:b-s9qn10) ([raw file](https://github.com/starkware-libs/committer/blob/e4a0c4c8a1d11689facf80cdfbaa342e8d06f19d/crates/committer_cli/src/tests/benchmark_tests.rs#L83)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can this nested JSON string be deserialized as part of a `RegressionOutput` struct? (see above)
</blockquote></details>

Will try in a later refactoring PR.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware)

___
*[`crates/committer_cli/benches/committer_bench.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/committer/277#-O1HFgUS9V8jj-HVXzz8:-O1HFgUS9V8jj-HVXzz9:bmkryzq) ([raw file](https://github.com/starkware-libs/committer/blob/2009ffe2fb489da1fe8365de35f655bba99f98da/crates/committer_cli/benches/committer_bench.rs#L59)):*
> ```XML
>     };
> 
>     let input: HashMap<String, String> = serde_json::from_str(FLOW_TEST_INPUT).unwrap();
> ```

add todo here
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 90 at r3](https://reviewable.io/reviews/starkware-libs/committer/277#-O1H4K4N-XmA5EMX4I0V:-O1HFY_35CTcLgCph-xU:b-hv9eb7) ([raw file](https://github.com/starkware-libs/committer/blob/e4a0c4c8a1d11689facf80cdfbaa342e8d06f19d/crates/committer_cli/src/tests/benchmark_tests.rs#L90)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

No, Rust doesn't allow it; I can do a destructuring with `let .. else`, is it preferable? (It is shorter)
</blockquote></details>

yes :)
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/committer/277#-O1HFR2cEicMI-_FcWqy:-O1HFR2d2ig-8o3sXc5o:bt89e6h) ([raw file](https://github.com/starkware-libs/committer/blob/2009ffe2fb489da1fe8365de35f655bba99f98da/crates/committer_cli/src/tests/benchmark_tests.rs#L59)):*
> ```XML
> 
>     // Assert the output of the committer flow test.
>     let committer_output: HashMap<String, Value> =
> ```

add todo above here
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 78 at r4](https://reviewable.io/reviews/starkware-libs/committer/277#-O1HFVw12aWoVXEcKwy4:-O1HFVw12aWoVXEcKwy5:bmkryzq) ([raw file](https://github.com/starkware-libs/committer/blob/2009ffe2fb489da1fe8365de35f655bba99f98da/crates/committer_cli/src/tests/benchmark_tests.rs#L78)):*
> ```XML
> 
>     // Assert the storage changes.
>     let Value::Object(storage_changes) = committer_output
> ```

add todo here

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

___
*[`crates/committer_cli/benches/committer_bench.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/committer/277#-O1HFgUS9V8jj-HVXzz8:-O1HLm9d6Y1qdCYSaXHL:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/2009ffe2fb489da1fe8365de35f655bba99f98da/crates/committer_cli/benches/committer_bench.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add todo here
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 59 at r4](https://reviewable.io/reviews/starkware-libs/committer/277#-O1HFR2cEicMI-_FcWqy:-O1HLmy02AS6f902FYEB:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/2009ffe2fb489da1fe8365de35f655bba99f98da/crates/committer_cli/src/tests/benchmark_tests.rs#L59)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add todo above here
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

___
*[`crates/committer_cli/benches/committer_bench.rs` line 67 at r3](https://reviewable.io/reviews/starkware-libs/committer/277#-O1H2oc51oJWe9IT2v1O:-O1HRvScEcdSati4nbrd:b-95o3oy) ([raw file](https://github.com/starkware-libs/committer/blob/e4a0c4c8a1d11689facf80cdfbaa342e8d06f19d/crates/committer_cli/benches/committer_bench.rs#L67)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

But the committer input (for `commit`) is an `&str,` not an `Input` object (that's currently done inside `commit`). 
Regarding deserializing using structs, I'll add a TODO, and open a refactor PR after fixing the regression tests.
</blockquote></details>

Then have
```
#[derive(Deserialize)]
struct RegressionInput {
    committer_input: &str,
}
```

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware)

___
*[`crates/committer_cli/src/tests/flow_test_files_prefix` line 1 at r6](https://reviewable.io/reviews/starkware-libs/committer/277#-O1HUyfuB5U_idCJ-5_Q:-O1HUyfuB5U_idCJ-5_R:b-k7i9ry) ([raw file](https://github.com/starkware-libs/committer/blob/7c50039c965226b812d6b5c5e989bf3208301be6/crates/committer_cli/src/tests/flow_test_files_prefix#L1)):*
> ```
> c4c2b5d
> ```

Input files should be adjusted



_Code quote:_
```
c4c2b5d
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

___
*[`crates/committer_cli/src/tests/flow_test_files_prefix` line 1 at r6](https://reviewable.io/reviews/starkware-libs/committer/277#-O1HUyfuB5U_idCJ-5_Q:-O1HZ-Rf0o9JsFPb_mmB:btis2pw) ([raw file](https://github.com/starkware-libs/committer/blob/7c50039c965226b812d6b5c5e989bf3208301be6/crates/committer_cli/src/tests/flow_test_files_prefix#L1)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Input files should be adjusted
</blockquote></details>

They were, but there was a conflict with Nimrod's change.

**Review by TzahiTaub — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/277)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
