### PR TITLE
chore!: move filled tree factory function to filled tree tree trait

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/125)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/125)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/125#-NyAR9ZT1bXaGN1hVvQn:-NyAR9ZT1bXaGN1hVvQo:b3x7suh) (no related file):*
Outline:
1. Moved error variants from the updated tree enum to the filled tree enum
2. Moved methods from the updated tree to the filled tree (some became associated function on the way).
3. As the updated skeleton no longer outputs a filled tree, it does not need a generic leaf type parameter anymore.
4. The filled tree error now needs the `L` leaf type parameter
5. Added `get_nodes` on the updated skeleton trait so the filled tree creation function has access to skeleton nodes for initilization

___
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 0 at r2](https://reviewable.io/reviews/starkware-libs/committer/125#-NyAQIKe1xrC5c0beKwb:-NyAQIKe1xrC5c0beKwc:b-ffe619) ([raw file](https://github.com/starkware-libs/committer/blob/e065fe7d513607f480384f69708f6f606e369b3f/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L0)):*
1. errors moved from updated tree enum to filled tree enum since the construction logic has moved.
2. `derive_more::Display` doesn't work for struct errors (e.g. `DoubleUpdate`), so removed this derive and replaced with `#[error]` attributes.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 0 at r2](https://reviewable.io/reviews/starkware-libs/committer/125#-NyAQfr_3IsMo18F1pH7:-NyAQfr_3IsMo18F1pH8:b-es3k06) ([raw file](https://github.com/starkware-libs/committer/blob/e065fe7d513607f480384f69708f6f606e369b3f/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L0)):*
Functions copied from updated skeleton tree. Some minor changes:
1. methods because associated functions (`self.` -> `Self::`)
2. error types changed from updated skeleton error to filled tree error
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs` line 0 at r2](https://reviewable.io/reviews/starkware-libs/committer/125#-NyAQyCkAerNypik8aHM:-NyAQyCkAerNypik8aHN:b-ugs1jo) ([raw file](https://github.com/starkware-libs/committer/blob/e065fe7d513607f480384f69708f6f606e369b3f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs#L0)):*
while moving errors from this enum to the filled tree error enum: added the `thiserror::Error` derive and the `#[error]` attribute
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs` line 15 at r2](https://reviewable.io/reviews/starkware-libs/committer/125#-NyAR3ql3z3ZQJ3q6YEz:-NyAR3qm-UaZ6up_zU3h:bkrfxe) ([raw file](https://github.com/starkware-libs/committer/blob/ea45f5dd2f735caeeaf951ab05ab362b5d9ca492/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs#L15)):*
> ```XML
>     },
>     PoisonedLock(String),
>     NonDroppedPointer(String),
> ```

this error was unused



_Code quote:_
```XML
NonDroppedPointer(String),
```

**Review by AvivYossef-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/125#-:-NyEeV8BD7wepZqFX49O:bnfp4nl)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/125)* status: all files reviewed, 8 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/committer/125#-NyKgG7A2mHPPrDwZ0SI:-NyKgG7A2mHPPrDwZ0SJ:b-edbvir) ([raw file](https://github.com/starkware-libs/committer/blob/e065fe7d513607f480384f69708f6f606e369b3f/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L21)):*
> ```XML
>     SerializeError(#[from] serde_json::Error),
>     #[error(transparent)]
>     UpdatedSkeletonError(#[from] UpdatedSkeletonTreeError),
> ```

Why was this added?



_Code quote:_
```XML
 UpdatedSkeletonError(#[from] UpdatedSkeletonTreeError),
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 193 at r2](https://reviewable.io/reviews/starkware-libs/committer/125#-NyKgYUyEz6k95Of229n:-NyKgYUyEz6k95Of229o:b-tpro6a) ([raw file](https://github.com/starkware-libs/committer/blob/e065fe7d513607f480384f69708f6f606e369b3f/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L193)):*
> ```XML
>     async fn create<H: HashFunction, TH: TreeHashFunction<L, H>>(
>         updated_skeleton: impl UpdatedSkeletonTree,
>         modifications: &Modifications<L>,
> ```

This was changed AFAIK



_Suggestion:_
```XML
LeafModifications
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs` line 4 at r2](https://reviewable.io/reviews/starkware-libs/committer/125#-NyKfewj3y9TKDcyFVxu:-NyKfewl0Dmz5Pi11y44:bwhauqh) ([raw file](https://github.com/starkware-libs/committer/blob/e065fe7d513607f480384f69708f6f606e369b3f/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs#L4)):*
> ```XML
> 
> #[derive(Debug, thiserror::Error)]
> #[allow(dead_code)]
> ```

Is this needed?



_Code quote:_
```XML
#[allow(dead_code)]
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/125)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 21 at r2](https://reviewable.io/reviews/starkware-libs/committer/125#-NyKgG7A2mHPPrDwZ0SI:-NyKt4RQ0S5o4bVMA9oD:br2903f) ([raw file](https://github.com/starkware-libs/committer/blob/e065fe7d513607f480384f69708f6f606e369b3f/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L21)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Why was this added?
</blockquote></details>

this line in `compute_filled_tree_rec`:
```
let node = updated_skeleton.get_node(index)?;
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 193 at r2](https://reviewable.io/reviews/starkware-libs/committer/125#-NyKgYUyEz6k95Of229n:-NyKtA_Q-UDgC-Hb1TNe:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e065fe7d513607f480384f69708f6f606e369b3f/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L193)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

This was changed AFAIK
</blockquote></details>

Done.

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 5 of 5 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/125)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @nimrod-starkware)

**Pull request merged**
