### PR TITLE
feat(skeleton): create in UpdatedSkeletonTree (completed)

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/169)

### CODE REVIEW

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/169)* status: 2 of 9 files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/169)* status: all files reviewed, 6 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/committer/169#-Nz9cj_q4UvlVeEwZV6s:-Nz9cj_q4UvlVeEwZV6t:brididz) ([raw file](https://github.com/starkware-libs/committer/blob/694696beae0964833e40eeeeb62222d5ceb5a405/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L26)):*
> ```XML
>         Self: std::marker::Sized;
> 
>     fn get_nodes(&self) -> &HashMap<NodeIndex, OriginalSkeletonNode>;
> ```

can you search and replace this type? it's used often (define a type for it)



_Suggestion:_
```XML
OriginalSkeletonNodeMap
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/committer/169#-Nz9d-VaD89yqRyce5Vw:-Nz9d-Vb5kDbiie-5Lce:bfwhqgz) ([raw file](https://github.com/starkware-libs/committer/blob/694696beae0964833e40eeeeb62222d5ceb5a405/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L69)):*
> ```XML
>                     },
>                 ))
>                 .collect();
> ```

this function is getting long, please move this logic to a private method of `UpdatedSkeletonTreeImpl`



_Code quote:_
```XML
        let skeleton_tree: HashMap<NodeIndex, UpdatedSkeletonNode> =
            leaf_modifications
                .iter()
                .filter(|(_, leaf)| !leaf.is_zero())
                .map(|(index, _)| (*index, UpdatedSkeletonNode::Leaf))
                .chain(original_skeleton.get_nodes().iter().filter_map(
                    |(index, node)| match node {
                        OriginalSkeletonNode::LeafOrBinarySibling(hash) => {
                            Some((*index, UpdatedSkeletonNode::Sibling(*hash)))
                        }
                        OriginalSkeletonNode::UnmodifiedBottom(hash) => {
                            Some((*index, UpdatedSkeletonNode::UnmodifiedBottom(*hash)))
                        }
                        OriginalSkeletonNode::Binary | OriginalSkeletonNode::Edge(_) => None,
                    },
                ))
                .collect();
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/committer/169#-Nz9dG5o46eJzmq_1l_V:-Nz9dG5o46eJzmq_1l_W:bjj2p7j) ([raw file](https://github.com/starkware-libs/committer/blob/694696beae0964833e40eeeeb62222d5ceb5a405/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L86)):*
> ```XML
>                 &leaf_indices,
>             )
>         };
> ```

extract to private method



_Code quote:_
```XML
        let leaf_indices: Vec<NodeIndex> = leaf_modifications.keys().cloned().collect();
        let temp_root = if original_skeleton.get_nodes().is_empty() {
            updated_skeleton_tree.update_node_in_empty_tree(&NodeIndex::ROOT, &leaf_indices)
        } else {
            updated_skeleton_tree.update_node_in_nonempty_tree(
                &NodeIndex::ROOT,
                original_skeleton.get_nodes_mut(),
                &leaf_indices,
            )
        };
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/committer/169#-Nz9dpoc-k2kUCnDKQU9:-Nz9dpoc-k2kUCnDKQUA:bap9gcd) ([raw file](https://github.com/starkware-libs/committer/blob/694696beae0964833e40eeeeb62222d5ceb5a405/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L90)):*
> ```XML
>         // Finalize root.
>         match temp_root {
>             TempSkeletonNode::Empty => {}
> ```

this must be true in this case, right?



_Suggestion:_
```XML
TempSkeletonNode::Empty => assert!(updated_skeleton_tree.skeleton_tree.is_empty())
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/committer/169#-Nz9e3Ly-FukgOHW1Z8r:-Nz9e3Ly-FukgOHW1Z8s:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/694696beae0964833e40eeeeb62222d5ceb5a405/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L109)):*
> ```XML
>                             OriginalSkeletonNode::UnmodifiedBottom(_) => {
>                                 unreachable!("Root node cannot be an unmodified bottom")
>                             }
> ```





_Suggestion:_
```XML
                            OriginalSkeletonNode::LeafOrBinarySibling(_)
                            | OriginalSkeletonNode::UnmodifiedBottom(_) => {
                                unreachable!(
                                    "Root node cannot be an unmodified bottom or a sibling."
                                )
                            }
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 110 at r2](https://reviewable.io/reviews/starkware-libs/committer/169#-Nz9dRg-Ayd9dgoJmiq7:-Nz9dRg08Ecz9g_a9sy3:bmvtgt5) ([raw file](https://github.com/starkware-libs/committer/blob/694696beae0964833e40eeeeb62222d5ceb5a405/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L110)):*
> ```XML
>                                 unreachable!("Root node cannot be an unmodified bottom")
>                             }
>                         },
> ```

IMO this would be more readable if you put the new node in a variable (`let new_node = match original_skeleton_node { ... }`) above the `skeleton_tree.insert`



_Code quote:_
```XML
                        match original_skeleton_node {
                            OriginalSkeletonNode::Binary => UpdatedSkeletonNode::Binary,
                            OriginalSkeletonNode::Edge(path_to_bottom) => {
                                UpdatedSkeletonNode::Edge(path_to_bottom)
                            }
                            OriginalSkeletonNode::LeafOrBinarySibling(_) => {
                                unreachable!("Root node cannot be a sibling")
                            }
                            OriginalSkeletonNode::UnmodifiedBottom(_) => {
                                unreachable!("Root node cannot be an unmodified bottom")
                            }
                        },
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/169)* status: 5 of 13 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs` line 26 at r2](https://reviewable.io/reviews/starkware-libs/committer/169#-Nz9cj_q4UvlVeEwZV6s:-NzKURd0A3iSC5Y02HWr:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/694696beae0964833e40eeeeb62222d5ceb5a405/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs#L26)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you search and replace this type? it's used often (define a type for it)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/committer/169#-Nz9d-VaD89yqRyce5Vw:-NzKWLqu0mbBsar-s2iX:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/694696beae0964833e40eeeeb62222d5ceb5a405/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L69)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this function is getting long, please move this logic to a private method of `UpdatedSkeletonTreeImpl`
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/committer/169#-Nz9dG5o46eJzmq_1l_V:-NzK_AWw0E0xq8D8FwLy:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/694696beae0964833e40eeeeb62222d5ceb5a405/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L86)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

extract to private method
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 90 at r2](https://reviewable.io/reviews/starkware-libs/committer/169#-Nz9dpoc-k2kUCnDKQU9:-NzKX-Su1fsbyBgeFqLR:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/694696beae0964833e40eeeeb62222d5ceb5a405/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L90)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this must be true in this case, right?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 109 at r2](https://reviewable.io/reviews/starkware-libs/committer/169#-Nz9e3Ly-FukgOHW1Z8r:-NzKX8FW452whfiYxmyQ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/694696beae0964833e40eeeeb62222d5ceb5a405/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L109)):*
> ```XML
>                             OriginalSkeletonNode::UnmodifiedBottom(_) => {
>                                 unreachable!("Root node cannot be an unmodified bottom")
>                             }
> ```

Done.

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/169)* status: 5 of 13 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs` line 3 at r3](https://reviewable.io/reviews/starkware-libs/committer/169#-NzKcI2FC4wE6LnhIukh:-NzKcI2FC4wE6LnhIuki:b7lf06j) ([raw file](https://github.com/starkware-libs/committer/blob/9da95bfaa1a45afc5f2a1ddd3b5e1d8922569ece/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs#L3)):*
> ```XML
> use std::collections::HashMap;
> 
> use crate::felt::Felt;
> ```

Moved all filled_tree tests to a new file

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/169#-:-NzN6ls-41dID-z9fw-z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
