### PR TITLE
chore(skeleton): add new ctor to PathToBottom

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/188)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/188)* status: 5 of 14 files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/errors.rs` line 15 at r1](https://reviewable.io/reviews/starkware-libs/committer/188#-NzT2R0IEB0id6t4zAnG:-NzT2R0IEB0id6t4zAnH:b-dojbva) ([raw file](https://github.com/starkware-libs/committer/blob/b9cfc2d6019ed55ad94bbe138690917a19b8e796/crates/committer/src/patricia_merkle_tree/node_data/errors.rs#L15)):*
> ```XML
>     },
> 
>     #[error("EdgePath {path:?} is too long for EdgePathLength {length:?}.")]
> ```

no newline between error variants (for consistency with everyone else)



_Suggestion:_
```XML
    },
    #[error("EdgePath {path:?} is too long for EdgePathLength {length:?}.")]
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/committer/188#-NzT2a2OD-cO7OvrtKQt:-NzT2a2OD-cO7OvrtKQu:b7hrqpe) ([raw file](https://github.com/starkware-libs/committer/blob/b9cfc2d6019ed55ad94bbe138690917a19b8e796/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L95)):*
> ```XML
> }
> 
> #[non_exhaustive]
> ```

ok this doesn't work



_Code quote:_
```XML
#[non_exhaustive]
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/188)* status: 5 of 14 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 95 at r1](https://reviewable.io/reviews/starkware-libs/committer/188#-NzT2a2OD-cO7OvrtKQt:-NzT5b8q0lvIrmq1Br2n:b2nh4fg) ([raw file](https://github.com/starkware-libs/committer/blob/b9cfc2d6019ed55ad94bbe138690917a19b8e796/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L95)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok this doesn't work
</blockquote></details>

:)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/188)* status: all files reviewed, 5 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/committer/188#-NzTIDSw9mSAClmnbIZj:-NzTIDSw9mSAClmnbIZk:b-brgzha) ([raw file](https://github.com/starkware-libs/committer/blob/d21a1768cee981d80a6b41ac1eb71da5b4344bbe/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L107)):*
> ```XML
>     /// Creates a new [PathToBottom] instance.
>     // Asserts the path is not longer than the length.
>     pub fn new(path: EdgePath, length: EdgePathLength) -> Result<Self, PathToBottomError> {
> ```

define a type for this (usages below)



_Suggestion:_
```XML
PathToBottomResult
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/committer/188#-NzTI0UQBBO_f0IGOzGQ:-NzTI0UQBBO_f0IGOzGR:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/d21a1768cee981d80a6b41ac1eb71da5b4344bbe/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L154)):*
> ```XML
>             _fake_field: (),
>         }
>     }
> ```





_Suggestion:_
```XML
    pub(crate) fn concat_paths(&self, other: Self) -> PathToBottomResult {
        Self::new(
            EdgePath::from((self.path.0 << other.length.0) + other.path.0),
            self.length + other.length,
        )
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/committer/188#-NzTIJTl5fxoeNCOP1sa:-NzTIJTl5fxoeNCOP1sb:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/d21a1768cee981d80a6b41ac1eb71da5b4344bbe/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L160)):*
> ```XML
>         &self,
>         n_edges: EdgePathLength,
>     ) -> Result<Self, PathToBottomError> {
> ```





_Suggestion:_
```XML
PathToBottomResult
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/committer/188#-NzTI7PQ4kS1mrzUvYrT:-NzTI7PQ4kS1mrzUvYrU:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/d21a1768cee981d80a6b41ac1eb71da5b4344bbe/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L171)):*
> ```XML
>             length: self.length - n_edges,
>             _fake_field: (),
>         })
> ```





_Suggestion:_
```XML
        Self::new(
            EdgePath(self.path.0 >> n_edges.0),
            self.length - n_edges,
        )
```
___
*[`crates/committer/src/storage/errors.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/committer/188#-NzTIW9GEHfKUwge_gR0:-NzTIW9GEHfKUwge_gR1:b-fxwnu6) ([raw file](https://github.com/starkware-libs/committer/blob/d21a1768cee981d80a6b41ac1eb71da5b4344bbe/crates/committer/src/storage/errors.rs#L28)):*
> ```XML
>     EdgePathError(#[from] EdgePathError),
>     #[error("Illegal PathToBottom: {0}")]
>     PathToBottomError(#[from] PathToBottomError),
> ```

while you're here... these should be transparent



_Suggestion:_
```XML
    #[error(transparent)]
    ParsingError(#[from] serde_json::Error),
    #[error(transparent)]
    EdgePathError(#[from] EdgePathError),
    #[error(transparent)]
    PathToBottomError(#[from] PathToBottomError),
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/188)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 107 at r2](https://reviewable.io/reviews/starkware-libs/committer/188#-NzTIDSw9mSAClmnbIZj:-NzTQPkCBlkC6mvtg5G2:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d21a1768cee981d80a6b41ac1eb71da5b4344bbe/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L107)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

define a type for this (usages below)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/committer/188#-NzTI0UQBBO_f0IGOzGQ:-NzTQWUc1XWH_SoAnhXF:bt68kt6) ([raw file](https://github.com/starkware-libs/committer/blob/d21a1768cee981d80a6b41ac1eb71da5b4344bbe/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L154)):*
> ```XML
>             _fake_field: (),
>         }
>     }
> ```

Not sure if its better to expect inside the concat function, as concatenation of two valid PathToBottoms should be a valid PathToBottom (unless they are too long together, but I think this will panic with u8 overflow and won't raise an error in any case). WDYT?
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/committer/188#-NzTIJTl5fxoeNCOP1sa:-NzTQkYw-InHmtfukVyK:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d21a1768cee981d80a6b41ac1eb71da5b4344bbe/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L160)):*
> ```XML
>         &self,
>         n_edges: EdgePathLength,
>     ) -> Result<Self, PathToBottomError> {
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/committer/188#-NzTI7PQ4kS1mrzUvYrT:-NzTR0zEAc3JyFwytDZb:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d21a1768cee981d80a6b41ac1eb71da5b4344bbe/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L171)):*
> ```XML
>             length: self.length - n_edges,
>             _fake_field: (),
>         })
> ```

Done.
___
*[`crates/committer/src/storage/errors.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/committer/188#-NzTIW9GEHfKUwge_gR0:-NzTRYM2AJcDURbaZz3A:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d21a1768cee981d80a6b41ac1eb71da5b4344bbe/crates/committer/src/storage/errors.rs#L28)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

while you're here... these should be transparent
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/188#-:-NzTbpTs6jUhpvI8maag:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
