### PR TITLE
refactor: rename comments and functions after removing sibling & unmodified bottom variants

### PR DESCRIPTION
**Pull request by nimrod-starkware**
…dified bottom variants

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/213)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/213)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`Cargo.lock` line 1951 at r1](https://reviewable.io/reviews/starkware-libs/committer/213#-NzxSxz4DyRDnsg1RBIh:-NzxSxz5Erabi2yulXJv:b-ij2w9o) ([raw file](https://github.com/starkware-libs/committer/blob/7aae30c5d66f3f1dfc061db481e5d3918f3cf489/Cargo.lock#L1951)):*
> ```TOML
> version = "0.13.0-dev.5"
> source = "registry+https://github.com/rust-lang/crates.io-index"
> checksum = "6638fe4fef6dd20ed962ccbfef7c41bd2eba356b67e5e20b5e1caa955cf5e467"
> ```

revert (why did this happen?)



_Code quote:_
```TOML
version = "0.13.0-dev.5"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "6638fe4fef6dd20ed962ccbfef7c41bd2eba356b67e5e20b5e1caa955cf5e467"
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/committer/213#-NzxT6me5Pc9um0Fcu76:-NzxT6me5Pc9um0Fcu77:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/7aae30c5d66f3f1dfc061db481e5d3918f3cf489/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L167)):*
> ```XML
>         };
> 
>         // Not a leaf or an unmodified.
> ```





_Suggestion:_
```XML
unmodified node.
```

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/213)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/committer/213#-NzxTOAU4O8eZhgKsn8v:-NzxTOAV42IElFSgY23h:b-y9ily1) ([raw file](https://github.com/starkware-libs/committer/blob/7aae30c5d66f3f1dfc061db481e5d3918f3cf489/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L88)):*
> ```XML
>     /// unmodified nodes.
> 
>     fn fetch_nodes(
> ```

IIUC, you mean we fetch nodes that are both non empty and unmodified right? I think this is clearer as the `and` suggests they may be distinct nodes/ + Remove blank line.



_Suggestion:_
```XML
    /// Given a list of subtrees, traverses towards their leaves and fetches all non-empty,
    /// unmodified nodes.
    fn fetch_nodes(
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/213)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 88 at r1](https://reviewable.io/reviews/starkware-libs/committer/213#-NzxTOAU4O8eZhgKsn8v:-NzxYCLU5Z36pO9ijj97:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7aae30c5d66f3f1dfc061db481e5d3918f3cf489/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L88)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

IIUC, you mean we fetch nodes that are both non empty and unmodified right? I think this is clearer as the `and` suggests they may be distinct nodes/ + Remove blank line.
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 167 at r1](https://reviewable.io/reviews/starkware-libs/committer/213#-NzxT6me5Pc9um0Fcu76:-NzxZ9ZK7kkLmimAPpp3:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7aae30c5d66f3f1dfc061db481e5d3918f3cf489/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L167)):*
> ```XML
>         };
> 
>         // Not a leaf or an unmodified.
> ```

Done.
___
*[`Cargo.lock` line 1951 at r1](https://reviewable.io/reviews/starkware-libs/committer/213#-NzxSxz4DyRDnsg1RBIh:-NzxZ7hhBRMkOnfVPKCb:b-1tzy14) ([raw file](https://github.com/starkware-libs/committer/blob/7aae30c5d66f3f1dfc061db481e5d3918f3cf489/Cargo.lock#L1951)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

revert (why did this happen?)
</blockquote></details>

i have no idea why it happened

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/213#-:-Nzxbjgs0zoiMcKq9pog:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/213)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
