### PR TITLE
refactor: remove contract states input from python

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/254)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
python side [PR](https://reviewable.io/reviews/starkware-industries/starkware/35331)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/254#-:-O0ONAas5KR-PP-2PZ-W:bn3yn7l)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by nimrod-starkware — COMMENTED** [review]
`test benchmark` fails because the input format has changed, once this PR is approved I'll edit the test input to match

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/254#-:-O0ONDGk2_KLy3TJ2cfS:bbi6xa8)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/254)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer_cli/src/parse_input/raw_input.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/committer/254#-O0OWw931xWJ7hxSzQw-:-O0OWw94CSRXOs4J-0ro:b-1wgs53) ([raw file](https://github.com/starkware-libs/committer/blob/a2e59e6670513a5a4bdc77760c635ba96d17b746/crates/committer_cli/src/parse_input/raw_input.rs#L43)):*
> ```XML
>     pub storage_root_hash: RawFelt,
>     pub class_hash: RawFelt,
> }
> ```

Do we have a test that tests the case where the only update is a nonce update? no storage changes?
I am curious how we get the previous storage root if there were no storage updates and we don't read the leaves from python



_Code quote:_
```XML
/// Represents current state leaf at the contract state tree. Later will be casted to
/// HashMap<Felt, (nonce, class_hash, storage_root_hash)> entry.
pub(crate) struct RawContractStateLeaf {
    pub address: RawFelt,
    pub nonce: RawFelt,
    pub storage_root_hash: RawFelt,
    pub class_hash: RawFelt,
}
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/254)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer_cli/src/parse_input/raw_input.rs` line 43 at r2](https://reviewable.io/reviews/starkware-libs/committer/254#-O0OWw931xWJ7hxSzQw-:-O0OlspU4fJIhHG6soKg:b-6x4ebo) ([raw file](https://github.com/starkware-libs/committer/blob/a2e59e6670513a5a4bdc77760c635ba96d17b746/crates/committer_cli/src/parse_input/raw_input.rs#L43)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Do we have a test that tests the case where the only update is a nonce update? no storage changes?
I am curious how we get the previous storage root if there were no storage updates and we don't read the leaves from python
</blockquote></details>

we do read the leaves in python
https://github.com/starkware-industries/starkware/pull/35249

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/254#-:-O0OmxHp4zFQVuQTBR2G:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
