### PR TITLE
refactor: remove dependency on tree_height parameter on forest impl

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/182)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/182)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/committer/182#-NzS752zDsP5gm6axPY4:-NzS752zDsP5gm6axPY5:b-efwc7h) ([raw file](https://github.com/starkware-libs/committer/blob/a860c3389f5fcd3f72c5acc603a1dbce88ff3b24/crates/committer/src/patricia_merkle_tree/types_test.rs#L38)):*
> ```XML
> #[case(15, NodeIndex::FIRST_LEAF + NodeIndex::from(15))]
> #[case(0xDEADBEEF, NodeIndex::FIRST_LEAF + NodeIndex::from(0xDEADBEEF))]
> fn test_cast_to_node_index(
> ```

The test has become quite redundant when the function doesn't depend on tree height; maybe it's better to remove it.



_Code quote:_
```XML
fn test_cast_to_node_index
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/182)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/committer/182#-NzS752zDsP5gm6axPY4:-NzSE_Sv4kpP0QkSK800:b3z50vf) ([raw file](https://github.com/starkware-libs/committer/blob/a860c3389f5fcd3f72c5acc603a1dbce88ff3b24/crates/committer/src/patricia_merkle_tree/types_test.rs#L38)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

The test has become quite redundant when the function doesn't depend on tree height; maybe it's better to remove it.
</blockquote></details>

It checks conversions from contract address and storage key, so not completely redundant
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/committer/182#-NzSEmjACsDo7Kp-ExPo:-NzSEmjB6IGw9UZ8DtrA:b-92mna0) ([raw file](https://github.com/starkware-libs/committer/blob/a860c3389f5fcd3f72c5acc603a1dbce88ff3b24/crates/committer/src/patricia_merkle_tree/types_test.rs#L42)):*
> ```XML
>     #[case] expected_node_index: NodeIndex,
>     #[values(true, false)] from_contract_address: bool,
> ) {
> ```

shorter, and means the same



_Suggestion:_
```XML
#[rstest]
fn test_cast_to_node_index(
    #[values(0, 15, 0xDEADBEEF)] leaf_index: u128,
    #[values(true, false)] from_contract_address: bool,
) {
    let expected_node_index = NodeIndex::FIRST_LEAF + leaf_index;
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/182)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/committer/182#-NzSEmjACsDo7Kp-ExPo:-NzSIHcuCxKDMC3YM-3D:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/a860c3389f5fcd3f72c5acc603a1dbce88ff3b24/crates/committer/src/patricia_merkle_tree/types_test.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shorter, and means the same
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/182#-:-NzSLZg5B3Twzg5oWqfd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
