### PR TITLE
chore(skeleton): function has_leaves_on_both_sides

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/81)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/81)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/committer/81#-NwoaVWq3_GIxarU198x:-NwoaVWr2AsAuNwDY5N9:bap0ctu) ([raw file](https://github.com/starkware-libs/committer/blob/d2b60a9ac7d94da180e639cd09606df6cd578247/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs#L262)):*
> ```XML
>             .0
>             & child_direction_mask)
> }
> ```

return an error in case the largest leaf is an invalid index



_Suggestion:_
```XML
#[allow(dead_code)]
fn has_leaves_on_both_sides(
    root_height: &TreeHeight, leaf_indices: &[NodeIndex]
) -> Result<bool, ???> {
    if leaf_indices.len() <= 1 {
        return false;
    }
    let last_index = leaf_indices.last().expect("leaf_indices unexpectedly empty.");
    let child_direction_mask = U256::ONE << (root_height.0 - 1);
    if last_index >= child_direction_mask * 2 {
        return Err(???);
    }
    Ok((leaf_indices[0].0 & child_direction_mask)
        != (last_index.0 & child_direction_mask))
}
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc_test.rs` line 303 at r1](https://reviewable.io/reviews/starkware-libs/committer/81#-NwobIBr3ikydTc2z9X-:-NwobIBr3ikydTc2z9X0:boay8qb) ([raw file](https://github.com/starkware-libs/committer/blob/d2b60a9ac7d94da180e639cd09606df6cd578247/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc_test.rs#L303)):*
> ```XML
>     2, 
>     vec![NodeIndex::from(8),NodeIndex::from(10),NodeIndex::from(11)], 
>     true)]
> ```

I am confused: in a tree of height 2, we have a total of 7 nodes, no? what are 8, 10, 11? shouldn't it be 6, 7 or 4, 5?
same question for the `small_tree_negative` case



_Code quote:_
```XML
#[case::small_tree_positive(
    2,
    vec![NodeIndex::from(8),NodeIndex::from(10),NodeIndex::from(11)],
    true)]
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc_test.rs` line 304 at r1](https://reviewable.io/reviews/starkware-libs/committer/81#-NwoZ840-czXuQc-0Ci6:-NwoZ840-czXuQc-0Ci7:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/d2b60a9ac7d94da180e639cd09606df6cd578247/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc_test.rs#L304)):*
> ```XML
>     vec![NodeIndex::from(8),NodeIndex::from(10),NodeIndex::from(11)], 
>     true)]
> #[case::smal_tree_negative(2, vec![NodeIndex::from(10),NodeIndex::from(11)], false)]
> ```

typo



_Suggestion:_
```XML
small
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/81)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/committer/81#-NwoaVWq3_GIxarU198x:-Nwp7fLO5bN9QiKSVQL_:bsjn8mu) ([raw file](https://github.com/starkware-libs/committer/blob/d2b60a9ac7d94da180e639cd09606df6cd578247/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs#L262)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

return an error in case the largest leaf is an invalid index
</blockquote></details>

No, that's OK. I've extended the description, tell me if it's clear now.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc_test.rs` line 303 at r1](https://reviewable.io/reviews/starkware-libs/committer/81#-NwobIBr3ikydTc2z9X-:-NwpA7yg-45MQBgGbssm:b-rkvo5c) ([raw file](https://github.com/starkware-libs/committer/blob/d2b60a9ac7d94da180e639cd09606df6cd578247/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc_test.rs#L303)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I am confused: in a tree of height 2, we have a total of 7 nodes, no? what are 8, 10, 11? shouldn't it be 6, 7 or 4, 5?
same question for the `small_tree_negative` case
</blockquote></details>

See the new description. I was thinking of a tree of a total height of 3.

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/81)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc_test.rs` line 303 at r1](https://reviewable.io/reviews/starkware-libs/committer/81#-NwobIBr3ikydTc2z9X-:-NwpAOV_8yqddnWx3Ask:bwbp1pl) ([raw file](https://github.com/starkware-libs/committer/blob/d2b60a9ac7d94da180e639cd09606df6cd578247/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc_test.rs#L303)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

See the new description. I was thinking of a tree of a total height of 3.
</blockquote></details>

I can add it to the case_name if that helps - `small_tree` -> `height_three_tree`

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/81)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/committer/81#-NwoaVWq3_GIxarU198x:-NwpBJRu55MZhvuv6XlY:b-odiejc) ([raw file](https://github.com/starkware-libs/committer/blob/d2b60a9ac7d94da180e639cd09606df6cd578247/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs#L262)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

No, that's OK. I've extended the description, tell me if it's clear now.
</blockquote></details>

1. why does root_height not equal the height of the tree it is the root of? seems non-intuitive
2. still, you expect some upper bound on the node index. consider a scenario where `root_height=2`, and `leaf_indices=[4, 7, 8]`. the (2-1)th bit is zero in both the first and last indices (`4=100` and `8=1000`), so the function will return `false`. but 4 and 7 are at different sides of the tree...
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs` line 252 at r3](https://reviewable.io/reviews/starkware-libs/committer/81#-NwpCNmt59KF6U6Q6AkQ:-NwpCNmt59KF6U6Q6AkR:b-kzzujp) ([raw file](https://github.com/starkware-libs/committer/blob/f9f45b9bdc36a4d1acdcdd1dc624217a31f807cf/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs#L252)):*
> ```XML
> ///
> /// E.g. for a tree of height 2, calling this function with root_height=1, will return true iff
> /// leaf_indices equals exactly [4,5] or [6,7] (not that by assumption it can't have elements of
> ```

if `leaf_indices` is a singleton (one of `{[4], [5], [6], [7]}`) this function should return true as well



_Suggestion:_
```XML
is contained in [4,5] or in [6,7]
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/81)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/committer/81#-NwoaVWq3_GIxarU198x:-NwplI7T9WIWGYbmX-AN:bgy3kp9) ([raw file](https://github.com/starkware-libs/committer/blob/d2b60a9ac7d94da180e639cd09606df6cd578247/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs#L262)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. why does root_height not equal the height of the tree it is the root of? seems non-intuitive
2. still, you expect some upper bound on the node index. consider a scenario where `root_height=2`, and `leaf_indices=[4, 7, 8]`. the (2-1)th bit is zero in both the first and last indices (`4=100` and `8=1000`), so the function will return `false`. but 4 and 7 are at different sides of the tree...
</blockquote></details>

1. This is a translation of the current Python code. The usage is to determine if some node in the "global tree" should be a binary or an edge - the computation is done based on the distance/height if such node from the leaves. I assume it can be written in different ways (like giving the index of the "root" we are interested in), but this works well. Maybe decide after seeing the usage if this should be changed? It is a helper function, not part of an API.
2. [4-7] and 8 are in different depths, so they can't all be leaves. All leaves have the same number of bits (no leading zeros).
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs` line 252 at r3](https://reviewable.io/reviews/starkware-libs/committer/81#-NwpCNmt59KF6U6Q6AkQ:-Nwpk36r29GYXVIYz5b8:b-f8w1v0) ([raw file](https://github.com/starkware-libs/committer/blob/f9f45b9bdc36a4d1acdcdd1dc624217a31f807cf/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs#L252)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if `leaf_indices` is a singleton (one of `{[4], [5], [6], [7]}`) this function should return true as well
</blockquote></details>

Why? It returns true iff there are leaves on **both sides** of some node of the root height (so either [4,5] are from the two sides of {2} or [6,7] of {3}). The usage will be to determine if a node should be binary. If the leaves are actually a leaf - it should be an edge.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/81)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/committer/81#-NwoaVWq3_GIxarU198x:-Nws9ont2kKHu-_Q-Xqn:bmktte1) ([raw file](https://github.com/starkware-libs/committer/blob/d2b60a9ac7d94da180e639cd09606df6cd578247/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs#L262)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

1. This is a translation of the current Python code. The usage is to determine if some node in the "global tree" should be a binary or an edge - the computation is done based on the distance/height if such node from the leaves. I assume it can be written in different ways (like giving the index of the "root" we are interested in), but this works well. Maybe decide after seeing the usage if this should be changed? It is a helper function, not part of an API.
2. [4-7] and 8 are in different depths, so they can't all be leaves. All leaves have the same number of bits (no leading zeros).
</blockquote></details>

1. OK, I can wait for a usage, but the distance in a depth 2 tree (4 leaves) between the root and a leaf is 2, so I still don't see why we need on off-by-one value. LMK when a usage PR is open please
2. yes, 8 can't be a leaf index in a depth-2 tree, so why not make sure no bad leaves are given as input? it's O(1) (unlike checking that the list is sorted)
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs` line 252 at r3](https://reviewable.io/reviews/starkware-libs/committer/81#-NwpCNmt59KF6U6Q6AkQ:-Nwy9lMjCMzfmxoUxy6B:b12g2g4) ([raw file](https://github.com/starkware-libs/committer/blob/f9f45b9bdc36a4d1acdcdd1dc624217a31f807cf/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs#L252)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Why? It returns true iff there are leaves on **both sides** of some node of the root height (so either [4,5] are from the two sides of {2} or [6,7] of {3}). The usage will be to determine if a node should be binary. If the leaves are actually a leaf - it should be an edge.
</blockquote></details>

As discussed, still blocking until the input is the root *index* and sanity checks are added for first and last elements in the leaf list
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs` line 262 at r3](https://reviewable.io/reviews/starkware-libs/committer/81#-Nwy9wOC6xIFH1lNKkw-:-Nwy9wOC6xIFH1lNKkw0:bdtm91p) ([raw file](https://github.com/starkware-libs/committer/blob/f9f45b9bdc36a4d1acdcdd1dc624217a31f807cf/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs#L262)):*
> ```XML
> fn has_leaves_on_both_sides(root_height: &TreeHeight, leaf_indices: &[NodeIndex]) -> bool {
>     if leaf_indices.len() <= 1 {
>         return false;
> ```

in case there is a single element, please check that the index is indeed a leaf of the root index



_Code quote:_
```XML
return false;
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/81)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs` line 262 at r1](https://reviewable.io/reviews/starkware-libs/committer/81#-NwoaVWq3_GIxarU198x:-Nx7k5wNCgIGmql-OK48:b7hdspx) ([raw file](https://github.com/starkware-libs/committer/blob/d2b60a9ac7d94da180e639cd09606df6cd578247/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs#L262)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. OK, I can wait for a usage, but the distance in a depth 2 tree (4 leaves) between the root and a leaf is 2, so I still don't see why we need on off-by-one value. LMK when a usage PR is open please
2. yes, 8 can't be a leaf index in a depth-2 tree, so why not make sure no bad leaves are given as input? it's O(1) (unlike checking that the list is sorted)
</blockquote></details>

Done. Not checking the entire list though (if we allowed to assume order than we're fine).
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs` line 252 at r3](https://reviewable.io/reviews/starkware-libs/committer/81#-NwpCNmt59KF6U6Q6AkQ:-Nx7jhF3AkXLXRqlAIEZ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f9f45b9bdc36a4d1acdcdd1dc624217a31f807cf/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs#L252)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

As discussed, still blocking until the input is the root *index* and sanity checks are added for first and last elements in the leaf list
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs` line 262 at r3](https://reviewable.io/reviews/starkware-libs/committer/81#-Nwy9wOC6xIFH1lNKkw-:-Nx7k4Wh4bQbOEmwJriH:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/f9f45b9bdc36a4d1acdcdd1dc624217a31f807cf/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs#L262)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

in case there is a single element, please check that the index is indeed a leaf of the root index
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/81)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 245 at r4](https://reviewable.io/reviews/starkware-libs/committer/81#-Nx7uIWs4b0lGSpQ3ZSa:-Nx7uIWs4b0lGSpQ3ZSb:bxidqu9) ([raw file](https://github.com/starkware-libs/committer/blob/e1a8b953b980888c3752c18e0144ae0c1701468e/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L245)):*
> ```XML
>         if (*last_leaf >> root_height.0) != *root_index {
>             panic!("Last leaf is not a descendant of the root.");
>         }
> ```

reduce code dup



_Suggestion:_
```XML
        let root_height = self.get_node_height(root_index);
        let assert_child = |leaf_index: NodeIndex| {
            if (leaf_index >> root_height.0) != *root_index {
                panic!("First leaf is not a descendant of the root.");
            }
        }

        let first_leaf = leaf_indices[0];
        assert_child(first_leaf);
        if leaf_indices.len() == 1 {
            return false;
        }

        let last_leaf = leaf_indices
            .last()
            .expect("leaf_indices unexpectedly empty.");
        assert_child(last_leaf);
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/81)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 245 at r4](https://reviewable.io/reviews/starkware-libs/committer/81#-Nx7uIWs4b0lGSpQ3ZSa:-Nx81iBu50qZy-cYAEHn:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/e1a8b953b980888c3752c18e0144ae0c1701468e/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L245)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

reduce code dup
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 225 at r5](https://reviewable.io/reviews/starkware-libs/committer/81#-Nx81jhZ4Y7Q2U4JI7NM:-Nx81jhZ4Y7Q2U4JI7NN:bclsgjv) ([raw file](https://github.com/starkware-libs/committer/blob/15ecf0ee2bd5bd00a33863a60f639189f4bb7822/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L225)):*
> ```XML
>     /// * The leaf indices array is sorted.
>     /// * All leaves are descendants of the root.
>     // TODO(Tzahi, 10/5/2024): Move implementation to a separate module.
> ```

@amosStarkware pointed that this file is meant solely for the create original tree funcs. So I'll split the creation of the update tree impls in the next PR.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/81#-:-Nx82tun-CeF-jnnmkkE:bnfp4nl)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 2 of 5 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/81)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
