### PR TITLE
feat(skeleton): add_construct_from_dege_data

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/129)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/129)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUHy7tAPa96Zc4cXXR:-NyUHy7tAPa96Zc4cXXS:b-1b18xo) ([raw file](https://github.com/starkware-libs/committer/blob/64d6d19fa549b86a1fa8a17cd8d0889a1908fe75/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L32)):*
> ```XML
>         Self(self.0 + rhs.0)
>     }
> }
> ```

shorter



_Suggestion:_
```XML
#[derive(Clone, Copy, Debug, Default, derive_more::Add, PartialEq, Eq, Hash)]
pub struct EdgePathLength(pub u8);
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUID-K3toDhDlV8MSn:-NyUID-K3toDhDlV8MSo:b-t32iev) ([raw file](https://github.com/starkware-libs/committer/blob/64d6d19fa549b86a1fa8a17cd8d0889a1908fe75/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L56)):*
> ```XML
>         path: EdgePath(Felt::ONE),
>         length: EdgePathLength(1),
>     };
> ```

please move these definitions to the test utils area (you should be able to add `impl PathToBottom` blocks as many times as you want).
when you do, remove the `cfg(test)` attribute.
also, add a newline between the functions



_Suggestion:_
```XML
    pub(crate) const LEFT_CHILD: Self = PathToBottom {
        path: EdgePath(Felt::ZERO),
        length: EdgePathLength(1),
    };
    
    pub(crate) const RIGHT_CHILD: Self = PathToBottom {
        path: EdgePath(Felt::ONE),
        length: EdgePathLength(1),
    };
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 67 at r1](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUKCe4E24N7ojQmwFf:-NyUKCe4E24N7ojQmwFg:baf6zlm) ([raw file](https://github.com/starkware-libs/committer/blob/64d6d19fa549b86a1fa8a17cd8d0889a1908fe75/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L67)):*
> ```XML
>             length: self.length + other.length,
>         }
>     }
> ```

non-blocking



_Suggestion:_
```XML
    pub(crate) fn concat_paths(&self, other: PathToBottom) -> Self {
        Self {
            path: EdgePath((self.path.0 * Felt::TWO.pow(other.length.0)) + other.path.0),
            length: self.length + other.length,
        }
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUKRJu0Ad0e9LKcTGN:-NyUKRJu0Ad0e9LKcTGO:bdq024g) ([raw file](https://github.com/starkware-libs/committer/blob/64d6d19fa549b86a1fa8a17cd8d0889a1908fe75/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L54)):*
> ```XML
> // Builds a (probably edge) node from its given descendant. Returns the TempSkeletonNode matching
> // the given root (the source for the path to bottom) for the subtree it is the root of. If bottom
> // is empty, returns an empty node.
> ```

triple slash



_Suggestion:_
```XML
/// Builds a (probably edge) node from its given descendant. Returns the TempSkeletonNode matching
/// the given root (the source for the path to bottom) for the subtree it is the root of. If bottom
/// is empty, returns an empty node.
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/129)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @TzahiTaub)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUh90ECIi25xvQ5STU):*
in general these commit messages will appear in release notes. branch names can be "neighborhood", commit messages - less



_Suggestion:_
```
add node_from_edge_data
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/129)* status: 2 of 9 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUHy7tAPa96Zc4cXXR:-NyUZI_w8kThza6ciAe9:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/64d6d19fa549b86a1fa8a17cd8d0889a1908fe75/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shorter
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUID-K3toDhDlV8MSn:-NyUZPx73Q2ssP7QbSx6:bbdvu9h) ([raw file](https://github.com/starkware-libs/committer/blob/64d6d19fa549b86a1fa8a17cd8d0889a1908fe75/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L56)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please move these definitions to the test utils area (you should be able to add `impl PathToBottom` blocks as many times as you want).
when you do, remove the `cfg(test)` attribute.
also, add a newline between the functions
</blockquote></details>

It's going to be in the actual code in the next PR. Replaced with allow dead code. A new line between the consts?
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 54 at r1](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUKRJu0Ad0e9LKcTGN:-NyUZzEMD-i2nrluqII1:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/64d6d19fa549b86a1fa8a17cd8d0889a1908fe75/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L54)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

triple slash
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/129)* status: all files reviewed, 10 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUqlAY5Ray1SjObDGw:-NyUqlAY5Ray1SjObDGx:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/test_utils.rs#L23)):*
> ```XML
>         PathToBottom {
>             path: EdgePath(Felt::from(path)),
>             length: EdgePathLength(length),
> ```





_Suggestion:_
```XML
        for c in value.chars() {
            path <<= 1;
            path |= match c {
                '0' => 0,
                '1' => 1,
                _ => panic!("Invalid character in path: {}", c),
            };
        }
        PathToBottom {
            path: EdgePath(Felt::from(path)),
            length: EdgePathLength(value.len()),
```
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUr7MG4Bh2iOq5NfwQ:-NyUr7MG4Bh2iOq5NfwR:b-t7ayek) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/test_utils.rs#L25)):*
> ```XML
>             length: EdgePathLength(length),
>         }
>     }
> ```

[the wheel has been invented previously](https://doc.rust-lang.org/std/primitive.u8.html#method.from_str_radix)



_Suggestion:_
```XML
    fn from(value: &str) -> Self {
        Self {
            path: EdgePath(Felt::from(u128::from_str_radix(value, 2))),
            length: EdgePathLength(value.len()),
        }
    }
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 56 at r1](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUID-K3toDhDlV8MSn:-NyUrRRV8ZO6LxIK3ux0:b-ya1m3c) ([raw file](https://github.com/starkware-libs/committer/blob/64d6d19fa549b86a1fa8a17cd8d0889a1908fe75/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L56)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

It's going to be in the actual code in the next PR. Replaced with allow dead code. A new line between the consts?
</blockquote></details>

ok, so good that you removed the cfg(test).
ah... right, these aren't functions... but they are multiline definitions so I still prefer newlines.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/node.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUrefR4rBiB1odOavs:-NyUrefR4rBiB1odOavt:bi085dv) ([raw file](https://github.com/starkware-libs/committer/blob/b59276ebf83143815bcac3363449fb625744f2ad/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/node.rs#L16)):*
> ```XML
>     EdgeSibling(EdgeData),
>     Leaf(SkeletonLeaf),
>     Empty,
> ```

rebase next time



_Code quote:_
```XML
Empty,
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUs66y5ZhIoMHdQFmv:-NyUs66y5ZhIoMHdQFmw:b-9cnc2a) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L72)):*
> ```XML
>             TempSkeletonNode::Original(original_node) => {
>                 let res = match original_node {
>                     OriginalSkeletonNode::Leaf(_) => {
> ```

to save indentation, please flatten these match arms like so:



_Suggestion:_
```XML
            TempSkeletonNode::Original(OriginalSkeletonNode::Leaf(_)) => {
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUsOgc6cxtT1TwnaAN:-NyUsOgc6cxtT1TwnaAO:b-3xevba) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L75)):*
> ```XML
>                         let leaf = leaf_modifications.get(bottom_index).unwrap_or_else(|| {
>                             panic!("Leaf modification {bottom_index:?} not found")
>                         });
> ```

I think you should return an error in this case
my reasoning is: if modification data is missing, then it's the *user of the committer library's fault*, not the committer.



_Suggestion:_
```XML
                        let leaf = leaf_modifications.get(bottom_index).ok_or(
                            UpdatedTreeError::MissingLeafData(bottom_index)
                        );
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUyMvOCYPEuCeZH5jd:-NyUyMvOCYPEuCeZH5je:b-gye2pt) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L116)):*
> ```XML
>     );
> }
> ```

suggestion: instead of the two `HashMap<NodeIndex, SkeletonLeaf>` inputs, use `&[(NodeIndex, SkeletonLeaf)]` and do the `HashMap::from()` in the test body (to reduce some boilerplate in the `#[case]`s).
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUykGgDPDYzADHAgzZ:-NyUykGgDPDYzADHAgz_:brnrtvv) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L160)):*
> ```XML
>         (NodeIndex::from(7),
>         UpdatedSkeletonNode::Binary)]
> ))]
> ```

wierd formatting here



_Suggestion:_
```XML
    HashMap::from([
        (NodeIndex::from(7), UpdatedSkeletonNode::Binary)
    ]))]
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUyqqC0k6ctPcp5JFy:-NyUyqqC0k6ctPcp5JFz:b-i6dwwm) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L171)):*
> ```XML
>         SkeletonLeaf::Zero)]),
>     TempSkeletonNode::Empty,
>         HashMap::new()
> ```

formatting



_Suggestion:_
```XML
    &HashMap::from([
        (NodeIndex::from(7), SkeletonLeaf::Zero)
    ]),
    TempSkeletonNode::Empty,
    HashMap::new()
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUyvMe1Fdytgkn1OQc:-NyUyvMe1Fdytgkn1OQd:b-i6dwwm) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L189)):*
> ```XML
>         UpdatedSkeletonNode::Leaf(SkeletonLeaf::NonZero))]
> )
> )]
> ```

formatting



_Suggestion:_
```XML
    &HashMap::from([
        (NodeIndex::from(7), SkeletonLeaf::NonZero)
    ]),
    TempSkeletonNode::Original(
        OriginalSkeletonNode::Edge {path_to_bottom: PathToBottom::RIGHT_CHILD}
    ),
    HashMap::from([
        (NodeIndex::from(7), UpdatedSkeletonNode::Leaf(SkeletonLeaf::NonZero))
    ]))]
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUxpI85jlLzXq_9v_S:-NyUxpI85jlLzXq_9v_T:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L196)):*
> ```XML
>     #[case] bottom: &TempSkeletonNode,
>     #[case] leaf_modifications: &LeafModifications<SkeletonLeaf>,
>     #[case] expected: TempSkeletonNode,
> ```





_Suggestion:_
```XML
expected_node
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/129)* status: 3 of 9 files reviewed, 9 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 23 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUqlAY5Ray1SjObDGw:-NyViFex-5P2OXovp0NS:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/test_utils.rs#L23)):*
> ```XML
>         PathToBottom {
>             path: EdgePath(Felt::from(path)),
>             length: EdgePathLength(length),
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 25 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUr7MG4Bh2iOq5NfwQ:-NyVSWhLAbZRp-Syspm-:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/test_utils.rs#L25)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

[the wheel has been invented previously](https://doc.rust-lang.org/std/primitive.u8.html#method.from_str_radix)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 72 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUs66y5ZhIoMHdQFmv:-NyViJMq3tX_Cjl7QHXF:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L72)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

to save indentation, please flatten these match arms like so:
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUsOgc6cxtT1TwnaAN:-NyVUQlu5oOBZWjwfEsR:b-ua01p0) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L75)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think you should return an error in this case
my reasoning is: if modification data is missing, then it's the *user of the committer library's fault*, not the committer.
</blockquote></details>

But AFAIU this is based on the OriginalSkeletonNode - so if the user of the lib missed data - it should be caught when building the original skeleton, and if we're here after it was created, we can assume the skeleton and modification list should match each other.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUykGgDPDYzADHAgzZ:-NyVbQKx4BK_L3judHSH:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L160)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

wierd formatting here
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 171 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUyqqC0k6ctPcp5JFy:-NyVhHjR7XdlnbZa0iRu:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L171)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

formatting
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 189 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUyvMe1Fdytgkn1OQc:-NyViO1_EAxjBf5hPh1p:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L189)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

formatting
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 196 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUxpI85jlLzXq_9v_S:-NyViEMhCY5CbTGSirF7:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L196)):*
> ```XML
>     #[case] bottom: &TempSkeletonNode,
>     #[case] leaf_modifications: &LeafModifications<SkeletonLeaf>,
>     #[case] expected: TempSkeletonNode,
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/node.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUrefR4rBiB1odOavs:-NyVTyWC5b7cIH1sAvDx:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b59276ebf83143815bcac3363449fb625744f2ad/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/node.rs#L16)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

rebase next time
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/129#-:-NyVkIrDE4zm5wO_ZXFX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/committer/129#-NyVk1wqEEUjMJ1LQsfY:-NyVk1wqEEUjMJ1LQsfZ:b-83n3qm) ([raw file](https://github.com/starkware-libs/committer/blob/06388d8ddc163beb0625a9bf0eb65ad702247c52/crates/committer/src/patricia_merkle_tree/test_utils.rs#L17)):*
> ```XML
>                 (value.len() - if value.starts_with('+') { 1 } else { 0 })
>                     .try_into()
>                     .expect("String is too large"),
> ```

if the character `+` is not in the string you are always non-negative; and if `+` is in the string, the length is at least 1, so still non-negative.
test util though, so non-blocking



_Suggestion:_
```XML
"Unreachable."
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/committer/129#-NyUsOgc6cxtT1TwnaAN:-NyVjgDa2fbhdCMTz16q:b-o1nedo) ([raw file](https://github.com/starkware-libs/committer/blob/89099a581087ac24f3a00deb44346800bf6bf91b/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L75)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

But AFAIU this is based on the OriginalSkeletonNode - so if the user of the lib missed data - it should be caught when building the original skeleton, and if we're here after it was created, we can assume the skeleton and modification list should match each other.
</blockquote></details>

good point, unblocking

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/129)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/committer/129#-NyVk1wqEEUjMJ1LQsfY:-NyWvESn4G8l0WZjW9Wv:b-7camjk) ([raw file](https://github.com/starkware-libs/committer/blob/06388d8ddc163beb0625a9bf0eb65ad702247c52/crates/committer/src/patricia_merkle_tree/test_utils.rs#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if the character `+` is not in the string you are always non-negative; and if `+` is in the string, the length is at least 1, so still non-negative.
test util though, so non-blocking
</blockquote></details>

It's not a negativity issue; it's converting a `usize` into `u8`. If your string is longer than 255 chars, this will fail.

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/129)* status: all files reviewed, 2 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs` line 57 at r5](https://reviewable.io/reviews/starkware-libs/committer/129#-NyWto1e7q494ia9ZqCb:-NyWto1e7q494ia9ZqCc:bt0dnpm) ([raw file](https://github.com/starkware-libs/committer/blob/06388d8ddc163beb0625a9bf0eb65ad702247c52/crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs#L57)):*
> ```XML
>     pub(crate) fn concat_paths(&self, other: Self) -> Self {
>         Self {
>             path: EdgePath((self.path.0 * Felt::TWO.pow(other.length.0)) + other.path.0),
> ```

This might be expensive (finite field)
@dorimedini-starkware, can we switch the type to U256 and use a simple bit shift here?



_Code quote:_
```XML
Felt::TWO.pow(other.length.0)
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 17 at r5](https://reviewable.io/reviews/starkware-libs/committer/129#-NyWvNonA61Nhv2sIT2I:-NyWvNonA61Nhv2sIT2J:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/06388d8ddc163beb0625a9bf0eb65ad702247c52/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L17)):*
> ```XML
> 
> #[derive(Debug, PartialEq, Eq)]
> /// A temporary skeleton node used to during the computation of the updated skeleton tree.
> ```





_Suggestion:_
```XML
n node used during the computation of the updated skeleton tree.
```

**Pull request merged**
