### PR TITLE
feat: move leaf fetching logic to leaf data trait

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/160)

### CODE REVIEW

**Comment by aner-starkware** [comment]
:lgtm:

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/160)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 22 at r3](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz8CK0gAlDOOqmZuc0g:-Nz8CK0h91NefIDGIlaY:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/ee674c442e1328af352e92aea87ee62f9ee63c4e/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L22)):*
> ```XML
>     // Use explicit desugaring of `async fn` to allow adding trait bounds to the return type, see
>     // https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html#async-fn-in-public-traits
>     // for details.
> ```





_Suggestion:_
```XML
    /// Returns / computes the NodeData.
    /// Use explicit desugaring of `async fn` to allow adding trait bounds to the return type, see
    /// https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html#async-fn-in-public-traits
    /// for details.
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 63 at r3](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz8MlO07fq1IRuVj69M:-Nz8MlO07fq1IRuVj69N:byp18fd) ([raw file](https://github.com/starkware-libs/committer/blob/ee674c442e1328af352e92aea87ee62f9ee63c4e/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L63)):*
> ```XML
>         index: &NodeIndex,
>         leaf_modifications: &LeafModifications<Self>,
>     ) -> FilledTreeResult<NodeData<Self>, Self> {
> ```

Remove



_Code quote:_
```XML
FilledTreeResult
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz8MNB04akSs4_gg_bm:-Nz8MNB04akSs4_gg_bn:b-9jjrab) ([raw file](https://github.com/starkware-libs/committer/blob/ee674c442e1328af352e92aea87ee62f9ee63c4e/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L66)):*
> ```XML
>         let leaf_data = leaf_modifications
>             .get(index)
>             .ok_or(FilledTreeError::<Self>::MissingDataForUpdate(*index))?
> ```

Need new errors and possible wrap them in the caller.



_Suggestion:_
```XML
LeafError::<Self>::MissingDataForUpdate(*index))?
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 69 at r3](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz8MTfhD62oimXhTLfe:-Nz8MTfhD62oimXhTLff:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/ee674c442e1328af352e92aea87ee62f9ee63c4e/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L69)):*
> ```XML
>             .clone();
>         if leaf_data.is_empty() {
>             return Err(FilledTreeError::<Self>::DeletedLeafInSkeleton(*index));
> ```





_Suggestion:_
```XML
(LeafError::<Self>::DeletedLeafInSkeleton(*index)
```

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/160)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz8MNB04akSs4_gg_bm:-Nz8muqcE16BG_qZ77Zx:bz5ate1) ([raw file](https://github.com/starkware-libs/committer/blob/ee674c442e1328af352e92aea87ee62f9ee63c4e/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L66)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, actually the name of the variants are still in the context of the fileedTree (what update? what skeleton? We are in a LeafData struct). Maybe switch to `MissingLeafModificationData` and `EmptyLeafInModifications`? You can keep the same name for the fileedTree transparency IMO.
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 16 at r4](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz8ner-DklZ4Jopd76O:-Nz8ner0EFRQNUzlKBNS:b-39mxbq) ([raw file](https://github.com/starkware-libs/committer/blob/5a4a5e35b8098ae37ba450e5a9cf4553f1455af0/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L16)):*
> ```XML
>     fn is_empty(&self) -> bool;
> 
>     /// Creates a leaf.
> ```

Is this because of the possible future computations? Because `get` seems better here (as if the index is missing in the map we'll get an error)



_Code quote:_
```XML
 Creates a leaf.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/160)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz8MNB04akSs4_gg_bm:-Nz8pPOQD00rYKJ_6DAi:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/ee674c442e1328af352e92aea87ee62f9ee63c4e/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L66)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Sorry, actually the name of the variants are still in the context of the fileedTree (what update? what skeleton? We are in a LeafData struct). Maybe switch to `MissingLeafModificationData` and `EmptyLeafInModifications`? You can keep the same name for the fileedTree transparency IMO.
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 16 at r4](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz8ner-DklZ4Jopd76O:-Nz8ol4q9Arfmp_sG2mz:b-kg21tc) ([raw file](https://github.com/starkware-libs/committer/blob/5a4a5e35b8098ae37ba450e5a9cf4553f1455af0/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L16)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Is this because of the possible future computations? Because `get` seems better here (as if the index is missing in the map we'll get an error)
</blockquote></details>

it's for the future, yes; IMO it's better that the API is clear from the start. `create` sounds more like "this operation may be non-trivial" to me

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/160)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 10 at r5](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz9YNp9ADsA2O0N1UD9:-Nz9YNp9ADsA2O0N1UDA:b15e42q) ([raw file](https://github.com/starkware-libs/committer/blob/9da95bfaa1a45afc5f2a1ddd3b5e1d8922569ece/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L10)):*
> ```XML
> pub enum FilledTreeError<L: LeafData> {
>     #[error("Deleted leaf at index {0:?} appears in the updated skeleton tree.")]
>     DeletedLeafInSkeleton(NodeIndex),
> ```

Revive error



_Code quote:_
```XML
    #[error("Deleted leaf at index {0:?} appears in the updated skeleton tree.")]
    DeletedLeafInSkeleton(NodeIndex),
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 176 at r5](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz9Y1IU2wgbuCXucBOe:-Nz9Y1IU2wgbuCXucBOf:bj4iend) ([raw file](https://github.com/starkware-libs/committer/blob/28a4e664a3e307c282cbfe9d99ce514c23e7361a/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L176)):*
> ```XML
>             UpdatedSkeletonNode::Leaf => {
>                 let node_data =
>                     NodeData::Leaf(LeafDataImpl::create(&index, leaf_modifications).await?);
> ```

Return the previous code block



_Suggestion:_
```XML
                let node_data =
                    NodeData::Leaf(LeafDataImpl::create(&index, leaf_modifications).await?);
                    if node_data.is_empty() {...FilledTreeError...
```
___
*[`crates/committer/src/patricia_merkle_tree/node_data/errors.rs` line 19 at r5](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz9XZJpDRm-3CK3Isqn:-Nz9XZJpDRm-3CK3Isqo:b2sk98q) ([raw file](https://github.com/starkware-libs/committer/blob/28a4e664a3e307c282cbfe9d99ce514c23e7361a/crates/committer/src/patricia_merkle_tree/node_data/errors.rs#L19)):*
> ```XML
> pub enum LeafError {
>     #[error("Deleted leaf at index {0:?} appears in the updated skeleton tree.")]
>     EmptyLeafInModifications(NodeIndex),
> ```

See the below comments.
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 68 at r5](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz9XLne1vbOYUy2HnUN:-Nz9XLne1vbOYUy2HnUO:b5hgw8u) ([raw file](https://github.com/starkware-libs/committer/blob/28a4e664a3e307c282cbfe9d99ce514c23e7361a/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L68)):*
> ```XML
>         if leaf_data.is_empty() {
>             return Err(LeafError::EmptyLeafInModifications(*index));
>         }
> ```

This isn't an error in this function, only in the context of appearing in as Leaf in the updated skeleton.

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/160)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 10 at r5](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz9YNp9ADsA2O0N1UD9:-NzAfkRV7jo8hnPqQ7dx:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/9da95bfaa1a45afc5f2a1ddd3b5e1d8922569ece/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L10)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Revive error
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs` line 176 at r5](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz9Y1IU2wgbuCXucBOe:-NzAgFu48sjXAFqdhn8z:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/28a4e664a3e307c282cbfe9d99ce514c23e7361a/crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs#L176)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Return the previous code block
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/node_data/errors.rs` line 19 at r5](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz9XZJpDRm-3CK3Isqn:-NzAgH8P1Aa3I9ha21XD:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/28a4e664a3e307c282cbfe9d99ce514c23e7361a/crates/committer/src/patricia_merkle_tree/node_data/errors.rs#L19)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

See the below comments.
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/node_data/leaf.rs` line 68 at r5](https://reviewable.io/reviews/starkware-libs/committer/160#-Nz9XLne1vbOYUy2HnUN:-NzAgIOACQarNjdnh0Cj:b-a1dckh) ([raw file](https://github.com/starkware-libs/committer/blob/28a4e664a3e307c282cbfe9d99ce514c23e7361a/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L68)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

This isn't an error in this function, only in the context of appearing in as Leaf in the updated skeleton.
</blockquote></details>

ah, right you are, good catch!
moved things back a bit

**Review by TzahiTaub — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/160#-:-NzKSsS861kuymbVv650:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
