### PR TITLE
feat(block_hash): calculate block hash command

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/226)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/226)* status: all files reviewed, 3 unresolved discussions (waiting on @yoavGrs)

___
*[`crates/committer_cli/src/main.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/committer/226#-O-W454P44ZaGUqxQMI_:-O-W454P44ZaGUqxQMIa:b-ugjs0y) ([raw file](https://github.com/starkware-libs/committer/blob/569698c3c27ebd0ca17ac78bd228ecefadf31066/crates/committer_cli/src/main.rs#L42)):*
> ```XML
>         #[clap(long)]
>         input: String,
>     },
> ```

why do you need to separate commands?
is there more than one place we need to compute hashes from the python side?



_Code quote:_
```XML
    /// Calculates the block hash.
    BlockHash {
        /// Json serialized BlockHashInput.
        #[clap(long)]
        input: String,
    },
    /// Given previous state tree skeleton and a state diff, computes the new commitment.
    /// Calculates commitments needed for the block hash.
    BlockHashCommitments {
        /// Json serialized BlockCommitmentsInput.
        #[clap(long)]
        input: String,
    },
```
___
*[`crates/committer_cli/src/main.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/committer/226#-O-W4Mnt05LQU9zqiVPH:-O-W4Mnt05LQU9zqiVPI:b-uptpwb) ([raw file](https://github.com/starkware-libs/committer/blob/569698c3c27ebd0ca17ac78bd228ecefadf31066/crates/committer_cli/src/main.rs#L42)):*
> ```XML
>         #[clap(long)]
>         input: String,
>     },
> ```

I know it's not related to your PR, but please open a PR for it before it gets worse:
all IO commands here should get `input_path` and `output_path`, like in the `Commit` command.
Currently it's stdin and stdout, but we may want to change this in the very near future;
so can you open a PR to define an `IoArgs` struct (with `clap(flatten)`), and use it in all 3 "production commands"?



_Code quote:_
```XML
    /// Calculates the block hash.
    BlockHash {
        /// Json serialized BlockHashInput.
        #[clap(long)]
        input: String,
    },
    /// Given previous state tree skeleton and a state diff, computes the new commitment.
    /// Calculates commitments needed for the block hash.
    BlockHashCommitments {
        /// Json serialized BlockCommitmentsInput.
        #[clap(long)]
        input: String,
    },
```
___
*[`crates/committer_cli/src/main.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/committer/226#-O-W4m7sEhezkAZsHyD_:-O-W4m7sEhezkAZsHyDa:b-3bokxr) ([raw file](https://github.com/starkware-libs/committer/blob/569698c3c27ebd0ca17ac78bd228ecefadf31066/crates/committer_cli/src/main.rs#L115)):*
> ```XML
>             .expect("Failed to serialize block hash");
>             print!("{}", block_hash);
>         }
> ```

is there a flow-test PR open on the python side?



_Code quote:_
```XML
        Command::BlockHash { input } => {
            let block_hash_input: BlockHashInput =
                serde_json::from_str(&input).expect("Failed to load block hash input");
            let block_hash = serde_json::to_string(&calculate_block_hash(
                block_hash_input.header,
                block_hash_input.block_commitments,
            ))
            .expect("Failed to serialize block hash");
            print!("{}", block_hash);
        }
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/226)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/src/main.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/committer/226#-O-W454P44ZaGUqxQMI_:-O-Wiceu9XxU4ey547BK:bxaco6f) ([raw file](https://github.com/starkware-libs/committer/blob/569698c3c27ebd0ca17ac78bd228ecefadf31066/crates/committer_cli/src/main.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need to separate commands?
is there more than one place we need to compute hashes from the python side?
</blockquote></details>

Yes, there are two steps: commitments and block hash.
___
*[`crates/committer_cli/src/main.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/committer/226#-O-W4Mnt05LQU9zqiVPH:-O-Wj4B70z83JicwWbhQ:b-523dg9) ([raw file](https://github.com/starkware-libs/committer/blob/569698c3c27ebd0ca17ac78bd228ecefadf31066/crates/committer_cli/src/main.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I know it's not related to your PR, but please open a PR for it before it gets worse:
all IO commands here should get `input_path` and `output_path`, like in the `Commit` command.
Currently it's stdin and stdout, but we may want to change this in the very near future;
so can you open a PR to define an `IoArgs` struct (with `clap(flatten)`), and use it in all 3 "production commands"?
</blockquote></details>

I'll look into it.
___
*[`crates/committer_cli/src/main.rs` line 115 at r1](https://reviewable.io/reviews/starkware-libs/committer/226#-O-W4m7sEhezkAZsHyD_:-O-Wim4B9il9R1Xheq_0:bnqv1pz) ([raw file](https://github.com/starkware-libs/committer/blob/569698c3c27ebd0ca17ac78bd228ecefadf31066/crates/committer_cli/src/main.rs#L115)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is there a flow-test PR open on the python side?
</blockquote></details>

https://reviewable.io/reviews/starkware-industries/starkware/35229

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/226)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/src/main.rs` line 42 at r1](https://reviewable.io/reviews/starkware-libs/committer/226#-O-W4Mnt05LQU9zqiVPH:-O-eN6Om6bRjhYbcVGYw:b-896fja) ([raw file](https://github.com/starkware-libs/committer/blob/569698c3c27ebd0ca17ac78bd228ecefadf31066/crates/committer_cli/src/main.rs#L42)):*
<details><summary><i>Previously, yoavGrs wrote…</i></summary><blockquote>

I'll look into it.
</blockquote></details>

Done!

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/226)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/committer_cli/src/main.rs` line 38 at r2](https://reviewable.io/reviews/starkware-libs/committer/226#-O-fs9yh9vipfc2bbds1:-O-fs9yh9vipfc2bbds2:b658x5a) ([raw file](https://github.com/starkware-libs/committer/blob/e3d59f2da8b4f5a028f68381179d3ddc47e95540/crates/committer_cli/src/main.rs#L38)):*
> ```XML
>         /// File path to output.
>         #[clap(long, short = 'o')]
>         output_path: String,
> ```

use IoArgs (see base PR)



_Code quote:_
```XML
        /// File path to input.
        #[clap(long, short = 'i')]
        input_path: String,

        /// File path to output.
        #[clap(long, short = 'o')]
        output_path: String,
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/226#-:-O-k4SPNAEnCuBemA8vG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
