### PR TITLE
refactor: leafdata implementations

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
Needed for the implementation of serialize for FilledTree<L: LeafData>.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/115)

### CODE REVIEW

**Comment by AvivYossef-starkware** [comment]
I would love to hear if you have a more elegant way of doing it.
Maybe changing the Serializable trait and making leaf data Implement Part of it.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/115)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by AvivYossef-starkware — COMMENTED** [review]
The PR is for LeafdataImpl impl DB object trait. 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/115#-:-NyTySlWBrRfua5hPs9x:b-lm9d62)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @amosStarkware and @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 3 of 5 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/115)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 42 at r3](https://reviewable.io/reviews/starkware-libs/committer/115#-NyUQUdW2tUB7DQuYPck:-NyUQUdXDzkJWYpfUT8x:b-9k0e02) ([raw file](https://github.com/starkware-libs/committer/blob/f1fdaff7620457dd5c86d2524f3fa97c7224df34/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L42)):*
> ```XML
> }
> 
> impl<L: LeafData + DBObject> DBObject for FilledNode<L> {
> ```

All "filled leaves" (i.e. leaves with actual data) should be DBObjects, right?
since this is the case, I would [bind the LeafData trait to DBObject directly](https://github.com/starkware-libs/committer/blob/main/crates/committer/src/patricia_merkle_tree/node_data/leaf.rs#L8) (and remove the extra binding here):
```
trait LeafData: Clone + Sync + Send + DBObject
```



_Suggestion:_
```XML
<L: LeafData>
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs` line 80 at r3](https://reviewable.io/reviews/starkware-libs/committer/115#-NyUPaiC69CPDzkGRtB9:-NyUPaiC69CPDzkGRtBA:brtehp7) ([raw file](https://github.com/starkware-libs/committer/blob/f1fdaff7620457dd5c86d2524f3fa97c7224df34/crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs#L80)):*
> ```XML
>     }
> 
>     /// Returns the prefix of the filled node.
> ```

move this docstring (and rephrase to be general) to the `DbObject` trait; in general it's best to document functions once.
if the specific implementation of a trait function should get it's own docstring, that would be a special case.



_Suggestion:_
```XML
/// Returns the storage key prefix of the DB object.
```
___
*[`crates/committer/src/storage/serde_trait.rs` line 0 at r3](https://reviewable.io/reviews/starkware-libs/committer/115#-NyUQGr39KF8y91UU3ds:-NyUQGr39KF8y91UU3dt:b54f6dy) ([raw file](https://github.com/starkware-libs/committer/blob/f1fdaff7620457dd5c86d2524f3fa97c7224df34/crates/committer/src/storage/serde_trait.rs#L0)):*
this file should be renamed to `db_object.rs` or something... "serde" is no longer a good name.
not part of this PR in any case (non-blocking)
___
*[`crates/committer/src/storage/serde_trait.rs` line 9 at r3](https://reviewable.io/reviews/starkware-libs/committer/115#-NyUQ-8_2pfkRHmsQJY2:-NyUQ-8_2pfkRHmsQJY3:b-4jz88e) ([raw file](https://github.com/starkware-libs/committer/blob/f1fdaff7620457dd5c86d2524f3fa97c7224df34/crates/committer/src/storage/serde_trait.rs#L9)):*
> ```XML
> 
>     fn get_prefix(&self) -> StoragePrefix;
>     /// Returns a `StorageKey` from a prefix and a suffix.
> ```

newline between functions



_Suggestion:_
```XML
    fn get_prefix(&self) -> StoragePrefix;
    
    /// Returns a `StorageKey` from a prefix and a suffix.
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 0 at r3](https://reviewable.io/reviews/starkware-libs/committer/115#-NyURHi18t4VIeY6eGHk:-NyURHi18t4VIeY6eGHl:b-o0o19m) ([raw file](https://github.com/starkware-libs/committer/blob/f1fdaff7620457dd5c86d2524f3fa97c7224df34/crates/committer_cli/src/tests/python_tests.rs#L0)):*
In this file I see this pattern several times:
```
leaf.get_db_key(leaf.suffix());
```
where `leaf` is a `FilledNode`.
please change this to
```
leaf.db_key();
```
I know you can't just add a `suffix()` function to the DBObject trait, but you *can* add a `db_key()` function to the `impl<L: LeafData> FilledNode<L>` block which uses the suffix.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/115#-:-NyVLJb3EElGg3z2aRXN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @AvivYossef-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/115)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @AvivYossef-starkware)

**Pull request merged**
