### PR TITLE
build: add tentative tree API

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/8)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@Yoni-Starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/8#-:-NuKTe0M7wJE8ZC45WyA:b-gza3mz)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @Yoni-Starkware)

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/8)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/8#-NuKh-dZ6pfigFdueFXV:-NuKh-d_07ULhgkvKR0a:b-arw458) ([raw file](https://github.com/starkware-libs/committer/blob/45e17c045b6609b96ed0c2381156014923c1e8f4/crates/committer/src/patricia_merkle_tree/filled_node.rs#L21)):*
> ```XML
> #[allow(dead_code)]
> pub(crate) struct EdgeData<L: Leaf> {
>     bottom_value: BottomData<L>,
> ```

This is just the bottom hash value.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/8)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/skeleton_tree.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/8#-NuNZDIRBdLU2_WMiPKN:-NuNZDIS-u3paoPP7KR1:b-sotazs) ([raw file](https://github.com/starkware-libs/committer/blob/45e17c045b6609b96ed0c2381156014923c1e8f4/crates/committer/src/patricia_merkle_tree/skeleton_tree.rs#L13)):*
> ```XML
>         &self,
>         index_to_updated_leaf: Map<NodeIndex, &SkeletonNode<L>>,
>     ) -> Result<SkeletonTreeError, impl UpdatedSkeletonTree<L, H>>;
> ```

is this equivalent to templating? or to `dyn`?



_Code quote:_
```XML
impl UpdatedSkeletonTree
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/committer/8#-NuN_3i69Qjm9uA8sdMr:-NuN_3i69Qjm9uA8sdMs:b-2o50vj) ([raw file](https://github.com/starkware-libs/committer/blob/45e17c045b6609b96ed0c2381156014923c1e8f4/crates/committer/src/patricia_merkle_tree/types.rs#L8)):*
> ```XML
>     /// Computes the hash of given input.
>     async fn compute_node_hash(skeleton_node: SkeletonNode<L>) -> HashOutput;
> }
> ```

don't you need an `H` type param?



_Code quote:_
```XML
pub(crate) trait TreeHashFunction<L: Leaf> {
    /// Computes the hash of given input.
    async fn compute_node_hash(skeleton_node: SkeletonNode<L>) -> HashOutput;
}
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/committer/8#-NuN_9QO8nbi-kV_VIYC:-NuN_9QO8nbi-kV_VIYD:b-l1zeex) ([raw file](https://github.com/starkware-libs/committer/blob/45e17c045b6609b96ed0c2381156014923c1e8f4/crates/committer/src/patricia_merkle_tree/types.rs#L18)):*
> ```XML
> 
> #[allow(dead_code)]
> pub(crate) struct EdgePathLength(pub Felt);
> ```

even if we combine top and bottom trees we'll only need 9 bits for the length



_Suggestion:_
```XML
EdgePathLength(pub u16);
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/committer/8#-NuN_SWoAeGHDbFdiZpJ:-NuN_SWoAeGHDbFdiZpK:b-csd7w8) ([raw file](https://github.com/starkware-libs/committer/blob/45e17c045b6609b96ed0c2381156014923c1e8f4/crates/committer/src/patricia_merkle_tree/types.rs#L28)):*
> ```XML
> pub(crate) trait Leaf {
>     /// Returns data of leaf.
>     fn get_data(&self) -> Self;
> ```

a `self -> Self` method is redundant;
1. if there is no LeafData concept - remove this function
2. if there is - return `LeafData`, and not `Self`



_Code quote:_
```XML
    /// Returns data of leaf.
    fn get_data(&self) -> Self;
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/8)* status: 8 of 13 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/8#-NuKh-dZ6pfigFdueFXV:-NuNjItJCiDvjUFR_JAt:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/45e17c045b6609b96ed0c2381156014923c1e8f4/crates/committer/src/patricia_merkle_tree/filled_node.rs#L21)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

This is just the bottom hash value.
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/skeleton_tree.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/8#-NuNZDIRBdLU2_WMiPKN:-NuNlw9yCDbIWAhts2dE:btpbj05) ([raw file](https://github.com/starkware-libs/committer/blob/45e17c045b6609b96ed0c2381156014923c1e8f4/crates/committer/src/patricia_merkle_tree/skeleton_tree.rs#L13)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is this equivalent to templating? or to `dyn`?
</blockquote></details>

The type is determined in compile time:
https://cotigao.medium.com/dyn-impl-and-trait-objects-rust-fd7280521bea#:~:text=This%20compiles%20fine,to%20code%20bloat.
does that answer your question?
should I add one of the Rust people to the PR?
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 8 at r1](https://reviewable.io/reviews/starkware-libs/committer/8#-NuN_3i69Qjm9uA8sdMr:-NuNnR7w1A74N8hiq4wm:bnj1s4s) ([raw file](https://github.com/starkware-libs/committer/blob/45e17c045b6609b96ed0c2381156014923c1e8f4/crates/committer/src/patricia_merkle_tree/types.rs#L8)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't you need an `H` type param?
</blockquote></details>

Fixed, thanks
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 18 at r1](https://reviewable.io/reviews/starkware-libs/committer/8#-NuN_9QO8nbi-kV_VIYC:-NuNo-_u1SpB9sA1lio9:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/45e17c045b6609b96ed0c2381156014923c1e8f4/crates/committer/src/patricia_merkle_tree/types.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

even if we combine top and bottom trees we'll only need 9 bits for the length
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 28 at r1](https://reviewable.io/reviews/starkware-libs/committer/8#-NuN_SWoAeGHDbFdiZpJ:-NuNoE6w0t7p0Swf1UT5:bgfque9) ([raw file](https://github.com/starkware-libs/committer/blob/45e17c045b6609b96ed0c2381156014923c1e8f4/crates/committer/src/patricia_merkle_tree/types.rs#L28)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

a `self -> Self` method is redundant;
1. if there is no LeafData concept - remove this function
2. if there is - return `LeafData`, and not `Self`
</blockquote></details>

All three trees may have LeafData, but I think you're right and the method is unnecessary (because the value can be accessed directly, without a method).

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 8 of 13 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/8)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by Yoni-Starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/8)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
