### PR TITLE
build: make log level depend on input

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/313)

### CODE REVIEW

**Review by nimrod-starkware — COMMENTED** [review]
python side [PR](https://reviewable.io/reviews/starkware-industries/starkware/35556)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/313#-:-O1zW4-v3-9GzvK7v5G4:bn3zysc)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/313)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/block_committer/input.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/committer/313#-O1zWH0-9gGXXDLTSNRV:-O1zWH0-9gGXXDLTSNRW:bkhvn93) ([raw file](https://github.com/starkware-libs/committer/blob/56575fd9a4c5051f74bc0a12a131d88906f670c9/crates/committer/src/block_committer/input.rs#L70)):*
> ```XML
>             40 => LevelFilter::Error,
>             _ => panic!("Unexpected log level."),
>         };
> ```

@dorimedini-starkware, do you know a better way to do that?



_Code quote:_
```XML
    pub fn new(warn_on_trivial_modifications: bool, python_logger_level: usize) -> Self {
        let log_level = match python_logger_level {
            10 => LevelFilter::Debug,
            20 => LevelFilter::Info,
            30 => LevelFilter::Warn,
            40 => LevelFilter::Error,
            _ => panic!("Unexpected log level."),
        };
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/313)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/block_committer/input.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/committer/313#-O1zWH0-9gGXXDLTSNRV:-O2-GY6AEoWvMP2QDmi2:b-3a3f1y) ([raw file](https://github.com/starkware-libs/committer/blob/56575fd9a4c5051f74bc0a12a131d88906f670c9/crates/committer/src/block_committer/input.rs#L70)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

@dorimedini-starkware, do you know a better way to do that?
</blockquote></details>

1. what about NOTSET and CRITICAL python levels? if you can set it in python, it should be accepted here.
2. since you use "magic numbers" in the test below, I would even suggest you add a `PythonLogLevel` enum, and add to/from conversions for `usize`. You can also add conversion to `LevelFilter`, to end up with something like this:
```
pub fn new(warn_on_trivial_modifications: bool, python_logger_level: PythonLogLevel)
    Self {
        warn_on_trivial_modifications,
        log_level: python_logger_level.into(),
    }
}
```
and to construct a `ConfigImpl` from python input (for example):
```
ConfigImpl::new(warn_on_trivial, python_level_usize.into());
```
and in tests, use the enum explicitly so it's clear to the reader:
```
config: ConfigImpl::new(true, PythonLogLevel::Debug),
```
___
*[`crates/committer/src/block_committer/input.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/committer/313#-O2-GOC66fYGYNd0qw-B:-O2-GOC66fYGYNd0qw-C:b4q47fs) ([raw file](https://github.com/starkware-libs/committer/blob/a4006c46f4a5a82f2994e2feb0f6da966c5e0359/crates/committer/src/block_committer/input.rs#L69)):*
> ```XML
>             30 => LevelFilter::Warn,
>             40 => LevelFilter::Error,
>             _ => panic!("Unexpected log level."),
> ```

I wouldn't want to ever panic due to bad logger settings... worst case log a warning/error and set the level to DEBUG



_Code quote:_
```XML
_ => panic!("Unexpected log level."),
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 168 at r2](https://reviewable.io/reviews/starkware-libs/committer/313#-O2-I3YPChF2OZ0a7FtK:-O2-I3YPChF2OZ0a7FtL:byr4ffv) ([raw file](https://github.com/starkware-libs/committer/blob/a4006c46f4a5a82f2994e2feb0f6da966c5e0359/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L168)):*
> ```XML
>         contracts_trie_root_hash: HashOutput(Felt::from(861_u128 + 248_u128)),
>         classes_trie_root_hash: HashOutput(Felt::from(155_u128 + 248_u128)),
>         config: ConfigImpl::new(true, 10),
> ```

see above



_Code quote:_
```XML
10
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 290 at r2](https://reviewable.io/reviews/starkware-libs/committer/313#-O2-I4teC1kgQsjEnm5Q:-O2-I4teC1kgQsjEnm5R:byr4ffv) ([raw file](https://github.com/starkware-libs/committer/blob/a4006c46f4a5a82f2994e2feb0f6da966c5e0359/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L290)):*
> ```XML
>         &input.state_diff.actual_classes_updates(),
>         &forest_sorted_indices,
>         &ConfigImpl::new(false, 20),
> ```

see above



_Code quote:_
```XML
20
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/313)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/block_committer/input.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/committer/313#-O1zWH0-9gGXXDLTSNRV:-O2-pETa7x8SD4cbWsiL:bh98ky4) ([raw file](https://github.com/starkware-libs/committer/blob/56575fd9a4c5051f74bc0a12a131d88906f670c9/crates/committer/src/block_committer/input.rs#L70)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. what about NOTSET and CRITICAL python levels? if you can set it in python, it should be accepted here.
2. since you use "magic numbers" in the test below, I would even suggest you add a `PythonLogLevel` enum, and add to/from conversions for `usize`. You can also add conversion to `LevelFilter`, to end up with something like this:
```
pub fn new(warn_on_trivial_modifications: bool, python_logger_level: PythonLogLevel)
    Self {
        warn_on_trivial_modifications,
        log_level: python_logger_level.into(),
    }
}
```
and to construct a `ConfigImpl` from python input (for example):
```
ConfigImpl::new(warn_on_trivial, python_level_usize.into());
```
and in tests, use the enum explicitly so it's clear to the reader:
```
config: ConfigImpl::new(true, PythonLogLevel::Debug),
```
</blockquote></details>

I changed `RawConfigImpl` to:
```
pub(crate) struct RawConfigImpl {
    warn_on_trivial_modifications: bool,
    log_level: PythonLogLevel,
}
```
where
```
#[derive(Deserialize_repr, Debug, Serialize)]
#[repr(usize)]
/// Describes a log level https://docs.python.org/3/library/logging.html#logging-levels
pub(crate) enum PythonLogLevel {
    NotSet = 0,
    Debug = 10,
    Info = 20,
    Warning = 30,
    Error = 40,
    Critical = 50,
}
```
and added `impl From<RawConfigImpl> for ConfigImpl`
___
*[`crates/committer/src/block_committer/input.rs` line 69 at r2](https://reviewable.io/reviews/starkware-libs/committer/313#-O2-GOC66fYGYNd0qw-B:-O2-p-380szSGk-fzxcV:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/a4006c46f4a5a82f2994e2feb0f6da966c5e0359/crates/committer/src/block_committer/input.rs#L69)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I wouldn't want to ever panic due to bad logger settings... worst case log a warning/error and set the level to DEBUG
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 168 at r2](https://reviewable.io/reviews/starkware-libs/committer/313#-O2-I3YPChF2OZ0a7FtK:-O2-p15j9FQ7IZnngliI:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/a4006c46f4a5a82f2994e2feb0f6da966c5e0359/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L168)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 290 at r2](https://reviewable.io/reviews/starkware-libs/committer/313#-O2-I4teC1kgQsjEnm5Q:-O2-pDy74E8Zfsd6i0pE:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/a4006c46f4a5a82f2994e2feb0f6da966c5e0359/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L290)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/313)* status: all files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/block_committer/input.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/committer/313#-O202n7IBLibgPGBw5r_:-O202n7IBLibgPGBw5ra:b-2kqyjc) ([raw file](https://github.com/starkware-libs/committer/blob/fcaf1d10004fc6fcab06424025a177f665e87916/crates/committer/src/block_committer/input.rs#L66)):*
> ```XML
>         }
>     }
> }
> ```

we do we not like this...? I see no reason to protect these members...
out of scope (requires changing all `::new` and all getter method usages) but good to keep in mind,
non-blocking



_Suggestion:_
```XML
#[derive(Debug, Eq, PartialEq)]
pub struct ConfigImpl {
    pub warn_on_trivial_modifications: bool,
    pub log_level: LevelFilter,
}
```
___
*[`crates/committer_cli/src/parse_input/raw_input.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/committer/313#-O203B5cEF5vDOD4vfzc:-O203B5cEF5vDOD4vfzd:b-z5nn5a) ([raw file](https://github.com/starkware-libs/committer/blob/fcaf1d10004fc6fcab06424025a177f665e87916/crates/committer_cli/src/parse_input/raw_input.rs#L41)):*
> ```XML
>     Error = 40,
>     Critical = 50,
> }
> ```

what will happen if you send `7` and try to deserialize?
we don't want to panic in this case



_Code quote:_
```XML
#[repr(usize)]
/// Describes a log level https://docs.python.org/3/library/logging.html#logging-levels
pub(crate) enum PythonLogLevel {
    NotSet = 0,
    Debug = 10,
    Info = 20,
    Warning = 30,
    Error = 40,
    Critical = 50,
}
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/313)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/src/parse_input/raw_input.rs` line 41 at r3](https://reviewable.io/reviews/starkware-libs/committer/313#-O203B5cEF5vDOD4vfzc:-O23gHTu12iPJp8pHmE4:b-hg6p88) ([raw file](https://github.com/starkware-libs/committer/blob/fcaf1d10004fc6fcab06424025a177f665e87916/crates/committer_cli/src/parse_input/raw_input.rs#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what will happen if you send `7` and try to deserialize?
we don't want to panic in this case
</blockquote></details>

Now, it will not panic; if an unknown variant is given, it will be set to the `Debug` level by default.

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/313)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/block_committer/input.rs` line 66 at r3](https://reviewable.io/reviews/starkware-libs/committer/313#-O202n7IBLibgPGBw5r_:-O23mLn6CQ4oWy3dwLLe:bhusitu) ([raw file](https://github.com/starkware-libs/committer/blob/fcaf1d10004fc6fcab06424025a177f665e87916/crates/committer/src/block_committer/input.rs#L66)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we do we not like this...? I see no reason to protect these members...
out of scope (requires changing all `::new` and all getter method usages) but good to keep in mind,
non-blocking
</blockquote></details>

The getters are for the `Config` trait... 
But I agree there is no need to keep those fields private..

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/313#-:-O23mtps2HOSciBPPXte:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Pull request merged**
