### PR TITLE
feat(skeleton): add_node_from_binary_data

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)

### CODE REVIEW

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZcfKF73_f_oq5lKYV:-NyZcfKF73_f_oq5lKYW:bzearsy) ([raw file](https://github.com/starkware-libs/committer/blob/5c95aa4f41ab0bf27bfa4439881a488767814d11/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L86)):*
> ```XML
>                         }
>                         OriginalSkeletonNode::Binary => UpdatedSkeletonNode::Binary,
>                         OriginalSkeletonNode::Leaf(_) => {
> ```

Updating this due to the changes in the UpdateSkeletonTree::create

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 86 at r1](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZcfKF73_f_oq5lKYV:-NyZdno35vLFWYY3XbEj:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/5c95aa4f41ab0bf27bfa4439881a488767814d11/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L86)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Updating this due to the changes in the UpdateSkeletonTree::create
</blockquote></details>

Done

**Review by Yoni-Starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZfC2y5sdW0R6NdeEj:-NyZfC2z0GHpqltLc_UK:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/5c95aa4f41ab0bf27bfa4439881a488767814d11/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L60)):*
> ```XML
>     /// Builds a (probably binary) node from its two updated children. Returns the TempSkeletonNode
>     /// matching the given root for the subtree it is the root of. if one or more children are
>     /// empty the resulting node will not be binary .
> ```





_Suggestion:_
```XML
he resulting node will not be binary.
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZfmhz5xx6u4qunEGm:-NyZfmhz5xx6u4qunEGn:b-s1ouad) ([raw file](https://github.com/starkware-libs/committer/blob/5c95aa4f41ab0bf27bfa4439881a488767814d11/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L70)):*
> ```XML
>         let [left_index, right_index] = root_index.get_children_indices();
> 
>         if *left != TempSkeletonNode::Empty && *right != TempSkeletonNode::Empty {
> ```

Implement `is_empty()` for `TempSkeletonNode`



_Code quote:_
```XML
if *left != TempSkeletonNode::Empty && *right != TempSkeletonNode::Empty {
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 70 at r1](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZfmhz5xx6u4qunEGm:-NyZsCR62cr4aE4oSyRH:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/5c95aa4f41ab0bf27bfa4439881a488767814d11/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L70)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Implement `is_empty()` for `TempSkeletonNode`
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 73 at r2](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZebX61kxjrX_KsloM:-NyZsXTj68U7LBoc9uSm:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/9447486ca63cbd862e663f1808068b5ef588a3be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L73)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think it's clearer to just loop, and not define a lambda function
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZew4ADf8m4k2QucEA:-NyZuvYi7D0nW09Ucgw0:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/9447486ca63cbd862e663f1808068b5ef588a3be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L75)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

save a bit of indentation by flattening the `match` and explicitly panicking on the `Empty` case. no need for `if let .. else`
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 76 at r2](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZfqKo4T6OpqT10cg6:-NyZvH1YBuZTemOm_5K-:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/9447486ca63cbd862e663f1808068b5ef588a3be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L76)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

destructure for the data you use
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 127 at r2](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZhBeM2xH_AJkg_aWy:-Ny_5aD2EdnU5aAtA63K:b-j6teyg) ([raw file](https://github.com/starkware-libs/committer/blob/9447486ca63cbd862e663f1808068b5ef588a3be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L127)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

change the test inputs to integer types and convert them in the test body; makes cases much easier to read.
SkeletonLeaf should have a `from_felt` function or something that you can use
</blockquote></details>

If you want the rest of the args, let's do it in another PR please.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 162 at r2](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZhxVh47EcRrfEUzbH:-NyZw2Oe3D8X2LpT0V7p:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/9447486ca63cbd862e663f1808068b5ef588a3be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L162)):*
> ```XML
>     &TempSkeletonNode::Original(OriginalSkeletonNode::Binary),
>     &[(NodeIndex::from(20), SkeletonLeaf::Zero)],
>     TempSkeletonNode::Original(OriginalSkeletonNode::Edge { path_to_bottom: PathToBottom::from("1") }),
> ```

Done.

**Review by Yoni-Starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 172 at r2](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZi7Zb6OEuBCJd-Dhp:-Ny_7_2UDBTeQGYwrSrK:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/9447486ca63cbd862e663f1808068b5ef588a3be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L172)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add a test case where the right child's subtree is deleted, and the left child was an edge. the expected node should be an edge with +1 length and a path prefixed with an extra `0`, right?
</blockquote></details>

Done.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZew4ADf8m4k2QucEA:-Ny_8jZ57b-TfWl52EDO:b-49c662) ([raw file](https://github.com/starkware-libs/committer/blob/9447486ca63cbd862e663f1808068b5ef588a3be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L75)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not sure the `TempSkeletonNode::Original(` prefix is better.
To avoid the indentation, you can add some kind of `unwrap` method to the temp node. Maybe `original()`.

Also, consider using the native Some/None Enum
```rust
type TempSkeletonNode = Option(OriginalSkeletonNode);
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZew4ADf8m4k2QucEA:-Ny_HsvRA-JJKOgOpQgi:bvxwiqp) ([raw file](https://github.com/starkware-libs/committer/blob/9447486ca63cbd862e663f1808068b5ef588a3be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L75)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Not sure the `TempSkeletonNode::Original(` prefix is better.
To avoid the indentation, you can add some kind of `unwrap` method to the temp node. Maybe `original()`.

Also, consider using the native Some/None Enum
```rust
type TempSkeletonNode = Option(OriginalSkeletonNode);
```
</blockquote></details>

Not sure either what is better, told that to @dorimedini-starkware . Uding Optional to mark an empty valid value seems to me like a bad practice as it's like using `null` as a value.

**Review by Yoni-Starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZew4ADf8m4k2QucEA:-Ny_K_2vAifuB1VkKP0K:ba088xu) ([raw file](https://github.com/starkware-libs/committer/blob/9447486ca63cbd862e663f1808068b5ef588a3be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L75)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Not sure either what is better, told that to @dorimedini-starkware . Uding Optional to mark an empty valid value seems to me like a bad practice as it's like using `null` as a value.
</blockquote></details>

Ok, still consider getting rid of `TempSkeletonNode::Original` using something similar to `unwrap()`/some() etc
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/committer/137#-Ny_LGa05H6Mk3f2i92A:-Ny_LGa05H6Mk3f2i92B:bu4rxf9) ([raw file](https://github.com/starkware-libs/committer/blob/980a1c21921820689b31e430a80bbdc861dd277e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L106)):*
> ```XML
>                             path_to_bottom: *path_to_bottom,
>                         }
>                     }
> ```

Can you document this special case?



_Code quote:_
```XML
                        self.skeleton_tree.insert(
                            path_to_bottom.bottom_index(index),
                            UpdatedSkeletonNode::Sibling(*bottom_hash),
                        );
                        UpdatedSkeletonNode::Edge {
                            path_to_bottom: *path_to_bottom,
                        }
                    }
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)* status: all files reviewed, 6 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 26 at r5](https://reviewable.io/reviews/starkware-libs/committer/137#-Ny_TPkm-huPb5O46HnA:-Ny_TPkm-huPb5O46HnB:baf6zlm) ([raw file](https://github.com/starkware-libs/committer/blob/980a1c21921820689b31e430a80bbdc861dd277e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L26)):*
> ```XML
> impl TempSkeletonNode {
>     fn is_empty(&self) -> bool {
>         *self == TempSkeletonNode::Empty
> ```

non-blocking



_Suggestion:_
```XML
*self == Self::Empty
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 43 at r5](https://reviewable.io/reviews/starkware-libs/committer/137#-Ny_bO6JA7uQGfs7nUaO:-Ny_bO6JA7uQGfs7nUaP:b-gykyea) ([raw file](https://github.com/starkware-libs/committer/blob/980a1c21921820689b31e430a80bbdc861dd277e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L43)):*
> ```XML
>         leaf_modifications,
>     )
> }
> ```

can you make a separate `updated_skeleton_tree` fixture that depends on the `leaf_modifications` fixture and just use both fixtures? why is the tuple fixture needed?
don't you get the `leaf_modifications` as input to the test anyway?



_Code quote:_
```XML
type UpdatedSkeletonAndModifications = (UpdatedSkeletonTreeImpl, LeafModifications<SkeletonLeaf>);

#[fixture]
fn updated_skeleton_and_modifications(
    #[default(&[])] leaf_modifications: &[(u128, u8)],
) -> UpdatedSkeletonAndModifications {
    let leaf_modifications: LeafModifications<SkeletonLeaf> = leaf_modifications
        .iter()
        .map(|(index, leaf_val)| (NodeIndex::from(*index), SkeletonLeaf::from(*leaf_val)))
        .collect();
    let skeleton_tree: HashMap<NodeIndex, UpdatedSkeletonNode> = leaf_modifications
        .iter()
        .filter(|(_, leaf)| !leaf.is_zero())
        .map(|(index, leaf)| (*index, UpdatedSkeletonNode::Leaf(*leaf)))
        .collect();
    (
        UpdatedSkeletonTreeImpl { skeleton_tree },
        leaf_modifications,
    )
}
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 133 at r5](https://reviewable.io/reviews/starkware-libs/committer/137#-Ny_bs8K1e7ythYZdPjO:-Ny_bs8K1e7ythYZdPjP:b-gh16yn) ([raw file](https://github.com/starkware-libs/committer/blob/980a1c21921820689b31e430a80bbdc861dd277e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L133)):*
> ```XML
>     &TempSkeletonNode::Empty,
>     &TempSkeletonNode::Empty,
>     &[(2,0), (3,1)],
> ```

second skeleton leaf should also be zero, no? why did the test pass?



_Suggestion:_
```XML
&[(2,0), (3,0)],
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 197 at r5](https://reviewable.io/reviews/starkware-libs/committer/137#-Ny_cIrUD4BkF0Sb_kHK:-Ny_cIrUD4BkF0Sb_kHL:b-iz57pw) ([raw file](https://github.com/starkware-libs/committer/blob/980a1c21921820689b31e430a80bbdc861dd277e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L197)):*
> ```XML
>     updated_skeleton_and_modifications: UpdatedSkeletonAndModifications,
> ) {
>     let (mut updated_skeleton, leaf_modifications) = updated_skeleton_and_modifications;
> ```

why was this change needed?
can't you send the `leaf_modifications` as fixture input *and* get them as input to the test?



_Code quote:_
```XML
    #[case] _leaf_modifications: &[(u128, u8)],
    #[case] expected_node: TempSkeletonNode,
    #[case] expected_skeleton_additions: &[(NodeIndex, UpdatedSkeletonNode)],
    #[with(_leaf_modifications)]
    updated_skeleton_and_modifications: UpdatedSkeletonAndModifications,
) {
    let (mut updated_skeleton, leaf_modifications) = updated_skeleton_and_modifications;
```

**Review by Yoni-Starkware — COMMENTED** [review]
I'm OOO next week, so you can dismiss my comments if they block you somehow (they should not)

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137#-:-Ny_pgCC8IIf8kxVYMWH:b1wrdld)* status: all files reviewed, 6 unresolved discussions (waiting on @TzahiTaub)

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 75 at r2](https://reviewable.io/reviews/starkware-libs/committer/137#-NyZew4ADf8m4k2QucEA:-Ny_bCUb3Sl611xk67r_:b-wmgu61) ([raw file](https://github.com/starkware-libs/committer/blob/9447486ca63cbd862e663f1808068b5ef588a3be/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L75)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Ok, still consider getting rid of `TempSkeletonNode::Original` using something similar to `unwrap()`/some() etc
</blockquote></details>

Dori to the rescue. Got a nice idea.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 106 at r5](https://reviewable.io/reviews/starkware-libs/committer/137#-Ny_LGa05H6Mk3f2i92A:-Nyb0b0l4_oOGCwtpmOr:bp2qd26) ([raw file](https://github.com/starkware-libs/committer/blob/980a1c21921820689b31e430a80bbdc861dd277e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L106)):*
<details><summary><i>Previously, Yoni-Starkware (Yoni) wrote…</i></summary><blockquote>

Can you document this special case?
</blockquote></details>

Is this OK? Made me think this EdgeSibling variant should be removed entirely from the OriginalSkeleton.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 43 at r5](https://reviewable.io/reviews/starkware-libs/committer/137#-Ny_bO6JA7uQGfs7nUaO:-Nyb2ycd6o8ZLywRLfHs:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/980a1c21921820689b31e430a80bbdc861dd277e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L43)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you make a separate `updated_skeleton_tree` fixture that depends on the `leaf_modifications` fixture and just use both fixtures? why is the tuple fixture needed?
don't you get the `leaf_modifications` as input to the test anyway?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 133 at r5](https://reviewable.io/reviews/starkware-libs/committer/137#-Ny_bs8K1e7ythYZdPjO:-Nyb4V3mDMqdUsO7DWXt:bl67ddz) ([raw file](https://github.com/starkware-libs/committer/blob/980a1c21921820689b31e430a80bbdc861dd277e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L133)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

second skeleton leaf should also be zero, no? why did the test pass?
</blockquote></details>

You are right, but the node_from functions don't check consistency with the leaf_modifications. They only use it when they reach a leaf node. Got me thinking I can rely on the first pass we make on the modifications at the beginning of the create function and not pass as an argument at all. So I changed everything a bit. Sorry.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 197 at r5](https://reviewable.io/reviews/starkware-libs/committer/137#-Ny_cIrUD4BkF0Sb_kHK:-Nyb3aEl2krdQIaWy_5s:b-ci84pw) ([raw file](https://github.com/starkware-libs/committer/blob/980a1c21921820689b31e430a80bbdc861dd277e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L197)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why was this change needed?
can't you send the `leaf_modifications` as fixture input *and* get them as input to the test?
</blockquote></details>

I think I'm done. Is this different from the previous comment about this? :neutral_face:

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 252 at r5](https://reviewable.io/reviews/starkware-libs/committer/137#-NybGdWnCC0nKvsLrJ29:-NybGdWnCC0nKvsLrJ2A:b-dh4sp8) ([raw file](https://github.com/starkware-libs/committer/blob/980a1c21921820689b31e430a80bbdc861dd277e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L252)):*
> ```XML
>     &PathToBottom::RIGHT_CHILD,
>     &NodeIndex::from(7),
>     &TempSkeletonNode::Original(OriginalSkeletonNode::Leaf(SkeletonLeaf::NonZero)),
> ```

Not a possible scenario - if bottom_index is of a deleted leaf, when reaching `node_from_edge_data` as bottom was already updated, it should be `Empty` and this case is the same as the first case.



_Code quote:_
```XML
TempSkeletonNode::Original(OriginalSkeletonNode::Leaf(SkeletonLeaf::NonZero)),
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 140 at r6](https://reviewable.io/reviews/starkware-libs/committer/137#-NynjA05-WmZWxMS_yO8:-NynjA05-WmZWxMS_yO9:b-xgqbls) ([raw file](https://github.com/starkware-libs/committer/blob/ea454da35e63509ab009c27c99946366728a5447/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L140)):*
> ```XML
>                     self.skeleton_tree.contains_key(bottom_index),
>                     "bottom is a non-empty leaf but doesn't appear in the skeleton."
>                 );
> ```

there can be no case where the original node is a leaf that has changed to zero? what's going on here?
if so, please add a TODO to get the set of nonzero leaves as input, instead of modifications (which were already deleted), so the `assert` will no longer be on `skeleton_tree.contains(index)`, but rather on `nonzer_leaves.contains(index)`, seems cleaner



_Code quote:_
```XML
                // Leaf is finalized upon updated skeleton creation.
                // bottom_index is in the skeleton iff it wasn't deleted from the tree.
                assert!(
                    self.skeleton_tree.contains_key(bottom_index),
                    "bottom is a non-empty leaf but doesn't appear in the skeleton."
                );
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 32 at r6](https://reviewable.io/reviews/starkware-libs/committer/137#-NynjkV75U48dfyCgTax:-NynjkV75U48dfyCgTay:b-n9rwlt) ([raw file](https://github.com/starkware-libs/committer/blob/ea454da35e63509ab009c27c99946366728a5447/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L32)):*
> ```XML
>             .filter(|(_, leaf)| !leaf.is_zero())
>             .map(|(index, leaf)| (index, UpdatedSkeletonNode::Leaf(leaf)))
>             .collect(),
> ```

no need to map twice



_Suggestion:_
```XML
        skeleton_tree: leaf_modifications
            .iter()
            .filter(|(_, leaf_val)| leaf_val != Felt::ZERO)
            .map(|(index, leaf_val)| (
               NodeIndex::from(*index),
               UpdatedSkeletonNode::Leaf(SkeletonLeaf::from(*leaf_val))
            ))
            .collect(),
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @Yoni-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs` line 140 at r6](https://reviewable.io/reviews/starkware-libs/committer/137#-NynjA05-WmZWxMS_yO8:-Nynm7MD6ay4BVC60fJy:b62jk94) ([raw file](https://github.com/starkware-libs/committer/blob/ea454da35e63509ab009c27c99946366728a5447/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs#L140)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there can be no case where the original node is a leaf that has changed to zero? what's going on here?
if so, please add a TODO to get the set of nonzero leaves as input, instead of modifications (which were already deleted), so the `assert` will no longer be on `skeleton_tree.contains(index)`, but rather on `nonzer_leaves.contains(index)`, seems cleaner
</blockquote></details>

`self.skeleton_tree` is the **updated** skeleton (added to the comment). Deleted leaves/nodes do not appear in it (we don't need it to compute any hashes, this becomes an empty subtree). No reason to get another input, we only need the fact that all modified non-zero leaves already appear in the updated skeleton.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 32 at r6](https://reviewable.io/reviews/starkware-libs/committer/137#-NynjkV75U48dfyCgTax:-NynlcLZ-_kgsDGMlu2t:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/ea454da35e63509ab009c27c99946366728a5447/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no need to map twice
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/137#-:-Nyo1eAe1ZoRJ8tOyNL7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Yoni-Starkware)

**Pull request merged**
