### PR TITLE
refactor: desrialization structs for regression test output

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/293)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/293)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/committer/293#-O1MtzAX-8N6o8mOx4ya:-O1MtzAX-8N6o8mOx4yb:bf5zxhc) ([raw file](https://github.com/starkware-libs/committer/blob/8ac50c4cde13e16e7e3b27c4c6bcdf1c42514002/crates/committer_cli/src/tests/benchmark_tests.rs#L36)):*
> ```XML
> struct StorageObject {
>     storage: Value,
> }
> ```

why do you need a wrapper for a type that's already serde?



_Code quote:_
```XML
#[derive(Deserialize)]
struct StorageObject {
    storage: Value,
}
```
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/committer/293#-O1Mtt4ZED8MnUbvlMTt:-O1Mtt4ZED8MnUbvlMTu:bt6vqr) ([raw file](https://github.com/starkware-libs/committer/blob/8ac50c4cde13e16e7e3b27c4c6bcdf1c42514002/crates/committer_cli/src/tests/benchmark_tests.rs#L42)):*
> ```XML
>     compiled_class_root_hash: Value,
>     storage: StorageObject,
> }
> ```

newlines between multiline structs please



_Suggestion:_
```XML
#[derive(Deserialize)]
struct CommitterRegressionInput {
    committer_input: String,
    contract_states_root: String,
    contract_classes_root: String,
    expected_facts: String,
}

#[derive(Deserialize)]
struct TreeRegressionOutput {
    root_hash: Value,
    storage_changes: Value,
}

#[derive(Deserialize)]
struct StorageObject {
    storage: Value,
}

#[derive(Deserialize)]
struct CommitterRegressionOutput {
    contract_storage_root_hash: Value,
    compiled_class_root_hash: Value,
    storage: StorageObject,
}
```
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/committer/293#-O1Mu9tcB0f7ECZQwSc8:-O1Mu9tcB0f7ECZQwSc9:bgfl4fj) ([raw file](https://github.com/starkware-libs/committer/blob/8ac50c4cde13e16e7e3b27c4c6bcdf1c42514002/crates/committer_cli/src/tests/benchmark_tests.rs#L85)):*
> ```XML
> 
>     // Assert correctness of the output of the single tree flow test.
>     let regression_output: TreeRegressionOutput = serde_json::from_str(&output).unwrap();
> ```

destructure (removes need for `regression_output.<field_name>`)



_Suggestion:_
```XML
let TreeRegressionOutput { bla } = serde_json::from_str(&output).unwrap();
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/293)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/committer/293#-O1MtzAX-8N6o8mOx4ya:-O1Mx88iBAH4tZHGw7IY:bovsaxs) ([raw file](https://github.com/starkware-libs/committer/blob/8ac50c4cde13e16e7e3b27c4c6bcdf1c42514002/crates/committer_cli/src/tests/benchmark_tests.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need a wrapper for a type that's already serde?
</blockquote></details>

That's not the reason - the reason is that the storage is double-nested in the committer output (i.e., `{"storage":{"storage":{....}}`); I asked about this in the channel, but apparently no one who is available knows.
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 42 at r2](https://reviewable.io/reviews/starkware-libs/committer/293#-O1Mtt4ZED8MnUbvlMTt:-O1Mxm5BBwrFYL9fWDEk:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/8ac50c4cde13e16e7e3b27c4c6bcdf1c42514002/crates/committer_cli/src/tests/benchmark_tests.rs#L42)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

newlines between multiline structs please
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 85 at r2](https://reviewable.io/reviews/starkware-libs/committer/293#-O1Mu9tcB0f7ECZQwSc8:-O1N0n_K046uuQIAHW3c:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/8ac50c4cde13e16e7e3b27c4c6bcdf1c42514002/crates/committer_cli/src/tests/benchmark_tests.rs#L85)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

destructure (removes need for `regression_output.<field_name>`)
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/293)* status: all files reviewed, 3 unresolved discussions (waiting on @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/committer/293#-O1MtzAX-8N6o8mOx4ya:-O1N3uGBA4WpquDA-EzZ:bfku9q0) ([raw file](https://github.com/starkware-libs/committer/blob/8ac50c4cde13e16e7e3b27c4c6bcdf1c42514002/crates/committer_cli/src/tests/benchmark_tests.rs#L36)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

That's not the reason - the reason is that the storage is double-nested in the committer output (i.e., `{"storage":{"storage":{....}}`); I asked about this in the channel, but apparently no one who is available knows.
</blockquote></details>

@nimrod-starkware ?
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 93 at r3](https://reviewable.io/reviews/starkware-libs/committer/293#-O1N41aCCJbls3_Ao0oI:-O1N41aCCJbls3_Ao0oJ:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/b3f50c341e2686bf681df845edba2018c5539e39/crates/committer_cli/src/tests/benchmark_tests.rs#L93)):*
> ```XML
>     let TreeRegressionOutput {
>         root_hash,
>         storage_changes: Value::Object(acutal_storage_changes),
> ```

typo



_Code quote:_
```XML
acutal_
```
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/committer/293#-O1N451JCp4Q55qlXQ-h:-O1N451JCp4Q55qlXQ-i:b61m0wb) ([raw file](https://github.com/starkware-libs/committer/blob/b3f50c341e2686bf681df845edba2018c5539e39/crates/committer_cli/src/tests/benchmark_tests.rs#L97)):*
> ```XML
>     else {
>         panic!("Expected storage changes object to be an object.");
>     };
> ```

strange that this is needed. if the output of `serde_json::from_str(&output)` cannot be destructured like you request, won't `unwrap()` panic now? nono-blocking



_Code quote:_
```XML
    else {
        panic!("Expected storage changes object to be an object.");
    };
```

**Comment by aner-starkware** [comment]
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/committer/293#-O1MtzAX-8N6o8mOx4ya:-O1N5kJKA8QfTM5LaLFC:bk0sirp) ([raw file](https://github.com/starkware-libs/committer/blob/8ac50c4cde13e16e7e3b27c4c6bcdf1c42514002/crates/committer_cli/src/tests/benchmark_tests.rs#L36)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

@nimrod-starkware ?
</blockquote></details>

I think it's probably @yoavGrs

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/293)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, @TzahiTaub, and @yoavGrs)

___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/committer/293#-O1N451JCp4Q55qlXQ-h:-O1N8Z9o-4NAONHQL2_O:bc7ujn1) ([raw file](https://github.com/starkware-libs/committer/blob/b3f50c341e2686bf681df845edba2018c5539e39/crates/committer_cli/src/tests/benchmark_tests.rs#L97)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

strange that this is needed. if the output of `serde_json::from_str(&output)` cannot be destructured like you request, won't `unwrap()` panic now? nono-blocking
</blockquote></details>

I didn't put this out of my own free will  :sweat_smile: 
p.s. does "nono-blocking" actually mean blocking? :thinking:

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/293#-:-O1NBIQe22ummoILI4pZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware, @TzahiTaub, and @yoavGrs)

___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 36 at r2](https://reviewable.io/reviews/starkware-libs/committer/293#-O1MtzAX-8N6o8mOx4ya:-O1NB7kD2VNsr2euM5AL:b-nlb3cb) ([raw file](https://github.com/starkware-libs/committer/blob/8ac50c4cde13e16e7e3b27c4c6bcdf1c42514002/crates/committer_cli/src/tests/benchmark_tests.rs#L36)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I think it's probably @yoavGrs
</blockquote></details>

why yoav? nimrod was in charge of python->rust serde, no?
unblocking anyway, out of scope
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 97 at r3](https://reviewable.io/reviews/starkware-libs/committer/293#-O1N451JCp4Q55qlXQ-h:-O1NAxueBGPgjmzpscZA:bq7o2hc) ([raw file](https://github.com/starkware-libs/committer/blob/b3f50c341e2686bf681df845edba2018c5539e39/crates/committer_cli/src/tests/benchmark_tests.rs#L97)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I didn't put this out of my own free will  :sweat_smile: 
p.s. does "nono-blocking" actually mean blocking? :thinking:
</blockquote></details>

yes, not all conversations are marked with :no_entry:

**Pull request merged**
