### PR TITLE
chore: change the inner field in NodeIndex from felt to U256

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/79)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/79)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/committer/79#-NwoEKAWEvanHxJYIskI:-NwoEKAWEvanHxJYIskJ:b-t8mtaj) ([raw file](https://github.com/starkware-libs/committer/blob/4f1d9e0af276700f0c0c79ed088ca20922ff4f0e/crates/committer/src/patricia_merkle_tree/types.rs#L27)):*
> ```XML
> 
> #[allow(dead_code)]
> // Wraps a U256. Maximal possible value is the largest index in a tree of height 252 (2 ^ 252 - 1).
> ```

max index in a tree of height `H` is `2^(H+1)-1`, right?



_Suggestion:_
```XML
// Wraps a U256. Maximal possible value is the largest index in a tree of height 251 (2 ^ 252 - 1).
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/committer/79#-NwoE_KC7Mf8AI-x2GNQ:-NwoE_KC7Mf8AI-x2GNR:bq5yli0) ([raw file](https://github.com/starkware-libs/committer/blob/4f1d9e0af276700f0c0c79ed088ca20922ff4f0e/crates/committer/src/patricia_merkle_tree/types.rs#L63)):*
> ```XML
>         NodeIndex(self.0 >> rhs)
>     }
> }
> ```

needed? I only see left shift



_Code quote:_
```XML
impl std::ops::Shr<u8> for NodeIndex {
    type Output = Self;

    fn shr(self, rhs: u8) -> Self::Output {
        NodeIndex(self.0 >> rhs)
    }
}
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/committer/79#-NwoEuEj5LFffg3R79W2:-NwoEuEj5LFffg3R79W3:baodis3) ([raw file](https://github.com/starkware-libs/committer/blob/4f1d9e0af276700f0c0c79ed088ca20922ff4f0e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L116)):*
> ```XML
>             UpdatedSkeletonNode::Binary => {
>                 let left_index = NodeIndex(index.0 * 2);
>                 let right_index = NodeIndex(left_index.0 + 1);
> ```

if you add `#[derive(derive_more::Add, derive_more::Mul)]` to the NodeIndex struct you should be able to do this.
non-blocking



_Suggestion:_
```XML
                let left_index = index * NodeIndex(2);
                let right_index = left_index + NodeIndex(1);
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/79)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 27 at r2](https://reviewable.io/reviews/starkware-libs/committer/79#-NwoEKAWEvanHxJYIskI:-NwoPjHs0SUQ0ayxFr-O:b-7xt2jw) ([raw file](https://github.com/starkware-libs/committer/blob/4f1d9e0af276700f0c0c79ed088ca20922ff4f0e/crates/committer/src/patricia_merkle_tree/types.rs#L27)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

max index in a tree of height `H` is `2^(H+1)-1`, right?
</blockquote></details>

Yes. 
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 63 at r2](https://reviewable.io/reviews/starkware-libs/committer/79#-NwoE_KC7Mf8AI-x2GNQ:-NwoQIDS7bLNnk5iomyp:b-iofm0z) ([raw file](https://github.com/starkware-libs/committer/blob/4f1d9e0af276700f0c0c79ed088ca20922ff4f0e/crates/committer/src/patricia_merkle_tree/types.rs#L63)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

needed? I only see left shift
</blockquote></details>

Not ATM, but it seems to make sense to add (same implementation, and it's what you need if you want to go from child to parent in the indices).
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/committer/79#-NwoEuEj5LFffg3R79W2:-NwoW-GJ2LzDBZu8AD2b:b-nmcnh9) ([raw file](https://github.com/starkware-libs/committer/blob/4f1d9e0af276700f0c0c79ed088ca20922ff4f0e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L116)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you add `#[derive(derive_more::Add, derive_more::Mul)]` to the NodeIndex struct you should be able to do this.
non-blocking
</blockquote></details>

I have no idea why the multiplication works directly, but is this OK?

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/79#-:-NwoYX3F6zBevGJbiarn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/committer/79#-NwoEuEj5LFffg3R79W2:-NwoYLtU9rDbU7tfJoOT:b-chcy0z) ([raw file](https://github.com/starkware-libs/committer/blob/4f1d9e0af276700f0c0c79ed088ca20922ff4f0e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L116)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I have no idea why the multiplication works directly, but is this OK?
</blockquote></details>

it's ok; I guess maybe `index * 2` is implicitly `index * 2.into()`?

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/79)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs` line 116 at r2](https://reviewable.io/reviews/starkware-libs/committer/79#-NwoEuEj5LFffg3R79W2:-Nwp44oY4TAYAJ8vET67:b-71s3d5) ([raw file](https://github.com/starkware-libs/committer/blob/4f1d9e0af276700f0c0c79ed088ca20922ff4f0e/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs#L116)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

it's ok; I guess maybe `index * 2` is implicitly `index * 2.into()`?
</blockquote></details>

But `left_index + 1` doesn't work, cant' think of a reason for the difference.

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/79)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
