### PR TITLE
build: add serialization tests

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This PR introduces serialization tests and updates to ensure consistency between Python and Rust

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/75)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/75)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`Cargo.lock` line 0 at r1](https://reviewable.io/reviews/starkware-libs/committer/75#-NwjjwWB7hAP8auYEgj4:-NwjjwWB7hAP8auYEgj5:b-o70don) ([raw file](https://github.com/starkware-libs/committer/blob/ca3f6394eadbf15498fc6222019568857ac8651e/Cargo.lock#L0)):*
why did this file change? I see no change to cargo.toml, can you revert this change?
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/committer/75#-NwjkFsa4ap8oYQ-wSRO:-NwjkFsa4ap8oYQ-wSRP:bo1fl2l) ([raw file](https://github.com/starkware-libs/committer/blob/ca3f6394eadbf15498fc6222019568857ac8651e/crates/committer_cli/src/tests/python_tests.rs#L17)):*
> ```XML
>     HashFunction,
>     BinarySerialize,
>     NodeKey,
> ```

there are four tests here; please split into 4 PRs.
I would like to see why the `pub(crate)`s need to become `pub`, and it is much harder with four tests at once



_Code quote:_
```XML
    FeltSerialize,
    HashFunction,
    BinarySerialize,
    NodeKey,
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/75)* status: 1 of 12 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 17 at r1](https://reviewable.io/reviews/starkware-libs/committer/75#-NwjkFsa4ap8oYQ-wSRO:-NwmwX0g7venMu1jQVEL:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/ca3f6394eadbf15498fc6222019568857ac8651e/crates/committer_cli/src/tests/python_tests.rs#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there are four tests here; please split into 4 PRs.
I would like to see why the `pub(crate)`s need to become `pub`, and it is much harder with four tests at once
</blockquote></details>

Done.
___
*[`Cargo.lock` line  at r1](https://reviewable.io/reviews/starkware-libs/committer/75#-NwjjwWB7hAP8auYEgj4:-NwmwmlXCTFy4ZvAjKFI:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/ca3f6394eadbf15498fc6222019568857ac8651e/Cargo.lock#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why did this file change? I see no change to cargo.toml, can you revert this change?
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/75)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/committer/75#-NwnB7Lx2mHyB7s1FixU:-NwnB7Lx2mHyB7s1FixV:bmg3fj5) ([raw file](https://github.com/starkware-libs/committer/blob/c0aedf48fccc87c96ce407dbfd4fc24549bc7807/crates/committer_cli/src/tests/python_tests.rs#L151)):*
> ```XML
> ///
> pub(crate) fn test_node_db_key() -> String {
>     let zero: u128 = 0;
> ```

either change the type of this variable (you only use it to make a Felt::ZERO, right?), or remove it completely (use Felt::ZERO everywhere)



_Suggestion:_
```XML
let zero: Felt = Felt::ZERO;
```
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/committer/75#-NwnAxbyA6zhF_X4UT5L:-NwnAxbyA6zhF_X4UT5M:b-ksxzvp) ([raw file](https://github.com/starkware-libs/committer/blob/c0aedf48fccc87c96ce407dbfd4fc24549bc7807/crates/committer_cli/src/tests/python_tests.rs#L154)):*
> ```XML
> 
>     // Generate keys for different node types.
>     let hash = HashOutput(Felt::from(zero));
> ```

there's a const for that, no?



_Suggestion:_
```XML
Felt::ZERO
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/75)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer_cli/src/tests/python_tests.rs` line 151 at r2](https://reviewable.io/reviews/starkware-libs/committer/75#-NwnB7Lx2mHyB7s1FixU:-NwnKgrH8J8I6L29jnzY:bsewfpt) ([raw file](https://github.com/starkware-libs/committer/blob/c0aedf48fccc87c96ce407dbfd4fc24549bc7807/crates/committer_cli/src/tests/python_tests.rs#L151)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

either change the type of this variable (you only use it to make a Felt::ZERO, right?), or remove it completely (use Felt::ZERO everywhere)
</blockquote></details>

I did it because I thought that it might cause a problem to put the same object as a field. But Its ok since it const. Thanks.
___
*[`crates/committer_cli/src/tests/python_tests.rs` line 154 at r2](https://reviewable.io/reviews/starkware-libs/committer/75#-NwnAxbyA6zhF_X4UT5L:-NwnPq2f-0jy4kSnbPe3:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/c0aedf48fccc87c96ce407dbfd4fc24549bc7807/crates/committer_cli/src/tests/python_tests.rs#L154)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

there's a const for that, no?
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/75#-:-NwniOTtEDYLbLqx-YHF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
