### PR TITLE
fix: fix bug in tree hash function definition

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/121)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/121)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/committer/121#-Ny2Xc-s7BGkBJTacr3e:-Ny2Xc-s7BGkBJTacr3f:b-ehc8m9) ([raw file](https://github.com/starkware-libs/committer/blob/7ed54e3d2a4b7046a47115340dad4d26f8c78074/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L28)):*
> ```XML
> pub const CONTRACT_STATE_HASH_VERSION: Felt = Felt::ZERO;
> // The hex string corresponding to b'CONTRACT_CLASS_LEAF_V0' in big-endian.
> pub const CONTRACT_CLASS_LEAF_V0: &str = "0x434f4e54524143545f434c4153535f4c4541465f5630";
> ```

add a tiny unit test that asserts this is true



_Code quote:_
```XML
// The hex string corresponding to b'CONTRACT_CLASS_LEAF_V0' in big-endian.
pub const CONTRACT_CLASS_LEAF_V0: &str = "0x434f4e54524143545f434c4153535f4c4541465f5630";
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs` line 65 at r2](https://reviewable.io/reviews/starkware-libs/committer/121#-Ny2XsYw6QBotzPF877N:-Ny2XsYw6QBotzPF877O:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/7ed54e3d2a4b7046a47115340dad4d26f8c78074/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs#L65)):*
> ```XML
> 
> #[rstest]
> // expected hash value was computed independently.
> ```





_Suggestion:_
```XML
Exp
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/121)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 28 at r2](https://reviewable.io/reviews/starkware-libs/committer/121#-Ny2Xc-s7BGkBJTacr3e:-Ny5nbcHANklj3yYb_Xq:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/7ed54e3d2a4b7046a47115340dad4d26f8c78074/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L28)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add a tiny unit test that asserts this is true
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/121#-:-Ny7pIEbDkcHOxBIbiV0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/121)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/committer/121#-NyEeLK2BvwXF-n40BWa:-NyEeLK2BvwXF-n40BWb:bxhmdg3) ([raw file](https://github.com/starkware-libs/committer/blob/cbb2b680c291063cd4e2585c20a910521a5abbcc/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L49)):*
> ```XML
>                     "could not parse hex string corresponding to b'CONTRACT_CLASS_LEAF_V0' to Felt",
>                 );
>                 PoseidonHashFunction::compute_hash(HashInputPair(
> ```

I don't like this... trees need *two* hash functions now? because the compiled class tree uses pedersen on internal nodes and poseidon on leaves?



_Code quote:_
```XML
PoseidonHashFunction
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/121)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @aner-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/committer/121#-NyEeLK2BvwXF-n40BWa:-NyF4BC818CYZsNkZ_OB:bfh0ctm) ([raw file](https://github.com/starkware-libs/committer/blob/cbb2b680c291063cd4e2585c20a910521a5abbcc/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L49)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

That's as far as I understand. Maybe we could leave it as an implementation detail (i.e., without generics) for now - we don't know if the second hash function (which is already Poseidon) will need to be changed.
</blockquote></details>

I think we need to get rid of `HashFunction` and only keep `TreeHashFunction`, and all implementation details / low-level hash function choices should be in the tree hash function.
Out of scope of this PR anyway;
please add a TODO over this line and I'll unblock

**Comment by aner-starkware** [comment]
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs` line 49 at r4](https://reviewable.io/reviews/starkware-libs/committer/121#-NyEeLK2BvwXF-n40BWa:-NyG3kCx2jR2eI7bsgdK:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/cbb2b680c291063cd4e2585c20a910521a5abbcc/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think we need to get rid of `HashFunction` and only keep `TreeHashFunction`, and all implementation details / low-level hash function choices should be in the tree hash function.
Out of scope of this PR anyway;
please add a TODO over this line and I'll unblock
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/121)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware, @nimrod-starkware, and @TzahiTaub)

**Pull request merged**
