### PR TITLE
build: impl db key to filled node

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
Implementation of db_key function for filled node.

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/49)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/49)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/committer/49#-Nvl2rQ6E94MFLkO2Wjn:-Nvl2rQ78dhw-5SBGonR:b-5y0fj) ([raw file](https://github.com/starkware-libs/committer/blob/a2b634690bd507612c4bbed13ed5007dae55d78e/crates/committer/src/patricia_merkle_tree/filled_node.rs#L171)):*
> ```XML
>                     db_key_from_suffix(STATE_TREE_LEAF_PREFIX, &suffix)
>                 }
>             },
> ```

no reason to nest the match



_Suggestion:_
```XML
            NodeData::Leaf(LeafData::StorageValue(_)) => db_key_from_suffix(STORAGE_LEAF_PREFIX, &suffix),
            NodeData::Leaf(LeafData::CompiledClassHash(_)) => {
                db_key_from_suffix(COMPLIED_CLASS_PREFIX, &suffix)
            }
            NodeData::Leaf(LeafData::StateTreeTuple { .. }) => {
                db_key_from_suffix(STATE_TREE_LEAF_PREFIX, &suffix)
            }
```
___
*[`crates/committer/src/storage/storage_trait.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/committer/49#-Nvl3LHY-JBdV2mH9ZnN:-Nvl3LHY-JBdV2mH9ZnO:b-26oiqn) ([raw file](https://github.com/starkware-libs/committer/blob/a2b634690bd507612c4bbed13ed5007dae55d78e/crates/committer/src/storage/storage_trait.rs#L31)):*
> ```XML
> 
> /// Returns a `StorageKey` from a prefix and a suffix.
> pub(crate) fn db_key_from_suffix(prefix: &[u8], suffix: &[u8]) -> StorageKey {
> ```

not from suffix - from both prefix and suffix



_Suggestion:_
```XML
db_key
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/49)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_node.rs` line 171 at r1](https://reviewable.io/reviews/starkware-libs/committer/49#-Nvl2rQ6E94MFLkO2Wjn:-Nvld4TG90YK2hYzH3y7:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/a2b634690bd507612c4bbed13ed5007dae55d78e/crates/committer/src/patricia_merkle_tree/filled_node.rs#L171)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no reason to nest the match
</blockquote></details>

Done.
___
*[`crates/committer/src/storage/storage_trait.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/committer/49#-Nvl3LHY-JBdV2mH9ZnN:-NvldgbU-Hb_thGtDK6G:b-i75fqe) ([raw file](https://github.com/starkware-libs/committer/blob/a2b634690bd507612c4bbed13ed5007dae55d78e/crates/committer/src/storage/storage_trait.rs#L31)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not from suffix - from both prefix and suffix
</blockquote></details>

Don't you think that it is a little confusing with the name of the function in serde trait?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/49)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @AvivYossef-starkware)

___
*[`crates/committer/src/storage/storage_trait.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/committer/49#-Nvl3LHY-JBdV2mH9ZnN:-Nvlf5k-3Ol1-UbkCvBe:b-vjq8j5) ([raw file](https://github.com/starkware-libs/committer/blob/a2b634690bd507612c4bbed13ed5007dae55d78e/crates/committer/src/storage/storage_trait.rs#L31)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Don't you think that it is a little confusing with the name of the function in serde trait?
</blockquote></details>

ok, so `create_db_key`?

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/49)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/storage/storage_trait.rs` line 31 at r1](https://reviewable.io/reviews/starkware-libs/committer/49#-Nvl3LHY-JBdV2mH9ZnN:-NvlfpVb2aW_WH5nIyOg:b2ni9bh) ([raw file](https://github.com/starkware-libs/committer/blob/a2b634690bd507612c4bbed13ed5007dae55d78e/crates/committer/src/storage/storage_trait.rs#L31)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ok, so `create_db_key`?
</blockquote></details>

ok.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/49#-:-Nvlh65-6PWdM51s5B1z:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
