### PR TITLE
fix: remove the usage of the bisection crate

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/318)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/318)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 283 at r1](https://reviewable.io/reviews/starkware-libs/committer/318#-O201uhJ3GiYYvyeGmfA:-O201uhJ3GiYYvyeGmfB:b-izo5sm) ([raw file](https://github.com/starkware-libs/committer/blob/b5c28dfaf467b207ce2369d0b0e8ec41f5b7338e/crates/committer/src/patricia_merkle_tree/types.rs#L283)):*
> ```XML
>             Ok(pos) => pos + 1,
>         }
>     }
> ```

can you add docstrings (`///`) above each of these please?



_Code quote:_
```XML
    pub(crate) fn bisect_left(&self, leftmost_value: &NodeIndex) -> usize {
        match self.0.binary_search(leftmost_value) {
            Ok(pos) | Err(pos) => pos,
        }
    }

    pub(crate) fn bisect_right(&self, rightmost_value: &NodeIndex) -> usize {
        match self.0.binary_search(rightmost_value) {
            Err(pos) => pos,
            Ok(pos) => pos + 1,
        }
    }
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/318)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 283 at r1](https://reviewable.io/reviews/starkware-libs/committer/318#-O201uhJ3GiYYvyeGmfA:-O240HLjCo0z3A-hotKO:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/b5c28dfaf467b207ce2369d0b0e8ec41f5b7338e/crates/committer/src/patricia_merkle_tree/types.rs#L283)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you add docstrings (`///`) above each of these please?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 273 at r2](https://reviewable.io/reviews/starkware-libs/committer/318#-O240J6KAtQgjg3obL7e:-O240J6KAtQgjg3obL7f:b-9895q9) ([raw file](https://github.com/starkware-libs/committer/blob/ecbc2c7d0de0235a43af31a6f199d4eb351a7a79/crates/committer/src/patricia_merkle_tree/types.rs#L273)):*
> ```XML
> 
>     /// Returns the leftmost position where `leftmost_value` can be inserted to the slice and
>     /// maintain sorted order. Assumes that the elements in the slice are unique.
> ```

In our context, it's always the case (we create the indices from keys of hashmaps).
Is it a reasonable assumption?



_Code quote:_
```XML
 Assumes that the elements in the slice are unique.
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/318)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 273 at r2](https://reviewable.io/reviews/starkware-libs/committer/318#-O240J6KAtQgjg3obL7e:-O249N3MBUj1c_01gusf:b-caegrs) ([raw file](https://github.com/starkware-libs/committer/blob/ecbc2c7d0de0235a43af31a6f199d4eb351a7a79/crates/committer/src/patricia_merkle_tree/types.rs#L273)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

In our context, it's always the case (we create the indices from keys of hashmaps).
Is it a reasonable assumption?
</blockquote></details>

yes; however, it may be wise to add a check for uniqueness in `SortedLeafIndices::new`. WDYT?

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/318#-:-O24A0CC8hKJm2iM3VkD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/318)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 273 at r2](https://reviewable.io/reviews/starkware-libs/committer/318#-O240J6KAtQgjg3obL7e:-O24EZZz4CV1UQdqBoTu:b-yt8cw7) ([raw file](https://github.com/starkware-libs/committer/blob/ecbc2c7d0de0235a43af31a6f199d4eb351a7a79/crates/committer/src/patricia_merkle_tree/types.rs#L273)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes; however, it may be wise to add a check for uniqueness in `SortedLeafIndices::new`. WDYT?
</blockquote></details>

I added a TODO for that.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/318)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
