### PR TITLE
feat(block_hash): add objects

### PR DESCRIPTION
**Pull request by yoavGrs**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/217)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/217)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/committer_cli/src/tests/utils/objects.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/committer/217#-O-15TNQ8DWq6vBf4jNi:-O-15TNQ8DWq6vBf4jNj:bpxsnp0) ([raw file](https://github.com/starkware-libs/committer/blob/cf72bf6ba6cbe329df514c1721c856bf7b594983/crates/committer_cli/src/tests/utils/objects.rs#L92)):*
> ```XML
> ) -> BlockCommitmentsInput {
>     BlockCommitmentsInput {
>         transactions_data: vec![get_tx_data(&TransactionExecutionStatus::Succeeded); n_txs],
> ```

maybe better to check an unsuccessful tx to check different variant serde; non-blocking



_Code quote:_
```XML
get_tx_data(&TransactionExecutionStatus::Succeeded); n_txs
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/217)* status: all files reviewed, 1 unresolved discussion (waiting on @yoavGrs)

___
*[`crates/committer_cli/src/main.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/committer/217#-O-20Og196XygFDfApwY:-O-20Og196XygFDfApwZ:b-gvflig) ([raw file](https://github.com/starkware-libs/committer/blob/89f44458c825c3ac2b71e6de523913fadd1c2961/crates/committer_cli/src/main.rs#L50)):*
> ```XML
>         #[clap(long)]
>         input: String,
>     },
> ```

1. alphabetize (and nice to have tests at the end)
2. add a docstring above BlockHashCommitments (should be printed out with `--help` IIUC)



_Suggestion:_
```XML
enum Command {
    BlockHashCommitments {
        #[clap(long)]
        input: String,
    },    
    /// Given previous state tree skeleton and a state diff, computes the new commitment.
    Commit {
        /// File path to input.
        #[clap(long, short = 'i', default_value = "stdin")]
        input_path: String,

        /// File path to output.
        #[clap(long, short = 'o', default_value = "stdout")]
        output_path: String,
    },
    PythonTest {
        /// Test name.
        #[clap(long)]
        test_name: String,

        /// Test inputs as a json.
        #[clap(long)]
        inputs: Option<String>,
    },
```

**Review by yoavGrs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/217)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer_cli/src/main.rs` line 50 at r2](https://reviewable.io/reviews/starkware-libs/committer/217#-O-20Og196XygFDfApwY:-O-FJtcv9W5PQuB6v7fr:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/89f44458c825c3ac2b71e6de523913fadd1c2961/crates/committer_cli/src/main.rs#L50)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. alphabetize (and nice to have tests at the end)
2. add a docstring above BlockHashCommitments (should be printed out with `--help` IIUC)
</blockquote></details>

Done.
___
*[`crates/committer_cli/src/tests/utils/objects.rs` line 92 at r1](https://reviewable.io/reviews/starkware-libs/committer/217#-O-15TNQ8DWq6vBf4jNi:-O-FJNO39ndSwb4EjDjh:bmjtait) ([raw file](https://github.com/starkware-libs/committer/blob/cf72bf6ba6cbe329df514c1721c856bf7b594983/crates/committer_cli/src/tests/utils/objects.rs#L92)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

maybe better to check an unsuccessful tx to check different variant serde; non-blocking
</blockquote></details>

We check it with `parse_tx_output_test`.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/217#-:-O-GBefW7EAyu9VRKu8J:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
