### PR TITLE
build: add bazel rules

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/3)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/3)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @TzahiTaub)

___
*[`crates/committer/BUILD` line 10 at r1](https://reviewable.io/reviews/starkware-libs/committer/3#-NtBgIuyEK8i7prrGA5O:-NtBgIuyEK8i7prrGA5P:bq51dpp) ([raw file](https://github.com/starkware-libs/committer/blob/8541a43100ea251c79971efd08b038352d1c610c/crates/committer/BUILD#L10)):*
> ```Starlark
>     edition = "2021",
>     proc_macro_deps = all_crate_deps(proc_macro = True),
>     visibility = ["//visibility:public"],
> ```

why does blockifier repo use `"//crates:__subpackages__"` visibility?



_Code quote:_
```Starlark
visibility = ["//visibility:public"],
```
___
*[`crates/committer/BUILD` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/3#-NtBgf_89LXG7q-TNpRz:-NtBgf_89LXG7q-TNpS-:b-moww0c) ([raw file](https://github.com/starkware-libs/committer/blob/8541a43100ea251c79971efd08b038352d1c610c/crates/committer/BUILD#L11)):*
> ```Starlark
>     proc_macro_deps = all_crate_deps(proc_macro = True),
>     visibility = ["//visibility:public"],
>     deps = all_crate_deps(),
> ```

same format and order as the blockifier BUILD file



_Suggestion:_
```Starlark
    name="committer_exe",
    srcs=glob(["src/**/*.rs"]),
    visibility=["//visibility:public"],
    deps=all_crate_deps(),
    proc_macro_deps=all_crate_deps(proc_macro=True),
    edition="2021",
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/3)* status: all files reviewed, 5 unresolved discussions (waiting on @alon-dotan-starkware and @TzahiTaub)

___
*[`crates/committer/src/main.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/committer/3#-NtBo7N2-C68PScvj2jX:-NtBo7N2-C68PScvj2jY:b-8it5sq) ([raw file](https://github.com/starkware-libs/committer/blob/8541a43100ea251c79971efd08b038352d1c610c/crates/committer/src/main.rs#L5)):*
> ```XML
> 
> /// Gets a binary input and an output file from the command line.
> /// Reads the input file, adds 1 to each byte, and writes the result to the output file.
> ```

forward-facing comment



_Suggestion:_
```XML
/// Main entry point of the committer CLI.
```
___
*[`crates/committer/src/main.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/committer/3#-NtBo2ykBqXwXw4rTlCi:-NtBo2ykBqXwXw4rTlCj:bro1gjy) ([raw file](https://github.com/starkware-libs/committer/blob/8541a43100ea251c79971efd08b038352d1c610c/crates/committer/src/main.rs#L7)):*
> ```XML
> /// Reads the input file, adds 1 to each byte, and writes the result to the output file.
> fn main() {
>     // Open the input file
> ```

we don't have comment linter scripts ATM



_Suggestion:_
```XML
// Open the input file.
```
___
*[`crates/committer/src/main.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/3#-NtBnfQd12-kpBujgO71:-NtBnfQd12-kpBujgO72:b-oy30ij) ([raw file](https://github.com/starkware-libs/committer/blob/8541a43100ea251c79971efd08b038352d1c610c/crates/committer/src/main.rs#L22)):*
> ```XML
>     }
>     std::fs::write(output_file_name, bytes).expect("Failed to write output");
> }
> ```

remove the dummy logic before merging (we keep the input-output file logic, it will be useful)



_Suggestion:_
```XML
use std::env;
use std::path::Path;

/// Gets a binary input and an output file from the command line.
/// Reads the input file, adds 1 to each byte, and writes the result to the output file.
fn main() {
    // Open the input file
    let args: Vec<String> = env::args().collect();
    let input_file_name = Path::new(&args[1]);
    let output_file_name = Path::new(&args[2]);
    assert!(
        input_file_name.is_absolute() && output_file_name.is_absolute(),
        "Given paths must be absolute"
    );
    
    // Business logic to be implemented here.
    let output = std::fs::read(input_file_name).unwrap();
    
    // Output to file.
    std::fs::write(output_file_name, output).expect("Failed to write output");
}
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/3)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @alon-dotan-starkware and @dorimedini-starkware)

___
*[`crates/committer/BUILD` line 10 at r1](https://reviewable.io/reviews/starkware-libs/committer/3#-NtBgIuyEK8i7prrGA5O:-NtBhUqe06mMbmGJf9hw:b-hbg2w) ([raw file](https://github.com/starkware-libs/committer/blob/8541a43100ea251c79971efd08b038352d1c610c/crates/committer/BUILD#L10)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why does blockifier repo use `"//crates:__subpackages__"` visibility?
</blockquote></details>

I had to change it to use it in the main repo. As far as I understand, the blockifier repo target you mention is not used externally, but is a dependency of the `py_lib` under `crates/native_blockifier/BUILD` which is the one that is used externally, and also has a visibility public. We use the target above directly.
___
*[`crates/committer/BUILD` line 11 at r1](https://reviewable.io/reviews/starkware-libs/committer/3#-NtBgf_89LXG7q-TNpRz:-NtBwcVZ4OUJFf76ooSJ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/8541a43100ea251c79971efd08b038352d1c610c/crates/committer/BUILD#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

same format and order as the blockifier BUILD file
</blockquote></details>

Done.
___
*[`crates/committer/src/main.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/committer/3#-NtBo7N2-C68PScvj2jX:-NtBwnqO4-YxQotdIKZP:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/8541a43100ea251c79971efd08b038352d1c610c/crates/committer/src/main.rs#L5)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

forward-facing comment
</blockquote></details>

Done.
___
*[`crates/committer/src/main.rs` line 7 at r1](https://reviewable.io/reviews/starkware-libs/committer/3#-NtBo2ykBqXwXw4rTlCi:-NtBwkLj9B2p9cuP-r1E:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/8541a43100ea251c79971efd08b038352d1c610c/crates/committer/src/main.rs#L7)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

we don't have comment linter scripts ATM
</blockquote></details>

Done.
___
*[`crates/committer/src/main.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/3#-NtBnfQd12-kpBujgO71:-NtBxWxs9JjM1WJUi6Qc:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/8541a43100ea251c79971efd08b038352d1c610c/crates/committer/src/main.rs#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove the dummy logic before merging (we keep the input-output file logic, it will be useful)
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/3)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @TzahiTaub)

___
*[`crates/committer/src/lib.rs` line 0 at r3](https://reviewable.io/reviews/starkware-libs/committer/3#-NtByHDP0PJ9n8V4yrXo:-NtByHDP0PJ9n8V4yrXp:bv6x3qn) ([raw file](https://github.com/starkware-libs/committer/blob/56a74f226a5086cbd66ce2cde8e2a75b5f08206c/crates/committer/src/lib.rs#L0)):*
ah... didn't notice the file locations...
the `committer` crate should be a lib crate.
1. restore this file
2. move `main.rs` into `crates/committer_cli/src/main.rs` (will need another Cargo.toml for this)

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/3)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @dorimedini-starkware)

___
*[`crates/committer/src/lib.rs` line  at r3](https://reviewable.io/reviews/starkware-libs/committer/3#-NtByHDP0PJ9n8V4yrXo:-NtF_RrW-0xkVfRoD9dB:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/56a74f226a5086cbd66ce2cde8e2a75b5f08206c/crates/committer/src/lib.rs#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah... didn't notice the file locations...
the `committer` crate should be a lib crate.
1. restore this file
2. move `main.rs` into `crates/committer_cli/src/main.rs` (will need another Cargo.toml for this)
</blockquote></details>

Done.

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/3)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @dorimedini-starkware)

___
*[`Cargo.lock` line 13 at r4](https://reviewable.io/reviews/starkware-libs/committer/3#-NtFavIG8lVzDo9Jg3iL:-NtFavIG8lVzDo9Jg3iM:bohgnv6) ([raw file](https://github.com/starkware-libs/committer/blob/166dcb8b6655b934b414b6697bc1a0d99af015f8/Cargo.lock#L13)):*
> ```TOML
> 
> [[package]]
> name = "committer_cli"
> ```

Does this make sense? It's like one package in the repo states in depends on another?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/3)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @TzahiTaub)

___
*[`crates/committer_cli/Cargo.toml` line 7 at r4](https://reviewable.io/reviews/starkware-libs/committer/3#-NtFrOgi9Sn96FKZr7OG:-NtFrOgi9Sn96FKZr7OH:b-kt4mys) ([raw file](https://github.com/starkware-libs/committer/blob/166dcb8b6655b934b414b6697bc1a0d99af015f8/crates/committer_cli/Cargo.toml#L7)):*
> ```TOML
> repository.workspace = true
> license-file.workspace = true
> description = "Cli for the committer package."
> ```

should this be all caps?



_Suggestion:_
```TOML
CLI
```
___
*[`crates/committer_cli/Cargo.toml` line 10 at r4](https://reviewable.io/reviews/starkware-libs/committer/3#-NtFrX9u4Wkd-t6KZepU:-NtFrX9u4Wkd-t6KZepV:b1fzrnr) ([raw file](https://github.com/starkware-libs/committer/blob/166dcb8b6655b934b414b6697bc1a0d99af015f8/crates/committer_cli/Cargo.toml#L10)):*
> ```TOML
> 
> [lints]
> workspace = true
> ```

you sure this is how we get both clippy and rust lints?



_Code quote:_
```TOML
[lints]
workspace = true
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/3)* status: all files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware and @TzahiTaub)

___
*[`crates/committer/BUILD` line 0 at r4](https://reviewable.io/reviews/starkware-libs/committer/3#-NtG4k6X2bG0aRoWlXGd:-NtG4k6X2bG0aRoWlXGe:b-7u8ez3) ([raw file](https://github.com/starkware-libs/committer/blob/166dcb8b6655b934b414b6697bc1a0d99af015f8/crates/committer/BUILD#L0)):*
delete this?

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/3)* status: all files reviewed, 3 unresolved discussions (waiting on @alon-dotan-starkware and @TzahiTaub)

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/3)* status: all files reviewed, 2 unresolved discussions (waiting on @alon-dotan-starkware and @dorimedini-starkware)

___
*[`crates/committer_cli/Cargo.toml` line 10 at r4](https://reviewable.io/reviews/starkware-libs/committer/3#-NtFrX9u4Wkd-t6KZepU:-NtIIuNK5sDsmPhGJD2g:b-tp4ftc) ([raw file](https://github.com/starkware-libs/committer/blob/166dcb8b6655b934b414b6697bc1a0d99af015f8/crates/committer_cli/Cargo.toml#L10)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

you sure this is how we get both clippy and rust lints?
</blockquote></details>

Yes, for rust/cargo 1.74 and above
___
*[`crates/committer/BUILD` line  at r4](https://reviewable.io/reviews/starkware-libs/committer/3#-NtG4k6X2bG0aRoWlXGd:-NtIIq3W8TpQ4WHRc8FB:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/166dcb8b6655b934b414b6697bc1a0d99af015f8/crates/committer/BUILD#L)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete this?
</blockquote></details>

Done.

**Review by alon-dotan-starkware — COMMENTED** [review]
> Reviewed 4 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/3)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`Cargo.lock` line 13 at r4](https://reviewable.io/reviews/starkware-libs/committer/3#-NtFavIG8lVzDo9Jg3iL:-NtKk4Wv99BvO7OfAFJU:b-fmd6gi) ([raw file](https://github.com/starkware-libs/committer/blob/166dcb8b6655b934b414b6697bc1a0d99af015f8/Cargo.lock#L13)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Does this make sense? It's like one package in the repo states in depends on another?
</blockquote></details>

Why do we need a different crate here?

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/3)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

___
*[`Cargo.lock` line 13 at r4](https://reviewable.io/reviews/starkware-libs/committer/3#-NtFavIG8lVzDo9Jg3iL:-NtKl3hS35mXMrI1bcYi:b-g2emxv) ([raw file](https://github.com/starkware-libs/committer/blob/166dcb8b6655b934b414b6697bc1a0d99af015f8/Cargo.lock#L13)):*
<details><summary><i>Previously, alon-dotan-starkware wrote…</i></summary><blockquote>

Why do we need a different crate here?
</blockquote></details>

@dorimedini-starkware ?

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/3#-:-NtKudwHBG1RvyuwevsJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alon-dotan-starkware and @TzahiTaub)

___
*[`Cargo.lock` line 13 at r4](https://reviewable.io/reviews/starkware-libs/committer/3#-NtFavIG8lVzDo9Jg3iL:-NtKuLOoBsjAFtOyrpG6:bolt0ca) ([raw file](https://github.com/starkware-libs/committer/blob/166dcb8b6655b934b414b6697bc1a0d99af015f8/Cargo.lock#L13)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

@dorimedini-starkware ?
</blockquote></details>

because this crate is an executable; we want to separate the business logic (library crate) from an executable that wraps it.
the lib crate will be published to crates.io, the executable (only used in our python backend) will not.

**Pull request merged**
