### PR TITLE
build: implementing updated skeleton forest

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/140)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/140)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_QsApE9AURIgg1Fwt:-Ny_QsApE9AURIgg1Fwu:b3ccjf0) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L41)):*
> ```XML
>         Self: std::marker::Sized;
> 
>     fn compute_updated_skeleton_forest<U: UpdatedSkeletonTree>(
> ```

this function should be defined as an associated function of UpdatedSkeletonForest, not as a method of OriginalSkeletonForest.
Please open a PR above this one that moves the code (so I can review the logic here, and only the code move later)



_Code quote:_
```XML
compute_updated_skeleton_forest
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_Q_ks-x8iWuPzXgar:-Ny_Q_ks-x8iWuPzXgas:b995z7l) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L49)):*
> ```XML
>         address_to_nonce: &HashMap<ContractAddress, Nonce>,
>         tree_heights: TreeHeight,
>     ) -> Result<UpdatedSkeletonForest<U>, UpdatedSkeletonTreeError>;
> ```

do we not have an `UpdatedSkeletonTreResult` type? maybe time to add it



_Code quote:_
```XML
Result<UpdatedSkeletonForest<U>, UpdatedSkeletonTreeError>
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_RvOS-TFcWtnff15m:-Ny_RvOS-TFcWtnff15n:bfdhzef) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L103)):*
> ```XML
> 
>     fn compute_updated_skeleton_forest<U: UpdatedSkeletonTree>(
>         mut self,
> ```

other than the `remove` (which should be changed to `get` IIUC), is there any reason this should be `mut`?



_Code quote:_
```XML
mut self
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_RF0_6QTHmaMGxfUh:-Ny_RF0_6QTHmaMGxfUi:bif2zwy) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L121)):*
> ```XML
>             let original_storage_trie = self
>                 .storage_tries
>                 .remove(address)
> ```

why `remove` and not `get`?



_Suggestion:_
```XML
.get(address)
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_SPZXAXTUJAeVekpR:-Ny_SPZXAXTUJAeVekpS:bx7oksy) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L144)):*
> ```XML
>             } else {
>                 SkeletonLeaf::NonZero
>             };
> ```

no reason to compute the answer as a boolean if you only want to convert it to a skeleton leaf



_Suggestion:_
```XML
            let skeleton_leaf = Self::updated_contract_skeleton_leaf(
                address_to_nonce.get(address),
                address_to_class_hash.get(address),
                current_leaf,
                storage_trie_becomes_empty,
            );
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_RVK-6iGVr88wLFg2:-Ny_RVK-6iGVr88wLFg3:b-4d0llm) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L246)):*
> ```XML
>     }
> 
>     fn will_address_become_empty(
> ```

add a docstring
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_RcvL2ft1-6a19Xef:-Ny_RcvL2ft1-6a19Xeg:b-1b18xo) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L259)):*
> ```XML
>         } else {
>             &previous_state.nonce
>         };
> ```

shorter



_Suggestion:_
```XML
        let actual_new_nonce = new_nonce.unwrap_or(&previous_state.nonce);
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 265 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_SdkMElkY-5Chwd4m:-Ny_SdkMElkY-5Chwd4n:b-1b18xo) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L265)):*
> ```XML
>         } else {
>             &previous_state.class_hash
>         };
> ```

shorter



_Suggestion:_
```XML
        let actual_new_class_hash = class_hash.unwrap_or(&previous_state.class_hash);
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 266 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_Subp9dvB2Cq6UINl:-Ny_Subp9dvB2Cq6UINm:b-jep5cr) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L266)):*
> ```XML
>             &previous_state.class_hash
>         };
>         actual_new_nonce.0 == Felt::ZERO && actual_new_class_hash.0 == Felt::ZERO
> ```

easier to read like this (since we know a contract leaf has 3 elements, nice to see all 3 checked)



_Suggestion:_
```XML
        let actual_new_nonce = if let Some(nonce) = new_nonce {
            nonce
        } else {
            &previous_state.nonce
        };

        let actual_new_class_hash = if let Some(class_hash) = new_class_hash {
            class_hash
        } else {
            &previous_state.class_hash
        };
        storage_becomes_empty && actual_new_nonce.0 == Felt::ZERO && actual_new_class_hash.0 == Felt::ZERO
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/140)* status: all files reviewed, 9 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_QsApE9AURIgg1Fwt:-Ny_VaqD4IxLKkKUJNTo:b-d7bhn0) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L41)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this function should be defined as an associated function of UpdatedSkeletonForest, not as a method of OriginalSkeletonForest.
Please open a PR above this one that moves the code (so I can review the logic here, and only the code move later)
</blockquote></details>

will do
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_Q_ks-x8iWuPzXgar:-Ny_Vcih2E0xMV60v-bS:bm7sr46) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L49)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

do we not have an `UpdatedSkeletonTreResult` type? maybe time to add it
</blockquote></details>

will do (in another PR on top of this one)
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_RvOS-TFcWtnff15m:-Ny_U5dU1FU63ZJSCacQ:b-n6bq3e) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L103)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

other than the `remove` (which should be changed to `get` IIUC), is there any reason this should be `mut`?
</blockquote></details>

there is no reason other than that.
the problem with `get` is that is returns a reference. and `UpdatedSkeletonTree::create` expects `impl OriginalSkeletonTree` (without a reference).
question is- keep it that way or change the trait to take `impl OriginalSkeletonTree` ?
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_RF0_6QTHmaMGxfUh:-Ny_VGmO7ljh7nQKXcef:b-d14jo3) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L121)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why `remove` and not `get`?
</blockquote></details>

please look above
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 144 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_SPZXAXTUJAeVekpR:-Ny_WcjjCP5U30ZXDaqw:bok0w5t) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L144)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no reason to compute the answer as a boolean if you only want to convert it to a skeleton leaf
</blockquote></details>

done, changed the return value to `SkeletonLeaf`
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 246 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_RVK-6iGVr88wLFg2:-Ny_XgN65pDn9aZSI5VB:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L246)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add a docstring
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 259 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_RcvL2ft1-6a19Xef:-Ny_VULY6_gMwZfgXTLt:b-7m74ox) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L259)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shorter
</blockquote></details>

nice!
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 265 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_SdkMElkY-5Chwd4m:-Ny_Wk5q3SJrVHd93Uk1:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L265)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

shorter
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 266 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_Subp9dvB2Cq6UINl:-Ny_WjMy74uRFvdbPIY3:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L266)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

easier to read like this (since we know a contract leaf has 3 elements, nice to see all 3 checked)
</blockquote></details>

Done.

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/140)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 49 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_Q_ks-x8iWuPzXgar:-Ny_awa69F2xFwYjueH5:buobp09) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L49)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

will do (in another PR on top of this one)
</blockquote></details>

PR [link](https://github.com/starkware-libs/committer/pull/141)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/140)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_RvOS-TFcWtnff15m:-Ny_drzn3QDuX4ThYFeV:bevn24n) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L103)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

there is no reason other than that.
the problem with `get` is that is returns a reference. and `UpdatedSkeletonTree::create` expects `impl OriginalSkeletonTree` (without a reference).
question is- keep it that way or change the trait to take `impl OriginalSkeletonTree` ?
</blockquote></details>

I would change the trait to accept `&impl OriginalSkeletonTree`
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_RF0_6QTHmaMGxfUh:-Ny_e7tt4DQVbLAXAjsl:bliifd9) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L121)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

please look above
</blockquote></details>

ansered
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 240 at r2](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_e-xwBN5Ul3kYZDP_:-Ny_e-xwBN5Ul3kYZDPa:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/8c3b385b1521f06eebe37896a9bde86e245c7762/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L240)):*
> ```XML
>     }
> 
>     /// Given the previous contract state, whether the contract has become empty or not, optional
> ```





_Suggestion:_
```XML
contract storage has
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/140)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 103 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_RvOS-TFcWtnff15m:-NynIl5o2zgJWsNcIu5F:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L103)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I would change the trait to accept `&impl OriginalSkeletonTree`
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 121 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_RF0_6QTHmaMGxfUh:-NynIlSO1-rUJtp0mGJy:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L121)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ansered
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 240 at r2](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_e-xwBN5Ul3kYZDP_:-NynHfCr4WpIdAks_rrq:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/8c3b385b1521f06eebe37896a9bde86e245c7762/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L240)):*
> ```XML
>     }
> 
>     /// Given the previous contract state, whether the contract has become empty or not, optional
> ```

Done.

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/140)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs` line 41 at r1](https://reviewable.io/reviews/starkware-libs/committer/140#-Ny_QsApE9AURIgg1Fwt:-NynjVfD8-c9PyX9xqJ1:buobp14) ([raw file](https://github.com/starkware-libs/committer/blob/8f4428382fd3e53e0eea3e92675b1f2f8f411a91/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs#L41)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

will do
</blockquote></details>

PR [link](https://github.com/starkware-libs/committer/pull/142)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/140)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/140#-:-Nynn6YuD60b_Yvm94sw:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

**Pull request merged**
