### PR TITLE
test: get bottom subtree

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234)

### CODE REVIEW

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 205 at r1](https://reviewable.io/reviews/starkware-libs/committer/234#-O-kPyYj3nWzxB6ws1KI:-O-ky1A93x4xr2VWx9My:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/19dd1016d18ca7d14f2845a347f121a4426cc56a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L205)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

the draw is misleading, IMO.
The root is not a binary node as the draw suggests
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 213 at r1](https://reviewable.io/reviews/starkware-libs/committer/234#-O-kQJDdAYTx1O-g8HVW:-O-kyBwB2LBFVSY3X_4p:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/19dd1016d18ca7d14f2845a347f121a4426cc56a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L213)):*
> ```XML
> ///     1
> ///    / \
> ///   2   *
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 226 at r1](https://reviewable.io/reviews/starkware-libs/committer/234#-O-kQOOpD_rA4ZXA9bm1:-O-kyF9E28JpN-IcIOID:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/19dd1016d18ca7d14f2845a347f121a4426cc56a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L226)):*
> ```XML
> ///   4
> ///  /  \
> /// 8   9
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 243 at r1](https://reviewable.io/reviews/starkware-libs/committer/234#-O-kQUCUDCxn632IsRW8:-O-kyJQt3JWgh6ACEaVq:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/19dd1016d18ca7d14f2845a347f121a4426cc56a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L243)):*
> ```XML
> ///         /
> ///
> /// NodeIndex::FIRST_LEAF
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 258 at r1](https://reviewable.io/reviews/starkware-libs/committer/234#-O-kQWen9kjmCDiqs56q:-O-kyMpxA-ImCoNIaORp:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/19dd1016d18ca7d14f2845a347f121a4426cc56a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L258)):*
> ```XML
> ///
> ///                    \
> ///                    NodeIndex::MAX
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 270 at r1](https://reviewable.io/reviews/starkware-libs/committer/234#-O-kQodp0RbtgCP9yS5R:-O-kz2nd8DTxl2mVrzvG:b1cu6vs) ([raw file](https://github.com/starkware-libs/committer/blob/19dd1016d18ca7d14f2845a347f121a4426cc56a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L270)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

please add a less trivial test case when some of the indices are deleted.
</blockquote></details>

What do you mean by indices are deleted?
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 365 at r1](https://reviewable.io/reviews/starkware-libs/committer/234#-O-kP4bY4RODJaCOBuIU:-O-kyvWk5a26WjM-OR7n:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/19dd1016d18ca7d14f2845a347f121a4426cc56a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L365)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

and add `#[derive(Debug, Eq)]` for `SubTree`
</blockquote></details>

Done.

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 270 at r1](https://reviewable.io/reviews/starkware-libs/committer/234#-O-kQodp0RbtgCP9yS5R:-O-oQrNq3Z8wGBn8TMqR:b-ikr8k3) ([raw file](https://github.com/starkware-libs/committer/blob/19dd1016d18ca7d14f2845a347f121a4426cc56a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L270)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

What do you mean by indices are deleted?
</blockquote></details>

Like the last case you wrote.
Where the bottom subtree's indices is a subset but not equal to the parent's indices.

For example this is the tree before:
                           1
                          /
                         *
                          \
                            *
                              \
                                23
                               /    \
                              46   47
if the root's indices are [35,38,45,46,55]

make sure that the bottom subtree's indices is [46]

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 279 at r2](https://reviewable.io/reviews/starkware-libs/committer/234#-O-obYy7AeRNE2R8QmqG:-O-obYy7AeRNE2R8QmqH:bite71n) ([raw file](https://github.com/starkware-libs/committer/blob/f0ddd25643133984cb5aaccf4b0563745177443a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L279)):*
> ```XML
>         PathToBottom::new(EdgePath(U256::ONE), EdgePathLength::new(1).unwrap()).unwrap(),
>         SubTree {
>             sorted_leaf_indices: &[small_tree_index_to_full(U256::from(3_u128), SubTreeHeight(1))],
> ```

if the root has subtree height 1
and the path is of length 1
shouldn't the bottom subtree have height 0? i see height 1 in the expected output...
or is subtree height only relevant for "the actual height of the full tree we are testing"?
if this is the case, please pass this subtree height (which is constant in the test case!) as a separate parameter and construct all the objects with it in the test body (see my comment below, the two comments go together well...)



_Code quote:_
```XML
        small_tree_index_to_full(U256::ONE,SubTreeHeight(1)),
        &[
            small_tree_index_to_full(U256::from(3_u128), SubTreeHeight(1))
        ],
        PathToBottom::new(EdgePath(U256::ONE), EdgePathLength::new(1).unwrap()).unwrap(),
        SubTree {
            sorted_leaf_indices: &[small_tree_index_to_full(U256::from(3_u128), SubTreeHeight(1))],
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 282 at r2](https://reviewable.io/reviews/starkware-libs/committer/234#-O-oafaP0aHhh9p7iQC6:-O-oafaP0aHhh9p7iQC7:b-hh8lad) ([raw file](https://github.com/starkware-libs/committer/blob/f0ddd25643133984cb5aaccf4b0563745177443a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L282)):*
> ```XML
>             root_index: small_tree_index_to_full(U256::from(3_u128), SubTreeHeight(1)),
>             root_hash: HashOutput(Felt::TWO),
>         },
> ```

try to do as much data manipulation as you can in the test body, so it's easier to read (and add) test cases.
To understand what the values in the test cases mean you need to read the test function signature anyway, so I think just numbers in the test case is easier.
non-blocking; it's also a question of style



_Suggestion:_
```XML
        1,
        &[(3, 1)],
        (1, 1),
        &[(3, 1)],
        (3, 1),
        2,
```

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 270 at r1](https://reviewable.io/reviews/starkware-libs/committer/234#-O-kQodp0RbtgCP9yS5R:-O03KTE2Crxtbej3WJyE:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/19dd1016d18ca7d14f2845a347f121a4426cc56a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L270)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Like the last case you wrote.
Where the bottom subtree's indices is a subset but not equal to the parent's indices.

For example this is the tree before:
                           1
                          /
                         *
                          \
                            *
                              \
                                23
                               /    \
                              46   47
if the root's indices are [35,38,45,46,55]

make sure that the bottom subtree's indices is [46]
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 279 at r2](https://reviewable.io/reviews/starkware-libs/committer/234#-O-obYy7AeRNE2R8QmqG:-O03CqQKA_1W6MKGzZ2Z:b-y7satj) ([raw file](https://github.com/starkware-libs/committer/blob/f0ddd25643133984cb5aaccf4b0563745177443a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L279)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if the root has subtree height 1
and the path is of length 1
shouldn't the bottom subtree have height 0? i see height 1 in the expected output...
or is subtree height only relevant for "the actual height of the full tree we are testing"?
if this is the case, please pass this subtree height (which is constant in the test case!) as a separate parameter and construct all the objects with it in the test body (see my comment below, the two comments go together well...)
</blockquote></details>

The bottom height is actually 0. I use the height of the input tree to compute the node indices based on the input tree structure.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 282 at r2](https://reviewable.io/reviews/starkware-libs/committer/234#-O-oafaP0aHhh9p7iQC6:-O03Cl6-AIklium75jzW:b-ucfknh) ([raw file](https://github.com/starkware-libs/committer/blob/f0ddd25643133984cb5aaccf4b0563745177443a/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L282)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

try to do as much data manipulation as you can in the test body, so it's easier to read (and add) test cases.
To understand what the values in the test cases mean you need to read the test function signature anyway, so I think just numbers in the test case is easier.
non-blocking; it's also a question of style
</blockquote></details>

Thanks!

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 343 at r3](https://reviewable.io/reviews/starkware-libs/committer/234#-O03McCl3KhHxZSUnVos:-O03McCl3KhHxZSUnVot:b45h) ([raw file](https://github.com/starkware-libs/committer/blob/17d51a910c56f365c9175fca2a771b64e7b78121/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L343)):*
> ```XML
> )]
> fn test_get_bottom_subtree(
>     #[case] height: u8,
> ```





_Suggestion:_
```XML
#[case] height: SubTreeHeight,
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 354 at r3](https://reviewable.io/reviews/starkware-libs/committer/234#-O03MyrY8adLmh4IKvKm:-O03MyrY8adLmh4IKvKn:bpd1ccg) ([raw file](https://github.com/starkware-libs/committer/blob/17d51a910c56f365c9175fca2a771b64e7b78121/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L354)):*
> ```XML
>     } else {
>         small_tree_index_to_full(U256::ONE, SubTreeHeight::new(height))
>     };
> ```

is that needed?
won't `small_tree_index_to_full(x, 251)` return x?



_Code quote:_
```XML
    let root_index = if height == SubTreeHeight::ACTUAL_HEIGHT.0 {
        NodeIndex::ROOT
    } else {
        small_tree_index_to_full(U256::ONE, SubTreeHeight::new(height))
    };
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 361 at r3](https://reviewable.io/reviews/starkware-libs/committer/234#-O03Mm3AEU53SnefluwE:-O03Mm3AEU53SnefluwF:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/17d51a910c56f365c9175fca2a771b64e7b78121/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L361)):*
> ```XML
>         .collect::<Vec<_>>();
> 
>     // Crate the input Subtree.
> ```

typo



_Suggestion:_
```XML
// Create
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234)* status: all files reviewed, 6 unresolved discussions (waiting on @AvivYossef-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 297 at r3](https://reviewable.io/reviews/starkware-libs/committer/234#-O03S1FgE4F2a_YIX6TY:-O03S1FgE4F2a_YIX6TZ:b-j62fez) ([raw file](https://github.com/starkware-libs/committer/blob/17d51a910c56f365c9175fca2a771b64e7b78121/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L297)):*
> ```XML
>         PathToBottom::new(EdgePath(U256::ONE), EdgePathLength::new(1).unwrap()).unwrap(),
>         &[U256::from(3_u128)],
>         small_tree_index_to_full(U256::from(3_u128), SubTreeHeight::new(1)),
> ```

this parameter also depends on the subtree height of the current case, correct? as such please only pass `3` and call `small_tree_index_to_full` in the function body; the subtree height for the current case should only appear once



_Suggestion:_
```XML
3
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 330 at r3](https://reviewable.io/reviews/starkware-libs/committer/234#-O03SZ6IDB4I1QMynWh2:-O03SZ6IDB4I1QMynWh3:bluxg7a) ([raw file](https://github.com/starkware-libs/committer/blob/17d51a910c56f365c9175fca2a771b64e7b78121/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L330)):*
> ```XML
>     1,
>     &[U256::from(2_u128),
>     U256::from(3_u128)],
> ```

keep in mind that auto-formatting, or formatting checks, doesn't work inside macros. Needs to be done manually



_Suggestion:_
```XML
    &[U256::from(2_u128), U256::from(3_u128)],
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 343 at r3](https://reviewable.io/reviews/starkware-libs/committer/234#-O03McCl3KhHxZSUnVos:-O03RqnR8itZ8wcJFPc5:b36b9wr) ([raw file](https://github.com/starkware-libs/committer/blob/17d51a910c56f365c9175fca2a771b64e7b78121/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L343)):*
> ```XML
> )]
> fn test_get_bottom_subtree(
>     #[case] height: u8,
> ```

If it reduces boilerplate / lines I prefer `u8`, otherwise each case will need to include the `SubTreeHeight` wrapper or an `into()` call

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 297 at r3](https://reviewable.io/reviews/starkware-libs/committer/234#-O03S1FgE4F2a_YIX6TY:-O03WofF8pHKb4peER9u:b-oozqno) ([raw file](https://github.com/starkware-libs/committer/blob/17d51a910c56f365c9175fca2a771b64e7b78121/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L297)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this parameter also depends on the subtree height of the current case, correct? as such please only pass `3` and call `small_tree_index_to_full` in the function body; the subtree height for the current case should only appear once
</blockquote></details>

But in other cases, I don't use this function.
For example, here I can't use it, since the index of leaf > 2^128



_Code snippet:_
```XML
#[case::long_left_path(
    SubTreeHeight::ACTUAL_HEIGHT.0,
    &[NodeIndex::FIRST_LEAF.0],
    PathToBottom::new(EdgePath(U256::ZERO), EdgePathLength::new(SubTreeHeight::ACTUAL_HEIGHT.0).unwrap()).unwrap(),
    &[NodeIndex::FIRST_LEAF.0],
    NodeIndex::FIRST_LEAF,
)]
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 330 at r3](https://reviewable.io/reviews/starkware-libs/committer/234#-O03SZ6IDB4I1QMynWh2:-O03YIu9CISeSTg0slGw:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/17d51a910c56f365c9175fca2a771b64e7b78121/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L330)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

keep in mind that auto-formatting, or formatting checks, doesn't work inside macros. Needs to be done manually
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 343 at r3](https://reviewable.io/reviews/starkware-libs/committer/234#-O03McCl3KhHxZSUnVos:-O03YEEW7zdePmh7wFUj:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/17d51a910c56f365c9175fca2a771b64e7b78121/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L343)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

If it reduces boilerplate / lines I prefer `u8`, otherwise each case will need to include the `SubTreeHeight` wrapper or an `into()` call
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 354 at r3](https://reviewable.io/reviews/starkware-libs/committer/234#-O03MyrY8adLmh4IKvKm:-O03XWuX8A0qQunUqAG1:b-t3czkm) ([raw file](https://github.com/starkware-libs/committer/blob/17d51a910c56f365c9175fca2a771b64e7b78121/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L354)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

is that needed?
won't `small_tree_index_to_full(x, 251)` return x?
</blockquote></details>

Not needed, thanks.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 297 at r3](https://reviewable.io/reviews/starkware-libs/committer/234#-O03S1FgE4F2a_YIX6TY:-O03ew1y5Y6AVTmvX2m7:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/17d51a910c56f365c9175fca2a771b64e7b78121/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L297)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

But in other cases, I don't use this function.
For example, here I can't use it, since the index of leaf > 2^128
</blockquote></details>

Done

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234)* status: all files reviewed, 4 unresolved discussions (waiting on @AvivYossef-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 330 at r3](https://reviewable.io/reviews/starkware-libs/committer/234#-O03SZ6IDB4I1QMynWh2:-O047JkkC-SLgtdYWuzH:b-irwhab) ([raw file](https://github.com/starkware-libs/committer/blob/17d51a910c56f365c9175fca2a771b64e7b78121/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L330)):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

where?

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs` line 330 at r3](https://reviewable.io/reviews/starkware-libs/committer/234#-O03SZ6IDB4I1QMynWh2:-O049KdV6jC7RFA1n9Wz:bzbo1xk) ([raw file](https://github.com/starkware-libs/committer/blob/17d51a910c56f365c9175fca2a771b64e7b78121/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs#L330)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

where?
</blockquote></details>

Sorry

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234#-:-O04L_X4575ozm3Yrgei:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234#-:-O04YwDS2RQ5LQFI0wtj:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/234)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

**Pull request merged**
