### PR TITLE
fix: changes to api

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/44)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware 
@nimrod-starkware any more changes you need?

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/44#-:-NvaWU6e4Ub2eEAvddjJ:b-vlm87g)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/committer/44#-NvaVqRNBbAX1Zz95ghr:-NvaVqRNBbAX1Zz95ghs:bm7t6k) ([raw file](https://github.com/starkware-libs/committer/blob/53728b1d3f3dfef2a57df23f0d90b99cb7900ab8/crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs#L22)):*
> ```XML
>         root_hash: HashOutput,
>         tree_height: TreeHeight,
>     ) -> OriginalSkeletonTreeResult<impl OriginalSkeletonTree<L>>;
> ```

Rust requires a box when returning Self, but this way it doesn't



_Code quote:_
```XML
) -> OriginalSkeletonTreeResult<impl OriginalSkeletonTree<L>>;
```

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/44)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/committer/44#-NvaiIgjBSLaQuBMuGYW:-NvaiIgjBSLaQuBMuGYX:b-p4iy5y) ([raw file](https://github.com/starkware-libs/committer/blob/53728b1d3f3dfef2a57df23f0d90b99cb7900ab8/crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs#L18)):*
> ```XML
> pub(crate) trait OriginalSkeletonTree<L: LeafDataTrait> {
>     fn compute_original_skeleton_tree(
>         storage: &mut impl Storage,
> ```

must this be mutable...?



_Code quote:_
```XML
storage: &mut impl Storage
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs` line 22 at r2](https://reviewable.io/reviews/starkware-libs/committer/44#-NvaVqRNBbAX1Zz95ghr:-NvaiMkU7JFnJRIdGRsZ:b-7m74ox) ([raw file](https://github.com/starkware-libs/committer/blob/53728b1d3f3dfef2a57df23f0d90b99cb7900ab8/crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs#L22)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

Rust requires a box when returning Self, but this way it doesn't
</blockquote></details>

nice!

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/44)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs` line 18 at r2](https://reviewable.io/reviews/starkware-libs/committer/44#-NvaiIgjBSLaQuBMuGYW:-NvalTonEhuWtSD50IPc:b1r3p67) ([raw file](https://github.com/starkware-libs/committer/blob/53728b1d3f3dfef2a57df23f0d90b99cb7900ab8/crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

must this be mutable...?
</blockquote></details>

It doesn't, thanks

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/44#-:-NvamOpP8Xwq-D0zYlDP:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
