### PR TITLE
refactor: remove tree_height parameter from split leaves

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/183)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/183)* status: all files reviewed, 5 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/committer/183#-NzSYPkjB2ImUjgFnH01:-NzSYPkjB2ImUjgFnH02:b-7ppheu) ([raw file](https://github.com/starkware-libs/committer/blob/df5487e280ee4965c429014f6b2e13dfeceab4bf/crates/committer/src/patricia_merkle_tree/test_utils.rs#L55)):*
> ```XML
> pub(crate) fn small_tree_index_to_full(index: U256, height: TreeHeight) -> NodeIndex {
>     NodeIndex::from_subtree_index(NodeIndex::new(index), height)
> }
> ```

why do you need `cfg(test)` on these three?
this entire module is already gated behind `cfg(any(feature = "testing", test))`



_Code quote:_
```XML
#[cfg(test)]
use crate::patricia_merkle_tree::types::{NodeIndex, TreeHeight};

#[cfg(test)]
impl NodeIndex {
    /// Assumes self represents an index in a smaller tree height. Returns a node index represents
    /// the same index in the starknet state tree as if the smaller tree was 'planted' at the lowest
    /// leftmost node from the root.
    pub(crate) fn from_subtree_index(subtree_index: Self, subtree_height: TreeHeight) -> Self {
        let height_diff = TreeHeight::MAX.0 - subtree_height.0;
        let offset = (NodeIndex::ROOT << height_diff) - 1.into();
        subtree_index + (offset << (subtree_index.bit_length() - 1))
    }
}

#[cfg(test)]
pub(crate) fn small_tree_index_to_full(index: U256, height: TreeHeight) -> NodeIndex {
    NodeIndex::from_subtree_index(NodeIndex::new(index), height)
}
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/committer/183#-NzSYmjM03X6V9NXnsc-:-NzSYmjM03X6V9NXnsc0:b-pmnwaw) ([raw file](https://github.com/starkware-libs/committer/blob/df5487e280ee4965c429014f6b2e13dfeceab4bf/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs#L48)):*
> ```XML
> )]
> fn test_split_leaves(
>     #[case] tree_height: u8,
> ```

so it's clear what's going on



_Suggestion:_
```XML
subtree_height
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/committer/183#-NzSZ1Yq0AyVcggzKCL6:-NzSZ1Yq0AyVcggzKCL7:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/df5487e280ee4965c429014f6b2e13dfeceab4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L71)):*
> ```XML
>     false)]
> fn test_has_leaves_on_both_sides(
>     #[case] tree_height: u8,
> ```





_Suggestion:_
```XML
subtree_height
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/committer/183#-NzSZNlZ1n5jo0dqqiWu:-NzSZNlZ1n5jo0dqqiWv:b-k3inov) ([raw file](https://github.com/starkware-libs/committer/blob/df5487e280ee4965c429014f6b2e13dfeceab4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L81)):*
> ```XML
>         .iter()
>         .map(|idx| NodeIndex::from_subtree_index(*idx, height))
>         .collect();
> ```

these two conversions are duplicated 3 times in this PR;
can you consolidate the logic into a fixture / function and use `#[with]` to get the converted values in the test?



_Code quote:_
```XML
    let root_index = small_tree_index_to_full(root_index.into(), height);
    let full_tree_leaf_indices: Vec<NodeIndex> = leaf_indices
        .iter()
        .map(|idx| NodeIndex::from_subtree_index(*idx, height))
        .collect();
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/committer/183#-NzSZ4cb47I6PlPv7awh:-NzSZ4cb47I6PlPv7awi:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/df5487e280ee4965c429014f6b2e13dfeceab4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L93)):*
> ```XML
> #[should_panic(expected = "is not a descendant of the root")]
> fn test_has_leaves_on_both_sides_assertions(
>     #[case] tree_height: u8,
> ```





_Suggestion:_
```XML
subtree_height
```

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/183)* status: all files reviewed, 5 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/committer/183#-NzSYPkjB2ImUjgFnH01:-NzT713KACLY6eFgGTwh:b-cqb8hl) ([raw file](https://github.com/starkware-libs/committer/blob/df5487e280ee4965c429014f6b2e13dfeceab4bf/crates/committer/src/patricia_merkle_tree/test_utils.rs#L55)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why do you need `cfg(test)` on these three?
this entire module is already gated behind `cfg(any(feature = "testing", test))`
</blockquote></details>

I've put it - because we get unused lint errors (IIRC) because it's used in "tests" but also compiled (without these attrs) in "testing"

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/183)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/test_utils.rs` line 55 at r2](https://reviewable.io/reviews/starkware-libs/committer/183#-NzSYPkjB2ImUjgFnH01:-NzTJO7n1A2mVzR4-kh9:b-4yljm3) ([raw file](https://github.com/starkware-libs/committer/blob/df5487e280ee4965c429014f6b2e13dfeceab4bf/crates/committer/src/patricia_merkle_tree/test_utils.rs#L55)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

I've put it - because we get unused lint errors (IIRC) because it's used in "tests" but also compiled (without these attrs) in "testing"
</blockquote></details>

we need to organize this better... [opened a task](https://starkware.monday.com/boards/6234683038/pulses/6756380785) for this

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/183#-:-NzX0RopCOq6UL6AUo36:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/183)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/committer/183#-NzSYmjM03X6V9NXnsc-:-NzTPbEG-LM9GDa2Dfhs:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/df5487e280ee4965c429014f6b2e13dfeceab4bf/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

so it's clear what's going on
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 71 at r2](https://reviewable.io/reviews/starkware-libs/committer/183#-NzSZ1Yq0AyVcggzKCL6:-NzTPgHOAcb8S4M-qC5D:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/df5487e280ee4965c429014f6b2e13dfeceab4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L71)):*
> ```XML
>     false)]
> fn test_has_leaves_on_both_sides(
>     #[case] tree_height: u8,
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 81 at r2](https://reviewable.io/reviews/starkware-libs/committer/183#-NzSZNlZ1n5jo0dqqiWu:-NzWwq8z8XX9fEZaMiiS:bs7wumb) ([raw file](https://github.com/starkware-libs/committer/blob/df5487e280ee4965c429014f6b2e13dfeceab4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L81)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

these two conversions are duplicated 3 times in this PR;
can you consolidate the logic into a fixture / function and use `#[with]` to get the converted values in the test?
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs` line 93 at r2](https://reviewable.io/reviews/starkware-libs/committer/183#-NzSZ4cb47I6PlPv7awh:-NzTPr_48TCTA73ohfeX:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/df5487e280ee4965c429014f6b2e13dfeceab4bf/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs#L93)):*
> ```XML
> #[should_panic(expected = "is not a descendant of the root")]
> fn test_has_leaves_on_both_sides_assertions(
>     #[case] tree_height: u8,
> ```

Done.

**Pull request merged**
