### PR TITLE
fix: original skeleton forest test fix

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/154)

### CODE REVIEW

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/154)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/committer/154#-NyvjECS-0Ee9msC72Ip:-NyvjECS-0Ee9msC72Iq:b-4ii08e) ([raw file](https://github.com/starkware-libs/committer/blob/093b3ab4c5b075db0d0e3b75cedf40bc2dbce830/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L62)):*
> ```XML
> ///               *         B                       B    ES
> ///              /         /  \                    / \    \
> ///             152       NZ   54                 NZ  47   NZ
> ```

UnmodifiedBottom



_Suggestion:_
```XML
UB
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/154)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 62 at r1](https://reviewable.io/reviews/starkware-libs/committer/154#-NyvjECS-0Ee9msC72Ip:-NyxsEN4ATaTdMS6jO0S:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/093b3ab4c5b075db0d0e3b75cedf40bc2dbce830/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L62)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

UnmodifiedBottom
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/154)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

**Comment by TzahiTaub** [comment]
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 60 at r3](https://reviewable.io/reviews/starkware-libs/committer/154#-Nyy7mSdDv9LJZ8xWW6r:-Nyy7mSdDv9LJZ8xWW6s:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/fdb8d3e6de608241b0f336abc0cf7c730674ebad/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L60)):*
> ```XML
> ///                 E     E                            B
> ///                /       \                         /   \
> ///               *         B                       B    ES
> ```





_Suggestion:_
```XML
E
```

**Pull request merged**
