### PR TITLE
chore: add benchmarking to ci

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/251)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/251)* status: all files reviewed, 10 unresolved discussions (waiting on @aner-starkware and @yoavGrs)

___
*[`.github/workflows/ci.yml` line 96 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0Jtp4nEHK-KDEiDZWV:-O0Jtp4nEHK-KDEiDZWW:bplkz85) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L96)):*
> ```YAML
>       - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
>         run: cargo build
>       - run: cargo test
> ```

I think this change should be reverted.
Caching is for *dependencies* only IIUC; so if you get a cache hit, you still want to run cargo test, because maybe the local code has changed (and not dependencies).
Also, `cargo build` is redundant when you later run `cargo test` - the latter will trigger a build anyway



_Code quote:_
```YAML
      - uses: Swatinem/rust-cache@v2
        id: "cache-cargo"
      - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        run: cargo build
      - run: cargo test
```
___
*[`.github/workflows/ci.yml` line 115 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JuJKN0jnPnDLtn4uS:-O0JuJKN0jnPnDLtn4uT:byqfzwv) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L115)):*
> ```YAML
>       - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
>         run: cargo build --release
>       - run: cargo test --release -- --include-ignored test_benchmark
> ```

revert this change for the same reasons as above



_Code quote:_
```YAML
      - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        run: cargo build --release
      - run: cargo test --release -- --include-ignored test_benchmark
```
___
*[`.github/workflows/ci.yml` line 117 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JuzcLByVb7kYSnzon:-O0JuzcM3BKRwEqkXMHb:b-jodtrj) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L117)):*
> ```YAML
>       - run: cargo test --release -- --include-ignored test_benchmark
> 
>   post-benchmarking:
> ```

please add `name`s to the different phases here, or at least `#` comments, so it's a bit clearer what is going on
___
*[`.github/workflows/ci.yml` line 127 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JuVj82bKT_B5iIe7y:-O0JuVj82bKT_B5iIe7z:b-mc01fe) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L127)):*
> ```YAML
>         id: "cache-cargo"
>       - if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
>         run: cargo build --release
> ```

delete this block
1. don't skip build on cache hit (see above)
2. you will trigger the build anyway when you run cargo bench below
___
*[`.github/workflows/ci.yml` line 136 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JuePaBPh2vvNR8B05:-O0JuePaBPh2vvNR8B06:b-24uy09) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L136)):*
> ```YAML
>       - run: gcloud storage cp gs://committer-products-external/tree_flow_inputs.json ./crates/committer_cli/benches/tree_flow_inputs.json
>       - run: gcloud storage cp gs://committer-products-external/committer_flow_inputs.json ./crates/committer_cli/benches/committer_flow_inputs.json
>       - run: cargo bench
> ```

don't you need the release flag here?



_Suggestion:_
```YAML
cargo bench --release
```
___
*[`.github/workflows/ci.yml` line 139 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JujNx6Jq9FXUYBInQ:-O0JujNx6Jq9FXUYBInR:b-hq6e3r) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L139)):*
> ```YAML
> 
>       - run: mv ./crates/committer_cli/benches/tree_flow_inputs.json ./crates/committer_cli/benches/tree_flow_inputs.json_bu
>       - run: mv ./crates/committer_cli/benches/committer_flow_inputs.json ./crates/committer_cli/benches/committer_flow_inputs.json_bu
> ```

`bu` is "backup"?



_Code quote:_
```YAML
      - run: mv ./crates/committer_cli/benches/tree_flow_inputs.json ./crates/committer_cli/benches/tree_flow_inputs.json_bu
      - run: mv ./crates/committer_cli/benches/committer_flow_inputs.json ./crates/committer_cli/benches/committer_flow_inputs.json_bu
```
___
*[`.github/workflows/ci.yml` line 147 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JupqVCrrbATGBwomo:-O0JupqVCrrbATGBwomp:byr4ffv) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L147)):*
> ```YAML
>       - run: mv ./crates/committer_cli/benches/committer_flow_inputs.json_bu ./crates/committer_cli/benches/committer_flow_inputs.json
> 
>       - run: cargo bench > bench_new.txt
> ```

see above



_Suggestion:_
```YAML
cargo bench --release
```
___
*[`.github/workflows/ci.yml` line 150 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0Jv7RB2KX5TCGYuQ5K:-O0Jv7RB2KX5TCGYuQ5L:b-uv7i6k) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L150)):*
> ```YAML
>       - run: sed -i '/tree_computation_flow/,$!d' bench_new.txt
>       - run: echo BENCHES_RESULT=$(cat bench_new.txt) >> $GITHUB_ENV
>       
> ```

remove whitespace



_Code quote:_
```YAML
···
```
___
*[`.github/workflows/ci.yml` line 165 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0Jv9C-7sE-z1HH0Ec2:-O0Jv9C-7sE-z1HH0Ec3:b-uv7i6k) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L165)):*
> ```YAML
>               path: 'Commits'
>             })
>       
> ```

remove whitespace
___
*[`crates/committer_cli/benches/committer_bench.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JvBKY51bKQBov1zXL:-O0JvBKY51bKQBov1zXM:b354p86) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/crates/committer_cli/benches/committer_bench.rs#L48)):*
> ```XML
>             ));
>             //TODO(Aner, 26/06/2024)!: remove this sleep after fixing the benchmark test!
>             sleep(Duration::from_millis(10));
> ```

what's this?



_Code quote:_
```XML
            //TODO(Aner, 26/06/2024)!: remove this sleep after fixing the benchmark test!
            sleep(Duration::from_millis(10));
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/251)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`.github/workflows/ci.yml` line 96 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0Jtp4nEHK-KDEiDZWV:-O0L-ozdB86uo268bmQJ:b27yb12) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L96)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I think this change should be reverted.
Caching is for *dependencies* only IIUC; so if you get a cache hit, you still want to run cargo test, because maybe the local code has changed (and not dependencies).
Also, `cargo build` is redundant when you later run `cargo test` - the latter will trigger a build anyway
</blockquote></details>

I think maybe we should rediscuss this - there is a downside to this approach.
___
*[`.github/workflows/ci.yml` line 115 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JuJKN0jnPnDLtn4uS:-O0L6E7zBt88a6ujSymz:bzd6zrr) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L115)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

revert this change for the same reasons as above
</blockquote></details>

Done. See above.
___
*[`.github/workflows/ci.yml` line 117 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JuzcLByVb7kYSnzon:-O0L6GZ988JeQ5YPbYJg:b3nj56r) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L117)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

please add `name`s to the different phases here, or at least `#` comments, so it's a bit clearer what is going on
</blockquote></details>

Added comments, is it enough?
___
*[`.github/workflows/ci.yml` line 127 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JuVj82bKT_B5iIe7y:-O0L6K4r9YbQ-urHq64l:br8ygwm) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L127)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

delete this block
1. don't skip build on cache hit (see above)
2. you will trigger the build anyway when you run cargo bench below
</blockquote></details>

Done. But see above.
___
*[`.github/workflows/ci.yml` line 136 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JuePaBPh2vvNR8B05:-O0Kw_mcDRdG4n8nzILj:b1jj4zs) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L136)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

don't you need the release flag here?
</blockquote></details>

AFAIK (and also according to what I see), `cargo bench` is with the `--release` flag by default (makes sense, you usually want to time the release code, not the debug code). If you insist, I will add it explicitly.
___
*[`.github/workflows/ci.yml` line 139 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JujNx6Jq9FXUYBInQ:-O0Kx-zD5uhhwdtm9Lva:b-7aske3) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L139)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

`bu` is "backup"?
</blockquote></details>

Yes, I added a comment. Should I change bu to backup in the variable name?
___
*[`.github/workflows/ci.yml` line 147 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JupqVCrrbATGBwomo:-O0Kx9O_20MYFSddf_zq:bribihm) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L147)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

see above
</blockquote></details>

As above.
___
*[`.github/workflows/ci.yml` line 150 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0Jv7RB2KX5TCGYuQ5K:-O0L6fSD-QantYWBIwzh:b-s313j8) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L150)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove whitespace
</blockquote></details>

There are very few newlines, it's really hard to read without them (I separated to 3 steps - 1. Downloading and benchmarking original code, 2. Downloading and benchmarking new code, 3. Posting results)
___
*[`.github/workflows/ci.yml` line 165 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0Jv9C-7sE-z1HH0Ec2:-O0L70NIBOS7L0gv48yD:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L165)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

remove whitespace
</blockquote></details>

Done.
___
*[`crates/committer_cli/benches/committer_bench.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JvBKY51bKQBov1zXL:-O0KxIid8fW_npO3va1e:bn24y1n) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/crates/committer_cli/benches/committer_bench.rs#L48)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

what's this?
</blockquote></details>

Some sanity test I added. I'll remove it once this PR starts converging.

**Comment by aner-starkware** [comment]
*[`.github/workflows/ci.yml` line 136 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JuePaBPh2vvNR8B05:-O0NcHbKECSW-N7wvGV2:bnsjtp7) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L136)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

AFAIK (and also according to what I see), `cargo bench` is with the `--release` flag by default (makes sense, you usually want to time the release code, not the debug code). If you insist, I will add it explicitly.
</blockquote></details>

Actually, adding `--release` explicitly doesn't seem to be possible for `cargo bench` (but is implicit). It's actually not that simple to disable the `--release` compilation for `cargo bench`.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/251)* status: all files reviewed, 4 unresolved discussions (waiting on @aner-starkware and @yoavGrs)

___
*[`.github/workflows/ci.yml` line 150 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0Jv7RB2KX5TCGYuQ5K:-O0Nczb4Ci5xYQp0TS4O:bi91ghk) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L150)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

There are very few newlines, it's really hard to read without them (I separated to 3 steps - 1. Downloading and benchmarking original code, 2. Downloading and benchmarking new code, 3. Posting results)
</blockquote></details>

no no, the newlines were good! please restore them.
the *whitespace* (spaces) is what I want removed, I see them as red dots in reviewable.
VSCode should have an auto-format option to remove trailing whitespace from every line in a file
___
*[`.github/workflows/ci.yml` line 165 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0Jv9C-7sE-z1HH0Ec2:-O0NdD458VasXZJ5oSnC:b7e2ppn) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L165)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not the newline, just the spaces :) my bad..
___
*[`.github/workflows/ci.yml` line 157 at r3](https://reviewable.io/reviews/starkware-libs/committer/251#-O0NdJIX-9GF5JKe65w3:-O0NdJIX-9GF5JKe65w4:bd8bkx0) ([raw file](https://github.com/starkware-libs/committer/blob/72fc5d7b251334e89ecd1e1561f9eea0c7e678b6/.github/workflows/ci.yml#L157)):*
> ```YAML
>               path: 'Commits'
>             })
>       - if: ${{contains(env.BENCHES_RESULT, 'improved') && !contains(env.BENCHES_RESULT, 'regressed')}}
> ```

how can both 'improved' and 'regressed' appear in the same result?
maybe add a comment about it, it's non intuitive



_Code quote:_
```YAML
${{contains(env.BENCHES_RESULT, 'improved') && !contains(env.BENCHES_RESULT, 'regressed')}}
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/251)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`.github/workflows/ci.yml` line 150 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0Jv7RB2KX5TCGYuQ5K:-O0OE66L6WCKl6L0VT6d:b-clxhwx) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L150)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no no, the newlines were good! please restore them.
the *whitespace* (spaces) is what I want removed, I see them as red dots in reviewable.
VSCode should have an auto-format option to remove trailing whitespace from every line in a file
</blockquote></details>

Ahh, OK, got you. Done.
___
*[`.github/workflows/ci.yml` line 165 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0Jv9C-7sE-z1HH0Ec2:-O0OEA-H4Iqk1lDlDOgE:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/.github/workflows/ci.yml#L165)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not the newline, just the spaces :) my bad..
</blockquote></details>

Done.
___
*[`.github/workflows/ci.yml` line 157 at r3](https://reviewable.io/reviews/starkware-libs/committer/251#-O0NdJIX-9GF5JKe65w3:-O0OEDcK4pTnsDX0SqKz:bdne420) ([raw file](https://github.com/starkware-libs/committer/blob/72fc5d7b251334e89ecd1e1561f9eea0c7e678b6/.github/workflows/ci.yml#L157)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

how can both 'improved' and 'regressed' appear in the same result?
maybe add a comment about it, it's non intuitive
</blockquote></details>

There are several benchmarkings; some might improve, while others may regress. But in any case, it will print all of them; only the title is different (so there's no point in double-printing the result).

What kind of comment explains this? (It's basically just because this format doesn't support if-else, which is a bit annoying)

**Comment by aner-starkware** [comment]
*[`.github/workflows/ci.yml` line 157 at r3](https://reviewable.io/reviews/starkware-libs/committer/251#-O0NdJIX-9GF5JKe65w3:-O0OG2oU0JsXW-uyOg0g:b-zdae1p) ([raw file](https://github.com/starkware-libs/committer/blob/72fc5d7b251334e89ecd1e1561f9eea0c7e678b6/.github/workflows/ci.yml#L157)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

There are several benchmarkings; some might improve, while others may regress. But in any case, it will print all of them; only the title is different (so there's no point in double-printing the result).

What kind of comment explains this? (It's basically just because this format doesn't support if-else, which is a bit annoying)
</blockquote></details>

There's another option of course, which is to split the benchmarkings and only post those that have regressed/improved. This is out of scope for this PR (but if you are interested, I'll add a TODO here)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/251)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`crates/committer_cli/benches/committer_bench.rs` line 48 at r2](https://reviewable.io/reviews/starkware-libs/committer/251#-O0JvBKY51bKQBov1zXL:-O0OH13w36-Rp3YKxEfI:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/fc87960dc9edcd48bf5bde1504408eeebf86974f/crates/committer_cli/benches/committer_bench.rs#L48)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Some sanity test I added. I'll remove it once this PR starts converging.
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/251)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @yoavGrs)

___
*[`.github/workflows/ci.yml` line 157 at r3](https://reviewable.io/reviews/starkware-libs/committer/251#-O0NdJIX-9GF5JKe65w3:-O0cWwOoDtomrYtIFR0m:bdnxq73) ([raw file](https://github.com/starkware-libs/committer/blob/72fc5d7b251334e89ecd1e1561f9eea0c7e678b6/.github/workflows/ci.yml#L157)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

There's another option of course, which is to split the benchmarkings and only post those that have regressed/improved. This is out of scope for this PR (but if you are interested, I'll add a TODO here)
</blockquote></details>

yeah todo for that would be good

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/251)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @yoavGrs)

___
*[`.github/workflows/ci.yml` line 157 at r3](https://reviewable.io/reviews/starkware-libs/committer/251#-O0NdJIX-9GF5JKe65w3:-O0dYXMV576N3TOkRyfq:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/72fc5d7b251334e89ecd1e1561f9eea0c7e678b6/.github/workflows/ci.yml#L157)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yeah todo for that would be good
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/251#-:-O0dc9Xl8o1KV5WBefD6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yoavGrs)

**Pull request merged**
