### PR TITLE
build: add storage trait and FilledTree::serialize

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/26)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/26#-:-Nv1Zro6D8q2ZWaqEBQ4:b-hz3kb8)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/26)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/current_skeleton_tree.rs` line 4 at r1](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv1_7yx476c1myAw18o:-Nv1_7yy2R72lDxgY5RM:b-e97a58) ([raw file](https://github.com/starkware-libs/committer/blob/707a58d5ca0c9e0dbf7280b9c37b040e67fcbfb6/crates/committer/src/patricia_merkle_tree/current_skeleton_tree.rs#L4)):*
> ```XML
> 
> use crate::hash::types::HashFunction;
> use crate::patricia_merkle_tree::errors::SkeletonTreeError;
> ```

I notice I forgot to split `SkeletonTreeError` into `CurrentSkeletonTreeError`, UpdatedSkeletonTreeError



_Code quote:_
```XML
use crate::patricia_merkle_tree::errors::SkeletonTreeError;
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/26)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv1_ETf3qK01cTH5ja-:-Nv1_ETf3qK01cTH5ja0:bq2io8i) ([raw file](https://github.com/starkware-libs/committer/blob/0bec52ce6f82bb9775cb6d78e10e9685e2120cd1/crates/committer/src/patricia_merkle_tree/filled_tree.rs#L13)):*
> ```XML
>     /// Serializes the tree into storage. Returns hash set of keys of the serialized nodes,
>     /// if successful.
>     fn serialize(&self, storage: &dyn Storage) -> Result<HashSet<&[u8]>, FilledTreeError>;
> ```

prefer generic type (compile time) to dynamic type (runtime)



_Suggestion:_
```XML
pub(crate) trait FilledTree<L: LeafDataTrait, S: Storage> {
    /// Serializes the tree into storage. Returns hash set of keys of the serialized nodes,
    /// if successful.
    fn serialize(&self, storage: &S) -> Result<HashSet<&[u8]>, FilledTreeError>;
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree.rs` line 14 at r1](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv1_ArD1h1XJpL0Pjvb:-Nv1_ArD1h1XJpL0Pjvc:b91yzl2) ([raw file](https://github.com/starkware-libs/committer/blob/0bec52ce6f82bb9775cb6d78e10e9685e2120cd1/crates/committer/src/patricia_merkle_tree/filled_tree.rs#L14)):*
> ```XML
>     /// if successful.
>     fn serialize(&self, storage: &dyn Storage) -> Result<HashSet<&[u8]>, FilledTreeError>;
> }
> ```

@aner-starkware note this change



_Code quote:_
```XML
pub(crate) trait FilledTree<L: LeafDataTrait> {
    /// Serializes the tree into storage. Returns hash set of keys of the serialized nodes,
    /// if successful.
    fn serialize(&self, storage: &dyn Storage) -> Result<HashSet<&[u8]>, FilledTreeError>;
}
```
___
*[`crates/committer/src/storage/storage_trait.rs` line 13 at r1](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv1_Tx9EedUAwPS6QPp:-Nv1_Tx9EedUAwPS6QPq:b6c5jkh) ([raw file](https://github.com/starkware-libs/committer/blob/0bec52ce6f82bb9775cb6d78e10e9685e2120cd1/crates/committer/src/storage/storage_trait.rs#L13)):*
> ```XML
>     /// Deletes value from storage.
>     fn delete(&mut self, key: &[u8]);
> }
> ```

1. please add @Itay-Tsabary-Starkware as a reviewer for this
2. are you sure we want an `Option` type for storage values? do we want to differentiate between `0` and `None`?
3. wrap the type of a storage value in a named type (not `&[u8]`)
4. ditto for storage key



_Code quote:_
```XML
pub(crate) trait Storage {
    /// Returns value from storage, if it exists.
    fn get(&self, key: &[u8]) -> Option<&[u8]>;
    /// Sets value in storage.
    fn set(&mut self, key: &[u8], value: &[u8]);
    /// Returns values from storage in same order of given keys. If key does not exist,
    /// value is None.
    fn mget(&self, keys: Vec<&[u8]>) -> Vec<Option<&[u8]>>;
    /// Sets values in storage.
    fn mset(&mut self, key: Vec<&[u8]>, value: Vec<&[u8]>);
    /// Deletes value from storage.
    fn delete(&mut self, key: &[u8]);
}
```

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@Itay-Tsabary-Starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/26#-:-Nv1d1aY9aqxNF_ZOWKw:b9trd3c)* status: all files reviewed, 3 unresolved discussions (waiting on @Itay-Tsabary-Starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/26)* status: all files reviewed, 5 unresolved discussions (waiting on @amosStarkware and @Itay-Tsabary-Starkware)

___
*[`crates/committer/src/storage/storage_trait.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv26dlpBfTxCfSiIFRs:-Nv26dlpBfTxCfSiIFRt:bo5x2we) ([raw file](https://github.com/starkware-libs/committer/blob/04abbaff08d623cd6908bf24c85896bda73649b2/crates/committer/src/storage/storage_trait.rs#L7)):*
> ```XML
> 
> #[allow(dead_code)]
> pub(crate) struct StorageValue<'a>(&'a [u8]);
> ```

@nimrod-starkware are you defining something similar?



_Code quote:_
```XML
#[allow(dead_code)]
pub(crate) struct StorageKey<'a>(&'a [u8]);

#[allow(dead_code)]
pub(crate) struct StorageValue<'a>(&'a [u8]);
```
___
*[`crates/committer/src/storage/storage_trait.rs` line 7 at r2](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv26mmRAziZVv-neIAB:-Nv26mmRAziZVv-neIAC:bkw7j4u) ([raw file](https://github.com/starkware-libs/committer/blob/04abbaff08d623cd6908bf24c85896bda73649b2/crates/committer/src/storage/storage_trait.rs#L7)):*
> ```XML
> 
> #[allow(dead_code)]
> pub(crate) struct StorageValue<'a>(&'a [u8]);
> ```

@amosStarkware any reason these types shouldn't own their internal data? (asking, not sure if this is possible with slices)



_Suggestion:_
```XML
#[allow(dead_code)]
pub(crate) struct StorageKey([u8]);

#[allow(dead_code)]
pub(crate) struct StorageValue([u8]);
```
___
*[`crates/committer/src/storage/storage_trait.rs` line 16 at r2](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv27-yV2RXppBBxZAQ5:-Nv27-yV2RXppBBxZAQ6:b-47ccwh) ([raw file](https://github.com/starkware-libs/committer/blob/04abbaff08d623cd6908bf24c85896bda73649b2/crates/committer/src/storage/storage_trait.rs#L16)):*
> ```XML
>     /// Returns values from storage in same order of given keys. If key does not exist,
>     /// value is None.
>     fn mget(&self, keys: Vec<StorageKey<'_>>) -> Vec<Option<StorageValue<'_>>>;
> ```

this should be better than constructing vectors, right?
is this possible without unreasonable lifetime syntax?



_Suggestion:_
```XML
&[StorageKey<'_>]
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/26)* status: all files reviewed, 4 unresolved discussions (waiting on @amosStarkware and @Itay-Tsabary-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/current_skeleton_tree.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv2BgN-7Q-Ae4sXedwV:-Nv2BgN-7Q-Ae4sXedwW:b-gccpxt) ([raw file](https://github.com/starkware-libs/committer/blob/da184c70f3c6627660f14f81117d062d11c907a0/crates/committer/src/patricia_merkle_tree/current_skeleton_tree.rs#L18)):*
> ```XML
> pub(crate) trait CurrentSkeletonTree<L: LeafDataTrait, H: HashFunction, TH: TreeHashFunction<L, H>>
> {
>     fn compute_current_skeleton_tree(
> ```

no computation being done, just storage traversal



_Suggestion:_
```XML
construct_current_skeleton_tree
```
___
*[`crates/committer/src/patricia_merkle_tree/current_skeleton_tree.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv2BYi6EyURTswBQeLK:-Nv2BYi6EyURTswBQeLL:b-ci5d2x) ([raw file](https://github.com/starkware-libs/committer/blob/da184c70f3c6627660f14f81117d062d11c907a0/crates/committer/src/patricia_merkle_tree/current_skeleton_tree.rs#L23)):*
> ```XML
>         root_hash: HashOutput,
>         tree_height: TreeHeight,
>     ) -> CurrentSkeletonTreeResult<Box<Self>>;
> ```

why `Box`?



_Suggestion:_
```XML
CurrentSkeletonTreeResult<Self>
```
___
*[`crates/committer/src/storage/storage_trait.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv2Bxv26q0N6fDk5ME9:-Nv2Bxv26q0N6fDk5MEA:brticdh) ([raw file](https://github.com/starkware-libs/committer/blob/da184c70f3c6627660f14f81117d062d11c907a0/crates/committer/src/storage/storage_trait.rs#L11)):*
> ```XML
> pub(crate) trait Storage {
>     /// Returns value from storage, if it exists.
>     fn get(&self, key: &StorageKey) -> Option<Box<StorageValue>>;
> ```

ah...
if we have a choice between using `struct StorageValue(Vec<u8>)`,
or defining `StorageValue([u8])` and having to use `Box`,
then I prefer the `Vector` route...
better to allocate vectors than to `unwrap` boxes



_Code quote:_
```XML
Box<
```
___
*[`crates/committer/src/storage/storage_trait.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv2CCKEDEFPZapEC-CD:-Nv2CCKEDEFPZapEC-CE:b-vydh3p) ([raw file](https://github.com/starkware-libs/committer/blob/da184c70f3c6627660f14f81117d062d11c907a0/crates/committer/src/storage/storage_trait.rs#L16)):*
> ```XML
>     /// Returns values from storage in same order of given keys. If key does not exist,
>     /// value is None.
>     fn mget(&self, keys: [&StorageKey]) -> [Option<Box<StorageValue>>];
> ```

subtle difference



_Suggestion:_
```XML
&[StorageKey]
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/26)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @Itay-Tsabary-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/current_skeleton_tree.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv2BgN-7Q-Ae4sXedwV:-Nv2Kjl06cx_ANC581o0:b-j1nvlb) ([raw file](https://github.com/starkware-libs/committer/blob/da184c70f3c6627660f14f81117d062d11c907a0/crates/committer/src/patricia_merkle_tree/current_skeleton_tree.rs#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

no computation being done, just storage traversal
</blockquote></details>

It's computed in the same sense that `compute_updated_skeleton_tree` computes the updated skeleton tree. should I change both to construct?
___
*[`crates/committer/src/patricia_merkle_tree/current_skeleton_tree.rs` line 23 at r3](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv2BYi6EyURTswBQeLK:-Nv2LPEC1PPn3UqaYIG1:b-pgm1s7) ([raw file](https://github.com/starkware-libs/committer/blob/da184c70f3c6627660f14f81117d062d11c907a0/crates/committer/src/patricia_merkle_tree/current_skeleton_tree.rs#L23)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why `Box`?
</blockquote></details>

its size isn't known at compile time, so I think it makes sense to allocate it on the heap. but maybe there's a better solution?
___
*[`crates/committer/src/storage/storage_trait.rs` line 11 at r3](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv2Bxv26q0N6fDk5ME9:-Nv2OnGh1SUZJOxSN8ri:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/da184c70f3c6627660f14f81117d062d11c907a0/crates/committer/src/storage/storage_trait.rs#L11)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

ah...
if we have a choice between using `struct StorageValue(Vec<u8>)`,
or defining `StorageValue([u8])` and having to use `Box`,
then I prefer the `Vector` route...
better to allocate vectors than to `unwrap` boxes
</blockquote></details>

Done.
___
*[`crates/committer/src/storage/storage_trait.rs` line 16 at r3](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv2CCKEDEFPZapEC-CD:-Nv2OjCe7QlR72J6JIIz:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/da184c70f3c6627660f14f81117d062d11c907a0/crates/committer/src/storage/storage_trait.rs#L16)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

subtle difference
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/26#-:-Nv2YUjoAmcgzGCOUeNr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Itay-Tsabary-Starkware)

___
*[`crates/committer/src/patricia_merkle_tree/current_skeleton_tree.rs` line 18 at r3](https://reviewable.io/reviews/starkware-libs/committer/26#-Nv2BgN-7Q-Ae4sXedwV:-Nv2YJA25EMD_6BSG-1r:b6twk9c) ([raw file](https://github.com/starkware-libs/committer/blob/da184c70f3c6627660f14f81117d062d11c907a0/crates/committer/src/patricia_merkle_tree/current_skeleton_tree.rs#L18)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

It's computed in the same sense that `compute_updated_skeleton_tree` computes the updated skeleton tree. should I change both to construct?
</blockquote></details>

no, current->updated includes computation (merge nodes, split notes etc).
constructing an instance of the current tree from storage requires no computation, just traversal.
unblocking anyway, it's not important

**Pull request merged**
