### PR TITLE
refactor: deserialize parse from python using structs and deserializer

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/289)

### CODE REVIEW

**Comment by aner-starkware** [comment]
Python side: https://reviewable.io/reviews/starkware-industries/starkware/35461

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/289)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware, @AvivYossef-starkware, and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/committer/289#-O1Msflu96rnma80JXMl:-O1Msflu96rnma80JXMm:b-59gbea) ([raw file](https://github.com/starkware-libs/committer/blob/09c320e40b61d33d6dabe39b9fbfbf135e2a5e4b/crates/committer_cli/src/tests/benchmark_tests.rs#L57)):*
> ```XML
>         storage,
>         root_hash,
>     } = input.tree_flow_input;
> ```

total destructuring



_Suggestion:_
```XML
    let TreeRegressionInput {
        tree_flow_input: TreeFlowInput {
            leaf_modifications,
            storage,
            root_hash,
        },
        expected_hash,
        expected_storage_changes
    } = serde_json::from_str(SINGLE_TREE_FLOW_INPUT).unwrap();
```
___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/committer/289#-O1Mt2doALuzLdVss5YA:-O1Mt2doALuzLdVss5YB:b-12qvcg) ([raw file](https://github.com/starkware-libs/committer/blob/09c320e40b61d33d6dabe39b9fbfbf135e2a5e4b/crates/committer_cli/src/tests/benchmark_tests.rs#L76)):*
> ```XML
>     };
>     let expected_storage_changes: Map<String, Value> =
>         serde_json::from_str(&input.expected_storage_changes).unwrap();
> ```

two "unclean" accesses here: one `map.get("storage_changes")` (should be field access) and another `serde_json::from_str` call



_Suggestion:_
```XML
    // Assert the storage changes.
    // TODO(Aner, 8/7/2024): use structs for deserialization.
    let Value::Object(storage_changes) = output_map.get("storage_changes").unwrap() else {
        panic!("Expected storage changes object to be an object.");
    };
    let expected_storage_changes: Map<String, Value> =
        serde_json::from_str(&input.expected_storage_changes).unwrap();
```

**Comment by aner-starkware** [comment]
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/committer/289#-O1Mt2doALuzLdVss5YA:-O1MtoI2BCRNStY9kMv2:b6wpb6t) ([raw file](https://github.com/starkware-libs/committer/blob/09c320e40b61d33d6dabe39b9fbfbf135e2a5e4b/crates/committer_cli/src/tests/benchmark_tests.rs#L76)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

two "unclean" accesses here: one `map.get("storage_changes")` (should be field access) and another `serde_json::from_str` call
</blockquote></details>

There's a TODO, which is dealt with in a later PR (if I understand correctly what you're referring to).

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/289)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 57 at r1](https://reviewable.io/reviews/starkware-libs/committer/289#-O1Msflu96rnma80JXMl:-O1MvdCFDZ0I_Wu3BoNJ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/09c320e40b61d33d6dabe39b9fbfbf135e2a5e4b/crates/committer_cli/src/tests/benchmark_tests.rs#L57)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

total destructuring
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/289#-:-O1MvwarDiURZ6Aj5Zhy:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware and @TzahiTaub)

___
*[`crates/committer_cli/src/tests/benchmark_tests.rs` line 76 at r1](https://reviewable.io/reviews/starkware-libs/committer/289#-O1Mt2doALuzLdVss5YA:-O1Mvk_m1ILP3nVXVkI5:b-xk2p0v) ([raw file](https://github.com/starkware-libs/committer/blob/09c320e40b61d33d6dabe39b9fbfbf135e2a5e4b/crates/committer_cli/src/tests/benchmark_tests.rs#L76)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

There's a TODO, which is dealt with in a later PR (if I understand correctly what you're referring to).
</blockquote></details>

right, reviewing in order sorry

**Pull request merged**
