### PR TITLE
build: add root_index and compute_bottom_index

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23)* status: all files reviewed, 7 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv0t1G05vSMhdtFAk39:-Nv0t1G05vSMhdtFAk3A:b-ugci5d) ([raw file](https://github.com/starkware-libs/committer/blob/a87a6b34685dcc851e513f3e16cd1502a8d1c60b/crates/committer/src/patricia_merkle_tree/types.rs#L6)):*
> ```XML
> 
> #[cfg(test)]
> #[path = "./types_test.rs"]
> ```

not needed; you need this directive if the module name is not the name you use in the `pub mod`.
for example:
```
#[path = "types_test.rs"]
pub mod test;
```
([blockifier example](https://github.com/starkware-libs/blockifier/blob/dori/jemalloc-in-native-blockifier/crates/blockifier/src/bouncer.rs#L17-L19))
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 23 at r1](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv0tRrC3tgwsjuqMP05:-Nv0tRrC3tgwsjuqMP06:b-4jz88e) ([raw file](https://github.com/starkware-libs/committer/blob/a87a6b34685dcc851e513f3e16cd1502a8d1c60b/crates/committer/src/patricia_merkle_tree/types.rs#L23)):*
> ```XML
>         NodeIndex(Felt::ONE)
>     }
>     pub(crate) fn compute_bottom_index(
> ```

newline between functions



_Suggestion:_
```XML
    }
    
    pub(crate) fn compute_bottom_index(
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv0tgOTE0Y-6d8KkMYZ:-Nv0tgOTE0Y-6d8KkMY_:b7tyje6) ([raw file](https://github.com/starkware-libs/committer/blob/a87a6b34685dcc851e513f3e16cd1502a8d1c60b/crates/committer/src/patricia_merkle_tree/types.rs#L32)):*
> ```XML
>             bottom_index *= Felt::TWO;
>         }
>         bottom_index += path.0;
> ```

does this work?



_Suggestion:_
```XML
        let bottom_index = index.0 * Felt::TWO.pow_felt(length.0) + path.0;
```
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 1 at r1](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv0w8D9EEFCyeWAKDDZ:-Nv0w8D9EEFCyeWAKDD_:bi6hbo6) ([raw file](https://github.com/starkware-libs/committer/blob/a87a6b34685dcc851e513f3e16cd1502a8d1c60b/crates/committer/src/patricia_merkle_tree/types_test.rs#L1)):*
> ```XML
> use starknet_types_core::felt::Felt;
> ```

don't use this Felt directly... use our internal representation



_Suggestion:_
```XML
use crate::types::Felt;
```
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 5 at r1](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv0ulbi8oLu5dUj-b0k:-Nv0ulbi8oLu5dUj-b0l:bvk92px) ([raw file](https://github.com/starkware-libs/committer/blob/a87a6b34685dcc851e513f3e16cd1502a8d1c60b/crates/committer/src/patricia_merkle_tree/types_test.rs#L5)):*
> ```XML
> use crate::patricia_merkle_tree::types::{EdgePath, EdgePathLength, NodeIndex, PathToBottom};
> 
> #[test]
> ```

Use `rstest` and cases



_Suggestion:_
```XML
#[rstest]
#[case(1, 1, 1, 3)]
#[case(1, 0, 2, 4)]
#[case(0xDAD, 0xFEE, 12, 0xDADFEE)]
#[case(0xDEAFBEE, 0xBFF, 16, 0xDEAFBEE0BFF)]
```
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv0uKqj6wvCbdOWrpSt:-Nv0uKqj6wvCbdOWrpSu:b-olzb5q) ([raw file](https://github.com/starkware-libs/committer/blob/a87a6b34685dcc851e513f3e16cd1502a8d1c60b/crates/committer/src/patricia_merkle_tree/types_test.rs#L22)):*
> ```XML
>         },
>     );
>     assert_eq!(bottom_index, NodeIndex(Felt::from(1 << 2)));
> ```

clearer, IMO



_Suggestion:_
```XML
Felt::from(4_u8)
```
___
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv0uY5J1DF8Y97xXwGM:-Nv0uY5J1DF8Y97xXwGN:b238tzm) ([raw file](https://github.com/starkware-libs/committer/blob/a87a6b34685dcc851e513f3e16cd1502a8d1c60b/crates/committer/src/patricia_merkle_tree/types_test.rs#L38)):*
> ```XML
>         },
>     );
>     assert_eq!(bottom_index, NodeIndex(Felt::from(0xDEAFBEE0BFF_u64)));
> ```

is the extra `0` expected? shouldn't it be `0xDEADBEEBFF`?



_Code quote:_
```XML
0xDEAFBEE0BFF_u64
```

**Comment by aner-starkware** [comment]
*[`crates/committer/src/patricia_merkle_tree/types_test.rs` line 38 at r1](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv0uY5J1DF8Y97xXwGM:-Nv1g1ucBhw6kBB6mxW1:bs774ai) ([raw file](https://github.com/starkware-libs/committer/blob/a87a6b34685dcc851e513f3e16cd1502a8d1c60b/crates/committer/src/patricia_merkle_tree/types_test.rs#L38)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

is the extra `0` expected? shouldn't it be `0xDEADBEEBFF`?
</blockquote></details>

It's expected, because of the length.

**Comment by aner-starkware** [comment]
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv0t1G05vSMhdtFAk39:-Nv1h2_i2H5MF55b9LtV:bqmbdyf) ([raw file](https://github.com/starkware-libs/committer/blob/a87a6b34685dcc851e513f3e16cd1502a8d1c60b/crates/committer/src/patricia_merkle_tree/types.rs#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

not needed; you need this directive if the module name is not the name you use in the `pub mod`.
for example:
```
#[path = "types_test.rs"]
pub mod test;
```
([blockifier example](https://github.com/starkware-libs/blockifier/blob/dori/jemalloc-in-native-blockifier/crates/blockifier/src/bouncer.rs#L17-L19))
</blockquote></details>

It doesn't work, so I added it—it's looking for the directory types otherwise. Idea?

**Comment by aner-starkware** [comment]
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv0t1G05vSMhdtFAk39:-Nv1hdITBuCkr1Ij3nGZ:b-3k16ug) ([raw file](https://github.com/starkware-libs/committer/blob/a87a6b34685dcc851e513f3e16cd1502a8d1c60b/crates/committer/src/patricia_merkle_tree/types.rs#L6)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

It doesn't work, so I added it—it's looking for the directory types otherwise. Idea?
</blockquote></details>

(Directory `types`)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @TzahiTaub)

___
*[`crates/committer/Cargo.toml` line 18 at r2](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv1kmWN9sIoo1fcyqKO:-Nv1kmWOAH6IlligOL-v:b-xufmer) ([raw file](https://github.com/starkware-libs/committer/blob/31486f8ab9ea7a3681471a5ce4e0191e22909504/crates/committer/Cargo.toml#L18)):*
> ```TOML
> starknet-types-core = "0.0.11"
> starknet_api = "0.12.0-dev.0"
> rstest = "0.17.0"
> ```

1. move this to the top-level Cargo.toml
2. use workspace=true here
3. add a newline at the end of this file



_Suggestion:_
```TOML
rstest.workspace = true
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv0t1G05vSMhdtFAk39:-Nv1kXby6_qo-F9D5oGJ:b-ncok81) ([raw file](https://github.com/starkware-libs/committer/blob/a87a6b34685dcc851e513f3e16cd1502a8d1c60b/crates/committer/src/patricia_merkle_tree/types.rs#L6)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

(Directory `types`)
</blockquote></details>

hmmm... right you are. bummer.
drop the `./` prefix though, you [shouldn't need it](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/blockifier/block.rs#L15-L17)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 6 at r1](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv0t1G05vSMhdtFAk39:-Nv1l_Jv0Pme7q1OcOJk:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/a87a6b34685dcc851e513f3e16cd1502a8d1c60b/crates/committer/src/patricia_merkle_tree/types.rs#L6)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

hmmm... right you are. bummer.
drop the `./` prefix though, you [shouldn't need it](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/blockifier/block.rs#L15-L17)
</blockquote></details>

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 32 at r1](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv0tgOTE0Y-6d8KkMYZ:-Nv1lwMh4IZKgeN87bo1:b-t67iz4) ([raw file](https://github.com/starkware-libs/committer/blob/a87a6b34685dcc851e513f3e16cd1502a8d1c60b/crates/committer/src/patricia_merkle_tree/types.rs#L32)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does this work?
</blockquote></details>

Yes! :)

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @aner-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 30 at r3](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv1mvF13eX-NMkpzf4x:-Nv1mvF13eX-NMkpzf4y:bcpih2f) ([raw file](https://github.com/starkware-libs/committer/blob/8f237c49ec00dc85ffb961a5ce431d4a66bb3cb2/crates/committer/src/patricia_merkle_tree/types.rs#L30)):*
> ```XML
>         let PathToBottom { path, length } = path_to_bottom;
>         let bottom_index = index.0 * Felt::TWO.pow(length.0) + path.0;
>         NodeIndex(bottom_index)
> ```

non-blocking, but nicer :)



_Suggestion:_
```XML
        NodeIndex(index.0 * Felt::TWO.pow(length.0) + path.0)
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/Cargo.toml` line 18 at r2](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv1kmWN9sIoo1fcyqKO:-Nv1n5dhA_IL0JODWGyH:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/31486f8ab9ea7a3681471a5ce4e0191e22909504/crates/committer/Cargo.toml#L18)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

1. move this to the top-level Cargo.toml
2. use workspace=true here
3. add a newline at the end of this file
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @aner-starkware, and @TzahiTaub)

___
*[`crates/committer/Cargo.toml` line 18 at r4](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv1nZFj38MvJDtCzUTM:-Nv1nZFk6lz5D7j537rJ:b-p6l69c) ([raw file](https://github.com/starkware-libs/committer/blob/d145ab5a8f66cb8f25ba2e72cce352fa505503b8/crates/committer/Cargo.toml#L18)):*
> ```TOML
> starknet-types-core = "0.0.11"
> starknet_api = "0.12.0-dev.0"
> rstest.workspace = true
> ```

only required for `#[cfg(test)]`
see [here](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/Cargo.toml#L52-L58)



_Suggestion:_
```TOML

[dev-dependencies]
rstest.workspace = true
```

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @aner-starkware, and @TzahiTaub)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23#-:-Nv1sn_e42guFcgpmj42:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @TzahiTaub)

**Comment by aner-starkware** [comment]
I messed up a bit with the Cargo.toml - please check if I set it right

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23#-:-Nv27peW4AvIboAXGj04:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @TzahiTaub)

**Comment by aner-starkware** [comment]
It fails the udeps, so I guess something is off... Maybe it's in the Cargo.lock?

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
see comment below, I have a suspicion 

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23#-:-Nv5zbXb3Z_d1dJuMB6d:b-3qmi9t)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @aner-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 9 at r9](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv5zMt-8T3E4XcKU2hL:-Nv5zMt-8T3E4XcKU2hM:b-k4fphk) ([raw file](https://github.com/starkware-libs/committer/blob/04eb21592495201a99b59baa33c3270d55a2fd47/crates/committer/src/patricia_merkle_tree/types.rs#L9)):*
> ```XML
> mod test_utils;
> #[path = "types_test.rs"]
> pub mod types_test;
> ```

without this attribute, you would be trying to declare the types_test module in production mode.
in production mode you don't have rstest, so CI would fail
(I hope this is the issue)



_Suggestion:_
```XML
#[cfg(test)]
#[path = "types_test.rs"]
pub mod types_test;
```

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 9 at r9](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv5zMt-8T3E4XcKU2hL:-Nv6PGC3EgWlprjI7qyz:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/04eb21592495201a99b59baa33c3270d55a2fd47/crates/committer/src/patricia_merkle_tree/types.rs#L9)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

without this attribute, you would be trying to declare the types_test module in production mode.
in production mode you don't have rstest, so CI would fail
(I hope this is the issue)
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware, @aner-starkware, and @TzahiTaub)

___
*[`crates/committer/Cargo.toml` line 17 at r10](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv6aqwh7-c8TU51Xtna:-Nv6aqwh7-c8TU51Xtnb:b7zw6zj) ([raw file](https://github.com/starkware-libs/committer/blob/94f97e3ba9d437824825031923ac153814b7a6bf/crates/committer/Cargo.toml#L17)):*
> ```TOML
> 
> [dependencies]
> starknet-types-core = { version = "0.0.11", features = ["hash"] }
> ```

move to the root Cargo.toml, use `workspace = true` here



_Code quote:_
```TOML
starknet-types-core = { version = "0.0.11", features = ["hash"] }
```

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23#-:-Nv6dpln9UXmm-EJy6ku:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware and @TzahiTaub)

**Review by aner-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @amosStarkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/Cargo.toml` line 17 at r10](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv6aqwh7-c8TU51Xtna:-Nv6cLx_6otkhTNpRvaC:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/94f97e3ba9d437824825031923ac153814b7a6bf/crates/committer/Cargo.toml#L17)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

move to the root Cargo.toml, use `workspace = true` here
</blockquote></details>

Done.

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/23)* status: all files reviewed, 2 unresolved discussions

___
*[`crates/committer/Cargo.toml` line 18 at r13](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv75xq140oJEka9Ziih:-Nv75xq140oJEka9Ziii:b-y80p5d) ([raw file](https://github.com/starkware-libs/committer/blob/3e0c47af4ba6f88742045248634882fe7f43204d/crates/committer/Cargo.toml#L18)):*
> ```TOML
> [dependencies]
> starknet-types-core.workspace = true
> derive_more = "0.99.17"
> ```

move to root cargo.toml



_Suggestion:_
```TOML
derive_more.workspace = true
```
___
*[`crates/committer/src/types.rs` line 14 at r13](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv763y96NCvR0E7JNuT:-Nv763y96NCvR0E7JNuU:bcq8fws) ([raw file](https://github.com/starkware-libs/committer/blob/3e0c47af4ba6f88742045248634882fe7f43204d/crates/committer/src/types.rs#L14)):*
> ```XML
> impl From<u128> for Felt {
>     fn from(value: u128) -> Self {
>         Self(StarknetTypesFelt::from(value))
> ```

if this works, it's better, because it doesn't depend on the internal type name (if we decide to swap it later, will be less code to change).
non-blocking



_Suggestion:_
```XML
Self(value.into())
```

**Comment by aner-starkware** [comment]
*[`crates/committer/src/types.rs` line 14 at r13](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv763y96NCvR0E7JNuT:-Nv77FH34XIeOFN2gb4r:b-kfzrpr) ([raw file](https://github.com/starkware-libs/committer/blob/3e0c47af4ba6f88742045248634882fe7f43204d/crates/committer/src/types.rs#L14)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if this works, it's better, because it doesn't depend on the internal type name (if we decide to swap it later, will be less code to change).
non-blocking
</blockquote></details>

Will do in the next PR

**Comment by aner-starkware** [comment]
*[`crates/committer/Cargo.toml` line 18 at r13](https://reviewable.io/reviews/starkware-libs/committer/23#-Nv75xq140oJEka9Ziih:-Nv77P-V7Wcq3Mu0DlEG:b-67wrdu) ([raw file](https://github.com/starkware-libs/committer/blob/3e0c47af4ba6f88742045248634882fe7f43204d/crates/committer/Cargo.toml#L18)):*
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

Tried, doesn't work
</blockquote></details>

Wait, maybe I forgot the workspace, will try again in the next PR

**Pull request merged**
