### PR TITLE
fix: warning for trivial modifications were not implied by an empty tree

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/276)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/276)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 71 at r1](https://reviewable.io/reviews/starkware-libs/committer/276#-O1BZIGp78Xhrzbnl8T9:-O1BZIGp78Xhrzbnl8TA:b-u6i80j) ([raw file](https://github.com/starkware-libs/committer/blob/7738bd3d476b54cc3c156918ffef794a6417bd45/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L71)):*
> ```XML
>             [..leftmost_index]
>             .iter()
>             .copied()
> ```

this can be a perf hit, no?
not worth it just for the warning



_Code quote:_
```XML
.copied()
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 344 at r1](https://reviewable.io/reviews/starkware-libs/committer/276#-O1B_kLh-VtBKbKri3Tr:-O1B_kLh-VtBKbKri3Ts:bms1437) ([raw file](https://github.com/starkware-libs/committer/blob/7738bd3d476b54cc3c156918ffef794a6417bd45/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L344)):*
> ```XML
>     /// modification if a leaf is modified to an empty leaf.
>     fn log_warning_for_empty_leaves<L: LeafData>(
>         leaf_indices: &[NodeIndex],
> ```

if you do this, do you still need the `copied` above?



_Suggestion:_
```XML
&[&NodeIndex]
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/276)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 179 at r1](https://reviewable.io/reviews/starkware-libs/committer/276#-O1BbpzVBu6ZVTv9XUlX:-O1BbpzVBu6ZVTv9XUlY:bb7hf91) ([raw file](https://github.com/starkware-libs/committer/blob/7738bd3d476b54cc3c156918ffef794a6417bd45/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L179)):*
> ```XML
>                     }
>                     OriginalSkeletonTreeImpl::log_warning_for_empty_leaves(
>                         previously_empty_leaves_indices.as_slice(),
> ```

here



_Code quote:_
```XML
previously_empty_leaves_indices.as_slice(),
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 344 at r1](https://reviewable.io/reviews/starkware-libs/committer/276#-O1B_kLh-VtBKbKri3Tr:-O1Bb8Qb6q2AZc2exEdf:b-nn034h) ([raw file](https://github.com/starkware-libs/committer/blob/7738bd3d476b54cc3c156918ffef794a6417bd45/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L344)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

if you do this, do you still need the `copied` above?
</blockquote></details>

No, but it won't match the type when calling [here](https://reviewable.io/reviews/starkware-libs/committer/276#-O1BbpzVBu6ZVTv9XUlX)

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/276)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 344 at r1](https://reviewable.io/reviews/starkware-libs/committer/276#-O1B_kLh-VtBKbKri3Tr:-O1Bbu-W-wqsCKiixcD-:b-evcmfd) ([raw file](https://github.com/starkware-libs/committer/blob/7738bd3d476b54cc3c156918ffef794a6417bd45/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L344)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

No, but it won't match the type when calling [here](https://reviewable.io/reviews/starkware-libs/committer/276#-O1BbpzVBu6ZVTv9XUlX)
</blockquote></details>

Ok, got rid of it :)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/276)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware, @nimrod-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 344 at r1](https://reviewable.io/reviews/starkware-libs/committer/276#-O1B_kLh-VtBKbKri3Tr:-O1BqvMC5B5Qv8dzSbi6:btcbrl8) ([raw file](https://github.com/starkware-libs/committer/blob/7738bd3d476b54cc3c156918ffef794a6417bd45/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L344)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Ok, got rid of it :)
</blockquote></details>

I don't understand why you need the abstraction: what is the type of `previously_empty_leaf_indices` if not `&[&NodeIndex]`?
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 338 at r2](https://reviewable.io/reviews/starkware-libs/committer/276#-O1BrAFqCeYQkAEXOpog:-O1BrAFqCeYQkAEXOpoh:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/82f6a99842647c73beefbfec9892b12ccd6f0c6b/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L338)):*
> ```XML
> 
>     /// Given leaf indices that were previously empty leaves, logs out a warning for trivial
>     /// modification if a leaf is modified to an empty leaf.
> ```





_Suggestion:_
```XML
    /// Given leaf indices that were previously empty leaves, logs out a warning for trivial
    /// modification if a leaf is modified to an empty leaf.
    /// If this check is suppressed by configuration, does nothing.
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 348 at r2](https://reviewable.io/reviews/starkware-libs/committer/276#-O1BrXhpDo4rUiJiKv7x:-O1BrXhpDo4rUiJiKv7y:bdvvfk7) ([raw file](https://github.com/starkware-libs/committer/blob/82f6a99842647c73beefbfec9892b12ccd6f0c6b/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L348)):*
> ```XML
>         let empty_leaf = L::default();
>         for leaf_index in leaf_indices {
>             if config.compare_leaf(leaf_index.borrow(), &empty_leaf)? {
> ```

does it still make sense to implement `compare_leaf` on the config object, if you only reach this code when `config.compare_modified_leaves()` is true?
where does the data come from? all leaf data is stored in the config struct??



_Code quote:_
```XML
if config.compare_leaf(leaf_index.borrow(), &empty_leaf)? {
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/276)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware, @dorimedini-starkware, and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 344 at r1](https://reviewable.io/reviews/starkware-libs/committer/276#-O1B_kLh-VtBKbKri3Tr:-O1C1gB12wa_MPjqMWk6:b-enlon0) ([raw file](https://github.com/starkware-libs/committer/blob/7738bd3d476b54cc3c156918ffef794a6417bd45/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L344)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

I don't understand why you need the abstraction: what is the type of `previously_empty_leaf_indices` if not `&[&NodeIndex]`?
</blockquote></details>

The type of `previously_empty_leaf_indices` is `Vec<&NodeIndex>`.
The abstraction is needed since I call this function twice.
Once when the type is `&[NodeIndex]` and once when the type is `Vec<&NodeIndex>`
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 338 at r2](https://reviewable.io/reviews/starkware-libs/committer/276#-O1BrAFqCeYQkAEXOpog:-O1C1e9hAbJ5Y4i4o3QL:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/82f6a99842647c73beefbfec9892b12ccd6f0c6b/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L338)):*
> ```XML
> 
>     /// Given leaf indices that were previously empty leaves, logs out a warning for trivial
>     /// modification if a leaf is modified to an empty leaf.
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 348 at r2](https://reviewable.io/reviews/starkware-libs/committer/276#-O1BrXhpDo4rUiJiKv7x:-O1C2-dy22NiIIa3JAQB:by6ih67) ([raw file](https://github.com/starkware-libs/committer/blob/82f6a99842647c73beefbfec9892b12ccd6f0c6b/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L348)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

does it still make sense to implement `compare_leaf` on the config object, if you only reach this code when `config.compare_modified_leaves()` is true?
where does the data come from? all leaf data is stored in the config struct??
</blockquote></details>

ATM, the config struct has a reference to all the modified leaves.
Do you think of a better way to do this?

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/276)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 348 at r2](https://reviewable.io/reviews/starkware-libs/committer/276#-O1BrXhpDo4rUiJiKv7x:-O1CTeNl7HlMsspPodYu:b1c922l) ([raw file](https://github.com/starkware-libs/committer/blob/82f6a99842647c73beefbfec9892b12ccd6f0c6b/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L348)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

ATM, the config struct has a reference to all the modified leaves.
Do you think of a better way to do this?
</blockquote></details>

the original skeleton has storage, right?
doesn't it make more sense to read and deserialize nodes from storage on demand, if warnings are requested?
out of scope of this pr anyway

**Pull request merged**
