### PR TITLE
fix: use buffered write to file

### PR DESCRIPTION
**Pull request by aner-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/267)

### CODE REVIEW

**Review by yoavGrs — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/267)* status: all files reviewed, 1 unresolved discussion (waiting on @aner-starkware and @dorimedini-starkware)

___
*[`crates/committer_cli/src/parse_input/read.rs` line 31 at r2](https://reviewable.io/reviews/starkware-libs/committer/267#-O0ny5cU3sxDDSyWcq27:-O0ny5cU3sxDDSyWcq28:b-e915tb) ([raw file](https://github.com/starkware-libs/committer/blob/87c2c38cfe31c4d154e8d3305e6ba098fe1650bd/crates/committer_cli/src/parse_input/read.rs#L31)):*
> ```XML
> 
> pub fn write_to_file<T: Serialize>(file_path: &str, object: &T) {
>     let file = BufWriter::new(File::create(file_path).expect("Failed to create file"));
> ```

Consider renaming.



_Code quote:_
```XML
file
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/267)* status: all files reviewed, 2 unresolved discussions (waiting on @aner-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/267#-O0nzvYW-ADnX650Ho5R:-O0nzvYW-ADnX650Ho5S:b-lrmor7) (no related file):*
nice!
python side PR?

___

**Comment by aner-starkware** [comment]
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

nice!
python side PR?
</blockquote></details>

I don't think this change is "visible" to the python side; I opened a PR to test this hypothesis:
https://reviewable.io/reviews/starkware-industries/starkware/35392

**Comment by aner-starkware** [comment]
<details><summary><i>Previously, aner-starkware wrote…</i></summary><blockquote>

I don't think this change is "visible" to the python side; I opened a PR to test this hypothesis:
https://reviewable.io/reviews/starkware-industries/starkware/35392
</blockquote></details>

It passed Hodor

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/267#-:-O0rckdg84iiPcBvCX-S:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @aner-starkware)

**Pull request merged**
