### PR TITLE
build: add mock storage

### PR DESCRIPTION
**Pull request by amosStarkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/40)

### CODE REVIEW

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/40)* status: 0 of 3 files reviewed, 2 unresolved discussions

___
*[`crates/committer/src/storage/storage_trait.rs` line 12 at r1](https://reviewable.io/reviews/starkware-libs/committer/40#-NvX6Lft-XMmhx8zwGsa:-NvX6Lft-XMmhx8zwGsb:b-ohlxok) ([raw file](https://github.com/starkware-libs/committer/blob/70f93b1d41c32649c731fe481fd4870b656d1902/crates/committer/src/storage/storage_trait.rs#L12)):*
> ```XML
> pub(crate) trait Storage {
>     /// Returns value from storage, if it exists.
>     fn get(&self, key: &StorageKey) -> Option<&StorageValue>;
> ```

I updated `get`, `set` and `delete` to behave the same as HashMap's `get`, `insert`, `delete`.
`mget` & `mset` don't have equivalent functions in stable releases (AFAIK)
___
*[`crates/committer/src/storage/storage_trait.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/committer/40#-NvX6kRQ4s-qhPf3Xhdj:-NvX6kRQ4s-qhPf3Xhdk:bfyd0at) ([raw file](https://github.com/starkware-libs/committer/blob/70f93b1d41c32649c731fe481fd4870b656d1902/crates/committer/src/storage/storage_trait.rs#L20)):*
> ```XML
>     fn mget(&self, keys: &[StorageKey]) -> Vec<Option<&StorageValue>>;
>     /// Sets values in storage.
>     fn mset(&mut self, key_to_value: HashMap<StorageKey, StorageValue>);
> ```

I don't return the old values here (as in `set`) to be more performant - WYT?



_Code quote:_
```XML
fn mset(&mut self, key_to_value: HashMap<StorageKey, StorageValue>);
```

**Review by amosStarkware — COMMENTED** [review]
+reviewer:@dorimedini-starkware +reviewer:@nimrod-starkware 

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/40#-:-NvX7AO577WINFRJUdd9:bhedhnc)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/40)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/storage.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/committer/40#-NvXKDc749MUC7gHmppd:-NvXKDc86Wdk7FJRd3qk:bybw863) ([raw file](https://github.com/starkware-libs/committer/blob/70f93b1d41c32649c731fe481fd4870b656d1902/crates/committer/src/storage.rs#L2)):*
> ```XML
> pub(crate) mod errors;
> pub(crate) mod mock_storage;
> ```

this should be a test util, right?



_Suggestion:_
```XML
#[cfg(test)]
pub(crate) mod mock_storage;
```
___
*[`crates/committer/src/storage/storage_trait.rs` line 20 at r1](https://reviewable.io/reviews/starkware-libs/committer/40#-NvX6kRQ4s-qhPf3Xhdj:-NvXKaR19QfxwR89HKtA:bb73djm) ([raw file](https://github.com/starkware-libs/committer/blob/70f93b1d41c32649c731fe481fd4870b656d1902/crates/committer/src/storage/storage_trait.rs#L20)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

I don't return the old values here (as in `set`) to be more performant - WYT?
</blockquote></details>

SGTM
___
*[`crates/committer/src/storage/storage_trait.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/40#-NvXKUE6-oNjE6eIIcL6:-NvXKUE6-oNjE6eIIcL7:b-psfrh5) ([raw file](https://github.com/starkware-libs/committer/blob/70f93b1d41c32649c731fe481fd4870b656d1902/crates/committer/src/storage/storage_trait.rs#L22)):*
> ```XML
>     fn mset(&mut self, key_to_value: HashMap<StorageKey, StorageValue>);
>     /// Deletes value from storage and returns its value if it exists. Returns None if not.
>     fn delete(&mut self, key: &StorageKey) -> Option<StorageValue>;
> ```

add newlines please



_Suggestion:_
```XML
    /// Returns value from storage, if it exists.
    fn get(&self, key: &StorageKey) -> Option<&StorageValue>;
    
    /// Sets value in storage. If key already exists, its value is overwritten and the old value is
    /// returned.
    fn set(&mut self, key: StorageKey, value: StorageValue) -> Option<StorageValue>;
    
    /// Returns values from storage in same order of given keys. Value is None for keys that do not
    /// exist.
    fn mget(&self, keys: &[StorageKey]) -> Vec<Option<&StorageValue>>;
    
    /// Sets values in storage.
    fn mset(&mut self, key_to_value: HashMap<StorageKey, StorageValue>);
    
    /// Deletes value from storage and returns its value if it exists. Returns None if not.
    fn delete(&mut self, key: &StorageKey) -> Option<StorageValue>;
```

**Review by nimrod-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/40)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware)

___
*[`crates/committer/src/storage/mock_storage.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/40#-Nv_Z5xS7UKJNTdoYr14:-Nv_Z5xS7UKJNTdoYr15:b-2z5ymv) ([raw file](https://github.com/starkware-libs/committer/blob/70f93b1d41c32649c731fe481fd4870b656d1902/crates/committer/src/storage/mock_storage.rs#L21)):*
> ```XML
>         let mut result = vec![];
>         result.extend(keys.iter().map(|key| self.get(key)));
>         result
> ```

IMO this is more clear
`keys.iter().map(|key| self.get(key)).collect::<Vec<_>>()`



_Code quote:_
```XML
        let mut result = vec![];
        result.extend(keys.iter().map(|key| self.get(key)));
        result
```

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/40)* status: all files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/storage.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/committer/40#-NvXKDc749MUC7gHmppd:-Nv_l1a8BDDGM6viPMUA:blxxtvw) ([raw file](https://github.com/starkware-libs/committer/blob/70f93b1d41c32649c731fe481fd4870b656d1902/crates/committer/src/storage.rs#L2)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

this should be a test util, right?
</blockquote></details>

no - I assumed this is what we will use until we have real storage.
I named it mock_storage because it's not real storage - should I rename?
___
*[`crates/committer/src/storage/mock_storage.rs` line 21 at r1](https://reviewable.io/reviews/starkware-libs/committer/40#-Nv_Z5xS7UKJNTdoYr14:-Nv_mK0z81CTxgrMHtw1:bb6un1j) ([raw file](https://github.com/starkware-libs/committer/blob/70f93b1d41c32649c731fe481fd4870b656d1902/crates/committer/src/storage/mock_storage.rs#L21)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

IMO this is more clear
`keys.iter().map(|key| self.get(key)).collect::<Vec<_>>()`
</blockquote></details>

Done
___
*[`crates/committer/src/storage/storage_trait.rs` line 22 at r1](https://reviewable.io/reviews/starkware-libs/committer/40#-NvXKUE6-oNjE6eIIcL6:-Nv_mdadAw6QJ-4q0cVl:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/70f93b1d41c32649c731fe481fd4870b656d1902/crates/committer/src/storage/storage_trait.rs#L22)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

add newlines please
</blockquote></details>

Done.

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/40)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @nimrod-starkware)

___
*[`crates/committer/src/storage.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/committer/40#-NvXKDc749MUC7gHmppd:-Nv_tt-e79p2PkA8ygXH:b-1wfmf2) ([raw file](https://github.com/starkware-libs/committer/blob/70f93b1d41c32649c731fe481fd4870b656d1902/crates/committer/src/storage.rs#L2)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

no - I assumed this is what we will use until we have real storage.
I named it mock_storage because it's not real storage - should I rename?
</blockquote></details>

yes, please use `DictStorage`

**Review by amosStarkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/40)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/storage.rs` line 2 at r1](https://reviewable.io/reviews/starkware-libs/committer/40#-NvXKDc749MUC7gHmppd:-Nv_wwRl9XTxRA40q2GZ:b-hwt51j) ([raw file](https://github.com/starkware-libs/committer/blob/70f93b1d41c32649c731fe481fd4870b656d1902/crates/committer/src/storage.rs#L2)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

yes, please use `DictStorage`
</blockquote></details>

Done. (`MapStorage`)

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/40#-:-Nv_x0YKDjofeB61RvsL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/40)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

**Review by nimrod-starkware — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/40#-:-Nv_yOxn2i50RI-KVf4v:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @amosStarkware)

**Pull request merged**
