### PR TITLE
refactor: sort once

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/300)

### CODE REVIEW

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed 4 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/300)* status: 4 of 15 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/external_test_utils.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/committer/300#-O1XC_bH93GpV9QFPSb8:-O1XC_bH93GpV9QFPSb9:b-dnzl35) ([raw file](https://github.com/starkware-libs/committer/blob/7e360b1300daedba8b538cd87b559d48d5af93e0/crates/committer/src/patricia_merkle_tree/external_test_utils.rs#L79)):*
> ```XML
>     let sorted_leaf_indices = SortedLeafIndices::new(&mut sorted_leaf_indices);
>     let mut original_skeleton: OriginalSkeletonTreeImpl =
>         OriginalSkeletonTree::create(storage, root_hash, sorted_leaf_indices, &config)
> ```

Was this ever valid?



_Code quote:_
```XML
 OriginalSkeletonTree::create(storage, root_hash, sorted_leaf_indices, &config)
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/committer/300#-O1XCrDTB5VJjw-u_Y3O:-O1XCrDTB5VJjw-u_Y3P:b-ud7aaq) ([raw file](https://github.com/starkware-libs/committer/blob/20482cc4cd95d2438bdfe0b2e004b2123a65231f/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L60)):*
> ```XML
>         let classes_trie = ClassesTrie::create::<TH>(
>             updated_forest.classes_trie.into(),
>             Arc::new(classes_updates),
> ```

Does this work? (for consistency)



_Suggestion:_
```XML
            Arc::new(updated_forest.classes_trie),
            Arc::new(classes_updates),
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/300)* status: 4 of 15 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/external_test_utils.rs` line 79 at r1](https://reviewable.io/reviews/starkware-libs/committer/300#-O1XC_bH93GpV9QFPSb8:-O1jxUgAAqc3sjFNVdkb:b-t79co1) ([raw file](https://github.com/starkware-libs/committer/blob/7e360b1300daedba8b538cd87b559d48d5af93e0/crates/committer/src/patricia_merkle_tree/external_test_utils.rs#L79)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Was this ever valid?
</blockquote></details>

What do you mean?
It was valid because the type annotation, but now since `OriginalSkeletonTreeImpl` needs a lifetime specifier, it needs to be annotated as well.
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs` line 60 at r1](https://reviewable.io/reviews/starkware-libs/committer/300#-O1XCrDTB5VJjw-u_Y3O:-O1jxOFT-HUUR28UmiM1:bm8vom0) ([raw file](https://github.com/starkware-libs/committer/blob/20482cc4cd95d2438bdfe0b2e004b2123a65231f/crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs#L60)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Does this work? (for consistency)
</blockquote></details>

Yes, it works; it's equivalent
Changed everywhere for consistency

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 8 of 15 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/300)* status: all files reviewed, 7 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/committer/300#-O1k7kPAAFHm4ipQyxC6:-O1k7kPAAFHm4ipQyxC7:bgqlye0) ([raw file](https://github.com/starkware-libs/committer/blob/dbe1ae17fe99731a9fdb5ff2a75510d9d2138f2c/crates/committer/src/patricia_merkle_tree/types.rs#L228)):*
> ```XML
> }
> 
> #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
> ```

why would you need these...? and is this an O(1) reference address comparison or does `x == y` trigger an O(n) operation?



_Code quote:_
```XML
 Eq, PartialEq
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 322 at r2](https://reviewable.io/reviews/starkware-libs/committer/300#-O1kGLO0CUae09W1nHwX:-O1kGLO0CUae09W1nHwY:bwe17ky) ([raw file](https://github.com/starkware-libs/committer/blob/dbe1ae17fe99731a9fdb5ff2a75510d9d2138f2c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L322)):*
> ```XML
>     }
> 
>     fn create_empty(sorted_leaf_indices: SortedLeafIndices<'a>) -> Self {
> ```

why does `create_empty` need the node indices as input?
this list is either empty, or contains one element (empty root node), right?



_Code quote:_
```XML
fn create_empty(sorted_leaf_indices: SortedLeafIndices<'a>) -> Self {
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/committer/300#-O1kL7if2hxhbwpTPmg9:-O1kL7if2hxhbwpTPmgA:b-tflt1) ([raw file](https://github.com/starkware-libs/committer/blob/dbe1ae17fe99731a9fdb5ff2a75510d9d2138f2c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L160)):*
> ```XML
>         config: ConfigImpl::new(true),
>     }, OriginalSkeletonForest{
>         classes_trie: OriginalSkeletonTreeImpl {
> ```

all the trees in these test cases have no leaves...?
if some have leaves, why are all `sorted_leaf_indices` fields empty?
if not, please use `SortedLeafIndices::default` (or even `Default::default()` should work)
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/committer/300#-O1kLkDj85Mel3URxh_B:-O1kLkDj85Mel3URxh_C:b-lxpwon) ([raw file](https://github.com/starkware-libs/committer/blob/dbe1ae17fe99731a9fdb5ff2a75510d9d2138f2c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L173)):*
> ```XML
>                     ),
>             sorted_leaf_indices: SortedLeafIndices::new(&mut [])
>         },
> ```

below, you have this code:
```
    let mut classes_indices = create_expected_sorted_indices(&expected_classes_trie_sorted_indices);
    let sorted_classes_indices = SortedLeafIndices::new(&mut classes_indices);
    let copied_expected_classes_skeleton = create_original_skeleton_with_sorted_indices(
        sorted_classes_indices,
        &expected_forest.classes_trie,
    );
```
wouldn't is just be easier to put the sorted indices here in the parametrization?



_Code quote:_
```XML
        classes_trie: OriginalSkeletonTreeImpl {
            nodes: create_expected_skeleton_nodes(
                        vec![
                            create_edge_skeleton_node(1, 0, 1),
                            create_binary_skeleton_node(2),
                            create_binary_skeleton_node(4),
                            create_edge_skeleton_node(5, 1, 1),
                            create_unmodified_subtree_skeleton_node(11, 72),
                            create_unmodified_subtree_skeleton_node(9, 47)
                        ],
                        3
                    ),
            sorted_leaf_indices: SortedLeafIndices::new(&mut [])
        },
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 325 at r2](https://reviewable.io/reviews/starkware-libs/committer/300#-O1kM5AI0cFJ8Yu3xab2:-O1kM5AI0cFJ8Yu3xab3:boqwqnt) ([raw file](https://github.com/starkware-libs/committer/blob/dbe1ae17fe99731a9fdb5ff2a75510d9d2138f2c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L325)):*
> ```XML
>             actual_forest.storage_tries[&contract_address]
>         )
>     }
> ```

can you share some code here / use the parametrization (see above) to reduce logic?
similar stuff is being done 3 times



_Code quote:_
```XML
    let mut classes_indices = create_expected_sorted_indices(&expected_classes_trie_sorted_indices);
    let sorted_classes_indices = SortedLeafIndices::new(&mut classes_indices);
    let copied_expected_classes_skeleton = create_original_skeleton_with_sorted_indices(
        sorted_classes_indices,
        &expected_forest.classes_trie,
    );
    assert_eq!(actual_forest.classes_trie, copied_expected_classes_skeleton);

    let mut contracts_indices =
        create_expected_sorted_indices(&expected_contracts_trie_sorted_indices);
    let sorted_contracts_indices = SortedLeafIndices::new(&mut contracts_indices);
    let copied_expected_contracts_skeleton = create_original_skeleton_with_sorted_indices(
        sorted_contracts_indices,
        &expected_forest.contracts_trie,
    );
    assert_eq!(
        actual_forest.contracts_trie,
        copied_expected_contracts_skeleton
    );

    for (contract, indices) in expected_storage_tries_sorted_indices {
        let mut leaf_indices = create_expected_sorted_indices(&indices);
        let sorted_indices = SortedLeafIndices::new(&mut leaf_indices);
        let contract_address = ContractAddress(Felt::from(contract));
        let copied_storage_trie = create_original_skeleton_with_sorted_indices(
            sorted_indices,
            expected_forest
                .storage_tries
                .get(&contract_address)
                .unwrap(),
        );
        assert_eq!(
            copied_storage_trie,
            actual_forest.storage_tries[&contract_address]
        )
    }
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/300)* status: all files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/committer/300#-O1k7kPAAFHm4ipQyxC6:-O1kOdfzASxTvS15hgmP:b13efh0) ([raw file](https://github.com/starkware-libs/committer/blob/dbe1ae17fe99731a9fdb5ff2a75510d9d2138f2c/crates/committer/src/patricia_merkle_tree/types.rs#L228)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why would you need these...? and is this an O(1) reference address comparison or does `x == y` trigger an O(n) operation?
</blockquote></details>

Removed it.
I thought it was needed for unit testing
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 322 at r2](https://reviewable.io/reviews/starkware-libs/committer/300#-O1kGLO0CUae09W1nHwX:-O1kPre_DRqQ2BDxDRcf:b-xohtmc) ([raw file](https://github.com/starkware-libs/committer/blob/dbe1ae17fe99731a9fdb5ff2a75510d9d2138f2c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L322)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

why does `create_empty` need the node indices as input?
this list is either empty, or contains one element (empty root node), right?
</blockquote></details>

`create_empty` is called when the tree is previously empty, while there can be a lot of modifications.
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/committer/300#-O1kL7if2hxhbwpTPmg9:-O1kRK1lDMnBPTAmze3G:b4vnp5f) ([raw file](https://github.com/starkware-libs/committer/blob/dbe1ae17fe99731a9fdb5ff2a75510d9d2138f2c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L160)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

all the trees in these test cases have no leaves...?
if some have leaves, why are all `sorted_leaf_indices` fields empty?
if not, please use `SortedLeafIndices::default` (or even `Default::default()` should work)
</blockquote></details>

All the trees should have leaves. The problem with parameterizing the indices is that `SortedLeafIndices` has a reference to values that are already dead within the function scope... (the reference is invalid). 
I couldn't find a nice way to do that, so I compared only the tree's nodes (and not the indices).
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 173 at r2](https://reviewable.io/reviews/starkware-libs/committer/300#-O1kLkDj85Mel3URxh_B:-O1kSOyu9uX2YZ1Mnx1v:b1c1r6n) ([raw file](https://github.com/starkware-libs/committer/blob/dbe1ae17fe99731a9fdb5ff2a75510d9d2138f2c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L173)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

below, you have this code:
```
    let mut classes_indices = create_expected_sorted_indices(&expected_classes_trie_sorted_indices);
    let sorted_classes_indices = SortedLeafIndices::new(&mut classes_indices);
    let copied_expected_classes_skeleton = create_original_skeleton_with_sorted_indices(
        sorted_classes_indices,
        &expected_forest.classes_trie,
    );
```
wouldn't is just be easier to put the sorted indices here in the parametrization?
</blockquote></details>

please see above

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/300)* status: 12 of 15 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 228 at r2](https://reviewable.io/reviews/starkware-libs/committer/300#-O1k7kPAAFHm4ipQyxC6:-O1kXP67-RqUqs1Zp8pL:b-dr0zl6) ([raw file](https://github.com/starkware-libs/committer/blob/dbe1ae17fe99731a9fdb5ff2a75510d9d2138f2c/crates/committer/src/patricia_merkle_tree/types.rs#L228)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Removed it.
I thought it was needed for unit testing
</blockquote></details>

it's an O(n) operation

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/300)* status: 12 of 15 files reviewed, 7 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/committer/300#-O1kL7if2hxhbwpTPmg9:-O1kXmsN2y2fDwqvLPUa:btnyle2) ([raw file](https://github.com/starkware-libs/committer/blob/dbe1ae17fe99731a9fdb5ff2a75510d9d2138f2c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L160)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

All the trees should have leaves. The problem with parameterizing the indices is that `SortedLeafIndices` has a reference to values that are already dead within the function scope... (the reference is invalid). 
I couldn't find a nice way to do that, so I compared only the tree's nodes (and not the indices).
</blockquote></details>

Sorry, what I wrote was not accurate.
We do compare the indices, but they arrive from the parameters 
`expected\_storage\_tries\_sorted\_indices`, `expected\_contracts\_trie\_sorted\_indices` & `expected\_classes\_trie\_sorted\_indices`

**Review by dorimedini-starkware — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/300)* status: all files reviewed, 6 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/300)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 160 at r2](https://reviewable.io/reviews/starkware-libs/committer/300#-O1kL7if2hxhbwpTPmg9:-O1kfsjd1ggKNPeDpcZq:b-kj0kva) ([raw file](https://github.com/starkware-libs/committer/blob/dbe1ae17fe99731a9fdb5ff2a75510d9d2138f2c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L160)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

Sorry, what I wrote was not accurate.
We do compare the indices, but they arrive from the parameters 
`expected\_storage\_tries\_sorted\_indices`, `expected\_contracts\_trie\_sorted\_indices` & `expected\_classes\_trie\_sorted\_indices`
</blockquote></details>

yes, which is why I was confused why you can't just paste them in the skeleton tree construction itself in the `#[case]`. nvm

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/300)* status: all files reviewed, 4 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 325 at r2](https://reviewable.io/reviews/starkware-libs/committer/300#-O1kM5AI0cFJ8Yu3xab2:-O1kkVVB1JuSZY7wPwtW:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/dbe1ae17fe99731a9fdb5ff2a75510d9d2138f2c/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L325)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

can you share some code here / use the parametrization (see above) to reduce logic?
similar stuff is being done 3 times
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/300)* status: all files reviewed, 4 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 323 at r4](https://reviewable.io/reviews/starkware-libs/committer/300#-O1lKg9U-mRaq_vL0v34:-O1lKg9U-mRaq_vL0v35:bmi50pj) ([raw file](https://github.com/starkware-libs/committer/blob/7dd25122cd2fe1f6d56aecf616340df57a996fcb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L323)):*
> ```XML
>         create_original_skeleton_with_sorted_indices(sorted_indices, expected_skeleton);
>     assert_eq!(actual_skeleton, &copied_expected_skeleton);
> }
> ```

non-blocking:
test utils with `assert!`s in them should IMO be macros, so if we hit an assert we see the relevant line number without rerunning the test with `RUST_BACKTRACE=1`.
the downside is, macros < functions in general... your call



_Code quote:_
```XML
fn compare_skeleton_tree<'a>(
    actual_skeleton: &OriginalSkeletonTreeImpl<'a>,
    expected_skeleton: &OriginalSkeletonTreeImpl<'a>,
    expected_indices: &[u128],
) {
    let mut indices = create_expected_sorted_indices(expected_indices);
    let sorted_indices = SortedLeafIndices::new(&mut indices);
    let copied_expected_skeleton =
        create_original_skeleton_with_sorted_indices(sorted_indices, expected_skeleton);
    assert_eq!(actual_skeleton, &copied_expected_skeleton);
}
```

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/300)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware and @TzahiTaub)

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/300)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs` line 323 at r4](https://reviewable.io/reviews/starkware-libs/committer/300#-O1lKg9U-mRaq_vL0v34:-O1lOHDI5Yxyv7r-_2ab:b1eft0b) ([raw file](https://github.com/starkware-libs/committer/blob/7dd25122cd2fe1f6d56aecf616340df57a996fcb/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs#L323)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

non-blocking:
test utils with `assert!`s in them should IMO be macros, so if we hit an assert we see the relevant line number without rerunning the test with `RUST_BACKTRACE=1`.
the downside is, macros < functions in general... your call
</blockquote></details>

changed to macros

**Pull request merged**
