### PR TITLE
chore: add modification data to error variant

### PR DESCRIPTION
**Pull request by dorimedini-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/150)

### CODE REVIEW

**Review by amosStarkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/150)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/committer/150#-NypINjM0G8fx4cwL5aF:-NypINjM0G8fx4cwL5aG:blg53t7) ([raw file](https://github.com/starkware-libs/committer/blob/b9871cecb7d511c5d56289c8b301918ac064e798/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L14)):*
> ```XML
>     },
>     #[error(
>         "Modification of index {index:?} does not match the skeleton leaf {skeleton_leaf:?}: \
> ```

please explicitly write which is skeleton and which is modification, even though it's obvious to us



_Code quote:_
```XML
"Modification of index {index:?} does not match the skeleton leaf {skeleton_leaf:?}: \
```
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/committer/150#-NypIWzO4x51lBZYH9s3:-NypIWzO4x51lBZYH9s4:b7idms6) ([raw file](https://github.com/starkware-libs/committer/blob/b9871cecb7d511c5d56289c8b301918ac064e798/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L20)):*
> ```XML
>         index: NodeIndex,
>         skeleton_leaf: SkeletonLeaf,
>         leaf_modification: Box<L>,
> ```

will requiring leaf data to be `sized` remove the need for this box? 



_Code quote:_
```XML
leaf_modification: Box<L>,
```

**Review by amosStarkware — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/150)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware and @TzahiTaub)

**Review by dorimedini-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/150)* status: all files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 14 at r2](https://reviewable.io/reviews/starkware-libs/committer/150#-NypINjM0G8fx4cwL5aF:-NypR2MMEhIKD1eeGzMh:b55w69s) ([raw file](https://github.com/starkware-libs/committer/blob/b9871cecb7d511c5d56289c8b301918ac064e798/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L14)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

please explicitly write which is skeleton and which is modification, even though it's obvious to us
</blockquote></details>

the `:?` print should output the type as well as the value, so it will be clear
___
*[`crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs` line 20 at r2](https://reviewable.io/reviews/starkware-libs/committer/150#-NypIWzO4x51lBZYH9s3:-NypRGuSC92_hcieh3Gl:b7n7svl) ([raw file](https://github.com/starkware-libs/committer/blob/b9871cecb7d511c5d56289c8b301918ac064e798/crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs#L20)):*
<details><summary><i>Previously, amosStarkware wrote…</i></summary><blockquote>

will requiring leaf data to be `sized` remove the need for this box?
</blockquote></details>

no; clippy complains about the max size of any implementation (137 bytes)

**Review by amosStarkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/150)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
