### PR TITLE
refactor: log trivial modifications should depend on the config

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/258)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/258#-:-O0d4kWT1_Gx2ri9Ubje:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Review by TzahiTaub — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/258)* status: all files reviewed, 3 unresolved discussions (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/committer/258#-O0d33_i22hV33I7kzVb:-O0d33_i22hV33I7kzVc:bimgg8) ([raw file](https://github.com/starkware-libs/committer/blob/85455195441032770e37980d69f7fc86853e35d2/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L119)):*
> ```XML
>         let should_fetch_leaves = config.compare_modified_leaves() || previous_leaves.is_some();
>         let mut next_subtrees = Vec::new();
>         let filled_roots = Self::calculate_subtrees_roots::<L>(&subtrees, storage)?;
> ```

Out of context, but I find it confusing to have the `filled` term to be used also for the final "tree/nodes" and also for an original node with all of its data.



_Code quote:_
```XML
filled_roots
```
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 177 at r1](https://reviewable.io/reviews/starkware-libs/committer/258#-O0d3HEb8b7Axt5ip3uz:-O0d3HEc8voujoc5M9aR:b-9wq4ls) ([raw file](https://github.com/starkware-libs/committer/blob/85455195441032770e37980d69f7fc86853e35d2/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L177)):*
> ```XML
>                             }
>                         }
>                     }
> ```

1. Define the var once.
2. Can the name/type of the tree go to the log so we'll now what tree we're talking about?



_Suggestion:_
```XML
                    if config.compare_modified_leaves() {
                        let empty_leaf = L::default();
                        for leaf_idx in previously_empty_leaves_indices {
                            if config.compare_leaf(leaf_idx, &empty_leaf)? {
                                warn!("Encountered a trivial modification at index {:?} in tree {:?}", leaf_idx, TREE);
                            }
                        }
                    }
```
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/committer/258#-O0d26WkBv6F_bFry1SH:-O0d26WkBv6F_bFry1SI:b73r8bp) ([raw file](https://github.com/starkware-libs/committer/blob/85455195441032770e37980d69f7fc86853e35d2/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs#L128)):*
> ```XML
>             );
>             if !self.skeleton_tree.contains_key(root_index) {
>                 // "Deletion" of an already empty leaf. Supported but not expected.
> ```

Please change for the inference to be clear.



_Suggestion:_
```XML
 // "Deletion" of an original empty leaf (as non-zero leaf modifications are finalized in `finalize_bottom_layer`). 
 // Supported but not expected.
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/258)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/committer/258#-O0d33_i22hV33I7kzVb:-O0gzN7S9hQy9lBqZHWH:b-hjtksh) ([raw file](https://github.com/starkware-libs/committer/blob/85455195441032770e37980d69f7fc86853e35d2/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L119)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Out of context, but I find it confusing to have the `filled` term to be used also for the final "tree/nodes" and also for an original node with all of its data.
</blockquote></details>

how about `original_roots`? is that clearer?
they called filled because we deserialize them to `FilledNode`
___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 177 at r1](https://reviewable.io/reviews/starkware-libs/committer/258#-O0d3HEb8b7Axt5ip3uz:-O0gyPeID3Y49Ez5MCjF:bw45an1) ([raw file](https://github.com/starkware-libs/committer/blob/85455195441032770e37980d69f7fc86853e35d2/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L177)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

1. Define the var once.
2. Can the name/type of the tree go to the log so we'll now what tree we're talking about?
</blockquote></details>

1. Done
2. A possible thing to do is to print the leaf data itself (which tells what tree we're talking about)
___
*[`crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs` line 128 at r1](https://reviewable.io/reviews/starkware-libs/committer/258#-O0d26WkBv6F_bFry1SH:-O0gzFunA6dxZA9lbDbJ:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/85455195441032770e37980d69f7fc86853e35d2/crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs#L128)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Please change for the inference to be clear.
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/258)* status: all files reviewed, 3 unresolved discussions (waiting on @TzahiTaub)

**Review by TzahiTaub — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/258)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 119 at r1](https://reviewable.io/reviews/starkware-libs/committer/258#-O0d33_i22hV33I7kzVb:-O0h74bE2O3NdLZ4nblv:b-vuu30q) ([raw file](https://github.com/starkware-libs/committer/blob/85455195441032770e37980d69f7fc86853e35d2/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L119)):*
<details><summary><i>Previously, nimrod-starkware wrote…</i></summary><blockquote>

how about `original_roots`? is that clearer?
they called filled because we deserialize them to `FilledNode`
</blockquote></details>

I think it does though it's also can be confusing because ewe have OriginalSkeletonNodes

**Pull request merged**
