### PR TITLE
build: add logger init

### PR DESCRIPTION
**Pull request by AvivYossef-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/257)

### CODE REVIEW

**Review by AvivYossef-starkware — COMMENTED** [review]
Block until the committer output pipe PR

> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/257#-:-O0cQP0g78NXe3YH6XdC:b5qgfdg)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @dorimedini-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/257)* status: all files reviewed, 1 unresolved discussion (waiting on @AvivYossef-starkware)

___
*[`crates/committer_cli/src/main.rs` line 78 at r1](https://reviewable.io/reviews/starkware-libs/committer/257#-O0cgpg5-yDDhtiEFbdS:-O0cgpg5-yDDhtiEFbdT:bdj6yd8) ([raw file](https://github.com/starkware-libs/committer/blob/fac9ac7843d314dcaf39b7dab02fb8d34f45acf6/crates/committer_cli/src/main.rs#L78)):*
> ```XML
>         Ok(_) => (),
>         err => eprintln!("Failed to initialize the logger: {:?}", err),
>     }
> ```

no need for `match` here



_Suggestion:_
```XML
    if let Err(error) = TermLogger::init(
        LevelFilter::Info,   // Set the logging level
        Config::default(),   // Use the default log format
        TerminalMode::Mixed, // Use mixed mode to log to both stdout and stderr
        ColorChoice::Auto,   // Automatically choose whether to use colored output
    ) {
        eprintln!("Failed to initialize the logger: {:?}", error);
    }
```

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/257)* status: all files reviewed, 2 unresolved discussions (waiting on @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/257#-O0rBgZYA5y51-Dd-WaJ:-O0rBgZYA5y51-Dd-WaK:bgkbrzy) (no related file):*
block until rebase is over main-v0.13.2

___

**Review by AvivYossef-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/257)* status: all files reviewed, 2 unresolved discussions (waiting on @dorimedini-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/257#-O0rBgZYA5y51-Dd-WaJ:-O0rIyqv-xqRYjEi8Uxd:b-j6gy8c) (no related file):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

block until rebase is over main-v0.13.2
</blockquote></details>

Do we have this brunch in the committer? I cant find it

___

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/257#-:-O0rcaZgBKX5j-84ZajG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AvivYossef-starkware)

*[a discussion](https://reviewable.io/reviews/starkware-libs/committer/257#-O0rBgZYA5y51-Dd-WaJ:-O0rcVfF1vfMoP_UM8fw:b-q962i3) (no related file):*
<details><summary><i>Previously, AvivYossef-starkware wrote…</i></summary><blockquote>

Do we have this brunch in the committer? I cant find it
</blockquote></details>

ah whoops... nope, my bad

___

**Pull request merged**
