### PR TITLE
chore: get_lca for NodeIndex

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/98)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/98)* status: all files reviewed, 3 unresolved discussions (waiting on @amosStarkware and @TzahiTaub)

___
*[`crates/committer/Cargo.toml` line 15 at r2](https://reviewable.io/reviews/starkware-libs/committer/98#-NxM3jaZ7W1qS4JLRtAC:-NxM3jaZ7W1qS4JLRtAD:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/c59efaf40a91bb3fcf7350c6231ff8282d40b031/crates/committer/Cargo.toml#L15)):*
> ```TOML
> pretty_assertions.workspace = true
> rstest.workspace = true
> rand.workspace = true
> ```





_Suggestion:_
```TOML
pretty_assertions.workspace = true
rand.workspace = true
rstest.workspace = true
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/committer/98#-NxM5VDT2dZ9vMF4P0bk:-NxM5VDT2dZ9vMF4P0bl:b-89bzui) ([raw file](https://github.com/starkware-libs/committer/blob/c59efaf40a91bb3fcf7350c6231ff8282d40b031/crates/committer/src/patricia_merkle_tree/types.rs#L83)):*
> ```XML
>             Ordering::Greater => adapted_self = adapted_self >> (bit_length - other_bit_length),
>             Ordering::Equal => return *self,
>         }
> ```

clearer?
also removes the need for `Ordering`.
if you like minimal amount of lines you can replace the `if .. else` with `match .. true => .. false => ..`



_Suggestion:_
```XML
    pub(crate) fn get_lca(&self, other: &NodeIndex) -> NodeIndex {
        if self == other {
            return *self;
        }
        let bit_length = self.bit_length();
        let other_bit_length = other.bit_length();

        // Bring self to the level of other.
        let adapted_self = if self < other {
            self << (other_bit_length - bit_length)
        } else {
            self >> (bit_length - other_bit_length)
        };
```
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 86 at r2](https://reviewable.io/reviews/starkware-libs/committer/98#-NxM60cl7kWBz9AvRPBb:-NxM60cm0Ea02JGQDOPI:bb7phvt) ([raw file](https://github.com/starkware-libs/committer/blob/c59efaf40a91bb3fcf7350c6231ff8282d40b031/crates/committer/src/patricia_merkle_tree/types.rs#L86)):*
> ```XML
> 
>         let xor = adapted_self.0 ^ other.0;
>         // The length of the reminder after removing the common prefix of the two nodes.
> ```

typo



_Suggestion:_
```XML
remainder
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/98)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @amosStarkware and @dorimedini-starkware)

___
*[`crates/committer/Cargo.toml` line 15 at r2](https://reviewable.io/reviews/starkware-libs/committer/98#-NxM3jaZ7W1qS4JLRtAC:-NxN7ZxP-SMnfS7RucqV:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/c59efaf40a91bb3fcf7350c6231ff8282d40b031/crates/committer/Cargo.toml#L15)):*
> ```TOML
> pretty_assertions.workspace = true
> rstest.workspace = true
> rand.workspace = true
> ```

Done.
___
*[`crates/committer/src/patricia_merkle_tree/types.rs` line 83 at r2](https://reviewable.io/reviews/starkware-libs/committer/98#-NxM5VDT2dZ9vMF4P0bk:-NxN8jZh5nWob8iVQSbU:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/c59efaf40a91bb3fcf7350c6231ff8282d40b031/crates/committer/src/patricia_merkle_tree/types.rs#L83)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

clearer?
also removes the need for `Ordering`.
if you like minimal amount of lines you can replace the `if .. else` with `match .. true => .. false => ..`
</blockquote></details>

Done.

**Review by dorimedini-starkware — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/98)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Review by TzahiTaub — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/98)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amosStarkware)

**Pull request merged**
