### PR TITLE
chore: implemented OriginalSkeletonTree trait

### PR DESCRIPTION
**Pull request by nimrod-starkware**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/51)

### CODE REVIEW

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/51#-:-NvlJTgGClntMNpS3e0f:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nimrod-starkware)

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/51)* status: all files reviewed, 1 unresolved discussion (waiting on @nimrod-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 203 at r2](https://reviewable.io/reviews/starkware-libs/committer/51#-NvldOKn8YfPNiPe2-Ba:-NvldOKn8YfPNiPe2-Bb:undefined) ([raw file](https://github.com/starkware-libs/committer/blob/d1f6015ed3d50e923cfa77af2ef475f2be370edb/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L203)):*
> ```XML
> }
> impl OriginalSkeletonTree<LeafData> for OriginalSkeletonTreeImpl {
>     fn compute_original_skeleton_tree(
> ```





_Suggestion:_
```XML
create
```

**Review by nimrod-starkware — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/51)* status: all files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs` line 203 at r2](https://reviewable.io/reviews/starkware-libs/committer/51#-NvldOKn8YfPNiPe2-Ba:-Nvlea6Y0Q8xMnmAUYvq:b-896fix) ([raw file](https://github.com/starkware-libs/committer/blob/d1f6015ed3d50e923cfa77af2ef475f2be370edb/crates/committer/src/patricia_merkle_tree/original_skeleton_calc.rs#L203)):*
> ```XML
> }
> impl OriginalSkeletonTree<LeafData> for OriginalSkeletonTreeImpl {
>     fn compute_original_skeleton_tree(
> ```

Done.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/51#-:-NvlfD47C5pSTO3xvycK:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
