### PR TITLE
chore(skeleton): replace EdgeSibling with UnmodifiedBottom in original

### PR DESCRIPTION
**Pull request by TzahiTaub**
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/committer/145)

### CODE REVIEW

**Review by dorimedini-starkware — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/145)* status: all files reviewed, 1 unresolved discussion (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/committer/145#-NyoE6oX8w5CS8mkLJcK:-NyoE6oX8w5CS8mkLJcL:b-luzqpg) ([raw file](https://github.com/starkware-libs/committer/blob/b3f12257ef96dda979ee8c24df8dca56fbe70fe3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L149)):*
> ```XML
>                         );
>                         self.nodes.insert(
>                             subtree.root_index,
> ```

wrong index (need root_index + path)



_Code quote:_
```XML
subtree.root_index
```

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/145)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @dorimedini-starkware and @nimrod-starkware)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/committer/145#-NyoE6oX8w5CS8mkLJcK:-NyoUHHv0g3yzrp6y2Yz:b-khdgs7) ([raw file](https://github.com/starkware-libs/committer/blob/b3f12257ef96dda979ee8c24df8dca56fbe70fe3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L149)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

wrong index (need root_index + path)
</blockquote></details>

Oops. OK, actually looked at the surrounding code as well :)
The testing of this was accidentally forgotten, I talked with @nimrod-starkware and added a todo.

**Review by dorimedini-starkware — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/145#-:-Nyp-r3kDStVVNMNcube:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/committer/145#-NyoE6oX8w5CS8mkLJcK:-Nyp-gtp3Ln1QT3hYVXn:b-u9uytx) ([raw file](https://github.com/starkware-libs/committer/blob/b3f12257ef96dda979ee8c24df8dca56fbe70fe3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L149)):*
<details><summary><i>Previously, TzahiTaub (Tzahi) wrote…</i></summary><blockquote>

Oops. OK, actually looked at the surrounding code as well :)
The testing of this was accidentally forgotten, I talked with @nimrod-starkware and added a todo.
</blockquote></details>

wait, why is the root index node inserted now, even if the subtree is *not* a sibling? why wasn't it inserted before, actually? missing test?

**Review by TzahiTaub — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/145)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

___
*[`crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs` line 149 at r1](https://reviewable.io/reviews/starkware-libs/committer/145#-NyoE6oX8w5CS8mkLJcK:-Nyp0rVW60pOBfRlz9Up:bxw3nin) ([raw file](https://github.com/starkware-libs/committer/blob/b3f12257ef96dda979ee8c24df8dca56fbe70fe3/crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs#L149)):*
<details><summary><i>Previously, dorimedini-starkware wrote…</i></summary><blockquote>

wait, why is the root index node inserted now, even if the subtree is *not* a sibling? why wasn't it inserted before, actually? missing test?
</blockquote></details>

I'm not sure I understand - it as inserted as an edge when it's not a sibling (the deleted chunk under `//Parse bottom`

**Review by dorimedini-starkware — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/committer/145)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TzahiTaub)

**Pull request merged**
